### ISSUE TITLE
Where to get started

### ISSUE THREAD

**Issue by alscheuring** [jobisoft/TbSync#1]
Hi, 
I wanted to try this out and I have it installed in Thunderbird, but I'm not positive what the next steps are. Can you give me a push in the right direction?

**Comment by alscheuring** [comment]
Never mind. I see the menu item now.

**Comment by jobisoft** [comment]
A double click on the TbSync status info in the lower right corner of the thunderbird main window opens the account manager. There is also a menu item in the "Extras" menu, which seems missing in TB45 for Linux. Looking into it...

**Comment by jobisoft** [comment]
I created a how-to-get-started page in the wiki of this repository. 

https://github.com/jobisoft/TbSync/wiki/How-to-get-started

Screenshots are from the latest release v.0.6.4. Is that release working for you as expected? Thanks for your feedback!
