### ISSUE TITLE
Sync to existing calendar

### ISSUE THREAD

**Issue by G0nzzzz** [jobisoft/TbSync#10]
Hi John. Thanks for your work on this extension. I use it at work to sync my exchange account with my thunderbird calendar.

One thing I'd love to see in future releases: to choose an already existing target calendar to sync to, instead of creating a new/unique one. Maybe you've already thought of this and it is planned anytime soon? If not I'd like to contribute and look into this matter.

Cheers
Ehm

**Comment by jobisoft** [comment]
Hi,

TBSync is not doing that by design. I do not want to interact with existing local calendars.

You could try to export your local calendar and import it into your online calendar using the webinterface of your calendar provider or something similar. That should work.

Thanks,
John

**Comment by G0nzzzz** [comment]
Well, in my case it's not a local calendar but a caldav calendar I subcribed to.

**Comment by jobisoft** [comment]
sorry, I will not implement that.

**Comment by jobisoft** [comment]
I added a [guide](https://github.com/jobisoft/TbSync/wiki/How-to-sync-an-existing-Thunderbird-calendar-to-a-remote-EAS-account) to the wiki, which explains how to sync an existing calendar to a remote EAS server. It is not  exactly what this issue is about, but very close:
