### ISSUE TITLE
Documentation issue: Shared calendars

### ISSUE THREAD

**Issue by mikko-ttlsystems** [jobisoft/TbSync#100]
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F is out of date, there are now several providers that do have EAS-shared calendars - Microsoft Office 365 for one, though not for all calendars yet. Newly shared have EAS enabled depending on how you do the sharing. 

See https://support.office.com/en-us/article/calendar-sharing-in-office-365-b576ecc3-0945-4d75-85f1-5efafb8a37b4 - the "new model" is EAS enabled. (EWS would seem to be on the way out.)

**Comment by jobisoft** [comment]
I updated the wiki, better?

**Comment by mikko-ttlsystems** [comment]
Yes, thank you.

There's also a side effect of how they're doing it - since the EAS really doesn't do "shared calendars", it's really just a proxy copy and the server has to do the sync between the proxy copy and the backend, so change propagation may a) take a while b) fail silently especially in the case of permissions problems.

**Comment by jobisoft** [comment]
I know. Another side effect: If the owner removes access, my "copy" of his calendar remains in my account, it just does not get updated anymore. But I can still see all old entries. I do not like that. Kopano is doing real sharing (from what I have heard).
