### ISSUE TITLE
Feature request: persistent calendar color

### ISSUE THREAD

**Issue by nitro322** [jobisoft/TbSync#102]
## Your environment

TbSync version: 0.7.10.8
Thunderbird version: 52.9.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Requested behavior
After changing the color of a TbSync calendar, the color should persist if the TbSync account is ever disabled and re-enabled for troubleshooting or any other reason.

## Actual behavior
When disabling an account, the associated calendar is removed entirely.  When re-enabling the account, the calendar is re-created using the default color.

## Steps to reproduce
1. Add/sync TbSync account
2. Modify calendar color
3. Disable/Re-enable account
4. Note calendar color reverted to default

## Additional comments
This is a minor feature request.  I can certainly live without, but I like keeping my work calendar a specific color that's distinct from my personal calendars, and every time I disable/re-enable the TbSync account the calendar reverts back to the default blue.  Would be convenient if the chosen color would remain persistent for configured accounts.   Given how the add-on handles calendars I get why it behaves this way, and I'm not sure of an easy or obvious way to "fix" that, but wanted to bring it up for future consideration.  Would be a nice quality of life type of improvement.

**Comment by jobisoft** [comment]
That is actually implemented. I cache names and colors of calendars on disable use the cached values upon reconnect. Are you sure this is not working? I just tried on my system (and its independet of the used server, because caching is done within TbSync)

Strange.

**Comment by jobisoft** [comment]
Wait, there IS a slight chance it depends on the server: If he does not return the same UID for the folder between disable/re-enable. Horde is doing that and I asked them to fix that.

What server are you using? Can you try a different one? Try demo Kerio:

server: demo.kerio.cloud
user: admin-en

**Comment by jobisoft** [comment]
Passwort: kerio

**Comment by nitro322** [comment]
It definitely doesn't persist with my Office 365 account.  I'll see if I can setup a sync account with kerio and let you know.

**Comment by nitro322** [comment]
Doesn't work for me with kerio, either.  Reverts to blue (#3366CC) every time.

**Comment by jobisoft** [comment]
That is strange.

Please pick a custom color and a custom name , disable account (or just the folder) and send me the folders.json from the tbsync folder in your thunderbird profile folder.

**Comment by jobisoft** [comment]
have you disabled caching?

![image](https://user-images.githubusercontent.com/5830621/42644941-1ae9ab4c-85fd-11e8-9d4a-aaf1c97bf721.png)

that option must be set.

**Comment by nitro322** [comment]
oh.  So short answer - yes, I disabled it, and re-enabling it allows my calendar color to persist.  Excellent.

Discussing that option more specifically, though, I disabled it because every time I re-enabled the account it'd want to sync extra folders (Tasks and Contacts) that I didn't want or need, taking longer to re-initialize ever time.  Tasks especially used to take something like 80s to complete the first sync, even though I don't use that feature, though that no longer seems to be the case now.  I've since enabled contacts syncing with the GAL search feature, but I still disable Tasks every time just because it's not needed.

The main issue now, I think, is that the option you highlighted option doesn't indicate it has anything to do with caching.  I honestly never would've guessed it was related to this issue.  It might be a good idea to either update that description or perhaps de-couple the caching functionality from that option.  I'm not sure of the edge cases you'd run into, but is there a reason you wouldn't want to always cache, and clear only when the account is deleted vs. disabled?

Either way, I'm good now.  Leaving it enabled isn't a major issue now that I know better what it does, and with all the improvements you've been making I have to re-enable my account much less frequently these days.  :-)  Leaving open for now just in case you have any further comments, but please feel free to close.

As always, thanks for your prompt response.

**Comment by jobisoft** [comment]
Just to make sure: That option should also honor your task-selection (or better your task-deselection).

If you have that option set, TbSync will sync all default folders on initial sync. If you than deselect the task folder (right click or double click on its folderlist entry) and than disable the account and re-enable it, the task folder should not be synced anymore. But its color setting is still cached, if you manually enable it again, it should come back with its old color.

TbSync caches the entire account configuration and tries to restore as it was before, including some folder specific settings. If that option is not set, nothing is cached.

That is what this option is currently doing. What behavior would you propose?

**Comment by jobisoft** [comment]
I did some thinking about this. I changed it as follows:
- caching is now always on and cannot be disabled
- the option is reduced to "subscribe to default folders on initial sync"
- if account gets disabled and re-enabled, that option has no effect, TbSync will always restore the last cached state

Feedback would be nice:
https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-beta.xpi

**Comment by nitro322** [comment]
Apologies for the delay - got tied up yesterday.  The new approach you described makes perfect sense to me.  I tested out the beta and confirmed that the caching is properly handled regardless of the initial sync option.  Looks great to me.

Thanks again, John.  This keeps getting better and better.
