### ISSUE TITLE
FAQ of users switching from the exchangecalendar extension to TbSync

### ISSUE THREAD

**Issue by afettouhi** [jobisoft/TbSync#106]
I recently switched to tbsync because like a few others I was using the exchangecalendar extension for my exchange calendar and then Thunderbird updated to version 60. My question is now does tbsync currently support sharing other users calendars? With the exchangecalendar extension I was able to add and see my siblings calendars. Is this possible with tbsync? If not is there plans to implement this?

**Comment by jobisoft** [comment]
Hi,

TbSync is using exchange active sync (EAS), not exchange web services (EWS), to talk to your server. These are two different protocols  and EAS simply does not support access to shares resources (on Microsoft servers). So I cannot implement that with EAS.

But there are plans to add EWS support to TbSync, but that will take a while.

https://github.com/ExchangeCalendar/exchangecalendar/issues/182

John

**Comment by jobisoft** [comment]
Also please note the following:

Sometimes TbSync is not syncing any entries from the Microsoft Exchange Server to Thunderbird without throwing an error message, even though there are entries on the server. It has been observed, that it sometimes needs an initial sync from Thunderbird to the server to "activate" the connection. So simply add an entry in Thunderbird and sync that to the server, with the next sync all remote entries should be synced down to Thunderbird.

It has also been observed, that it needs some time, before Microsoft Exchange Server accept TbSync as a client. Set auto sync to 10min and just let it sit there for a day/night.

**Comment by afettouhi** [comment]
Thanks for the clarification. Been using it for a few days now and seems to work fine so far. Looking forward to the EWS implementation when that is ready.

**Comment by jobisoft** [comment]
Thanks for your feedback, I keep this issue open for others to see.

**Comment by ovari** [comment]
Will [Exchange Calendar](https://github.com/ExchangeCalendar/exchangecalendar) become a Provider (like [DAV-4-TbSync](https://github.com/jobisoft/DAV-4-TbSync) and [EAS-4-TbSync](https://github.com/jobisoft/EAS-4-TbSync)) for [TbSync](https://github.com/jobisoft/TbSync/) in the future?

Thank you

**Comment by jobisoft** [comment]
I plan to help them to convert. But do not expect anything soon.
