### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by edmunch** [jobisoft/TbSync#107]
Please keep on going. This is an essential function preventing me switching to Outlook.

So how can i donate?

Best Regards
Maik

TbSync version: 0.7.10.18
Thunderbird version: 60.0

**Comment by jobisoft** [comment]
Thanks for considering a donation! You can donate via paypal:
https://www.paypal.me/johnbieling

**Comment by edmunch** [comment]
+50€. thank you

**Comment by jobisoft** [comment]
Thank you! Push will be implemented in 2018 :-)

**Comment by ldmpub** [comment]
And for email, the full answer can be found here: https://github.com/jobisoft/TbSync/wiki/What-about-email-support-via-EAS%3F
