### ISSUE TITLE
Screenshots in the setup guide are in German, please translate to English

### ISSUE THREAD

**Issue by MagicFab** [jobisoft/TbSync#108]
Thank you for your work on TbSync Account Manager.

This add-on was very useful when I recently [helped someone find a solution to sync Thunderbird and their Office 365 information](https://support.mozilla.org/en-US/questions/1229595).

The [documentation for setting up TbSync](https://github.com/jobisoft/TbSync/wiki/How-to-sync-an-existing-Thunderbird-calendar-to-a-remote-EAS-account) has German screenshots, would it be possible to update it with English screenshots? I would have helped with this but I don't use Office 365 or Outlook so I can't make the screenshots.

**Comment by jobisoft** [comment]
I will update the screenshoots. 

But just to make sure: The link you provided in the forum is not the standard guide to set up TbSync, which is [here](https://github.com/jobisoft/TbSync/wiki/How-to-get-started) and I tried to be as specific as possible (but still some german screenshots).

The link you used is describing how to copy an existing local calendar (which has nothing to do with Office365, could be from anywhere) into an Office365 account. I think that was the wrong link for the user?

**Comment by MagicFab** [comment]
I didn't go through the documents myself but noticed the screenshots. I think it would be nice to link to the main document from the add-on page itself, thanks for clarifying that.

**Comment by jobisoft** [comment]
Done. Could you update the link in the forum? 

Thanks!

**Comment by jobisoft** [comment]
One other thing, if you ever have to deal with such a question:

It is not known, if the sogoconnector for CardDAV sync will be fixed to work with TB 60.0. One can of course switch to CardBook, but that is "to much" for me and one of my clients. That is why I added CardDAV support to the latest beta of TbSync.

I think the next stable will be released in 2 or 3 weeks, including that new feature. Up to then, one has to use the latest beta, to get CardDAV sync with TbSync.

**Comment by MagicFab** [comment]
@jobisoft link fixed, many thanks for the update!

Regarding SOGo connector [it will support TB60](https://lists.inverse.ca/sogo/arc/users/2018-07/msg00062.html), it's just not clear when.

More choices to sync CalDAV from TB are always welcome!
