### ISSUE TITLE
Office365 calendar sync

### ISSUE THREAD

**Issue by eberna** [jobisoft/TbSync#109]
## Your environment

TbSync version: 0.7.10.19
Thunderbird version: Thunderbird 60 on debian testing

[ x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync calendar with office365 exchange account

## Actual behavior
Successfully added a office365 exchange account but still no sync with calendar or tasks, if i add a calendar event i get the error: The EAS server rejected your items for the following reasons: 1x <Invalid item! Mandatory fields missing? Dublicate item?>. Check the debug log for "Bad item skipped".

## Steps to reproduce

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
So it is resolved now? Than it can be closed indeed.
