### ISSUE TITLE
How to use TbSync with self signed SSL's

### ISSUE THREAD

**Issue by pyromanci** [jobisoft/TbSync#11]
In my office I'm the only employee who needs access to their email outside of the office. While i do have a VPN to the office from my home this does not help when i'm out and about. So I setup a webmail and Active Sync for mobile. But considering i'm the only person who needs it, we didn't waste money on a real SSL. 

To get around the SEC_ERROR_UNKNOWN_ISSUER error message, the self signed SSL certificate needs to be added to Thunderbird:

* In Mozilla Thunderbird, go to Tools > Options > Advanced > tab Certificates.
* Click on View Certificates and go to tab Servers.
* Click on Add Exception.
* Enter the name of your mail server and click on Get Certificate.
* Save the exception.

**Comment by Feli-xyz** [comment]
+1

Thank you.

**Comment by embeddedDev** [comment]
Great thanks to the core developer and all the maintainers of the ancestor projects at first.
I think the word choice should be more friendly at first, there is no "need" to be anything at last!
Where is the problem to use (a well-signed free certificate you can get from) Let's Encrypt? The developer did a great work so far and does not have to care of others' insufficient expertise on administering servers and security.

**Comment by pyromanci** [comment]
No need to fucking ass embeddedDev. It's not a insufficient expertise. It's simple matter of being stuck on a old windows server cause of a penny pinching boss. Resulting no existing certbot for Let's Encrypt on that platform.

**Comment by jobisoft** [comment]
If I understand your edited first message correctly, it works now? This issue breaks down to "inform the user, that there is an ssl exception due to untrusted cert and show the user your steps above to resolve the issue?"

**Comment by jobisoft** [comment]
I might have found a simple way to inform the user about the SSL stuff. Could you send me the URL to your EAS server with the untrusted SSL, so I could test it? I just need the URL, no username or password. You could send it to my official e-mail address, if you do not want to post it here.

**Comment by Alwinator** [comment]
In newer versions, you can find the setting under 
Edit > Preferences > Privacy & Security > Certificates > Manage Certificates > Server > Add Exception
