### ISSUE TITLE
Latest version available: 0.0.0.0

### ISSUE THREAD

**Issue by ovari** [jobisoft/TbSync#112]
## Your environment

TbSync version: 0.7.10
Thunderbird version: 52.9.1

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Latest version available: x.y.z.r

## Actual behavior
Latest version available: 0.0.0.0
![image](https://user-images.githubusercontent.com/17465872/44450661-d4975d80-a634-11e8-8db8-446b54f5bba5.png)

## Steps to reproduce
See screenshot above.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by ovari** [comment]
![image](https://user-images.githubusercontent.com/17465872/44453166-c39e1a80-a63b-11e8-8f5a-ec847d701afa.png)

**Comment by ovari** [comment]
Updated without a restart. Does your add-on update without needing to restart?

**Comment by jobisoft** [comment]
yes, it is restartless, ready for TB61+

**Comment by jobisoft** [comment]
Thanks for reporting this, is fixed now. The error occurred, because there was no beta version at the moment and the help screen was only looking for beta versions.

Fixed and released a new beta, which "fixes" this also for older versions.
