### ISSUE TITLE
Empty folders using Office365 EAS

### ISSUE THREAD

**Issue by mabuchho** [jobisoft/TbSync#117]
## Your environment

TbSync version: 0.7..12.4 beta
Thunderbird version: 60.0

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
All folders should be in sync using Office365 EAS

## Actual behavior
Folders are sychronized and sync status is marked as "ok" but all folders (address book, calanders, etc.) are emtp.

## Steps to reproduce
Integrate Office365 account within TBsync and start synchronization

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
-> email sent in parallel to this issue creation

**Comment by jobisoft** [comment]
This is [known](https://github.com/jobisoft/TbSync/wiki/Troubleshooting-(Exchange-ActiveSync)#microsoft-exchange-server-and-maybe-other-microsoft-servers-like-office365)

Currently I have no idea why.

**Comment by jobisoft** [comment]
What you could also try to "activate" the connection, is to search the GAL. Open a new email and type some name (longer 3 chars) into the TO field, TbSync will try to autocomplete from the directory of your O365. 

Wait a few minutes and than try to sync your account again, did that help?

**Comment by jobisoft** [comment]
Status?

**Comment by be-neth** [comment]
Hello,

I am not the original reporter of this issue, but I can confirm that your manipulation is working with the last beta release for me.
Contact folder is empty in my Exchange folder, but when I try to complete a contact it get from the GAL address list.

Btw, thanks for your addon ! I just switch from ExchangeCalendar[1] to this one, and it works well.

[1]: https://github.com/Ericsson/exchangecalendar

**Comment by jobisoft** [comment]
Just to make sure: 
 - TbSync did not sync anything down (no entries in calendar)
 - you did the GAL trick
 - you synced again and your calendar items showed up?

**Comment by be-neth** [comment]
> 
>     TbSync did not sync anything down (no entries in calendar)
Yep.

>     you did the GAL trick
Yes.

>     you synced again and your calendar items showed up?
I don't quite remember this. Something like : yesterday my calendar was empty, but I setup sync every 10 minutes and this morning I get my full calendar in thunderbird.

**Comment by mabuchho** [comment]
Hi guys,

stupid question: How do I access the Global address list within Thunderbird/TBsync? 

Within Outlook I have an entry within the address book in order search for related items. Within the synchronized TBsync Office 365 addressbooks I can't find it. When just typing in the first letters of a contact within a new email (as recommended above), nothing is happening (no look up seems to happen to the GAL implicitly).

Looking forward to your suggestions.

Best

**Comment by jobisoft** [comment]
Update: The GAL trick does not help. While the connection is not yet "activated", the search request returns status "3" = Server Error. Waiting and syncing every 10 min is the only solution at the moment.

**Comment by jobisoft** [comment]
@mabucho: After the server has accepted TbSync as a client (which might need some time on O365) the GAL is searched during autocomplete and if you search an addressbook connected to your O365 account.

**Comment by jobisoft** [comment]
No, sorry. I am investigating this, but have no clue yet. 

Make sure you have set auto sync to 10 minutes.

**Comment by mabuchho** [comment]
Done. I recognized that I'm receiving an error message "DeviceIsBlockedForThisUser" (status 129). The credentials are still ok.  When I'm using the same again, the sync status is ok but it's switching over again to status 129 after a few hours (reproducable issue).

**Comment by jobisoft** [comment]
Sorry, that means your enterprise does not allow TbSync. Get in contact with your IT, but I doubt they will remove that restriction. TbSync is "too small" and probably a "security risk" for your IT.
