### ISSUE TITLE
Request: More details in case of errors

### ISSUE THREAD

**Issue by edmunch** [jobisoft/TbSync#118]
## Your environment

TbSync version: latest
Thunderbird version: latest

[x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Suggestion
Handling with 4-5 calenders (tasks + events) in thunderbird is not fault tolerant like other applications.

- Sometime i'm not using the correct calender for task and events -> error message
- Sometime i'm making false events like Mo 10 - Di 12 + repeat until Di -> error message <invalid item! mandatory fiels missing? Dublicate item?

Problem is, that it's not obvious witch event or task the problem is, so that i'm spending some time to search the faulty event.

Maybe you find the time to point to the wrong events in the error message.

Thanks for your work

**Comment by jobisoft** [comment]
The faulty element is added to the debug log, can you enable debug log and try if that is helping you? 

But I also plan to add an easy-to-access sync-log, which contains status and error messages.

I use this issue as a reminder for the sync-log, so lets keep it open...

**Comment by jobisoft** [comment]
The latest beta now has a dedicated error log:

![image](https://user-images.githubusercontent.com/5830621/50366285-20bdc480-0579-11e9-9f1a-9fb46fd44a25.png)

If you want to try:
https://tbsync.jobisoft.de/TbSyncBetaInstaller.xpi
