### ISSUE TITLE
Meeting Requests Not Being Sent To Individuals

### ISSUE THREAD

**Issue by schoggy123** [jobisoft/TbSync#119]
## Your environment

TbSync version:  0.7.12.4
Thunderbird version: 52.9.1 (32-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...
meeting invitations should be emailed to people however they are not
## Actual behavior
...

## Steps to reproduce
...
create a meeting request and click save and send

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
This is part of the "meeting stuff" which is not yet supported fully. It is on the list, but not top priority.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#7
