### ISSUE TITLE
Email is not deleted after event acceptance

### ISSUE THREAD

**Issue by trourance** [jobisoft/TbSync#120]
## Your environment

TbSync version: 0.7.15
Thunderbird version: 60.0

[X ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Delete the email when the event has been processed.

## Actual behavior
When I receive and accept an invitation (with multiple events) sent to the email address used with tbsync, the email stays in my inbox.

## Steps to reproduce
Click Accept (or Accept all) and see the email still in inbox. Even if you force the synchro.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by trourance** [comment]
Ok, thanks for the information.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#6
