### ISSUE TITLE
Merges unrelated contacts (quite major issue)

### ISSUE THREAD

**Issue by poVoq** [jobisoft/TbSync#123]
## Your environment

TbSync version: Dev version updated 30.August
Thunderbird version: 60.0 (Windows10)

[ x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When right clicking on contact in mail interface and selecting "edit contact" and then changing the Addressbook from a local to a CardDAV one it should copy the contact and delete it in the local one.

## Actual behavior
The contact is deleted in the local one, but merged with an existing contact in the CardDAV Calendar (Some field get overwritten others ramain). It is not clear to me if it happens at random or based on some hidden numeric ID.

## Steps to reproduce
See above.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/DAV-4-TbSync#30
