### ISSUE TITLE
Bad item skipped

### ISSUE THREAD

**Issue by NormRobichaud** [jobisoft/TbSync#124]
## Your environment

TbSync version: 0.7.15
Thunderbird version: 60.0

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

... Sync calendar without errors

## Actual behavior

... Syncing calendar with error, "The EAS server rejected your items for the following reasons: 1x <forbidden Tasks item in Calendar folder>. Check the debug log for "Bad item skipped".

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That is an instruction, not an error. I will send more details via email.
