### ISSUE TITLE
Office365 stopped working after update of TbSync

### ISSUE THREAD

**Issue by plague-doctor** [jobisoft/TbSync#126]
## Your environment

TbSync version: 0.7.5.0-5
Thunderbird version: 60.0 (64-bit) Arch Linux

[/] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Connect to Office365 and sync calendar, tasks, etc.

## Actual behavior
Connects, no error, all ok - nothing displays on calendar; no way to search for addresses
When adding the new event and trying to re-sync - it errors out with 
`
The EAS Server rejected your items for the following reason: 1x <Invalid item! Mandatory fields missing?
Duplicate item?>. Check the debug log for "Bad item skipped".
`

## Steps to reproduce
Every time since upgrade of TbSync. 

Reverting to the previous version dos not help...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

[tbsync_log](https://ybin.me/p/e4a8d8cd219ab006#b6+ZvSzqP60Gr9H9J7YA9sk3NNTe/58wuITUuoRqrfg=)

**Comment by jobisoft** [comment]
What do you mean with update? 

1. Does a working TbSync install stopped working and shows empty calendar, after TbSync has been updated, so it actively removed all entries from a lightning calendar?

2. You tried to setup a new TbSync Install (so no local data avail), but this time, after syncing, no entries are downloaded from the server?

What was the last version this worked for you?

**Comment by tuxtm** [comment]
I had a similar issue yesterday with the latest beta version available (I have updated TbSync from the Help tab of the TbSync Account Manager window). As suggested here [https://github.com/jobisoft/TbSync/wiki/Troubleshooting-(Exchange-ActiveSync)](url), I have set the Sync Interval (minutes) property to 30 and left it over night. In the morning all the events the were available in the Office 365 Web portal were synced to Thunderbird and the event created from Thunderbird was also available in the Office 365  Web portal.

**Comment by jobisoft** [comment]
Do you know, what version you were using before the update? Was there also a Thunderbird update in between? 

The Thunderbird update could change the UserAgent, which is the only reason I can think of, which might cause this (the "identifier" of your TbSync has changed, which might reset your connections state on the remote server)

**Comment by tuxtm** [comment]
I forgot to mention that Wednesday(19.09.2018) I have installed Thunderbird and TbSync for the first time. The versions were the last versions officially available (60.0 for Thunderbird and  0.7.15 for TbSync). So there was no Thunderbird update that could cause the issue, and also. When I was saying that I had a similar issue I was referring to the  error message 

>The EAS Server rejected your items for the following reason: 1x <Invalid item! Mandatory fields missing? Duplicate item?>. Check the debug log for "Bad item skipped". 
 cause by the fact that TbSync tried to send an event created in Thunderbird to the Office 365 server, and the server rejected the update.
 I apologize for the misunderstanding.

**Comment by jobisoft** [comment]
@tuxtm That clarification was important :-) So your issue was "case 2" of https://github.com/jobisoft/TbSync/issues/126#issuecomment-424215537 and was just the standard trouble on initial connection. And yes, sometimes the server sends that bold error, if you want to send something to the server, but the connection is not yet "active". I wish I knew why this happens...

@plague-doctor Can you comment on https://github.com/jobisoft/TbSync/issues/126#issuecomment-424215537 ?

**Comment by plague-doctor** [comment]
Sorry for a delay, @jobisoft . We leave in different time zones, so the communication may be a bit tricky.
I have upgraded from version 0.7.12 to 0.7.15.x (not sure about x anymore) and it stopped working completely. So I have tried the standard options: re-create connection, leave it for a night with 15 minutes interval -  nothing. I have tried to downgrade back to 0.7.12 - nothing.

I have checked the status of the mobile agent in my office365 - I have found three TbSync devices with right synchronization time and status OK. 
I have removed them all and re-tried steps above - same thing - no events are displayed in Thunderbird, same error is generated when I try to create a new event and synchronize.

What else can I try? At the moment I use Exchange Calendar (4.0.0-beta6) compiled manually. It works, but the usability is nowhere near to TbSync...

**Comment by plague-doctor** [comment]
Can you please precise "completely removed"? I just click on "Delete account" from the account list in TbSync. Do I need to do something extra?

No, autodiscover never worked for me. My company uses office365 with our own domain name and SSO.

**Comment by jobisoft** [comment]
Remove is ok, some users only disable.

Could that be a common base for this error? "My company uses office365 with our own domain name and SSO"

@tuxtm : Does autodiscover work for you?

**Comment by jobisoft** [comment]
@plague-doctor Do you know someone from your IT, who has access to the O365 Exchange Admin Center?

**Comment by plague-doctor** [comment]
unfortunately not. This is a corporate and everything goes through the proper channels... :(

**Comment by plague-doctor** [comment]
I have tried autodiscover once again - it tries to do it for some time, but errors out (timeout?). Interesting thing is, when I use the wrong username or I type the wrong password it errors out right away with wrong credentials error.

**Comment by jobisoft** [comment]
I just tried something, I am admin of an O365 Server (just like your IT) and I enabled quarantine for all unknown devices -> I do not get any events anymore.

ALSO (and that is bad), TbSync is not showing up in the quarantine list. My iPhone however does show up (and can be released). 

I will now let it sit there for a while and see what happens. Later I will try to add a rule to allow TbSync. Interesting...

**Comment by plague-doctor** [comment]
Is there a way to spoof a device? What to do to pretend it is Android? :thinking:

**Comment by jobisoft** [comment]
There might be something in the air, but I have to go to bed. I will check this tomorrow.

**Comment by jobisoft** [comment]
Hm, now I did get the quarantine notification and I did show up in the list… need to Sleep.

Your device is temporarily blocked from accessing content via Exchange ActiveSync because the device has been quarantined. You don't need to take any action. Content will automatically be downloaded as soon as access is granted by your administrator.

Information about your device:
Device model: 	TbSync
Device type: 	TbSync
Device ID: 	mztb3155420189c6520c9209fb197903
Device OS: 	
Device user agent: 	Thunderbird ActiveSync Lightning/6.2
Device IMEI: 	
Exchange ActiveSync version: 	14.0
Device access state: 	Quarantined
Device access state reason: 	Global

**Comment by jobisoft** [comment]
I deleted the last comment because it was misleading, it has nothing to do with quarantine. It is about how I identify. I tried something new. Wanna try?

Please remove your account first, then install the new version, and create the new account and see what happens...
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/2421486/TbSync-beta.zip)

**Comment by plague-doctor** [comment]
Ha! Now we are cruising again!
Whatever you did - it worked right away. Kudos!

Thanks a lot!

**Comment by jobisoft** [comment]
Nice. 

The version you use now is bleeding edge. I continued to work on it and would ask you to upgrade to the next beta release candidate:
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/2421630/TbSync-beta.zip)

Would you risk to remove your account again and create a new one with this version?

**Comment by plague-doctor** [comment]
Works like a charm :+1:

**Comment by tuxtm** [comment]
@jobisoft 
Sorry for the late reply. I didn't seen your question until now.
Yes, autodiscover works for me!
