### ISSUE TITLE
Cannot authenticate, "asversion is not defined"

### ISSUE THREAD

**Issue by tgoeg** [jobisoft/TbSync#127]
## Your environment

TbSync version: 0.7.15.5
Thunderbird version: 52.9.1

[/] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync should be able to login

## Actual behavior
Login impossible due to "asversion is not defined" in the debug log:
```
** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[setSyncState] : State: prepare.request.options, Account: user.name

** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[Sending] : OPTIONS https://mail.my.domain/ews/exchange.asmx/Microsoft-Server-ActiveSync

** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[setSyncState] : State: send.request.options, Account: user.name

** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[setSyncState] : State: eval.request.options, Account: user.name

** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[EAS OPTIONS with response (status: 200)] : 
responseText: 
responseHeader(MS-ASProtocolVersions): null
responseHeader(MS-ASProtocolCommands): null

** Thu Sep 27 2018 10:35:04 GMT+0200 (CEST) **
[setSyncState] : State: accountdone, Account: user.name

** Thu Sep 27 2018 10:35:05 GMT+0200 (CEST) **
[JavaScript Error: "asversion is not defined" {file: "chrome://tbsync/content/provider/eas/eas.js" line: 493}]
eas.start<@chrome://tbsync/content/provider/eas/eas.js:493:25
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
```
## Steps to reproduce
Our Exchange (2016?) does not allow autodiscovery. Therefore, I added the url manually as https://mail.my.domain/ews/exchange.asmx
No matter what version of ActiveSync I use, I always get the same in the debug log.

With 0.7.15 the error message in the UI is different: "Could not authenticate, check username and password"
and it repeatedly prompts for a username and password.
This is the content of the debug log for 0.7.15:
```
** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: prepare.request.options, Account: user.name

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[Sending] : OPTIONS https://mail.my.domain/ews/exchange.asmx/Microsoft-Server-ActiveSync

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: send.request.options, Account: user.name

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: eval.request.options, Account: user.name

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[EAS OPTIONS with response (status: 200)] : 
responseText: 
responseHeader(MS-ASProtocolVersions): null
responseHeader(MS-ASProtocolCommands): null

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: prepare.request.folders, Account: user.name

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: send.request.folders, Account: user.name

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[Sending (EAS v14.0)] : POST https://mail.my.domain/ews/exchange.asmx/Microsoft-Server-ActiveSync?Cmd=FolderSync&User=user.name&DeviceType=TbSync&DeviceId=mztbaab78afa73496ad6834f7fbe8ab7

** Thu Sep 27 2018 10:54:26 GMT+0200 (CEST) **
[setSyncState] : State: accountdone, Account: user.name
```

I am successfully using ExQuilla (but have to update to Thunderbird 60.x) so I do not think it is some kind of policy/blocking that prevents the authentication on server side.
Btw: Is TbSync supposed to work with Tb 60.x ?

If I use chromium to visit https://mail.my.domain/ews/exchange.asmx I can successfully login and get the .wsdl details. Responses of this request attached (.html renamed to .txt to allow uploading)
[logon.txt](https://github.com/jobisoft/TbSync/files/2423351/logon.txt)
[Service.txt](https://github.com/jobisoft/TbSync/files/2423352/Service.txt)

**Comment by jobisoft** [comment]
I fixed the asversion issue, but this is not your actual issue. You are using the wrong URL.

TbSync is a client for Exchange ActiveSync, the URL you use is an URL for Exchange WebServices.

SInce autodiscover does not work, it could be that your Server does not support EAS. But you can ask your IT for help.

Could you update to beta .6 and try again just using the base URL?
https://mail.my.domain

**Comment by tgoeg** [comment]
Thanks, problem solved! I always had to enter https://mail.my.domain/ews/exchange.asmx manually in ExQuilla, that's why I instinctively entered it here too, although the base url would be a lot more logical.
If possible, probably just add this as hint next to the input field.
Now I "just" have to find a way to also sync mails - I know that's not on your roadmap..
