### ISSUE TITLE
Cannot add exchange account

### ISSUE THREAD

**Issue by reaganch** [jobisoft/TbSync#128]
## Your environment
Linux Mint 19 Cinnamon

TbSync version: 0.7.15.7 (latest beta)
Thunderbird version: 60.0

[Check] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I downloaded and installed TBSync from the Thunderbird addons page (do not remember version I downloaded) for the first time a week ago when I was running Thunderbird 52.9. At this time, I was able to add my exchange account and worked flawlessly for a week, syncing both my contacts and calendars.
A couple of days ago, my OS auto-upgraded Thunderbird to 60.0 and TBSync still worked without a glitch for the last two days.

## Actual behavior
Just about an hour ago, first my Contacts folder disappeared from the TBSync folder sync list (on the right side of the TBSync window). Upon opening the address book, the exchange address book being synced by TBSync was saved as a local backup and no longer being synced. So I tried removing the exchange account from TBSync and re-adding, but have been unable to re-add my account using the same settings as I did the first time around. Updating to the latest beta version (0.7.15.7) and downgrading to the previous version (0.7.12) do not solve this.

## Steps to reproduce
Install latest beta version of TBSync and try adding exchange account.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
What is the error reported by TbSync? Why is it not working anymore? Can you send me a debug log?
https://github.com/jobisoft/TbSync/wiki/Found-a-bug%3F

Can you check the connection validator, if your server still supports ActiveSync (your IT may hav switched it off)

https://testconnectivity.microsoft.com/

**Comment by jobisoft** [comment]
Please use the latest beta for your tests. It fixes lots of issues regarding enterprise setups...

**Comment by reaganch** [comment]
Thanks so much for your prompt response to this. I think I'm using the latest beta (v0.7.15.7) downloaded from the Releases section of this github page.
But it appears the server is down from checking at https://testconnectivity.microsoft.com/. Thanks a lot for sharing this. I had no idea such a testing tool existed. Will definitely post back here after checking on the server status with my IT folks.

**Comment by reaganch** [comment]
It's odd though. I have the same account synced on my mobile phone using EAS, and things seem to be syncing perfectly fine (both ways) on it.

**Comment by jobisoft** [comment]
Your mobile may use EWS. If it justs says "Exchange" you never know what it is actually using.

**Comment by reaganch** [comment]
Still haven't heard back from IT, but I think I may have finally solved this mystery. It appears there may be a limit of 10 phones I can have simultaneously connected to my exchange account via ActiveSync under Outlook Web Access -> Options -> Phone -> Mobile Phones. After deleting a bunch of old entries, I'm able to successfully add my exchange account via TBSync again.

Thanks so much for your help trying to troubleshoot this and apologies for the false alarm.

Love the work you're doing with this addon!
