### ISSUE TITLE
Category Sync with ZOHO

### ISSUE THREAD

**Issue by Zavars** [jobisoft/TbSync#129]
## Your environment

TbSync version: 0.7.15
Thunderbird version: 60.0 - 32 bit

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I use Zoho for my email.  TbSync will sync the address book, however my Zoho contact categories are not pulled over and do not show up using the CategoryManager extension.

## Actual behavior
Was hoping to be able to sync categories to keep contact better organized.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
After asking Zoho twice to get a test account (and they declined) I no longer support Zoho. It works with other providers, except outlook.

**Comment by Zavars** [comment]
I can provide you with a test account if you'd like.

**Comment by jobisoft** [comment]
With enabled EAS? The free accounts do not have that. But yes, send further details to my email address.
