### ISSUE TITLE
Contacts sync Office365 Directory Lists

### ISSUE THREAD

**Issue by cseader** [jobisoft/TbSync#131]
## Your environment
openSUSE Tumbleweed Latest Weekly Build

TbSync version: 0.7.16
Thunderbird version: 60.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When getting a list of Contact Lists I want to see the Office365 Directory Lists such as All Rooms, All Users, All Distribution Lists, All Contacts, All Groups, Offline Global Address List. 

## Actual behavior
The actual behavior is that all I see from Office365 is the "Your Contacts" Lists which are Contacts, Skype for Business Contacts, Other contacts, Business, Frequent Contacts and others that were created.

## Steps to reproduce
Sync for the first time. :-) not much to it. It just never pulls in Office365 Directory Lists for Corporate directories. I know it works because I can search them using my phone. So I know active sync can for sure sync them.

**Comment by jobisoft** [comment]
The directory is not pulled as separated "books". They are searched if you enter something into the search bar inside the Address book or if you type a recipient into the message composer.

Does that answer your question?

**Comment by cseader** [comment]
> The directory is not pulled as separated "books". They are searched if you enter something into the search bar inside the Address book or if you type a recipient into the message composer.
> 
> Does that answer your question?

No. I'm not experiencing this behavior. If I search anywhere I don't get a result of someone that would be in my Directory Listing at all. It never works. How would it know to search the Directory? So if this is the case then how would I set this up?

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#12
