### ISSUE TITLE
Vacation Message / Out of Office Message ?

### ISSUE THREAD

**Issue by ds2k5** [jobisoft/TbSync#132]
Hi,
is it possible to get a "Vacation Message / Out of Office Message" Manager ?
Thanks

**Comment by jobisoft** [comment]
That would be possible but it's not on my agenda. But I am open for pull requests ("someone else may do it")

**Comment by sphh** [comment]
This was the only issue which kept me from switching from ExchangeCalendar to TbSync! Now that I was automatically updated to TB60, ExchangeCalendar does not work anymore and I had to switch.

Maybe the code used by ExchangeCalendar does help implementing this feature for all TB users who have to use Exchange Servers:

- https://github.com/ExchangeCalendar/exchangecalendar
- https://github.com/Ericsson/exchangecalendar

**Comment by sphh** [comment]
I just found https://github.com/ExchangeCalendar/exchangecalendar/issues/182. Will this adapter include vacation / out of office messages?

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#11
