### ISSUE TITLE
Keep backup of config files in case of crash-on-write

### ISSUE THREAD

**Issue by Dagefoerde** [jobisoft/TbSync#133]
## Your environment

TbSync version: 0.7.16
Thunderbird version: 60.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
As long as I don't actively delete my account from TbSync settings, I expect them to remain configured and to continue syncing my calendar.

## Actual behavior
The account mysteriously disappeared from TbSync settings and synchronisation stopped completely. However, the calendar remained visible in Lightning, including all events that have once been synchronised to my computer. The calendar shows no indication of a problem whatsoever, i.e. it took a few days until I discovered that synchronisation has halted.

## Steps to reproduce
[sadly, I have no idea what went wrong. I am happy to assist in finding the cause of this, if you have an idea how I can investigate this]

**Comment by jobisoft** [comment]
That is very strange and the first time I heard that. There is no method for deleting accounts except the one attached to the delete button. Can you email me the 3 json files in the tbsync folder inside your thunderbird profile folder? They do not contain passwords, but all other config data. I also need the name of the vanished account.

**Comment by Dagefoerde** [comment]
Hm, interesting thought. Battery is okay, but my computer regularly freezes so from time to time I have to restart it. 
Usually that shouldn't corrupt these files though, should it? I would assume that `accounts.json` would only be written occasionally, and if it is not being written at the time of restarting (or just before that) the contents of that file should remain unaffected.

**Comment by jobisoft** [comment]
It is always written on TB close and on each sync (the global folder sync key). If something goes bad during write, the file is corrupt. That one is not easy to fix...

**Comment by Dagefoerde** [comment]
Ah, I see you changed the title. That was a solution that I was thinking about, too. However, would that really help? I am worried that we would write a backup and a new file - and then **both** would get corrupted, leaving us with two corrupt/empty files...

Anyway, I was wondering whether something different may be the case. I have had a first look at the code and saw that db.accounts, db.folders, and db.changelog are populated asynchronously by the `init` method in `content/db.js`. Persisting methods write the contents of these properties to disk. However, these persisting methods never check whether the properties have actually been initialised. For example, on shutdown files are saved, but `init` is asynchronous, so it might not have run yet.

**Comment by Dagefoerde** [comment]
If you agree that this is at all possible, I'd like to offer trying to develop a patch. I haven't worked on Thunderbird extensions before, but I'd love to try.

**Comment by jobisoft** [comment]
Sure, I am open for PR! Help is always appreciated. At the end of the init sequence (after the JSON files have been read), tbSync.enabled gets set to true:

https://github.com/jobisoft/TbSync/blob/v0.7.16/content/tbsync.jsm#L304

I use that all over the place to check, whether I am allowed to do stuff, like open the Manager, sync etc. I should of course also only write stuff to disk, if that is set to true. I think I am NOT checking that at the moment. Which is bad.

I also do not have an idea on how to do that backup stuff. I do use atomic writes to minimize crash on write errors:
https://github.com/jobisoft/TbSync/blob/v0.7.16/bootstrap.js#L189

But maybe this issue is simply due to your finding of me writing DB files, even if not read?

**Comment by Dagefoerde** [comment]
Thanks for the assessment and the pointer towards `tbSync.enabled`. I will have a look at that!

**Comment by jobisoft** [comment]
maybe introducing some sort of checksum, to know during read, that the file is valid? just brainstorming...

**Comment by jobisoft** [comment]
forget that, if the file did not load, it will probably never load again, so no need to check something. All we would learn is "oh, broken, got to reset", what is happening anyways... so this is realy just an issue for the write... I think ...

**Comment by Dagefoerde** [comment]
Still not a bad idea, because then the extension would be able to show a warning that the config is broken and needs to be reset. Part of my problem was that I didn't even know that the account was not configured anymore until I found out by chance.

**Comment by jobisoft** [comment]
I played around with backup files and it is not helping. If I only keep one backup, than the chance is almost 100% that the user somehow also overwrites the good backup. The other solution would be to keep multiple backups but than we again have to decide which and how often. 

I decide to close this issue. I think you found the main cause. If it ever happens again, we may rethink this.

**Comment by Dagefoerde** [comment]
I tend to agree that the backups would probably be overwritten as well. Thanks for playing around with it. I have not experienced the original issue in the recent version and believe that it is indeed fixed.

Thanks a lot for your work on this add on.
