### ISSUE TITLE
UI broken with latest beta with Thunderbird < 60

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/TbSync#134]
## Your environment

TbSync version: 0.17.6.5
Thunderbird version: 52.9.1
Linux Ubuntu 18.04

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

In my case, this issue does not happen with 0.17.6. With the latest beta I have two issues
1/ the fonts look out of place. Compare how 0.17.6 uses the same UI fonts as Thunderbird whereas 0.17.6.5 doesn't
![bildschirmfoto von 2018-10-10 02-20-53](https://user-images.githubusercontent.com/3609611/46706323-18214780-cc34-11e8-8be2-f41128aeba5c.png)
![bildschirmfoto von 2018-10-10 02-23-31](https://user-images.githubusercontent.com/3609611/46706324-18214780-cc34-11e8-842d-363abe1e8f3c.png)

2/ The more important part, the UI is completely empty. I can switch between the 4 tabs, but they just show a grey area.

**Comment by mbiebl** [comment]
I've just tried this on another distro which has Thunderbird 60.
While the font issue still persists, the UI is not completely broken. So I suspect this is related to the Thunderbird version. I'll use this bug report for the problem with TB 52.9 and file a separate one for the font issue.

**Comment by jobisoft** [comment]
So if i enforce TB60 as min version for the next stable release of TbSync, this would be fixed?

But it is still strange, the latest changes work on MacOS and on Windows, but not on Linux?  Hm...

**Comment by jobisoft** [comment]
To simplify the workflow, I close this issue, it is strongly related to #135
