### ISSUE TITLE
TbSync does no longer use system configured fonts / font sizes

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/TbSync#135]
## Your environment

TbSync version: 0.17.6.5
Thunderbird version: 60.0

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

As you can see from the attached screenshots, the fonts with 0.17.6.5 look out of place. With 0.17.6 the correct fonts are used.

![bildschirmfoto von 2018-10-10 02-59-34](https://user-images.githubusercontent.com/3609611/46707143-e3fc5580-cc38-11e8-9af3-d0ce71d65e45.png)
![bildschirmfoto von 2018-10-10 03-00-08](https://user-images.githubusercontent.com/3609611/46707144-e3fc5580-cc38-11e8-84f0-ae60ae765876.png)

**Comment by jobisoft** [comment]
I think I will not be able to make everyone happy here. I fixed an issue, where the UI was messed up if the user has enforced a min font size in the Thunderbird options. That min font size setting should be applied to emails and stuff, but not UI. However I was using the wrong display mode and that min font size setting messed up the TbSync UI to be unusable.

Now I use the correct display mode, where I as the developer can define fonts and sizes and make it look the same on all systems. When you say "out-of-place", is there anything "cut off" which makes the UI unusable right now?

**Comment by jobisoft** [comment]
What does this version do?
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/2463735/TbSync-beta.zip)

**Comment by jobisoft** [comment]
In this version I also changed how the subframes of the manager are loaded, can you test this one with TB52?
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/2463886/TbSync-beta.zip)

**Comment by jobisoft** [comment]
I could verify your empty-tab observations on TB52 and the fix seems to work, so I released a new beta so that others do not run into this issue. 

Can you give feedback on the font issue? I removed a fixed font size setting in my css, so it is now using some default value as before I guess, but is not bound to the minimum font size setting anymore.

**Comment by mbiebl** [comment]
0.17.6.6 works great (fonts look normal again, UI works with TB 52)
Thanks a lot
