### ISSUE TITLE
Why do calendar colours disappear every time TBSync synchronises?

### ISSUE THREAD

**Issue by alurasg** [jobisoft/TbSync#136]
## Your environment

TbSync version:  0.7.16
Thunderbird version: 60.2.1 (32-bit)

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Within Thunderbird, I adjusted the calendar colours of all calendars synced via TBSync (via  sabre/dav). I expect them to stay as adjusted.

## Actual behavior
Everytime TBSync synchronises (no matter whether automatically or manually), all calendar colours are put back to the default light blue color.

## Steps to reproduce
See above.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I take the color from the server. Try changing it in your web interface.

**Comment by jobisoft** [comment]
To be precice, this only happens for caldav calendars, so I close this here and add that as a question at [dav-4-tbsync](https://github.com/jobisoft/DAV-4-TbSync/issues/21).
