### ISSUE TITLE
[feature request] edit account settings

### ISSUE THREAD

**Issue by pcause** [jobisoft/TbSync#137]
There doesn't seem to be a way to edit an account.  For example, if I change my O365 password I'd like to just be able to go in and change the tbsync password.  at least have a password change option, please.

**Comment by jobisoft** [comment]
Next time you manually sync your account, you will get prompted for a password, if the server reports the currently used one is wrong.

Settings are not changable by design, because that could mess up the sync state. You must disable your account to edit its settings. You can view your current settings by double clicking the small slider below the folder list.

**Comment by pcause** [comment]
understood.  could you have an "edit" item that pops up saying to edit you are going to disable.  if user says "yes" then you disable and allow the account to be edited.  just makes is obvious how to do it.  didn't know disable would let me edit.

**Comment by jobisoft** [comment]
If you have time, could you make a screenshoot of the current manager and modify that and place an edit button (or whatever you have in mind) somewhere, so that it still looks nice?

**Comment by sphh** [comment]
What about adding an `Edit` item to the context sensitive menu which appears when right-clicking onto an account in the account list in the `TbSync account manager`? Also adding this `Edit` item to the `Account actions` at the bottom of the account list would make a lot of sense to me ...

**Comment by jobisoft** [comment]
I will probably go for tabs (like in the thunderbird settings window) in the right window pane, which will also be needed to provide access to an out-of-office-settings area... but this has low prio... so many other things to do...

**Comment by jobisoft** [comment]
I just released new betas with the new UI:

https://tbsync.jobisoft.de/beta/TbSync.xpi
https://tbsync.jobisoft.de/beta/DAV-4-TbSync.xpi
https://tbsync.jobisoft.de/beta/EAS-4-TbSync.xpi

You must update all modules you are currently using! Feedback is appreciated.
