### ISSUE TITLE
Sync Shared Calendar

### ISSUE THREAD

**Issue by laclaro** [jobisoft/TbSync#139]
Hello!

I would like to sync a shared calendar with folder ID like groupmeetings@server.com with my account myaccount@server.com. In the exchangecalendar addon (https://github.com/Ericsson/exchangecalendar/wiki/Exchange-EWS-Provider), there is a field to differentiate these two things, in TbSync not.

Please include this.

Best,

Henning

TbSync version: 0.7.16.6
Thunderbird version: 52.3.0

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F

**Comment by laclaro** [comment]
Unfortunately, https://github.com/Ericsson/exchangecalendar is not developed anymore, and ExQuilla is closed-source. Is it a huge piece of work to implement the EWS protocol for this feature (maybe based on https://github.com/Ericsson/exchangecalendar code)?

Best,

Henning

**Comment by jobisoft** [comment]
There was some comment about EWS Integration, but it is gone now? Long term goal is to support EWS via [EWS-4-TbSync](https://github.com/jobisoft/EWS-4-TbSync). But the original EWS Provider is also on its way to be functional again: 
- https://github.com/ExchangeCalendar/exchangecalendar/releases
- https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-431148291

**Comment by laclaro** [comment]
I would like to not involve a second addon just for the purpose of beeing able to sync a shared calendar. Maybe this is possible for myself, but for most users certainly not. Do you still work on this in https://github.com/jobisoft/EWS-4-TbSync?.

Best

Henning

**Comment by jobisoft** [comment]
I am underfunded so I cannot work on EWS at the moment. Together with my Thunderbird mentor, we are currently finalizing the TbSync API (external interface) so other authors can "hook" a provider into TbSync. I hope that I can get the EWS people to join forces and release one of their next versions as a TbSync provider.

I hope to have that ready when TB68 will be released, and I will help the EWS people to migrate (if they want to), but I cannot give you any time estimates or promises. It is all a hell lot of work.

Best regards,
John
