### ISSUE TITLE
Allow to change order of accounts in account manager (relevant for order of GAL search)

### ISSUE THREAD

**Issue by trourance** [jobisoft/TbSync#140]
## Your environment

TbSync version: 0.7.16.6
Thunderbird version: 60.0

## Expected behavior
Choose which contacts list is used first when I choose the recipient of an email.

## Actual behavior
I haven't try, but it seems that the first list used is the first one in the Accounts list. In that case, it would be nice to move up/move down the accounts to use another one first. Otherwise, it would be nice to set one as default.

**Comment by jobisoft** [comment]
I have not understood this issue. Can you provide screenshoots to point out what you are reporting?

**Comment by trourance** [comment]
Ok, I have two accounts as you can see in the screenshot. I would like that the email addresses of the second in the list appear as first suggestions when I choose the recipient.
![capture du 2018-10-16 10-33-54](https://user-images.githubusercontent.com/6951977/47003451-88960000-d12f-11e8-8d84-82b472cbf813.png)

Is it much clearer ?

**Comment by jobisoft** [comment]
What suggestion do you mean, can I have a screenshot of that as well? 

I think the order is taken from the alphabetical order of the adressbooks? Rename them in the thunderbird address books to swap positions?

**Comment by trourance** [comment]
No, because the one starting with "S" appears before the one starting with "F". And I would like the opposite.

**Comment by jobisoft** [comment]
I still do not know what suggestions you are referring to...

**Comment by trourance** [comment]
The ones that are displayed when you type the first letters of a recipient in thunderbird.
![suggestion](https://user-images.githubusercontent.com/6951977/47008685-0a3f5b00-d13b-11e8-9814-278734f5f001.png)

**Comment by trourance** [comment]
Yes, an extra sort property is exactly what would be useful in that case.
