### ISSUE TITLE
"No information" when creating events

### ISSUE THREAD

**Issue by GameMonkey** [jobisoft/TbSync#141]
## Your environment

TbSync version: 0.7.16
Thunderbird version: 6.2.1

## Expected behavior
When I want to create an event I expect to see when I, and others, are available. 

## Actual behavior
When I want to create a new event my information in the calendar is no available. 
Thunderbird directly states that my information is not available even though the calendar is synced.
![no_information](https://user-images.githubusercontent.com/7374161/47083369-a6876180-d210-11e8-959d-19be78add090.jpg)

Is this a bug? And if it is not, can it then be fixed via a feature request? 

If more information is needed I will be happy to provide.

Thanks in advance

**Comment by jobisoft** [comment]
I do not think this is supported by active sync 14.0. All this advanced meeting stuff is currently not on my agenda, as I focus on bringing back EWS.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#5
