### ISSUE TITLE
Losing contacts

### ISSUE THREAD

**Issue by Pehabo** [jobisoft/TbSync#142]
## Your environment

TbSync version: 7.16.6
Thunderbird version: 60.2.1

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
After synchronizing I seem to lose contacts. The total amount gets down. Is it possible to log deleted contacts so I cab find them again?

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
EAS or CardDAV? What type of server? What is the amount on the server saying?

**Comment by jobisoft** [comment]
Still with me?

**Comment by Pehabo** [comment]
Sorry, very busy. Next week I try again

Met vriendelijke groet,
Ivo ten Hagen
