### ISSUE TITLE
Newest Thunderbird beta is incompatible with tbsync

### ISSUE THREAD

**Issue by Caemor** [jobisoft/TbSync#143]
## Your environment

TbSync version: 
Thunderbird version: 63.0b1

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

The reason for that should be the "new" addon-policy without xul addons: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63

## Expected behavior

TbSync is compatible

## Actual behavior

TbSync is not compatible

## Steps to reproduce

Update to 63.0b1

**Comment by jobisoft** [comment]
That is correct.

**Comment by Caemor** [comment]
Will there be a update in the future when long term stable 67 will come out?

**Comment by jobisoft** [comment]
Yes, but from what I have heard the next ESR is TB68. Due to the many changes I will skip all versions in between and see what is needed for TB68.

**Comment by Caemor** [comment]
okay :+1:
