### ISSUE TITLE
Dind not work with SOGo Mailserver

### ISSUE THREAD

**Issue by hfl123** [jobisoft/TbSync#15]
I've tried to connect thr TBSync to our SOGo Mailserver with AES. I tried Version 2.5 and 14, but the Sync hangs after login with the folloing log:

** Thu Sep 21 2017 15:34:25 GMT+0200 **
[PROVIDER] : owncloud::Owncloud (CardDAV & CalDAV)

** Thu Sep 21 2017 15:34:25 GMT+0200 **
[PROVIDER] : eas::Exchange Active Sync

** Thu Sep 21 2017 15:34:28 GMT+0200 **
[setSyncState] : State: accountdone

** Thu Sep 21 2017 15:34:28 GMT+0200 **
[setSyncState] : State: idle

** Thu Sep 21 2017 15:34:29 GMT+0200 **
[JavaScript Error: "Please do not load stuff in the multimessage browser directly, use the SummaryFrameManager instead." {file: "resource://gre/modules/summaryFrameManager.js" line: 84}]
SummaryFrameManager.prototype._onLoad@resource://gre/modules/summaryFrameManager.js:84:9

** Thu Sep 21 2017 15:34:30 GMT+0200 **
[calendarObserver::onLoad] : <Ferien NRW> was loaded.

** Thu Sep 21 2017 15:34:30 GMT+0200 **
[calendarObserver::onLoad] : <Feiertage DE> was loaded.

** Thu Sep 21 2017 15:34:41 GMT+0200 **
[calendarObserver::onLoad] : <Kalender (Arbeit)> was loaded.

** Thu Sep 21 2017 15:34:46 GMT+0200 **
[calendarObserver::onLoad] : <Termine (Allg.)> was loaded.

** Thu Sep 21 2017 15:34:49 GMT+0200 **
[JavaScript Error: "Die Zeichenkodierung des Reintext-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Transferprotokoll deklariert werden oder die Datei muss eine Byte-Order-Markierung als Kodierungssignatur verwenden." {file: "file:///C:/Users/uweh/AppData/Roaming/Thunderbird/Profiles/zjrfeisb.uweh/TbSync/debug.log" line: 0}]

** Thu Sep 21 2017 15:34:49 GMT+0200 **
[JavaScript Error: "Die Zeichenkodierung des Reintext-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Transferprotokoll deklariert werden oder die Datei muss eine Byte-Order-Markierung als Kodierungssignatur verwenden." {file: "file:///C:/Users/uweh/AppData/Roaming/Thunderbird/Profiles/zjrfeisb.uweh/TbSync/debug.log" line: 0}]

** Thu Sep 21 2017 15:34:51 GMT+0200 **
[calendarObserver::onLoad] : <Urlaub> was loaded.

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[setSyncState] : State: syncing, Account: uweh

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[setSyncState] : State: requestingprovision, Account: uweh

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[Sending data requestingprovision (WBXML)] : 
3 1 6a 0 0 e 45 46 47 48 3 4d 53 2d 45 41 53 2d 50 72 6f 76 69 73 69 6f 6e 69 6e 67 2d 57 42 58 4d 4c 0 1 1 1 1

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[Sending data requestingprovision (XML)] : 
<?xml version="1.0"?>
<Provision xmlns='Provision'>
<Policies>
<Policy>
<PolicyType>MS-EAS-Provisioning-WBXML</PolicyType>
</Policy>
</Policies>
</Provision>

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[sending] : POST http://sogo.mz.local/Microsoft-Server-ActiveSync?Cmd=Provision&User=uweh&DeviceType=Thunderbird&DeviceId=mztb989e9766fddb0b6b8e1a3081cca3

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[PolicyKey used] : 0

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[Receiving Data (WBXML)] : 
3 1 6a 0 0 e 45 69 3 31 0 1 1

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[Receiving Data (XML)] : 
<?xml version="1.0"?>
<Provision xmlns='Provision'>
<AllowHTMLEmail>1</AllowHTMLEmail>
</Provision>

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[Extracted XML data] : 
Provision => 
 AllowHTMLEmail = [1]
Provision <= 

** Thu Sep 21 2017 15:35:31 GMT+0200 **
[JavaScript Error: "TypeError: wbxmlData.Provision.Policies is undefined" {file: "chrome://tbsync/content/provider/eas/eas.js" line: 358}]

Could you please help me?

**Comment by jobisoft** [comment]
Disable provision in your account in the TbSync account manager.

The log shows, that TbSync send a provision request, which should be answered with at least a provision status and a policy key. Both is missing in the answer from your SOGo server. I was expecting those fields and did not check for them first, so the sync process stopped with an javascript error. Nevertheless, syncing would not have been possible without the policy key. 

I will catch that error and implement a proper error message.
