### ISSUE TITLE
hu (magyar - Hungarian) translation

### ISSUE THREAD

**Issue by ovari** [jobisoft/TbSync#150]
Please accept [pull requests](https://github.com/jobisoft/TbSync/pulls): https://github.com/jobisoft/TbSync/pull/144 https://github.com/jobisoft/TbSync/pull/145 https://github.com/jobisoft/TbSync/pull/146 https://github.com/jobisoft/TbSync/pull/147 https://github.com/jobisoft/TbSync/pull/148 https://github.com/jobisoft/TbSync/pull/149

Thank you

Edit: https://github.com/jobisoft/TbSync/pull/153 should contain all the above pull requests.

**Comment by jobisoft** [comment]
Thanks, that makes it a lot easier. I wait till tomorrow to make sure all github problems have been solved.

**Comment by ovari** [comment]
You're welcome. GitHub problems were only with PR and issues and were fixed ~20 hours ago.

**Comment by jobisoft** [comment]
I am reviewing right now...

**Comment by ovari** [comment]
Thank you!
