### ISSUE TITLE
Exchange Calendar not in Calendar List

### ISSUE THREAD

**Issue by Pantek59** [jobisoft/TbSync#152]
Hi

I'm using TbSync to connect to my work exchange calendar and things are working flawlessly until I receive an invitation to a meeting event. I can press _Accept_ or _Deny_, but then I am asked to select the calendar, where the event should be saved. The exchange calendar is not listed.
Is this a feature simply not implemented yet or do I keep doing things wrong?

Thanks, Jan

**Comment by jobisoft** [comment]
I do not know, all this meeting stuff is not tested because it is not on my agenda. Maybe you have to set the correct email identity in lightning on that calendar?

**Comment by Pantek59** [comment]
That was exactly it! Thanks a lot!
