### ISSUE TITLE
Cannot sync event to Office 365: Bad item skipped <Invalid item! Mandatory fields missing? Dublicate item?>

### ISSUE THREAD

**Issue by SlimG** [jobisoft/TbSync#154]
- OS: Ubuntu 18.04.1 LTS
- Thunderbird: 60.2.1
- Lightning: 6.2.2.1
- TbSync: 0.7.16

First of all: you are my only hope in a otherwise bleak Office 365 environment at work :)

I am using this for the first time, and tried to create a event into my friend Bjørn's calendar.
But when syncronizing I get the following error:

> ** Tue Oct 23 2018 12:42:24 GMT+0200 (CEST) **
> [Sending (EAS v14.0)] : POST https://outlook.office365.com/Microsoft-Server-ActiveSync?Cmd=Sync&User=erik%40secret.com&DeviceType=TbSync&DeviceId=MZTBed79e59e68dbca78a6c4234765ff
> 
> ** Tue Oct 23 2018 12:42:24 GMT+0200 (CEST) **
> [setSyncState] : State: eval.response.remotechanges, Account: Erik, Folder: Bjørn Andersen
> 
> ** Tue Oct 23 2018 12:42:24 GMT+0200 (CEST) **
> [setSyncState] : State: prepare.request.localchanges, Account: Erik, Folder: Bjørn Andersen
> 
> ** Tue Oct 23 2018 12:42:24 GMT+0200 (CEST) **
> [setSyncState] : State: send.request.localchanges, Account: Erik, Folder: Bjørn Andersen
> 
> ** Tue Oct 23 2018 12:42:24 GMT+0200 (CEST) **
> [Sending (EAS v14.0)] : POST https://outlook.office365.com/Microsoft-Server-ActiveSync?Cmd=Sync&User=erik%40secret.com&DeviceType=TbSync&DeviceId=MZTBed79e59e68dbca78a6c4234765ff
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [setSyncState] : State: eval.response.localchanges, Account: Erik, Folder: Bjørn Andersen
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [wbxml status check] : Sync: Sync.Collections.Collection.Responses.Add[0].Status = 6
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [Bad item skipped <Invalid item! Mandatory fields missing? Dublicate item?>] : 
> BEGIN:VCALENDAR
> PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
> VERSION:2.0
> BEGIN:VTIMEZONE
> TZID:Arctic/Longyearbyen
> BEGIN:DAYLIGHT
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0200
> TZNAME:CEST
> DTSTART:19700329T020000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
> END:DAYLIGHT
> BEGIN:STANDARD
> TZOFFSETFROM:+0200
> TZOFFSETTO:+0100
> TZNAME:CET
> DTSTART:19701025T030000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VEVENT
> CREATED:20181023T104127Z
> LAST-MODIFIED:20181023T104139Z
> DTSTAMP:20181023T104139Z
> UID:50f37c60-90fd-4e1c-8e08-ba2096842bf7
> SUMMARY:Funka detta Bjørn?
> DTSTART;TZID=Arctic/Longyearbyen:20181023T133000
> DTEND;TZID=Arctic/Longyearbyen:20181023T143000
> TRANSP:OPAQUE
> END:VEVENT
> END:VCALENDAR
> 
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [setSyncState] : State: prepare.request.localchanges, Account: Erik, Folder: Bjørn Andersen
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [finishFolderSync(Erik.Bjørn Andersen)] : The EAS server rejected your items for the following reasons: 1x <Invalid item! Mandatory fields missing? Dublicate item?>. Check the debug log for "Bad item skipped".
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [setSyncState] : State: done, Account: Erik
> 
> ** Tue Oct 23 2018 12:42:25 GMT+0200 (CEST) **
> [setSyncState] : State: accountdone, Account: Erik

I tried to validate the VCALENDAR code from the error in https://icalendar.org/validator.html,
and it seems to be valid according to them.

**Comment by SlimG** [comment]
I am conveniently the administrator of this Office 365 service. And I haven't received any emails.

TbSync does download existing events from the server

Thank you for the EWS tip! I have installed it, but I cannot for the life of me figure out where I configure it. I'll figure it out somehow ...

**Comment by jobisoft** [comment]
ok. if you intend to sync shared calendars, you have to stick with EWS, because they are not supported by EAS. If not, we can keep investigating this.

Any details in the O365-Exchange-Admin-mobile view? What is your policy for unknown devices?

Can you just retry with a differnt event, with subject, location, start and stop?

**Comment by SlimG** [comment]
I'm trying to find out where I can add my Office 365 account in this new EWS Plugin, but I cannot find the window shown here -> https://github.com/ExchangeCalendar/exchangecalendar/issues/178#issuecomment-430652432
All I can find are these two new buttons in my "Settings" called "Exchange (EWS)" and "Extras", but they are not related to accounts.

I am happy to assist in investigating this error I'm seeing in EAS.

I've checked the Exchange policy for our organization. It is left to the default setting, which is to allow access to unknown devices.

I tried filling out Location which seemed to be the only field I had not filled out, but still same error:
** Tue Oct 23 2018 14:18:49 GMT+0200 (CEST) **

> [Bad item skipped <Invalid item! Mandatory fields missing? Dublicate item?>] : 
> BEGIN:VCALENDAR
> PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
> VERSION:2.0
> BEGIN:VTIMEZONE
> TZID:Europe/Oslo
> BEGIN:DAYLIGHT
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0200
> TZNAME:CEST
> DTSTART:19700329T020000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
> END:DAYLIGHT
> BEGIN:STANDARD
> TZOFFSETFROM:+0200
> TZOFFSETTO:+0100
> TZNAME:CET
> DTSTART:19701025T030000
> RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VEVENT
> CREATED:20181023T121805Z
> LAST-MODIFIED:20181023T121842Z
> DTSTAMP:20181023T121842Z
> UID:f12acb99-1b02-414a-9fb6-b7f7755381ec
> SUMMARY:Husk det her
> DTSTART;TZID=Europe/Oslo:20181023T150000
> DTEND;TZID=Europe/Oslo:20181023T160000
> TRANSP:OPAQUE
> LOCATION:Det her her lokasjonen
> SEQUENCE:1
> END:VEVENT
> END:VCALENDAR

**Comment by SlimG** [comment]
If you suspect the problem is the content of the VCALENDAR then you can try to construct a few of them for me that I can test if you have any theories of what's wrong.

**Comment by jobisoft** [comment]
I cannot assist you with EWS. I also do not know, why your server rejects events from TbSync. I just added this event to my O365 account without error:

```
BEGIN:VEVENT
CREATED:20181023T132343Z
LAST-MODIFIED:20181023T132358Z
DTSTAMP:20181023T132358Z
UID:2tjoanTeS0CJ3QTsq5vdNQAAAAABDdrY6Gp03ktAid0E7Kub3TUAAO5BMr81
SUMMARY:Neuer Termin
DTSTART;TZID=Europe/Berlin:20181016T160000
DTEND;TZID=Europe/Berlin:20181016T170000
TRANSP:OPAQUE
LOCATION:Test
DESCRIPTION:Juh
END:VEVENT
```

Has this account a pending password change? Can you log into the portal? Strange, very strange.

**Comment by jobisoft** [comment]
Could you check what happens, if you add the event with berlin timezone?

**Comment by SlimG** [comment]
I think I've figured it out, It seems to dislike the missing "CLASS" entry.
When I add that, I no longer get problems. As far as this report is considered, my problems are sorted.

Thank you very much good sir! You have saved me from having to use Outlook on Ubuntu, a giant step for this man! :)

**Comment by jobisoft** [comment]
Can you elaborate this a bit more, so I can fix this? What CLASS entry are you referring too?

**Comment by jobisoft** [comment]
Is this related to this issue?
https://github.com/jobisoft/TbSync/issues/74#issue-321509643

**Comment by SlimG** [comment]
Yes! I was about to file a request for this default feature as I also cannot find anywhere in Thunderbird to set this default.

**Comment by jobisoft** [comment]
Is the calendar you are using and having this issue a (pseudo) shared calendar?
