### ISSUE TITLE
Email Account Not Visible

### ISSUE THREAD

**Issue by lefrog** [jobisoft/TbSync#156]
## Your environment

TbSync version: 0.7.16
Thunderbird version: 60.2.1

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After adding an account I would expect to see it in the email tab.

## Actual behavior
I don't see any email account.
![selection_109](https://user-images.githubusercontent.com/274512/47545270-8eff4700-d8a8-11e8-9d7c-2ae8ab9a7bea.png)

## Steps to reproduce
Install TbSync. Add and synchronize with work Office 365 account.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
TbSync only supports contacts, tasks and calendars. Could you tell me which TbSync description gave you the impression, it also supports email? I would like to improve the wording than.

Thanks,
John

**Comment by lefrog** [comment]
I guess it's because I've been trying different solutions to work with our work corporate email (Office 365). I was trying a few days ago ExQuilla and it did add a mail account so I was somehow expecting to see the same thing.
I guess the only wording that could be added is to explicitly mention it is not doing email.

FYI, it's working really great so far. I think I finally found something to work with our corporate email :)
