### ISSUE TITLE
Replace UUID lib with Mozilla function

### ISSUE THREAD

**Issue by benbucksch** [jobisoft/TbSync#157]
TbSync imports a UUID lib. Mozilla already has this feature:
```
const { generateUUID } = Cc["@mozilla.org/uuid-generator;1"].getService(Ci.nsIUUIDGenerator);
var uuid = generateUUID().toString();
```

**Comment by benbucksch** [comment]
Code examples: https://searchfox.org/mozilla-central/search?q=generate.*uuid&case=false&regexp=true&path=

**Comment by benbucksch** [comment]
The UUID lib is under GPL2 or later

**Comment by jobisoft** [comment]
Removed. It was not yet used in TbSync, but in DAV-4-TbSync and has been removed there as well. 

Thanks for your help!

**Comment by benbucksch** [comment]
You're welcome. Thank _you_. :)
