### ISSUE TITLE
Syncing shared calendars (or other shared directories)

### ISSUE THREAD

**Issue by de-vri-es** [jobisoft/TbSync#16]
First of all, thanks for the add-on. It's good to have an open-source solution.

I couldn't see how to synchronize with shared calendars. They don't show up in the directory list. I'm guessing support for shared calendars isn't implemented currently. Is this correct?

**Comment by jobisoft** [comment]
Currently not, because I do not have access to one. You could enable debug log and check if your shared folder shows up at all in the found folder list, that would be helpful.

**Comment by de-vri-es** [comment]
I'm not seeing any shared calendars or otherwise anywhere in the debug log. I deleted and re-added the account to make sure to get the whole picture. I did see all my email folders in the log, but none of the shared calendars or groups.

I'd guess that it requires a different API call to enumerate shared programs.

**Comment by jobisoft** [comment]
thanks, i keep this on the list. What is your backend? Office 365? Outlook.com?

**Comment by de-vri-es** [comment]
I'm pretty sure it's Office 365, though I didn't make the account so I'm not 100% sure. But the web interface is at `https://portal.office.com` and the logo at the top says Office 365. So that's a pretty strong hint :)

**Comment by jobisoft** [comment]
https://blogs.msdn.microsoft.com/exchangedev/2015/06/08/announcing-exchange-activesync-v16/

After searching for "shared" on this page, I think O365 simply does not support that feature.... If you could get hold of an hotmail accounts or an outlook.com account, we could test, if it is working there (I have one of each, so you could share with me or I with you).

**Comment by jobisoft** [comment]
OK, I can see a shared calendar in my O365 account and in TbSync!

1. I shared a calendar of user A using the "share" button in O365 (I gave the maximum rights, including viewing private events) to user B.
2. User B received an email with an accept button, which I clicked (using the portal, not thunderbird)
3. The calendar shows up in the portal and in TbSync of user B.

From what I understand, user B does not directly see the shared calendar of user A, but a copy of the calendar which is stored in the account of user B. If user A changes something in his calendar, than these changes get copied to the calendar copy of user B (by Microsoft). 

This is why the calendar remains in the account of user B, even if user A removes his access right. However, the calendar is no longer updated, it has become disconnected to the original calendar of user A.

Maybe this helps.

**I still would like to test the "true" sharing with an outlook.com or hotmail account, to see wether that works as well, or not. Anyone to help?**

**Comment by de-vri-es** [comment]
Hmm, Microsoft makes stuff kinda complex. What we have is calendars that are automatically shared with the entire organization. So I can see all my colleagues' calendars. But I do need to manually add them in the web interface with a free text input (with auto completion). After doing that they still don't show up in TbSync.

Additionally, we have a number of groups. Each group has a calendar as well. In the web-interface these show up automatically, but under the respective group. I can't see these either in TbSync.

None of these are explicitly shared calendars, and apparently that makes a difference for EAS :/

**Comment by jobisoft** [comment]
Yep, there is nothing I can do about those global shares. This is not a limitation of TbSync, but of EAS.

**Comment by bonanza123** [comment]
I have access to an institutional (self-hosted) Exchange Server 2016. Is there a way I could contribute to this by providing detailed logs or something similar?

**Comment by jobisoft** [comment]
Yes, activate debug log (in TbSync account manager under help), disconnect your account and reconnect again. This will force TbSync to download the entire folder structure again, dumping it into the debug log.

You can than check the debug log, if the shared folder you want to access shows up there. If not, there is nothing I can do about that.

There are two different Exchange protocols: EAS and EWS. "Pure" shared folders are only accessible via EWS. The only way to access shared folders with EAS (what TbSync is using) is the copy-trick O365 is using, to get around that limitation.

I assume EXS2016 is not doing that copy-trick for you. You need to use EWS to sync.

**Comment by bonanza123** [comment]
All right, I will try this out. Please let me drop you these links for reference:

https://github.com/officedev/ews-managed-api
https://github.com/dseph/EwsEditor

**Comment by bonanza123** [comment]
@jobisoft I obtained the log and it has 114000 lines. Is there pointer I have to look for to figure this out?
Should they appear in the "FolderSync" data?

**Comment by jobisoft** [comment]
Yes, FolderSync is the correct pointer. All found folders will be listed after a line like this:

`[Receiving data <requestingfolders> for AccountName (XML)] :`

with AccountName being replaced by the name of the TbSync account.

**Comment by bonanza123** [comment]
Thanks for the information! Looks like I can only see my own calendar, at least the only related entry is:

```   
17 => 
    ServerId = [18]
    ParentId = [0]
    DisplayName = [Kalender]
    Type = [8]
   17 <= 
```

**Comment by Svendergrosse** [comment]
Hi, thanks for all the work on TBsync.
I have some more information about the shared calendar issue. I was previously using Exchange EWS Provider for Thunderbird and managed to access shared calendars. The EWS add-on had an additional entry "postbox". Attached is a screen shot of the settings (in German). It shows beside the server address and the user name the additional entry "Postfachname" - postbox. I wonder whether this would be accessible for TBsync, too.

Would be great to see shared calendars.

Thanks,
![physics_key_dates](https://user-images.githubusercontent.com/6673512/49141071-ae492400-f2ed-11e8-93d7-b8be73e0657b.png)

**Comment by jobisoft** [comment]
@Svendergrosse For the shared calendars, this is not a limitation of TbSync, but of ActiveSync (EAS). It does not support shared calendars as EWS does. I do report everything I can see to the user.

Some servers do announce shared calendars via EAS (Office 365 for example), but this is using some proxy technique: You get a COPY of the calendar shared with you in your own account and if the owner adds something, the backend will transfer these changes to you. You can do whatever you want in that copy of yours and on next sync it will set it back to the owners version. There is no real ACL management  in EAS, that is why "real" shared resources are not supported.

As for email sync, I will probably not add that.

**Comment by TheDarkPower** [comment]
Greetings. First and foremost, thank you so much for this add-on. I've been using Thunderbird for years and until version 60, I used the EWS Exchange Connector to attach to Exchange calendars. The EWS connector had an extra setting in which one would specify the Exchange email address to connect to in addition to a setting to specify my own account to connect as.
In other words, I  would authenticate with my own account but connect to the specified shared calendar account (email address).
Would this be something that could be easily implemented in TBSync?

**Comment by jobisoft** [comment]
Sadly no, because that is not supported by EAS/ActiveSync (TbSync is using EAS, not EWS).

But the EWS connector is back on track.

**Comment by TheDarkPower** [comment]
Rats! Thanks for the quick response.
