### ISSUE TITLE
'Local backup of: <calendar> [forced folder resync]' after sync

### ISSUE THREAD

**Issue by paul70078** [jobisoft/TbSync#162]
When 2 Thunderbird instances sync the same calendar, backups of the calendar are created. Additionally event notifications pop up and need to be confirmed again.

## Your environment

TbSync version: v0.7.16
Thunderbird version: 60.2.1

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

No duplicate/backup calendars on sync

## Actual behavior

Local backup of <calendar> after sync

## Steps to reproduce

Adding the same calendar to 2 Thunderbird instances running at the same time

**Comment by jobisoft** [comment]
What provider? EAS or DAV?

**Comment by paul70078** [comment]
EAS according to log

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#19
