### ISSUE TITLE
New Events are automatically confirmed without accepting them

### ISSUE THREAD

**Issue by kwoxer** [jobisoft/TbSync#163]
## Your environment

TbSync version:0.7.16
Thunderbird version:60.2.1 (64-bit)
Ubuntu 18.04

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.
not yet

## Expected behavior
New Events are not automatically **confirmed**.

## Actual behavior
New Events are automatically **confirmed**.

## Steps to reproduce
Get invited to event, and you are automatically confirmed to that event.

**Comment by jobisoft** [comment]
All this meeting stuff is currently not top prio for me. Sorry. Better use the EWS addon.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#4
