### ISSUE TITLE
Which version of owncloud is compatible?

### ISSUE THREAD

**Issue by etron770** [jobisoft/TbSync#164]
Debian Stretch

TbSync version: 0.7.15
Thunderbird version: 60.0

[x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Connecting to owncloud calendar 

## Actual behavior

Not working with this server
## Steps to reproduce
I can connect to an old 7.0 owncloud server debian jessie but there are only the contacts available not the calendars. Connecting to Owncloud 10.0.8 does not work

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
It works with every server with correctly configured discovery service.

You can try to investigate by looking at the URLs you used to setup calendars in lightning. From that you could get the actual carddav or caldav server, for example

```
myowncloud.de/owncloud/remote.php/caldav/.... 
myowncloud.de/owncloud/remote.php/carddav/.... 
```

You can use these two servers addresses to setup calendar OR contact sync (without /... of course). I tested against your actual server from the log file you send me.

Everything would work smoothly, if your owncloud installation has a proper discovery service setup, which requires these redirects:

```
RewriteRule ^.well-known/carddav /remote.php/carddav/ [R=301,L]
RewriteRule ^.well-known/caldav /remote.php/caldav/ [R=301,L]
```

And than you could simply use the following server address, to get both, calendars and contacts.

```
myowncloud.de/owncloud/
```

Your server does not seem to have these redirects.

**Comment by jobisoft** [comment]
I would like to declare this a doublicate of https://github.com/jobisoft/DAV-4-TbSync/issues/28 and discuss any further details there.

It might be, that it does not work with your server, even with fully setup redirects, because the owncloud install is not at the root of your server, but in the subfolder "owncloud". 

Can you confirm, that it works for your servers, if you use the `remote.php/carddav` or `remote.php/caldav`

We will get this working ...
