### ISSUE TITLE
Calendars color deleted after synch

### ISSUE THREAD

**Issue by jllorensi** [jobisoft/TbSync#166]
## Your environment

TbSync version: 0.7.16
Thunderbird version: 52.9.1
sabre/dav (CalDAV & CardDAV) provider for TbSync version: 0.8.29

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Synchronized to an account with several (4 in my case) CalDAV calendars.

## Expected behavior
After setting a color in each calendar, it should remain after each synchronization.

## Actual behavior
All calendars color return to default blueish one.

## Steps to reproduce
Go to Lightning and set a color for a calendar.
Manually, or wait for automatic, synch.
Previously selected color is replaced by default one.

## Notes
File folders.json seems to be updated after each sync --> Parameter's "targetColor" value is replaced by empty string :""

...
[debug.log](https://github.com/jobisoft/TbSync/files/2545572/debug.log)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jllorensi** [comment]
Sorry, I didn't read previous solved issues.

**Comment by jobisoft** [comment]
This is explained here:
https://github.com/jobisoft/DAV-4-TbSync/issues/21

I *might* add an option to change the color via the TbSync Manager, but that has low prio at the moment.

**Comment by jobisoft** [comment]
Thank you very much for your donation!

**Comment by jllorensi** [comment]
I can understand that it is not a priority. I think it is just a matter of documenting it somewhere.
At the end I changed the colours in my Baikal server and everything worked fine.

P.D.: You're welcome!
