### ISSUE TITLE
Shift + tab in the address input doesn't move focus to the previous input element

### ISSUE THREAD

**Issue by brettp** [jobisoft/TbSync#168]
## Your environment

TbSync version: 0.7.16.9
Thunderbird version: 60.3.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Shift + tab in the address field should always go to the previous input element.

## Actual behavior
The focus incorrectly moves to the previously selected element (the 2nd recipient's email address) instead of the previous input in the layout.

## Steps to reproduce
1. Create a new message and enter a recipient. 
2. Push enter at the end of the recipient line to create a new field for a second recipient.
3. Push shift + tab to go to previous input (the To, CC, etc dropdown).
4. Push shift + tab again to go to previous input (the first recipient field)
5. Push shift + tab again.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I do not think this is related to TbSync.

**Comment by jobisoft** [comment]
Thanks. A debug report would be nice, Maybe there is Pops up some error message.
https://github.com/jobisoft/TbSync/wiki/Found-a-bug%3F

**Comment by jobisoft** [comment]
My Thunderbird just updated to 60.3.3 and in the release notes there is something about a fix in the autocomplete. Do you still have this bug with this version of TB?

**Comment by brettp** [comment]
Sorry for the delayed reply. Attached is a debug log, but it doesn't offer much help.

FWIW I seem to only be able to duplicate this bug with TB Sync enabled on this single instance of Thunderbird. I tried on another computer and didn't have the problem. That said, I didn't actually configure TB Sync because I don't have access to an Exchange server on that computer.

[tb-sync.log](https://github.com/jobisoft/TbSync/files/2668791/tb-sync.log)

**Comment by jobisoft** [comment]
Just out of curiosity, creating a new thunderbird profile on the faulty instance gives the same erroneous behavior?

**Comment by jobisoft** [comment]
Just out of curiosity, creating a new Thunderbird profile on the faulty instance of Thunderbird gives the same erroneous behavior?

FYI: You can also use TbSync to setup CalDAV/CardDAV accounts. 

If you set up a test-profile, I suggest to try out the latest beta:
https://tbsync.jobisoft.de/TbSyncBetaInstaller.xpi

**Comment by jobisoft** [comment]
Can I close this?
