### ISSUE TITLE
Syncing problems - due to port number?

### ISSUE THREAD

**Issue by fieseline** [jobisoft/TbSync#17]
I am in a school network and I am trying to connect to my school Office 365 account. Autodiscover fails though password and user name are correct. This configuration works fine on my home PC, so I think the reason is some port that is closed in my school network.
Is there any way to get it working? Are there any ports to be opened for autodiscover?

Thanks, fl

**Comment by jobisoft** [comment]
Autodiscover uses standard http and https Protocol, no special Ports.

If it works at home, you could simply write down the configuration found and setup your account at school manually with that config.

**Comment by fieseline** [comment]
Finally worked by using manual configuration. Great tool, making it possible to use Thunderbird/Lightning instead of Outlook. Keep on!
fl
