### ISSUE TITLE
support for Thunderbird 64

### ISSUE THREAD

**Issue by monperrus** [jobisoft/TbSync#172]
I'm reading on the Add-On tab in TB "TbSync is incompatible with Thunderbird 64.0" (the same for sabre/dav).

What's the solution?

**Comment by jobisoft** [comment]
There is no version yet for Thunderbird Beta. There will be a solution for the next ESR, but currently all my time is used up to improve the version for TB 60.

**Comment by monperrus** [comment]
OK, so I will stick to TB60. Thanks.
