### ISSUE TITLE
Primary mail with different accounts not working

### ISSUE THREAD

**Issue by bromix** [jobisoft/TbSync#174]
Last try :( without any mention my issue got deleted.

## Your environment

TbSync 0.7.18:
Thunderbird 60.3.0:

[] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Option to use a username instead of the primary email as login. We use 2 usernames for one primary mail, so we can work in different departments in one company.

## Actual behavior
The login uses the primary mail as login, which is not correct in all cases

To clarify the issue: We've a primary mail (e.g. nickname@company.com). The password is via domain. Now some of us work in different departments in this company and have therefore additional mail accounts. The login (in Thunderbird, Outlook, EWS-Provider) uses the primary mail for identification in the domain (nickname@company.com) but a different usernames.

**Comment by jobisoft** [comment]
Your issue got moved to the EAS Provider:
https://github.com/jobisoft/EAS-4-TbSync/issues/22

You did not get an email about that move? It is a beta feature of github i started to use to better organize the issues.

**Comment by bromix** [comment]
Oh sorry :( and no, I got no notification via mail from git. Should I update the moved issue with the information of this issue?

**Comment by jobisoft** [comment]
Did you get my answer from the other issue? Can you answer there? No need to update anything...
