### ISSUE TITLE
Unable to install 0.7.18 on TB 52.9.1

### ISSUE THREAD

**Issue by tuxmaster5000** [jobisoft/TbSync#175]
## Your environment

TbSync version: 0.7.18 
Thunderbird version:52.9.1

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Update from 0.7.16

## Actual behavior
Error message that 0.7.18 is not compatible with TB 52.9.1

## Steps to reproduce
Try to use the update function of TB or install it via hand.

**Comment by jobisoft** [comment]
TbSync 0.7.18 needs Thunderbird 60. This is not an error. If you want to keep using TB52, stick with 0.7.16. This is also documented here:

https://addons.thunderbird.net/de/thunderbird/addon/tbsync/versions/
