### ISSUE TITLE
attachments size unknown

### ISSUE THREAD

**Issue by jasmines** [jobisoft/TbSync#176]
## Your environment

TbSync version: 0.7.18
Thunderbird version: 60.3.1. (ubuntu 64 bit)

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

Attachments should show their size inline as other account types do.

## Actual behavior

See screenshot attached.

## Steps to reproduce

Just receive a zip file in the Exchange account.
![screenshot_20181114_103536](https://user-images.githubusercontent.com/894920/48473599-116c8e00-e7f9-11e8-9237-284aee9e4577.png)

**Comment by jobisoft** [comment]
This is not related to TbSync, which only syncs contacts, tasks and events. 



Am 14.11.18 um 10:36 schrieb jasmines
