### ISSUE TITLE
Horde / status.policykey-failed

### ISSUE THREAD

**Issue by sjau** [jobisoft/TbSync#18]
Hi there

I'd love to sync contacts etc. with Horde. Setup seems all fine and autodiscover seems to work as well. But when I click on the "Connect" button I get a popup "status.policykey-failed". No idea what's wrong.

**Comment by jobisoft** [comment]
Any chance I could get an account on your horde server, to find out what might be the problem? You can use my official e-mail address to send me the URL, username and password...

**Comment by sjau** [comment]
Email sent

**Comment by jobisoft** [comment]
The actual error is, that your server reports "There is no policy for this client", if provisioning is enabled and TbSync tries to get the provisioned policy.

QuickFix: Disable provisioning in TbSync Account Manager.

Remaining Question: Why does it work "out of the box" with Outlook and also with the TouchDown App? 

**Could you check the horde active sync device list, if your own Outlook device is listed as provisioned or unprovisioned?**

**Comment by jobisoft** [comment]
I close this issue as resolved in 0.6.8.3. TbSync is simply going on without provision, if it finds there is no policy for this device, however it will not disable provisioning, as there could be a policy implemented later. TbSync will ask for policy on every request.

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
