### ISSUE TITLE
TbSync Account manager page does'nt properly support dark themes

### ISSUE THREAD

**Issue by isorochan** [jobisoft/TbSync#182]
## Your environment

TbSync version: 0.7.19
Thunderbird version: 60.3.1 64 bit 

## Expected behavior
Colors should be compatible with dark gtk themes.

## Actual behavior
Colors aren't compatible with dark gtk themes.

## Steps to reproduce
1 Change gtk theme  dark theme (Adwaita-dark, breeze-dark or similar)
2. Restart Thunderbird
3. Open TbSync
![tb_sync_base](https://user-images.githubusercontent.com/5279583/48713740-c77d1100-ec19-11e8-9712-e38394114596.png)
![tbsync_dark](https://user-images.githubusercontent.com/5279583/48713741-c815a780-ec19-11e8-9126-56ec2c8db3c8.jpeg)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can you contribute? The manager css is not theme-aware:
https://github.com/jobisoft/TbSync/blob/master/content/manager/manager.css

If you contribute: TbSync exists in two editions at the moment. The current released one, which is actually the old one in branch `0.7.16.9-(last-TbSync-with-EAS)` and the new editon (without bundled EAS) which is not yet released. The switch-over will happen in 1 or 2 weeks.

**Comment by pagdot** [comment]
I just took a look into it, but didn't manage to apply styles from thunderbird. Only from my OS

**Comment by Feichtmeier** [comment]
I do not know how the theming system in thunderbird works, but maybe if you would build the UI with thunderbird components it should "just work" - thunderbird, minus the calendar, works pretty well with the dark theme in Ubuntu for example

![grafik](https://user-images.githubusercontent.com/15329494/96978457-ac5e5e80-151e-11eb-83b8-66c6635cc6f1.png)

![grafik](https://user-images.githubusercontent.com/15329494/96978567-ca2bc380-151e-11eb-965a-4f531902eb03.png)

**Comment by jobisoft** [comment]
There is a dupe of this somewhere.
