### ISSUE TITLE
EWS not usable yet

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/TbSync#183]

**Comment by jobisoft** [comment]
@sinya13

You just foked the EWS provider. That is not only not working but it is even incompatible with the current released TbSync. You need to build the current TbSync your self (master branch) to get a version of TbSync hat can actually load the current EWS provider.

I will let you know in this issue, when the new TbSync has been released, which loads the EWS provider again. ETA 2 weeks.

**Comment by sinya13** [comment]
I tried to translate TbSync into Russian here https://github.com/sinya13/TbSync. In the near future I will translate the language of the other components in folders nearby. I would like to see the addition and with ru. For some reason my translation does not want to run in modified tbsync@jobisoft.de.xpi from Thunderbird Add-on repository.

**Comment by jobisoft** [comment]
Thanks for your kind offer. I would suggest to wait 2 weeks until the transition is finished. I will contact you, as soon as possible?

**Comment by sinya13** [comment]
Ok. Suitable for me in its current form. Like eas ok. It only prevents that the answering machine on the exchange server cannot be changed through this! And global address book server is needed ...

**Comment by jobisoft** [comment]
Out-of-office is planed for next big release, global addressbook is there already, just type something into to TO field while composing and the GAL is searched. A search in the adress book is also searching the GAL.

**Comment by sinya13** [comment]
A separate icon of address book in server would look more familiar ...
