### ISSUE TITLE
McAfee Endpoint Security reports "Virus found" for TbSync 0.7.22 

### ISSUE THREAD

**Issue by Menapax** [jobisoft/TbSync#184]
## Your environment

TbSync version: 0.7.22
Thunderbird version: 60.3.1

My Antivirus (McAfee Endpoint Security) says the last version of tbsync (0.7.22) has a malware (Suspicious Attachment!script) and delete all the files of TBSync. I have installed version 0.7.20 and all is good and no problems. What's the problem? Can you solve it?

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I do not think I can do anything about that. It has been reviewed by Mozilla and there is no virus part of TbSync.

**Comment by WDenda** [comment]
Hi,

don't panic. This is (IMHO) a false positive for sure, as those dumb 
scanners kill several install scripts and similar (oh, contains rm -rf, 
such a bad thing).

Regards,
Wolli

Am 26.11.18 um 12:27 schrieb John Bieling:

**Comment by level420** [comment]
@jobisoft if the false positive of mcaffe persists, then a lot of users won't be able to install tbsync aynmore.

You could actively try to delist TBSync at mcaffe as described here:
[How to submit virus samples and false positives to McAfee](https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&locale=en-US&articleId=TS102053&_afrLoop=902095746434152&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25¢erWidth=100%25)

**Comment by jobisoft** [comment]
I would need the actual file that triggered the alert and I would also need the Version of McAffe that @Menapax is using. Don't I?

Is this some sort of hash test? Could I just change something in TbSync and release a new version, which has a different hash from 0.7.22 ? How is this working in the first place?

**Comment by level420** [comment]
Yes @Menapax should give the needed informations to you.

And the tests are done using the file you should attach to your false positive mail as described in the link above.

**Comment by Menapax** [comment]
Ok, I Will send the file to McAfee and I Hope they Will solve the problemi.....

In data 26 novembre 2018 2:35:30 PM Dietrich Streifert 
<notifications@github.com> ha scritto:

**Comment by Menapax** [comment]
I have tried on my Pc the version of Tbsync downloaded from Github, I don't Know if this version is different with the version on ATN (addon thunderbird net), but with the new version downloaded today tehere was no problem with McAfee Endpoint Security.
I think now it's all Ok, then I can close the thread, sorry for the time you spent for me, and sorry for my horrible english.
