### ISSUE TITLE
Timezone-issue

### ISSUE THREAD

**Issue by Olen** [jobisoft/TbSync#187]
## Your environment

TbSync version: 0.7.22
Thunderbird version: 60.3.0 (64-bit)

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

I am not 100% sure this is a TBSync-issue, but I need to start debugging it somewhere...

When I add a new event to the calendar in TB it syncs fine to Exchange.
However, when THOSE events are synced out to the published ics-file (from OWA), the timezone is wrong.
Other events, either added directly in outlook, or where I receive an invitation, does not show this behavior.  It would be great if the debugging of TBsync would add the _actual_ data that is sent to the exchange-server, so I could verify what info is sent.
   

## Expected behavior
Timezones sould be correct all the way

## Actual behavior
Here is a test-event I created:
BEGIN:VEVENT
SUMMARY:Timezone?
DTSTART;TZID=Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@:20181127T150000
DTEND;TZID=Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@:20181127T160000
UID:6f9e990a-b458-4fcf-822a-e34e2ea17deb
CLASS:PERSONAL
PRIORITY:5
DTSTAMP:20181127T133729Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

So _something_ is adding a lot of ^@-characters to the DTSTART and DTEND-TZID.

I have not found a way to see this directly in outlook, but by using "Publish on internet" and fetching the ICS-file, I can see it in all events created by Thunderbird.

## Steps to reproduce
1) Add a new even in thunderbird
2) Sync to Exchange-server
3) Publish calendar from Exchange (OWA) to internet
4) Download ics-file

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
before sending the new event to the server, you could export the calendar in lightning, to see how lightning has stored that event. After you have send the evemt to the server, disconnect the account and re-connect, which downloads the new event (and all others) back into lightning. Re-Export the calendar inlightning and look what is has now. Anything strange?

**Comment by Olen** [comment]
Thanks for the tip.

Exporting the calendar directly in Thundebird does not show the problem:
SUMMARY:Timezone?
DTSTART;TZID=Europe/Paris:20181127T150000
DTEND;TZID=Europe/Paris:20181127T160000

- And this is also strange.  To test, I changed the default Timezone of TB to be Europe/Paris, but it is still set to Europe/Oslo when it syncs to exchange with TBsync. 
(But for me that is a minor issue.  The core problem is that the ICS-files with all the ^@ in them is not possible to import in other calendars.


I will remove the account shortly to test.

**Comment by Olen** [comment]
Weird.
Removing the Exchange-account from TBSync, and re-adding it, and then exporting the local Thunderbird calendar is also fine.

What I see is that at the top of the ICS-file from OWA, I have a VTIMEZONE which also includes all the ^@s

BEGIN:VTIMEZONE
TZID:Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
BEGIN:STANDARD
DTSTART:16010101T020000

Unfortunately this is a hosted exchange-thing, so I have no access to the server or any logs or settings there.
I do see the same for one other entry in the timezone-definitions:
BEGIN:VTIMEZONE
TZID:Europe/Chisinau^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
BEGIN:STANDARD

While most of the others are fine:

BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000

Is this some kind of known issue with either Exchange Server 2010 or OWA?

**Comment by Olen** [comment]
Great.  Let me know if there is anything else I can do to test.
And as I said - if there is a way to see the actual data that TbSync is sending and receiving, I could debug it further myself.

**Comment by Olen** [comment]
Thanks for the tips.
I enabled the debugging, and got the info.  However I have not been able to decode the xml yet.

But I do suspect that the issue is here, somehow:
StandardName (64 bytes): (...) "Any unused WCHARs in the array MUST be set to 0x0000."

My hunch is that those "0" are somehow encoded wrongly.   ^@ is a "null" in vim, so that is why I see it like that in the files.
"Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@" is exactly 32 bytes

The spec says that the name should be 64 bytes, but it might be that there is some extra stuff here that I don't understand yet...

**Comment by jobisoft** [comment]
This is my impl. maybe you see something:
https://github.com/jobisoft/EAS-4-TbSync/blob/master/content/provider/eas/eas.js#L1191

Also test with events created by other clients (phones) and see what kind of TimeZone tags they create...

**Comment by jobisoft** [comment]
Just one important info: if you actually want to clone/fork to play with it yourself, I recommend to work with the branch '0.7.16.9-(last-TbSync-with-EAS)' of the TbSync project. 
https://github.com/jobisoft/TbSync/tree/0.7.16.9-(last-TbSync-with-EAS)

It is complicated, the project is being restructured right now and if you want to work with the master branch, you would probably run into build errors. There is no "release" yet of the new TbSync.

The 'old' branch is currently used to build the official version for addons.thunderbird.net and the switchover will be in 1 or 2 weeks. The old branch has the code at:
https://github.com/jobisoft/TbSync/blob/0.7.16.9-(last-TbSync-with-EAS)/content/provider/eas/eas.js#L1128

**Comment by Olen** [comment]
I'm not that fluent in Javascript (this is over my head...), but I might still be able to help debugging.

Just created two entries.  One from my phone, and one from Thunderbird.
The one from thunderbird is the exported in the ics as
```
SUMMARY:Test TbSync
DTSTART;TZID=Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@:20181128T090000
DTEND;TZID=Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@:20181128T100000
```  

The one from my phone is added as
```
SUMMARY:Test TbSync 2
DTSTART;TZID=Customized Time Zone:20181128T103000
DTEND;TZID=Customized Time Zone:20181128T113000
```

As far as I understand your code, you are first creating a 172 Byte buffer filled with nul, and then you add content at the proper indexes in that buffer.
I just don't manage to wrap my head around the difference between a nul as a regular BYTE, and as a WCHAR.  Could that be the issue?  That you are adding 172 nul_bytes_, whereas you should initiate the buffer with 86 WCHAR-nuls?  Is there any difference?

**Comment by Olen** [comment]
Just realized you use `this.buf.setUint16(byteoffset+i*2, 0);` in setstr
But Uint8 in set easTimeZone64

So I might be barking up the wrong tree here.  Although I still feel I am on the right track...

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/blob/0.7.16.9-(last-TbSync-with-EAS)/content/provider/eas/eas.js#L1173

I set it to 16bit of 0. That is zero. I am more curious about the encoding/decoding. How can ^@ be zero?

**Comment by Olen** [comment]
^@ is just vim (and bash and other linux applications) way of displaying a nul-byte.
It is actually shown as ctrl-@

On a less serious note.  Microsoft... Who in their right mind takes a data-structure, pushes it into a bytestring, THEN base64-encodes the thing and adds it to an xml-tag.
Was it SO difficult to add a few <StandardName>, <StandardDate> tags to the xml-schema?

**Comment by jobisoft** [comment]
just for the record, this is the urlencoded value

xP%2F%2F%2F0UAdQByAG8AcABlAC8AQgBlAHIAbABpAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAFAAIAAAAAAAAAAAAAAEUAdQByAG8AcABlAC8AQgBlAHIAbABpAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAFAAEAAAAAAAAAxP%2F%2F%2Fw%3D%3D

this is the plain base64

xP///0UAdQByAG8AcABlAC8AQgBlAHIAbABpAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAFAAIAAAAAAAAAAAAAAEUAdQByAG8AcABlAC8AQgBlAHIAbABpAG4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAFAAEAAAAAAAAAxP///w==

and if i turn that into hex (http://en.1mu.info/tools/hexbase64.html) I get

```
c4 ff ff ff 45 00 75 00 72 00 6f 00 70 00 65 00 2f 00 42 00 65 00 72 00 6c 00 69 00 6e 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0a 00 00 00 05 00 02 00 00 00 00 00 00 00 00 00 00 00 45 00 75 00 72 00 6f 00 70 00 65 00 2f 00 42 00 65 00 72 00 6c 00 69 00 6e 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03 00 00 00 05 00 01 00 00 00 00 00 00 00 c4 ff ff ff
```

which looks pretty good...

**Comment by jobisoft** [comment]
Can we get the timezone tag value from an event added by your phone?

**Comment by jobisoft** [comment]
When thunderbird receives it as a new event from your server, it show up in the debug.log.

**Comment by Olen** [comment]
For the fun of it, I tried testing with some different timezones for events explicitly.

If I set the timezone for a single event to "UTC/GMT", TbSync will send it as "`standardName: Coordinated Universal Time (UTC)`" 
(And I don't get all the extra NULs in the ics file for that event).

If I set it to "Local Time" TbSync will send whatever was set as default timezone in TB when it started (it does not detect that I change the default timezone).

If I set it to something new - e.g Europe/Berlin, it seems til TbSync is sending it as Europe/Berlin, but when it comes back as an ics-file it is set to Europe/Oslo (with extra NULs again).

But I think we can be assured that this issue is not related to TbSync.

I even tested setting the default timezone in TB to Europe/Paris, and modified the default in Outlook to be "Paris, Copenhagen..." instead of "Amsterdam, Oslo...".
But still, after adding an event in TB, and seeing it is sent as Europe/Paris to the server, the ics-file shows it as "TZID=Europe/Oslo....."

I'm giving up at the moment, but you can close this case I believe.

**Comment by jobisoft** [comment]
> For the fun of it, I tried testing with some different timezones for 
> events explicitly.
>
> If I set the timezone for a single event to "UTC/GMT", TbSync will 
> send it as "|standardName: Coordinated Universal Time (UTC)|"
> (And I don't get all the extra NULs in the ics file for that event).
>
> If I set it to "Local Time" TbSync will send whatever was set as 
> default timezone in TB when it started (it does not detect that I 
> change the default timezone).
>
That is true, I pick up the default timezone on start up. I will 
probably change that.
>
> If I set it to something new - e.g Europe/Berlin, it seems til TbSync 
> is sending it as Europe/Berlin, but when it comes back as an ics-file 
> it is set to Europe/Oslo (with extra NULs again).
>
What happen if you set it to some other offset (I think Oslo and Berlin 
share the same), what happens if you set it to USA? You can do that 
directly in the event, you do not need to play with the default timezone...
>
> But I think we can be assured that this issue is not related to TbSync.
>
> I even tested setting the default timezone in TB to Europe/Paris, and 
> modified the default in Outlook to be "Paris, Copenhagen..." instead 
> of "Amsterdam, Oslo...".
> But still, after adding an event in TB, and seeing it is sent as 
> Europe/Paris to the server, the ics-file shows it as 
> "TZID=Europe/Oslo....."
>
How does it come back to Thunderbird (disconnect/reconnect)? Also as 
Oslo? That is utterly strange... What is your phone doing differently? 
If THAT is adding an event, that does not happen, right?
>
> I'm giving up at the moment, but you can close this case I believe.
>
There are still open questions, I think. If possible, I would like to 
get to know the reason for this...

**Comment by Olen** [comment]
Sorry, I used this issue as some kind of "notepad" while debugging, so some stuff might have been lost in the noise.

The only thing I have seen that is common for this issue is that all the TZIDs with NULs have a "/" in them when they come from OWA to the ics.  While all TZIDs without a "/" does not have the problem

This _might_ be a conicedence, as I have only seen TWO TZIDs with a "/" in the ics-file:
```
TZID=Europe/Chisinau^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
TZID=Europe/Oslo^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

While any other TZID seems fine:
```
TZID=Romance Standard Time
TZID=Customized Time Zone
TZID=W. Europe Standard Time
TZID=Coordinated Universal Time (UTC)
```

The last one was even sent from Thunderbird when I created an event and explicitly set the timezone for _that_ event to GMT/UTC in TB.

So it would be interesting to see what happens if you are able to reverse the "translation" of Timezone-names, so if an event is added to TB with TZID=Europe/Oslo, it is sent by TbSync to Exchange as "W. Europe Standard Time" (for instance).  Or maybe even just "Europe, Oslo" - basically just removing the "/".

In the mean time, I have just created a simple "proxy" that fetches the ics-file from owa, removes all the NULs, and outputs it.

**Comment by Flamefire** [comment]
I know this is old but this seems to be still happening in 2.11

- Create Event in OWA and forward it -> All good. `TZID:W. Europe Standard Time`
- Create Event in TB, sync and forward it (from OWA) -> Boom. `TZID:Europe/Berlin�������������������`

**Comment by jobisoft** [comment]
In the current beta I now translate IANA timezone names to Windows timezone names. Wanna give it a spin?
https://tbsync.jobisoft.de
