### ISSUE TITLE
Feature request: Verify software integrity of addon(s) when updating

### ISSUE THREAD

**Issue by Letterus** [jobisoft/TbSync#197]
It seems the Thunderbird updating process works without any integrity validation of the downloaded software currently.

As TbSync handles confidential or even critical data it would be great if one can be sure only validated code will executed. Usually this is achieved by implementing some kind of hash-/signature-checks of the downloaded data.

I think it would be a great security advantage if TbSync implements this.

**Comment by jobisoft** [comment]
I reposted that question here:
https://groups.google.com/forum/m/#!topic/tb-planning/10sZUT9TZvY

I will try out signing and see if that helps. Do you have these concerns for my beta releases from tbsync.jobisoft.de, or also for the stable releases from ATN?

**Comment by Letterus** [comment]
Thank you! Generally I'd like Thunderbird to verify every code package it executes. This is an advantage of installing fe. Lightning using a Linux package manager, but not everyone uses Linux and you can't do this with any small addon.

**Comment by Letterus** [comment]
> I reposted that question here:
> https://groups.google.com/forum/m/#!topic/tb-planning/10sZUT9TZvY

There someone wrote:
> Updates from ATN are protected because they are sent over https, so the server can be identied as the real server.

Of course this is a necessary, but not a sufficient security feature: The addon could be exchanged on the server side. Without a hash and the author's signature you are not able to identify that you are installing malware.

**Comment by jobisoft** [comment]
Yes, you are correct, https only protects against manipulations during transport. 

Since my Beta release channel from tbsync.jobisoft.de uses the same auto-update as the stable channel from ATN, you do not know WHEN an update happend, so you cannot check a hash/checksum. This only works for the initial manual install.

So I think I will try out the signing stuff.

**Comment by jobisoft** [comment]
I think I have to close this, as the signing infrastructure for Thunderbird is broken and not officially supported. It also looks like, no one will work on this. -(

**Comment by Letterus** [comment]
Thanks for investigating. That are kind of bad news for a professional setup. I'm taking a note that we are looking for somebody either fixing Thunderbird code signing or making a Debian package out of your addons.

Do you have some links to ressources how Thunderbird code signing should be done?
Thanks and merry christmas!
