### ISSUE TITLE
Detailed changelog & roadmap

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/TbSync#2]
Moved to wiki

**Comment by jobisoft** [comment]
Fixed timeout problem (which was a sync loop problem)

**Comment by jobisoft** [comment]
### Internals:
- what about changelog?
   -> it gets cleared if a target is deleted, or if it is taken offline
- what about write/save of TbSync data (accounts, folders, changelog)?
   -> each write cmd actually is a write request which schedules an async write after 6s and each write request resets the write timer, so multiple write requests are merged into one final write request, on exit (unload of messenger) all write timers are reset and a final async write is initiated, onbeforeunload did not work with Linux TB, so using onunload to trigger
- what about updating an non-existing folder?
   -> we could resync everything but that might be an overkill, I just use the information of the update request and add the missing folder as not selected (selecting it will initiate the actual sync)
- what about subfolders (parent != 0)?
   -> all subfolders are shown as flat hierarchy, trashed folders handled separately
- what about adding two jobs shortly after another?
   -> jobs are added to a queue and processed one after the other, the exact same job cannot be added twice
- what about resync loop?
   -> if more then 3 resyncs in a row, TbSync is assumed to be unable to recover from some unknown error and stops, user must disconnect and start clean
- what about resyncing with unsynced changes?
   -> during hierarchy resync, local folder information is replaced by server information but targets are kept, if the id does not change (as with horde)

### Notes:
 - explicitly use if (error !== "") not if (error) - fails on "0" and ""
 - loop over all properties when card copy
 - do not use add + modify trick, but a true add, so we can cope with any add
 - Link calendar sync to lightning-sync-button using providerId
 - better separate global strings and functions from  EAS provider strings and functions

**Comment by bonanza123** [comment]
Sorry for hijacking this issue, but are there plans to support shared calendars? Meaning calendars of other user that I'm allowed to read?

**Comment by jobisoft** [comment]
There is an issue for that question already:

https://github.com/jobisoft/TbSync/issues/16#issuecomment-342446917

The last 3  comments of that issue represent the current status. Please (reopen) and use that issue, if you want to discuss that further. What is your EAS backend, O365?
