### ISSUE TITLE
Request to update account password after change

### ISSUE THREAD

**Issue by mattiaverga** [jobisoft/TbSync#205]
After changing the account password on Outlook web interface I only have thunderbird status bar displaying "TbSync: error". I need to open TbSync window and manually click on "Synchronize this account" to have TbSync ask me to update password.
It would be nice if TbSync shows a popup without having to do all these manual steps.

**Comment by jobisoft** [comment]
Fixed in latest beta. Password Prompt i now global and will popup even if the manager is not open.

Info about the beta release channel can be found here:
tbsync.jobisoft.de
