### ISSUE TITLE
No html mails after syncing to CardDAV server

### ISSUE THREAD

**Issue by planmacher** [jobisoft/TbSync#206]
TbSync version: 0.7.22
Provider für CalDav/CardDav: 0.10
Thunderbird version: 60.4.0

I've tried it several times now. 
Allways when I install TBsync and the CalDAV/CardDAV Provider  there ist something going wrong when writing html Emails. The autodetection, if the mail is plain text or html is not working anymore. 
In writing-window I allways have to go to "options=>mail-format=>html" to send the mail as html.

All other settings in TB are correct for sending html mails - or "html and plain text".
Everything is working correct until first connection with some CardDav server. (Tried nextcloud and baikal)

Any ideas?

**Comment by planmacher** [comment]
Yes - I can confirm all of this:
=> this server was synced with sogo connector before.
=> there are Mozilla html: false entries in the card data

But I set TB to send mails as "plain text and(!) html" if address is marked as "plan text" under settings=>writing=>send-options
So mails should be send as html anyway ?!?!

**Comment by jobisoft** [comment]
I think I cannot help there. What happens, if you change the setting in the card itself (in Thunderbird)?
