### ISSUE TITLE
Possible Bug With Recurring Meetings

### ISSUE THREAD

**Issue by ndunn990** [jobisoft/TbSync#21]
Hi there. First off, I love this add-on. Thank you for taking your personal time to make this!

Now, I didn't see any mention of this, but if there is and I missed it please feel free to close this. It seems it fails to sync recurring meetings. I have a feeling I'm not the only one.

**Comment by jobisoft** [comment]
As written on the main project page: That is not yet implemented and is scheduled for v0.7.0.

**Comment by jobisoft** [comment]
Implemented by [Chris Allen] (https://github.com/jobisoft/TbSync/pull/30#issuecomment-355742902).
