### ISSUE TITLE
JavaScript error on contacts sync

### ISSUE THREAD

**Issue by leture** [jobisoft/TbSync#211]
## Your environment

TbSync version: 0.7.22
Thunderbird version: 60.4.0

In addition I use CategoryManager 2.09

[x] Yes, I have installed the latest available version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Sync is done against a Nextcloud 14.0.4 instance.

## Expected behavior

That contacts are synced completely or that the error is handled gracefully so that for example the error does not prevent sync of calendars which would be processed after the failure causing addressbook.

## Actual behavior

Screenshot:

![tbsync_error](https://user-images.githubusercontent.com/288004/50833967-1eb67c80-1353-11e9-9b82-123240b64596.png)

## Steps to reproduce

I have no clue how to reproduce it just happens on every attempt to sync.

I send you the debug log.

**Comment by jobisoft** [comment]
fixed in beta:
tbsync.jobisoft.de
