### ISSUE TITLE
Sync with Microsoft Office 365 - usual password does not work

### ISSUE THREAD

**Issue by DaKarli** [jobisoft/TbSync#212]
This is not an issue but a way to circumvent a common problem when authenticating to Office 365.
Maybe this could be added to the wiki?
But on the other hand, this hint may be used to integrate the mentioned authentication into the EAS add-on, so this could be an improvement for it.

I saw several people having problems to sync their Office 365 calendar with Thunderbird (Lightning) calendar.
The instructions to set up an Exchange Active Sync are correct so far, but when it comes to the point where TbSync tries to connect to the server, it won't accept any password you provide.

**The solution for this is quite simple but not obvious at first sight:**

In case, nothing seems to work, the administrator of your Office 365 tenant maybe enabled Multi-Factor Authentication for all users. 

As Thunderbird and TbSync do not seem to support the way, this kind of Authentication works (forms-based or other old authentication methods vs. Modern Authentication aka Azure AD Authentication Library (ADAL) using OAuth based authentication) you simply cannot be authenticated by your "regular" password.

**All you have to do is to create a so called "App-Password" within the Office 365 portal an use that for TbSync instead of your "regular" login password. For doing so, I added the links to Microsoft's descriptions in english and german, which describe, how to do it.**

German:
https://support.office.com/de-de/article/erstellen-eines-app-kennworts-f%C3%BCr-office-365-3e7c860f-bda4-4441-a618-b53953ee1183

English:
https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183?omkt=en-US&ui=en-US&rs=en-US&ad=US

I hope this will help some people to successfully use TbSync and Thunderbird with Office 365.

With best regards, Harry.

**Comment by jobisoft** [comment]
Awesome, thanks for the info. Would you be so kind to add this to my wiki? I would make you a collaborator for that. 

For Google I am working on OAuth2 authentication, would that also be helpful for O365?

**Comment by jobisoft** [comment]
This issue is pinned, so I can close it.

**Comment by coolacid** [comment]
Just commenting that not all companies allow App-Password -- Thus, OAUTH2 is still a requirement for some people.

**Comment by jobisoft** [comment]
Thanks, I hope someone can contribute.

**Comment by fleskesvor** [comment]
Like @coolacid wrote, app-password is often disabled by companies for security reasons, to enforce the use of two-factor authentication. Therefore, I'm not sure if the "solution inside" label applies, though it might potentially solve the issue for a few people.

**Comment by jobisoft** [comment]
I really need help on the two-factor-authentication. Removing the label.

**Comment by fleskesvor** [comment]
I'm not knowledgeable on the subject, but the Microsoft AD documentation has a list of libraries that might be useful:
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries

**Comment by xaxis3** [comment]
I'm on the same boat, I was looking for an app capable of supporting o365 + 2step (no app-password), when you have it, I will install it again. Thanks for the work otherwise!

**Comment by Mati24** [comment]
Hello,
I used an Office 365 account whitout problem since yesterday. I changed my password, and TbSync tell me to enter the new, but won't accept it. So I tried to remove the accound and add it again, but it tells me to check my username or my password (but they are good because I can't get my emails and login on Office 365 web ui.
`Autodiscover for user <*****@****.**> failed.

Could not authenticate, check username and password (HTTP Error 401).`

I have a two-factor-auth too, but nothing new since the last time

**Comment by jobisoft** [comment]
thunderbird sometimes caches passwords. does restarting thunderbird fixes it for you? If not try to open the thunderbird options and open the password manager and remove any entry that starts with eas:// or looks like an O365 entry, restart thunderbird and try again.

**Comment by Mati24** [comment]
I tried restart and reboot yesterday, clean cache and delete passwords in thunderbird, but I have the same error

**Comment by jobisoft** [comment]
sorry to hear that. If the server tells me the creds are wrong, they are wrong. maybe the O365 server needs a while to populate the new password to teh EAS service? Or maybe two factor auth is messing this up?

sorry.

two factor auth is on my list for september.

**Comment by Mati24** [comment]
Yes I understand thank you. I don't understand why it still working on the imap part, and why It brokes with the password change

**Comment by jobisoft** [comment]
I would like to inform you, that the latest beta of TbSync has OAUTH support for Office 365. Does that also fix the MFA issue?
https://github.com/jobisoft/EAS-4-TbSync/issues/87#issuecomment-553479268

Feedback is welcome.
