### ISSUE TITLE
Translate for Quicktext

### ISSUE THREAD

**Issue by sinya13** [jobisoft/TbSync#214]
Hello John!
I created a Russian translation to Thunderbird add-on Quicktext. You know the add-on Quicktext creators? Can you add this translation? It is here: https://github.com/sinya13/quicktext

**Comment by jobisoft** [comment]
I am the maintainer of quicktext.

Create a pull request and I will merge it.

Best regards,
John

**Comment by jobisoft** [comment]
Wow, I did not know I can do that. I initiated the pull request by myself. I will check it out soon.
