### ISSUE TITLE
Issue with PortableApps Version of TB

### ISSUE THREAD

**Issue by roadrunnerjb** [jobisoft/TbSync#217]
## PortableApps Version of TB

TbSync version: 2.14.7
Thunderbird version: 60.4.0 32 Bit PortableApps Version

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

I use PortableApps on a  SSD connected via USB on different machines, so I get differen driveletters
PortableApps TB can deal with this but I think there is an issue in TBSync using the path location of the point in time when the calendar is defined. Is there a way to fix this may be by editing the settings xpi ? 

## Actual behavior
![20190116_173736-kp-angelab 192_-_192 168 111 130_-_remotedesktopverbindung](https://user-images.githubusercontent.com/6381558/51264712-6bcfc980-19b7-11e9-8912-996896f5bcc0.jpg)
...

## Steps to reproduce
This error occurs every time the path of TB directory changes and TB is started ...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
The hardcoded link is pointing to something in Lightning. Can you remove TbSync and Setup the calendars "by hand" and see if that works after changing the drive letter?

**Comment by roadrunnerjb** [comment]
Thx for your quick response,

first I removed the calendars from ligtning, then i removed the connections form tbsysnc. 
Then I tried to reconfigure one of the source without success,
I can activate the account, get the list of dav ressource but when I sync I get the same error.

Then I removed and reinstalled tbsync, configured one of the dav ressource, and it works.

Do you have an idea for a portable solution because there are many machines and many dav ressources to change for me...

Regards

**Comment by roadrunnerjb** [comment]
yes. I use Thunderbird in the portableApps Suite

https://portableapps.com/

**Comment by ThomasAusSinsheim** [comment]
I use TB portable too. Everytime when I plug my USB stick on another pc, it would help to do theese steps:
- deactivate Lightning and all TbSync add-ons
- restart TB
- activate Lightning
- restart TB
- activate all TbSync add-ons

**Comment by jobisoft** [comment]
With all these changes in the addon world, i do not have the resources to fix this issue with the non official portable version.
