### ISSUE TITLE
Office 365 - special character break sync

### ISSUE THREAD

**Issue by fabienduval** [jobisoft/TbSync#22]
Hi,

I just discovered this plugin after my company migrated to office 365.

I am experiencing an issue at the first synchronization, I have this error : 

"ActiveSync protocol violation: Mandatory field <Sync.Collections.Collection.Status> is missing in server response."

From the plugin's interface, I see that we are using ActiveSync version 14.0.

Does anyone has encountered this issue?

**Comment by jobisoft** [comment]
could you enable debug log and post it here?

**Comment by jobisoft** [comment]
Also you can try, if it is resolved in the current master version (beta). Rename the file from ZIP to XPI and install it manually at the Thunderbird Add-On page
[TbSync_0.6.8.3.zip](https://github.com/jobisoft/TbSync/files/1461460/TbSync_0.6.8.3.zip)

If it still does not work, a debug log would be very helpful. It can be enabled under "Help" in the TbSync account manager.

**Comment by fabienduval** [comment]
The logs helped me a lot, the actual error was inside an event in my calendar, I erased it and everything works now.

Here the log if that can help you in improving the plugins reliability : 


** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[setSyncState] : State: recievingchanges, Account: Fabien DUVAL, Folder: Calendrier

** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[Extracted XML data] : 
parsererror => 
 sourcetext = [HERE WAS A FRENCH MESSAGE, I LET THE SPECIAL CHARACTERS: c\FDl\FDbrer avec l \FDqu le tr\FDs  \FDt\FD u\FD u \FD pr\FDs.
------------------------------------------------------------------------------------------------^]
parsererror <= 


** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[wbxml status] : Server response does not contain mandatory <Sync.Collections.Collection.Status> field . Error? Aborting Sync.

** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[finishSync(): Error @ Account Fabien DUVAL] : ActiveSync protocol violation: Mandatory field <Sync.Collections.Collection.Status> is missing in server response.

** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[setSyncState] : State: done, Account: Fabien DUVAL

** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[setSyncState] : State: accountdone, Account: Fabien DUVAL

** Fri Nov 10 2017 19:47:56 GMT+0100 (CET) **
[JavaScript Error: "XML Parsing Error: not well-formed
Location: moz-nullprincipal:{008a7366-7947-45bf-82e8-05b082cc97e5}
Line Number 60, Column 97:" {file: "moz-nullprincipal:{008a7366-7947-45bf-82e8-05b082cc97e5}" line: 60 column: 97 source: "HERE WAS A FRENCH MESSAGE, I LET THE SPECIAL CHARACTERS: r c\FDl\FDbrer  l \FDqule tr\FDs   a \FDt\FD effectu\FD jusqu \FD pr\FDsent,."}]

** Fri Nov 10 2017 19:47:58 GMT+0100 (CET) **
[setSyncState] : State: idle

**Comment by jobisoft** [comment]
I would like to fix this, since TbSync should cope with any text stored in events. Could you send me the full log via email? Or could you tell me, what french text I should add to the event? Which field?

**Comment by fabienduval** [comment]
I fowarded you the event. I'm sorry I can't send you the full log as there is some confidential informations in it.

**Comment by lsumal** [comment]
Hi, 

I was just wondering if you had a fix for this error? I'm getting the same problem but it's only when syncing my personal Outlook.com calendar. TbSync is able to receive my partner's shared calendar no problem and I can see all the events fine. I downloaded the beta version using the link you posted above and the same issue occurs.

If it was just one event that's causing the issue, I could delete it but how can I find which one is causing it? I don't want to delete everything if possible!

Thanks.

**Comment by jobisoft** [comment]
Do NOT delete any of your user data! 

You could enable debug log and send me the full log of such a failure. I was not yet able to solve the problem.

**Comment by jobisoft** [comment]
Can you retry with the latest beta [TbSync v0.6.8.3 (2017.12.28)](https://github.com/jobisoft/TbSync/releases/download/v0.6.8.2/TbSync-0.6.8.3-2017.12.28.xpi) ?

Can i have a debug log of when that error happens?

**Comment by jobisoft** [comment]
probably fixed in v0.7.1

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
