### ISSUE TITLE
Add Inbox Calendar Column

### ISSUE THREAD

**Issue by cseader** [jobisoft/TbSync#225]
## Your environment
TbSync version: latest
Thunderbird version: latest
Use openSUSE Tumbleweed

I'm not reporting any problem, but please consider an enhancement.

It would be great to have an extra calendar column in the Inbox so that each email received that has an appointment attached shows it in a calendar column in the Inbox with a little calendar icon by the email for that column. 
Thoughts?

**Comment by jobisoft** [comment]
You would need to file a bug for this with Thunderbird itself.
