### ISSUE TITLE
Only 1 result in autocomplete and 4 on search

### ISSUE THREAD

**Issue by bastien30** [jobisoft/TbSync#228]
## Your environment

TbSync version: 0.7.22
Thunderbird version: 60.5.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
1. When typing address in "To" form, there should be all the matchings results from GAL in the dropdown menu.
2. When searching in address book, there should be all the matchings results from GAL

## Actual behavior
1. There is only 1 matching result in the dropdown menu.
2. There is only 4 matching results.

Not really a bug but rather an improvement.

Thanks !

**Comment by jobisoft** [comment]
Could you verify, that this is valid for the beta as well?
https://tbsync.jobisoft.de

**Comment by bastien30** [comment]
Yes I've tested with the beta and this is the same behaviour.

**Comment by jobisoft** [comment]
Ok, can you provide a test account where you and I can reproduce this 100%? Credentials via email, of course.

**Comment by bastien30** [comment]
Email sent :blush:

**Comment by jobisoft** [comment]
That is very strange. If you look at the debug log of such a request, it looks like this:

```
[XML: Sending data <SearchingGAL> for bastien30] : 
<?xml version="1.0"?>
<Search xmlns='Search'>
<Store>
<Name>GAL</Name>
<Query>test</Query>
</Store>
</Search>

** Fri Feb 01 2019 17:04:41 GMT+0100 **
[Sending (EAS v14.0)] : POST https://xxx/Microsoft-Server-ActiveSync?Cmd=Search&User=test1%40routeprivee.com&DeviceType=TbSync&DeviceId=MZTB94b3775e1faff36ba32b01b1b52b

** Fri Feb 01 2019 17:04:41 GMT+0100 **
[XML: Receiving data <SearchingGAL> for bastien30] : 
<?xml version="1.0"?>
<Search xmlns='Search'>
<Status>1</Status>
<Response>
<Store>
<Status>1</Status>
<Result>
<Properties>
<DisplayName xmlns='Gal'>test1</DisplayName>
<LastName xmlns='Gal'>test1</LastName>
<EmailAddress xmlns='Gal'>test1%40routeprivee.com</EmailAddress>
</Properties>
</Result>
<Range>0-0</Range>
<Total>1</Total>
</Store>
</Response>
</Search>
```

So your server only return one match. 

*reading the docs again*

**Comment by jobisoft** [comment]
Your server needs a RANGE value if 0-99 is default:
https://msdn.microsoft.com/en-us/library/gg663546(v=exchg.80).aspx

After adding that, I get all results:
![image](https://user-images.githubusercontent.com/5830621/52135913-337eeb00-2647-11e9-9701-92e27e7bd004.png)

And:
![image](https://user-images.githubusercontent.com/5830621/52135973-501b2300-2647-11e9-8a9b-de21cb0d9d30.png)

The next beta will include this, but I need to let pass a few days, because I released a new stable yesterday and must now switch all beta users back to stable. During that time I cannot release new betas...

**Comment by jobisoft** [comment]
If you want to try it before it is released:
[EAS-4-TbSync-0.10.1.zip](https://github.com/jobisoft/TbSync/files/2822478/EAS-4-TbSync-0.10.1.zip)

**Comment by bastien30** [comment]
I confirm it works as expected.

Thanks for your reactivity and your work, it's not so much, but I've offered you a beer on paypal ;)

You can close the issue if you want, this is solved to me, I will use the beta until the next stable release.

By the way, is there any changelog for TbSync and the providers modules ? I can't find it.

**Comment by jobisoft** [comment]
I am changing so much at the moment, that I stopped updating it. You can look at the commit Messages, which is of Course a lot of small steps, but you get the idea.

https://github.com/jobisoft/TbSync/commits/master
https://github.com/jobisoft/DAV-4-TbSync/commits/master
https://github.com/jobisoft/EAS-4-TbSync/commits/master

**Comment by jobisoft** [comment]
I just released it via the beta release channel.

Your current version was out of line and does not update automatically. Please download and install all current beta modules as described here:
https://tbsync.jobisoft.de

**Comment by bastien30** [comment]
Done. Thanks 😉

**Comment by Mer0me** [comment]
'lo world,

I'm using TBSync 2.9 on Thunderbird 68.3.1 (32 bits) / Windows 10.
Two accounts are configured in TBSync : 
- Exchange 2007 account with Provider for Exchange ActiveSync
- Nextcloud account with Provider pour CalDAV & CardDAV (NextCloud 17.0.1)
I also have a LDAP directory (Active Directory) configured.

Contacts are very well synchronized and I can search and find them in Address Book, but auto-complete doesn't work for some of them.

In the example below, you can see that the search for "delp" in address book returns 4 results, 3 from Exchange Account, 1 from NextCloud account.
But when typing the same four letters in the composition windows, only the first result is displayed.

![tbsyncbug](https://user-images.githubusercontent.com/6248852/71089735-c4987b00-21a1-11ea-9b78-b31f5363de97.jpg)

Debug log corresponding to this action is provided below :

[debug.log](https://github.com/jobisoft/TbSync/files/3978612/debug.log)

It seems that, at least, the 3 results from Exchange Account are returned. I'm not sure of the meaning of the log for the NextCloud Account.

 Autocomplete  on other search terms works well, combining results from LDAP, Exchange Account and NextCloud Account like this : 

![tbsyncbug2](https://user-images.githubusercontent.com/6248852/71090366-25748300-21a3-11ea-84bc-1c8ee93aef61.jpg)

Anyway, thank you for your amazing job with TBSync !

**Comment by jobisoft** [comment]
Can you retry with beta? I did some fixes for autocomplete in the last week.
https://tbsync.jobisoft.de

**Comment by Mer0me** [comment]
It doesn't work with beta. No change at all.
