### ISSUE TITLE
Caldav issue accepting events

### ISSUE THREAD

**Issue by jgato** [jobisoft/TbSync#229]
Using Caldav Provider with Davmail daemon and Office365 server. 

Some accepted events are shown in "light" colour in the  calendar, as if they were pending. I does not always happens, but I dont  know the difference between when it happens ok. I have asked also in [Caldav Repo](https://github.com/jobisoft/DAV-4-TbSync/issues/70), but it seems is not an issue from them (and I dont think it is a problem with lightning, other calendars work properly).

As it can be seen in this image:
![image](https://user-images.githubusercontent.com/3435696/52035566-1ce37180-252b-11e9-9792-b223f64141a1.png)

The event at 09:00 is ok, it was accepted and it appears with a regular blue color.
The event at 12:00 appears in a light colour as it was pending to accept or deny, but, I have accepted it. Actually, if I edit the event:

![image](https://user-images.githubusercontent.com/3435696/52035684-413f4e00-252b-11e9-9e97-6e190420f1e3.png)

It can be seen as accepted. but If I look in detais, there is other parameter still saying tentative.

![image](https://user-images.githubusercontent.com/3435696/52035703-51efc400-252b-11e9-9355-28d10ca14439.png)

So, I guess this is the main issue, this incorrect status, accepted and pending at the same time.

Doing more tests I think it depends on how I accept the event:

1 - If I accept the event from the email it seems is working ok
2 - If I accept the event from the calendar it happens this estrange situation...

## Your environment

TbSync version: beta 1.0.32
DAV-4-TbSync version: 0.10.44
Thunderbird version: 60.4.0

[X ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Lets continue to discuss this in the other issue :-)
