### ISSUE TITLE
Changelog for new releases

### ISSUE THREAD

**Issue by szpak** [jobisoft/TbSync#231]
I would be happy to know what (importantn) new features/bugfixes are incorporated into the new versions of TbSync. Currently it seems to be not available - apart from Git commit history.

I saw #2 and the [roadmap page](https://github.com/jobisoft/TbSync/wiki/Roadmap), but it doesn't anwer my questions (I might also missed something obvious :) ). I would be nice to have it in the [release information](https://github.com/jobisoft/TbSync/releases/tag/v1.5) on GitHub or alternatively have there a link to a changelog file (or some other place).

**Comment by jobisoft** [comment]
I know, I stopped doing so. At the moment I just have so much to work on, that I do not have time for documenting. The commit history is your only friend at the moment.

Any particular reason your are asking?

**Comment by szpak** [comment]
I understand,

Not really. I just woudn't like to miss any important feature that is added and which needs to be explicitly "enabled".

**Comment by jobisoft** [comment]
That is true, I should at least do that.

One of those is the new group sync for the DAV Provider (iCloud uses it).

**Comment by jobisoft** [comment]
I will, starting with the next release, put release notes on ATN, which will also be visible inside Thunderbird AddOn Manager if clicked on „recent updates“.

**Comment by grahamperrin** [comment]
Where would I find the log of changes between 4.11 and 4.16? 

https://github.com/jobisoft/TbSync/tags has 4.12 uppermost, and there's no release note with the add-on. 

Thanks
