### ISSUE TITLE
Suggestion to add two offset options

### ISSUE THREAD

**Issue by sinya13** [jobisoft/TbSync#233]
Hello John!

I have a suggestion to add two offset options for building a priority order for several accounts.

![tbsync-m-1-change](https://user-images.githubusercontent.com/4994987/52549699-7da16280-2de5-11e9-8964-fb4598764489.jpg)

**Comment by jobisoft** [comment]
Duplicate of https://github.com/jobisoft/TbSync/issues/140

**Comment by sinya13** [comment]
Ok
