### ISSUE TITLE
Exchange account disappears sporadically

### ISSUE THREAD

**Issue by rawroland** [jobisoft/TbSync#234]
## Your environment

TbSync version: 1.5
Thunderbird version: 60.4.0 (64-bit)
Operating System: Ubuntu 18.04

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
My exchange account does not disappear.
...

## Actual behavior
My exchange account disappears sporadically and I have not been able to find out why yet.
...

## Steps to reproduce
I have not been able to reproduce the error yet.
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Your account is being removed from the accounts list in the TbSync account manager and you have to set it up anew? What happens to the calendars and address books which have been created by TbSync, do they still exist or are they removed as well?

**Comment by rawroland** [comment]
> Your account is being removed from the accounts list in the TbSync account manager and you have to set it up anew?
Yes.
> What happens to the calendars and address books which have been created by TbSync, do they still exist or are they removed as well?
They still exist.

I have activated debugging for now, and will send a debug log if the problem repeats itself.

**Comment by jobisoft** [comment]
Please switch to the beta release channel:
https://tbsync.jobisoft.de

**Comment by rawroland** [comment]
Done. Thanks for your assistance.

**Comment by rawroland** [comment]
Hello, the problem reoccurred after a long period. Find the debug log attached.
[debug.log](https://github.com/jobisoft/TbSync/files/2919739/debug.log)

**Comment by pjstevns** [comment]
Same problem hit me today. Using: 

tbsync 1.7
tb: 60.5.1 (ubuntu's package)
ubuntu: bionic (18.04)

I'm not sure when it occurred. I check the TbSync pane regularly, since I first found out this sometimes happens. It must have been sometimes between today and two weeks ago. So my guess is, it's related to a thunderbird upgrade.

**Comment by jobisoft** [comment]
I will add a check on save, that will prevent the empty-save in the future. Very strange bug.

**Comment by jobisoft** [comment]
I close this now as it looks like it is fixed. If not, reopen.

**Comment by planicka** [comment]
All my accounts (exchange and google) disappeared today :(
tbsync 2.12, provider for exchange 1.14, provider for caldav 1.12
thunderbird 68.7.0

**Comment by emilnhiper** [comment]
My Office 365 account added with Oauth has disappeared without a trace twice now.

**Comment by RenWal** [comment]
My Nextcloud accounts disappeared as well.
Thunderbird 91.8.0
TbSync 3.0.2

Interestingly enough, it looks like the accounts are still synchronizing, just the TbSync settings don't show the account anymore.
