### ISSUE TITLE
Sync of shared calendars with Horde backend

### ISSUE THREAD

**Issue by xj25vm** [jobisoft/TbSync#235]
## Your environment

TbSync version:1.5
Thunderbird version: 60.5.0
Horde: 5.2.20

I see there are a few tickets opened for shared calendars in relation to Outlook365 or MS Exchange. I can't work out though if TBSync supports shared calendars (or address books) with Horde? So far:

1. I created a calendar belonging to User A in Horde.
2. I've given permission to User B to access the calendar.
3. I have logged in as User B  in Horde and I can see the calendar.
4. When I connect through TBSync as User B, I can't see the shared calendar under "Available resources" in TBSync

Is this supposed to work, or it isn't supported yet?

**Comment by jobisoft** [comment]
I show everything that your server reports via EAS, however EAS is not designed for that. So mostly it is not supported (EAS has no Rights Management). 

O365 is using Proxy calendars, which means if you share a calendar, O365 will create a new calendar in your account and will sync it (server-to-server) with the shared one. This way you have full write Access to your copy and cannot mess up the original shared one. O365 will then revert changes in your copy.

**Comment by xj25vm** [comment]
Thank you for the quick reply. It sounds like there isn't much that can be done about it. Which is a shame - as shared calendars or address books are a significant reason for having a synced back-end. Thank you again.

**Comment by jobisoft** [comment]
EAS is the simple Version of EWS, which supports shared calendars. However, TbSync does not yet support EWS, but there is an EWS addon as well
https://github.com/ExchangeCalendar/exchangecalendar/releases
