### ISSUE TITLE
TBsync OSX not shows the addon settings

### ISSUE THREAD

**Issue by voicenoise** [jobisoft/TbSync#239]
Hi i have thunderbird 60.5.2 (64-Bit) on OSX 10.12.6
the addon can install with no problems but i miss the settings for the addon.
I can show only the lighning settings

edit i try version 0.12 and now the beta too. At booth version are the same.

**Comment by jobisoft** [comment]
Can you open the TbSync Manager via the other options?
https://github.com/jobisoft/TbSync/wiki/How-to-get-started#1-open-tbsync-account-manager

**Comment by voicenoise** [comment]
yes i see this instructions but i miss the Add-onOptions > TbSync 
![](https://github.com/jobisoft/TbSync/raw/master/screenshots/TbSync_000.png)

the addon is activated under extensions

**Comment by voicenoise** [comment]
i don't know what i do wrong... there is no addon !?
also i try version 60.4.0 but is the same the addon is not visible in options.

![screeshot](https://user-images.githubusercontent.com/46731907/53907959-96044600-404e-11e9-8a74-21546e23140c.png)

**Comment by jobisoft** [comment]
You need TbSync as well. From what I see, you only installed the EAS Provider (which tells TbSync how to talk to EAS Servers). Just search for TbSync in the AddOn Manager.

**Comment by jobisoft** [comment]
If you installed the beta of the provider, you also need the beta of TbSync.

**Comment by voicenoise** [comment]
great thats my fault, so you can close this.
many thanks for helping
