### ISSUE TITLE
ActiveSync protocol violation error

### ISSUE THREAD

**Issue by bumface11** [jobisoft/TbSync#24]
My initial sync fails with the following error:
![image](https://user-images.githubusercontent.com/8397194/33525329-34fe5216-d825-11e7-8bdd-862f2be202c9.png)

Error console shows:
XML Parsing Error: not well-formed
Location: moz-nullprincipal:{b20fc7a0-92aa-4b25-bd74-b829c3a50157}
Line Number 37, Column 12482:  {b20fc7a0-92aa-4b25-bd74-b829c3a50157}:37:12482

**Comment by jobisoft** [comment]
Could you disconnect the failing account in TbSync Account Manager, enable the debug Log (@ Help) and reconnect again and send me the debug log? It does not contain any passwords but your contact and appointment data and your user name.

I need the full debug log, because your "user data" is the reason for the error, which somehow breaks the XML, so I cannot parse it correctly. You can send the log directly to my email address.

Thanks for your time
John

**Comment by jobisoft** [comment]
Can you retry with the latest beta [TbSync v0.6.8.3 (2017.12.28)](https://github.com/jobisoft/TbSync/releases/download/v0.6.8.2/TbSync-0.6.8.3-2017.12.28.xpi) ?

Can i have a debug log of when that error happens?

**Comment by jobisoft** [comment]
Cannot fix this without proper debug log. Added better error identification, so XML parse errors now have a dedicated error message with instructions on how to help me to fix this bug.

**Comment by jobisoft** [comment]
probably fixed in v0.7.1

**Comment by bumface11** [comment]
Fixed for me.  Thanks very much!

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
