### ISSUE TITLE
Get and display more information from Exchange?

### ISSUE THREAD

**Issue by michel34** [jobisoft/TbSync#242]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.5.3 (32 bits), Windows

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

This add-in works so well that it is frustrating that it does not display everything that it could.

## Expected behavior
1) in Global Address List:
  a) display entire list
  b) show tree structure (ex: GroupX, with people Xa and Xb; Rooms, with Room1 and Room2;...)

2) in Calendar: ability to display other people's calendar, not just my calendar. Possible with "Exchange Calendar" ( https://github.com/ExchangeCalendar/exchangecalendar/releases ) but not very convenient (must subscribe to each people's calendar)

## Actual behavior

1) Global Address List:
   a) addresses appear when searching in addressbook, and for autocompletion when writing an e-mail, but the list itself cannot be displayed
   b) the tree structure is not displayed

2) Calendar: I found no way to see other people's calendar

## Steps to reproduce
- install TbSync and Provider for Exchange ActiveSync
- configure an Office365 account
- synchronize
- look at addressbook in Thunderbird
- look at calendar in Thunderbird (Lightning)

**Comment by jobisoft** [comment]
1. The GAL is only searchable via EAS, I need at least 3 chars. Searches with less chars are ignored. No way to get the entire directory.

2. EAS does not have any ACL and does not support shared resources. There are some servers like O365 that proxy shared calendars into local resources for each user (and sync them via an extra backend), but the protocoll itself does not support that.

:-(

Sorry. If you need that, EWS is your friend (the plugin of your link)

EAS = Exchange ActiveSync
EWS = Exchange WebServices

**Comment by michel34** [comment]
It's a pity! Thank you for your answer and your work.
