### ISSUE TITLE
Issue with outlook.com

### ISSUE THREAD

**Issue by goerni1** [jobisoft/TbSync#244]
## Your environment

TbSync version:1.7
Thunderbird version:60.6.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync stopped working with my outlook account for some reason - Error "http status 503". 

I removed the outlook account from TbSync and tried adding it serveral times, but failed - Error: something like "Server not sending Information. Is EAS active for this user or the program (TbSnyc) ?"

I got it to work again, while not using my real login but an outlook alias email adress, which I created for this purpose. 

Weird behavior is that Tbsync fails now to sync, when I use my real outlook/live login (which is an @googlemail.com adress and setted as "primary alias"). However all settings for my new outlook EAS account are exactly the same (instead of the user login, which is now @outlook.com)

All callender notes now sync correctly again.

If needed I think I can reproduce the error annd send some log data.

**Comment by jobisoft** [comment]
Thanks for the report. As nothing changed on my side, I assume outlook.com has updated/migrated their service and no longer supports non-outlook.com addresses for EAS.

Glad you found a solution, will make this issue sticky for others to find.

**Comment by goerni1** [comment]
Thank you for clarifying my complete meaningless topic!
