### ISSUE TITLE
Set addressbook as read-only on the user side

### ISSUE THREAD

**Issue by franjb68** [jobisoft/TbSync#245]
Good morning.

We'd like to use Exchange ActiveSync to share some addressbooks with a group of users, but we don't want them to modify the data.

If we set an addressbook as read-only for a user in the server, TBSync with EAS don't show it to that user.

A possible solution for us would be to give the users full access to the addressbook and set it as read-only on the user side. That addressbook shouldn't allow any modification made by the user, not even local modifications, to avoid misunderstandings.

Do you see it as a possible new feature?

Thanks in advance,

**Comment by jobisoft** [comment]
One more thing: if you set the addressbook as readonly on the server and the user does make changes in Thunderbird and tries to sync them, what kind of error message does he get? I could use that error to enable read-only mode in TbSync.

For calendars, Thunderbird has a true readonly mode, for contacts however I currently cannot prevent local modifications, but revert them on next sync.

Does that readonly option in TbSync solve your problem? You do not need to grant users full access rights.

What kind of server are you using?

Best regards,
John

**Comment by franjb68** [comment]
If the addressbook is set as readonly on the server, that addressbook is not shown in the 'Available resources' list. I'm using a Horde server.

But your comment has made me look carefully my TBSync installation and I must apologize for not seeing the 'Read-only server access (revert local changes)' option next to the addressbooks in the 'Available resources' list before opening this request. It works fine for me and does what it says.

I'm sorry for wasting your time.

Thank you very much!

**Comment by jobisoft** [comment]
> Am 26.03.2019 um 11:37 schrieb franjb68 <notifications@github.com>:
> 
> If the addressbook is set as readonly on the server, that addressbook is not shown in the 'Available resources' list. I'm using a Horde server.
> 
Ah, probably due to the missing acl support, so they simply do not allow access.
> But your comment has made me look carefully my TBSync installation and I must apologize for not seeing the 'Read-only server access (revert local changes)' option next to the addressbooks in the 'Available resources' list before opening this request. It works fine for me and does what it says.
> 
> I'm sorry for wasting your time.
> 
You can donate to make up for it :-)

https://github.com/jobisoft/TbSync/issues/107


> Thank you very much!
> 

You are welcome,
John
