### ISSUE TITLE
Outlook synced address book dominating Thunderbird

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/TbSync#246]
I'm afraid  I don't know if this is a TBSync issue, an EAS-4-TBSync issue, a Thunderbird issue, or my own ignorance/stupidity (probably the latter), but I haven't had any replies to a query on the Mozilla Thunderbird support forum, so ...

I have recently started using an outlook.com email account alongside my other mail accounts, wanted to sync TB calendar and address book/contacts to outlook.com, found and installed  TBSync and EAS-4-TBSync and synced. TBSync created a new Outlook (Contacts) address book in Thunderbird. I solved an initial problem (no button to complete editing of any contacts in the Outlook (Contacts) address book) by then installing the latest betas of TBSync and EAS-4-TBSync, but have now run into some behaviour I just can't figure out.

In the Thunderbird address book I already had the default Personal address book and a Gmail address book that syncs to my Gmail account Contacts using gContactSync. Both have identical content. To start with this Outlook.com account I exported the gmail.com contacts with the Outlook CSV option, then imported that into the outlook.com People. That was what was then synced back to create the new Outlook (Contacts) address book in TB by TBSync. It has all the same contacts as the Personal and Gmail TB address books EXCEPT different Display Names (gmail.com Contacts doesn't export those, so outlook.com People never got them, but TBSync created Display Name entries from the name fields producing in many cases different results to the display names I'd assigned by hand in the Personal address book that were then copied to the Gmail address book).

And what has me stumped is that TB will now ONLY use the Display Names in the Outlook (Contacts) address book created by and syncing with TBSync. If I tick to use the display name in the Outlook address book, then those appear in the main Thunderbird message list and messages; if I untick using the display name in the Outlook address book, then I get the email addresses in the main Thunderbird interface - and it makes no difference whether I have use display names ticked or not in the Personal or Gmail-synced address books. For some reason the TBSync created and syncing address book appears to be overriding the others, and I cannot find why, or a setting anywhere to control which address book's display names and display name use settings should be followed. I have been able to find no way to get TB to use the display names in the Personal or gmail-syncing address books with the Outlook (Contacts) TBSync created address book present.

I can work round this in effect by manually changing all the display name entries in the Outlook address book to what I want - but I just wouldn't have thought I should have to.  Where different address books have the same contact but different display names, surely there's some mechanism to set which should be used? Which leaves me thinking that either I'm missing something (probably an obvious something), or TBSync or Thunderbird has some bug that's making one address book override the others somehow.

**Comment by jobisoft** [comment]
If there are more then one entries to an email, TB is free to choose which "contact" it uses, thus which display name to use. If you disable the outlook address book in the tbsync manager, it should start to honor another contact and its displayname. Probably after a restart. Can you verify that?

In the long run, you want to remove the gcontact sync book from TB?

I may help you to get the correct display names in a batch job, not by hand. What is teh display name supposed to look like? Firstname + Lastname?

best regards,
John

**Comment by jobisoft** [comment]
status?
