### ISSUE TITLE
Flagged messages as tasks?

### ISSUE THREAD

**Issue by 1one-w01f** [jobisoft/TbSync#249]
This is an awesome add-on; thank you very much for the hard work.

Just one quick question. Was wondering if it is currently possible to fetch tasks created based on flagged emails?

**Comment by jobisoft** [comment]
That is a function independent from TbSync, right? You want to create a Task based on an email? That is the domain of Thunderbird + Lightning. TbSync could than of course sync that task.

Or did I misunderstood this request?

**Comment by 1one-w01f** [comment]
Hi,

I don't think this is a purely Thunderbird + Lightning function. A bit more details:

Say you use your Android phone to flag an email on your Office 365 inbox (or similarly, flag it using the Office 365 Outlook Web interface), then on the Office 365 side, a task will automatically be created (under the "Flagged items and tasks" list on the Outlook Web interface). 

My question was whether TbSync can also fetch those tasks automatically created by Office 365. Recently the [Microsoft To-Do app on Android](https://play.google.com/store/apps/details?id=com.microsoft.todos&hl=en_US) has also added such feature, so I was wondering if it is possible to have something similar on TbSync.

**Comment by jobisoft** [comment]
So it is a normal task? In your task folder? If you have that task folder subscribed to in TbSync and have enabled autosync, it should show up eventually in Lightning. Like any other taks created remotely. Not?

**Comment by 1one-w01f** [comment]
I'm not sure about the folder hierarchy on Office 365, but the automatically created tasks do not show up in the normal Tasks folder.

As shown below, using the Outlook Web interface, those will be put under the "Flagged items and tasks" list (is it a separate folder?)
![image](https://user-images.githubusercontent.com/35460075/56830363-259ac980-6834-11e9-8ef3-9d5f781dfc09.png)

Also, this "Flagged items and tasks" list does not show up in the list of "Available resources" in the TbSync account manager window. Only the normal "Tasks" list is available. As the result of which, all manually created tasks that are saved to "Tasks" are synchronized, but not the ones Office 365 created based on flagged messages.

**Comment by jobisoft** [comment]
I have on O365 account. How do I flag emails as tasks? I do not see that option. Does the email Needs to contain Special data, to trigger that Option (an ics file?)

**Comment by jobisoft** [comment]
Found it. The folder, where that info is stored is of type 12 (you can see that, if you activate log). 
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/8f3efbfb-9a60-4f6c-a031-f0c863b9d4b7

That is an email Folder and TbSync cannot handle email folders. This is sadly a wontfix as I have no resources to implement that.

**Comment by 1one-w01f** [comment]
I totally understand. Was curious about the technical details. Thanks for digging into it. I really appreciate the effort.
