### ISSUE TITLE
Group members

### ISSUE THREAD

**Issue by okelet** [jobisoft/TbSync#253]
TbSync version: 1.7
Thunderbird version: 60.6.1

Hi all, I am using TbSync for months without any major issue (Office 365 from my company). Using Linux 99% (Ubuntu 18.04), I wonder if I can see the members of a group. Is this an issue of TbSync or Thunderbird? Any workaround?

I can see the group contact in the address book, but when I click on it, I can't see any tab or section where I can list the members of that group.

**Comment by jobisoft** [comment]
I think EAS Groups are send as categories. If that is the case, my CategoryManager should help:
https://addons.thunderbird.net/addon/categorymanager/

**Comment by jobisoft** [comment]
Status?

**Comment by okelet** [comment]
Sorry for the delay, but I could'nt make it work. Perhaps I don't understand how the TbSync/CategoryManager integration works. These are some screenshots, after installing CategoryManager (I can see the integration, but no info about members):

- [Main address book view](https://imgur.com/ahWDXbb)
- [Searching a group contact](https://imgur.com/VNYaTWh)
- [Group contact info](https://imgur.com/pGwaFwl)
- [Group contact categories](https://imgur.com/zW7jt5s)

**Comment by jobisoft** [comment]
I see an empty address book? I thought you have an Office 365 addressbook which has groups defined (visible in the Office 365 portal) and you want to see these Groups in Thunderbird?

Can we first define, what you refer to as "groups"? Can I have a screenshoot, where these groups are seen?

**Comment by okelet** [comment]
Mmmmm well, by group I mean distribution lists, in Office 365. [This is a screenshot from the Outlook web page](https://imgur.com/a/QwidkUU) where I can see the same group searched before, with the members I would like to see in Thunderbird address book.

About the empty address book, I suupose that is because the entire address book is not synced, but when I search for something, I can see the results.

**Comment by jobisoft** [comment]
I investigated this and I cannot resolve this. Those contact lists are not transmitted via the Exchange Active Sync protocol. I simply do not see them.

So this is a WONTFIX. Sorry.
