### ISSUE TITLE
Office365 lost response to the invitation

### ISSUE THREAD

**Issue by trourance** [jobisoft/TbSync#254]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.0 (64 bits)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I accept an invitation, I sync with the server and my calendar entry shows "You have accepted this invitation".

## Actual behavior
I accept an invitation, I sync with the server and my calendar entry shows "You have accepted this invitation". When I relaunch Thunderbird the day after, the same invitation is in the list again and the status in the calendar is "You haven't yet responded to the invitation"

## Steps to reproduce
As stated above.

**Comment by jobisoft** [comment]
ActiveSync or CalDAV?

**Comment by trourance** [comment]
Exchange ActiveSync

**Comment by jobisoft** [comment]
Handling of meeting stuff in ActiveSync is not fully implemented and it will take a while before I can get to that. Support from the community (donations/actual work) is pretty low. 

Your issue is probably already covered by one of the issues listed here:

https://github.com/jobisoft/EAS-4-TbSync/issues

**Comment by trourance** [comment]
Ok. Should I switch to CalDav & CardDav ? Is that going to work better with Office365 ?

**Comment by jobisoft** [comment]
No :-) Office 365 does not support CalDAV/CardDAV. Sorry.

**Comment by jobisoft** [comment]
Closing, as this issue has been filed in the wrong repository.
