### ISSUE TITLE
[BETA Release] Latest add-ons fail to install in TBird 67

### ISSUE THREAD

**Issue by 05nelsonm** [jobisoft/TbSync#256]
## Your environment

TbSync version: Beta Release last updated on [2019-05-01 20:22] from url -> https://tbsync.jobisoft.de/beta/
Thunderbird version: 67.0b3 (64-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
.xpi files should install upon draging from file manager to TBird Add-ons Manager, or using the gear to elect "Install Add-on From File" option.

## Actual behavior
.xpi files do not install, either being selected individually, or all 3 at the same time. Receiving a popup stating that the add-ons are not compatible with v67.

## Steps to reproduce
-download .xpi files from provided source
-drag and drop into Thunderbird 67.0b3 (64-bit) Add-ons Manager tab

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Due to limited resources I only support the latest ESR, so TB60 and TB68 after it has landed (but probably not the beta of TB68)

**Comment by 05nelsonm** [comment]
Copy. Love the add-on btw. Was using it in TB60.
