### ISSUE TITLE
Unable to sync with Gmail addresses

### ISSUE THREAD

**Issue by stephenaustin** [jobisoft/TbSync#257]
Unable to sync Gmail addresses. Get this error message
<img width="454" alt="tbsync" src="https://user-images.githubusercontent.com/33739991/58064294-1816fc00-7bb4-11e9-8cc3-ac077a364f0d.png">

Thanks for any suggestions

## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Google switched off their active sync support a few years ago. And for carddav/caldav they require OAUTH2 which I have not yet implemented. TbSync does not support google at the moment and it will take me until after the release of Thunderbord 68 before I can start working on that.

Subscribe to this issue, for updates:
https://github.com/jobisoft/DAV-4-TbSync/issues/56

**Comment by stephenaustin** [comment]
Thank you for taking the trouble to reply, and for your information.

**Comment by jobisoft** [comment]
**Tada:** The latest beta has google support! You now can now setup the sync of your google contacts and your google calendars from one single UI!

You can get the beta here: https://tbsync.jobisoft.de

Feedback is appreciated!

![grafik](https://user-images.githubusercontent.com/5830621/69188445-d80de300-0b1c-11ea-8723-811d0dd5b0b3.png)
