### ISSUE TITLE
Autosync when event detected

### ISSUE THREAD

**Issue by Aohzan** [jobisoft/TbSync#258]
## Your environment

TbSync version: 1.7
Thunderbird version: 60.7.0

Hello,
Is it possible to add the possibility to sync account as soon as a item is added, modified or deleted ?
It's really frustrating when I make a modification and shutdown my computer directly after, that I don't have this modification on my others devices
Thanks

**Comment by jobisoft** [comment]
I am currently busy working on getting ready for TB68. This feature is on the todo list, but do not expect this before TB68.

**Comment by raulpardo** [comment]
Would it be possible to have some temporary solution such as a shortcut (e.g., Crlt+Alt+s)?

**Comment by jobisoft** [comment]
I will add sync-on-local-changes soon.

**Comment by raphaelquast** [comment]
is there already an outlook when such an option could be available?
