### ISSUE TITLE
Q: Will TbSync continue to work when TB 68 is released in July?

### ISSUE THREAD

**Issue by David-S-Morgan** [jobisoft/TbSync#259]
Just a question -- is it expected that TbSync will continue to work with the upcoming major releases of TB (68 / 69 LTS) in July? I'd read that at least some extensions will cease to function.  Just want to plan accordingly.  Thanks.

**Comment by jobisoft** [comment]
Yes, this is what I am doing at the moment. I will be late for TN68 Beta, but on time for TB68 ESR.

**Comment by David-S-Morgan** [comment]
Great -- thanks for the response.  Good luck!
