### ISSUE TITLE
Ignorierter Fehler (404)

### ISSUE THREAD

**Issue by Moto1987** [jobisoft/TbSync#263]
Hallo,

ich habe (mehr oder weniger als Laie) Nextcloud auf einem eigenem Server eingerichtet.
Alles Funktioniert auch bestens nur wenn ich Meine Termine und Kontakte mit TbSync synchronisieren möchte dann gibt es folgenden Fehler:

Ignorierter Fehler (404)
Account: Se****** Ri***
URL:
https://se******ri***clo**.ddns.net/remote.php/dav/addressbooks/groups/Se******%2bRi***/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: groups in 'addressbooks'</s:message>
</d:error>

Die Synchronisierung an sich funktioniert nur gibt es jedesmal so einen Fehler.

Was muss ich beim Server einstellen, um die Fehlermeldung weg zu bekommen.

Grüße
Moto1987

**Comment by jobisoft** [comment]
Der Fehler ist nicht schlimm, und sollte nur im Fehlerlog auftauchen, oder?

Das heißt einfach nur, dass Nextcloud ein bestimmtes Feature nicht unterstützt (irgendwas mit Gruppen und Freigaben) und er deswegen auf meine Anfrage ein 404 zurückwirft. Du kannst daran glaube ich nix ändern. Vielmehr muss ich lernen, wie ich deinen Server fragen kann, ob er Feature XY unterstützt, anstatt ihn in ein 404 zu zwingen. 

Kann ich das hier schließen?

**Comment by Moto1987** [comment]
Hallo,

wenn ich da nichts machen kann und ich den Fehler so weit ignorieren kann, kann das hier geschlossen werden.

Danke und Grüße
Moto1987

**Comment by Quix0r** [comment]
Den Fehler hatte ich mit TBSync 3.0.2 und Thunderbird 91.13.0 (64-bit) auch bekommen und so gefixt, dass ich einfach Thunderbird neugestartet habe. Andersfalls liessen sich die Kalender (!) nicht aktivieren (wurden immer wieder deaktiviert).

Also: Neustart (dieses Mal nur die Anwendung) kann "magisches" bewirken ... ;-)
