### ISSUE TITLE
Same account on 2 computers issue

### ISSUE THREAD

**Issue by dmstech12** [jobisoft/TbSync#265]
## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
... My calender on booth computers should sync normally without making a "forced folder resync"

## Actual behavior
... I have just got a home computer where i installed thunderbird and tbsync for the calender.
when i sync on my work computer. It needs to resync on my home computer. So that it opens a popup with a lot of notifications. 
That is quite annoying.
Same problem the other way. When i have synced a change on home computer the work computer make the same problem.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Solution:

If you have transfered a Thunderbird profile from one computer to another one, both have the same client ID and thus will mess up each others sync. Simply delete the EAS account on one of the computers and set ip up anew, which will generate a new random client ID.
