### ISSUE TITLE
does not work with TB69 (beta)

### ISSUE THREAD

**Issue by n8v8R** [jobisoft/TbSync#269]
## Your environment

TbSync version: 1.7
Thunderbird version: 69.0b1 (64-bit)
OS version: W10 Pro x_64 v1903 b18362.267
____

Perhaps a bit early for heads up and rather informative. The accounts stored in TbSync been wiped and new accounts cannot be created

**Comment by jobisoft** [comment]
TbSync and its providers are compatible with next ESR : TB 68.

Do not ask me why they pushed Beta to 69 before release of ESR. TbSync is NOT compatible with 69.

Update your addons or install them fresh via the AddOn Manager: TB68 needs TbSync 2.x and Providers 1.x.

However, wipeout is true. Migration was not possible, to much internal changes. Need to add a notification about that. You need to setup TbSync again :-(

Jörg posted on tb-planning a link to unofficial ESR release candidate. Maybe you can find that and try that. Feedback is more than welcome.

**Comment by n8v8R** [comment]
Thanks for the response. Jumped to 69 because 68 not being released (or whatever reason).
Not sure whether I can downgrade to 68 since it may break storage.

I know it is early to take 69 into consideration but likely the changes that will come with the next ESR after 68 will cause the same issue. At least thought to let you know.

**Comment by jobisoft** [comment]
I will adapt to 69 after 68 is out and I have feedback, that it works. Keep this issue open for further notifications.

**Comment by LeoniePhiline** [comment]
Heya :)
I came across the same issue - because https://www.thunderbird.net/de/channel/ only offers TB 69b1 and I just could not find the TB 68rc.

1) I know this is not a support forum... but where can I find a tgz of TB 68rc? I would have liked to help test the new TbSync release. ✨

2) You wrote:
> However, wipeout is true. Migration was not possible, to much internal changes. Need to add a notification about that. You need to setup TbSync again :-(

Do you know if that also wipes the existing notifications in the calendar notifications/reminders popup? I usually use that to keep track of stuff I have not yet gotten around doing (slowly switching to the use of actual Tasks rather than Events now, which is more reliable).
If the un-dismissed Events in the Reminder Popup would be gone after installing TB 68, then I'd better find a solution before they're all gone. :D

**Comment by jobisoft** [comment]
TB68 RC2: https://ftp.mozilla.org/pub/thunderbird/candidates/68.0-candidates/build2/

For the question regarding reminder popus: I honestly do not know. You can backup your profile and fire up TB68 and see what happens. If not happy with your findings, exit TB68, restore you profile and use TB60 again.

After you started TB68, please install the TbSync modules from my [beta release channel](https://tbsync.jobisoft.de), as the versions hosted on addons.thunderbird.net have bug. I actually fixed the bug and uploaded new versions, but they are still waiting to be reviewed.

As a side note: The latest version now does migrate the account settings, but (as you know) I recommend to disable all your accounts before upgrading to TB68.

**Comment by LeoniePhiline** [comment]
Thank you!

**Comment by jobisoft** [comment]
The beta-release-channel (BRC) is now compatible with TB69. Install the files from the TB68 folder:
https://tbsync.jobisoft.de

It will take another week or so, before that hits ATN. Feedback is always welcome.

For those who are already on the BRC, just update your addons. You can still post, even if this is closed now. Reopen, on error.

**Comment by n8v8R** [comment]
Thank you! Works for me with TB 69 beta 3 (after having also installed the EAS beta).

What happens when it hits ATN though - do the extensions remain on the beta channel or are you updating the beta update refer to ATN?

**Comment by jobisoft** [comment]
If you install files from the BRC, you will always stay on the BRC. Same with the beta channel from Thunderbird itself. I do not do crazy stuff with the BRC and I usually test things before I push them. But with the BRC I can fix bugs much faster than with the version on ATN. And I can get feedback, if the fix works before shipping it to ATN.
