### ISSUE TITLE
syncronization delete when TB closes

### ISSUE THREAD

**Issue by LaYesera** [jobisoft/TbSync#271]
After an update from W7 to W10 I have problems with MT. My calendar doesn't work properly anymore. I have already removed MT completely and reinstalled it but without result. My mailprovider (one.com)can't find the error either.
After running TbSync the calendars in TB and on the server synchronize well and I can adjust the calendars in TB and in the webmail of my host and synchronize them perfectly. 
When I close TB and start it again a little later, the calendars in TB are no longer synchronized and are even switched off. If I make the calendar active again with a right mouse click, the calendar is active for 1 second and then switches to inactive.
If I run TbSync and sync my calendar again, the calendar will be visible and active again and I can fully work with it again until................................................ I close TB again and start it up again later. So first I have to run TbSync again. 
What do I have to change or set up to solve this problem?
Greetings  Hans.

Translated with www.DeepL.com/Translator

**Comment by jobisoft** [comment]
I need some information:

- you used „MT“ multiple times in your report, what does that stand for?
- what version of Thunderbird are you using?
- what Provider for TbSync are you using, „Exchange Active Sync“ or „CalDAV/CardDAV“
- did you setup more than 1 one.com account in TbSync?

**Comment by jobisoft** [comment]
Hans? I am from Germany, we could switch language, if that would be better for you.
