### ISSUE TITLE
iCloud sync Display Names created mixed (John Doe, some Doe John)

### ISSUE THREAD

**Issue by SwissSneaker** [jobisoft/TbSync#272]
## Your environment

TbSync version: Beta 1.7.6
Thunderbird version: 60.8.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Goal is to synchronize iCloud addresses to TB, storing prename and given name into equal field and creates "display name" ether "prename & given name" or vice verca "given name & prename"

## Actual behavior
Sync is working fine. Creation of display name is mixed. Some contacts are "prename & given name" (John Doe) some others "given name & prename" (Doe John). As well with extendet options I have not found a solution / option to fix this.

## Steps to reproduce
De-sync of iCloud, close TB, reopen TB, sync again -> address book gets created and filled again -> still same behavior.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
-> No debug file generated -> seams no "bug notice".

**Comment by jobisoft** [comment]
This is a 1-on-1 Sync between the „fn“ vCard field and the DisplayName field of Thunderbird. I do not think I manipulate the DisplayName.

It could be that iCloud.com (the web view of your contacts) does not actually display the fn field but just firstname + lastname, so you cannot see the actual fn value.

Can you download the vCard of a few contacts from iCloud.com which you think are wrong and compare their fn value with the DisplayName in Thunderbird?

**Comment by SwissSneaker** [comment]
You are 100% correct! Viewing the vCard with in plaintext shows me the fn field prefilled randomly by iCloud. I see there no option, how to change this in iCloud, as the fn is not displayed somwhere.

My mistake - I thought your tool are filling it (as I was not aware of this existing, hidden field).

**Comment by jobisoft** [comment]
Sorry, I do not know any method besides doing it by hand :-(
