### ISSUE TITLE
How to deactivate/disable TbSync accounts?

### ISSUE THREAD

**Issue by LFenske** [jobisoft/TbSync#273]
## Your environment

TbSync version: 1.7.0.1
Thunderbird version: 60.8.0 (64-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Account is deactivated.

## Actual behavior
No way to deactivate?

There is a yellow message at the bottom of my Thunderbird screen that refers to DEACTIVATING my account before upgrading to Thunderbird 68.  I have been searching for an hour and a half and cannot find any reference to account deactivation.  How do I deactivate an account?

I know how to disable an account.  Could the yellow message really have meant to say disable instead of deactivate?

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
You are correct. I have to change the wording. I meant disable.

**Comment by LeoniePhiline** [comment]
@jobisoft 
Is this about disabling the account in the TbSync Account Manager window, or something under Edit > Account Settings?

**Comment by jobisoft** [comment]
It is about disabling the account in the TbSync Account Manager, by unchecking the box shown here:

![image](https://user-images.githubusercontent.com/5830621/63053657-9a2c6d80-bee2-11e9-9019-7035830a873b.png)

All your accounts should than have the "disabled" icon:

![image](https://user-images.githubusercontent.com/5830621/63053751-cb0ca280-bee2-11e9-9c45-d4a93fe78ead.png)

Sorry if the notification window caused confusion.

**Comment by LeoniePhiline** [comment]
Thank you for clearing this up! 🙏

If the data loss issue is serious (is it?) then maybe it's better to rephrase the notification? (And make it show again even if dismissed already.)

**Comment by jobisoft** [comment]
It is not serious as in "I delete all your data from your server", but it could happen, that after the update your addressbooks and calendars are still there in Thunderbird, but no longer connected to your server and if you make local changes, they will never make it to your server. So these changes will be lost.

That is why I ask to disable all accounts and start fresh to ensure proper connection between Thunderbird and your servers.

**Comment by jobisoft** [comment]
I will probably add a help button which opens this issue :-)

**Comment by LeoniePhiline** [comment]
Thanks, that makes it clearer. 

Good idea! :)

Maybe first an UPGRADING.md FAQ page or something like that. Otherwise you might (or might not?) get swamped with discussion in your bug tracker. 😉

**Comment by jobisoft** [comment]
What about this rephrased notification:

> The add-on "TbSync" has been almost completely rewritten for Thunderbird 68 (the next major release). To avoid data loss during the upgrade, the author recommends to synchronize and to disable all your TbSync accounts before (!) upgrading to Thunderbird 68. After the upgrade has finished, your TbSync accounts can be enabled again.

Besides the "show no more" button, I will also add a button going here:
https://github.com/jobisoft/TbSync/blob/master/UPDATE68.md#update-instructions-for-thunderbird-68

Ideas for the label of that button: 
* More information
* What does that mean?
* ?

**Comment by jobisoft** [comment]
Closing, as the new Update Instruction Page is online.
