### ISSUE TITLE
Javascript Error EAS beta xpi, MS Office365, TB 68

### ISSUE THREAD

**Issue by LeoniePhiline** [jobisoft/TbSync#274]
## Your environment

TbSync version: 2.2.4 (beta channel)
EAS version: 1.1.3 (beta channel)
Thunderbird version: TB68

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync EAS syncs perfectly with Office 365

## Actual behavior
Sync error. Event protocol shows:
```
eas.finish is not a function

sendLocalChanges@chrome://eas4tbsync/content/includes/sync.js:664:23
```

## Steps to reproduce
Hit "sync now"

## To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Will do.

**Comment by LeoniePhiline** [comment]
Log sent by email.

**Comment by jobisoft** [comment]
i think it is fixed in the beta release channel version of the eas provider now. can you update your addons and try again?

**Comment by jobisoft** [comment]
Leonie, can I close this?

**Comment by LeoniePhiline** [comment]
Hey,
I haven't checked yet will let you know.
If you're confident you fixed the bug, then just close - I can still reopen if needed. :)
Thanks for the quick fix in any case!
