### ISSUE TITLE
exception during calendar sync

### ISSUE THREAD

**Issue by n8v8R** [jobisoft/TbSync#276]
* W10 Pro x_64 1903 b18362.295
* TB 69.0b3 (64-bit)
* EAS / TbSync beta channel
____
Could be a bug in TB's Calendar module. Observing during sync

![Annotation 2019-08-19 113906](https://user-images.githubusercontent.com/13611490/63255408-ff32eb00-c275-11e9-9872-6c8b1448da25.png)

**Comment by jobisoft** [comment]
Always reproducable? Does it happen with TB68 RC2?

**Comment by n8v8R** [comment]
Yes, always reproduces on every sync action.

I am skipping 68 entirely and thus cannot test I am afraid.

**Comment by n8v8R** [comment]
seems to be triggered by

```
notify(func, args=[]) {
        let currentObservers = [...this.values()];
        for (let observer of currentObservers) {
            try {
                observer[func](...args);
            } catch (exc) {
                let stack = exc.stack || (exc.location ? exc.location.formattedStack : null);
                Cu.reportError(exc + "\nSTACK: " + stack);
```

**Comment by jobisoft** [comment]
> I am skipping 68 entirely and thus cannot test I am afraid.

Oh, but that is the next ESR, which will be used by millions of users. I will have a look.

> seems to be triggered by

Where is that from?

**Comment by n8v8R** [comment]
> Where is that from?

calDataUtils.jsm:43 -> function starts at line 36
___
[off topic]

The TB ESR release cycle is a bit slow for my taste and never understood why TB releases are only ESR.
I know, I have to live with the downside of beta, now particularly the issues for extensions in the 69+ branch...
And I am not sure about the millions of users. Whilst I do like TB the development, in comparison to other email clients, is less promising, despite some public announcements made a few months back. And even that activity has come to a rest:

* last post on https://twitter.com/mozthunderbird dating 06 AUG 201**8**
* https://twitter.com/mozthunderbird is not very active either and nothing new of what to expect of TB's future
* https://blog.mozilla.org/thunderbird seems to be promoting more of wishful thinking rather than actually delivering
* long time bugs like this https://bugzilla.mozilla.org/show_bug.cgi?id=1445778 getting stale and just printing in release notes that it does not work

**Comment by jobisoft** [comment]
The daily update pings of lightning is at 7 Million.

I spend almost every minute of my free time to fix bugs or to impr. TB, For example https://bugzilla.mozilla.org/show_bug.cgi?id=1544596. A few things mentioned on https://blog.mozilla.org/thunderbird/ I am actually involved with but it still needs time. We did anounce it so you can see what is scheduled, but it is not done yet.

It is difficult to say things we planed and what is coming up in the future (as expected by you) without being called "not to deliver" if it needs longer than anticipated. One of the reasons it takes longer is missing funding.

Problem about some bugs: None of use has deep knoweldge, the Twitter bug being one of them. Twitter switched off an API so we currently cannot read twitter in the way we need it (no 3rd party app with a huge userbase can, there now is a poll limit, Twitter wants users to use the twitter app so they can show ads). We have no idea how to fix it, but of course are open to any suggestion.

Keep smiling, we are doing our best.
