### ISSUE TITLE
Synology calDAV/cardDAV setup fails

### ISSUE THREAD

**Issue by truthsword** [jobisoft/TbSync#281]
## Your environment

TbSync version: 1.7.0.2
Thunderbird version: 60.9.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior 
...

## Actual behavior
![](https://i.imgur.com/RqrWdu9.png)
...

## Steps to reproduce

I'm using the following calDAV/cardDAV links
diskstationDDNS:port/caldav/USERNAME
diskstationDDNS:port/addressbooks/users/USERNAME

I have an LE cert for this DDNS. It appears in Thunderbird server cets
![i](https://i.imgur.com/ezirEvD.png)
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by truthsword** [comment]
The cert expires on October 22. Verified on browser.

**Comment by jobisoft** [comment]
@truthsword : You did not get an EXPIRED error, you got a REVOKED error. The issuer of your cert REVOKED your cert which makes it useless and invalid. Independent of when it would usually expire. That is the whole point behind the revocation process.

Please contact your issuer. This is not a problem with TbSync.

**Comment by jobisoft** [comment]
Maybe this is what is causing your issue:
https://mariushosting.com/dsm-6-2-2-24922-update-3-sec_error_revoked_certificate/

**Comment by truthsword** [comment]
Interesting post. Thank you. Coincidentally, Synology posted this same issue today...
https://community.synology.com/enu/forum/1/post/128540

I'll wait for the OS update, as I will soon need to update the cert.

I'll post back when this is "resolved" by Synology.

**Comment by truthsword** [comment]
I didn't wait for Synology's patch. I used the link you provided and generated a new cert. The calendar sync is fantastic.

I'm having a small problem with the CardDAV that I believe is related to user photos since the sync terminated in the middle of what appeared to be a jpg encoded section. 

I've just run across the post on using Synology's reverse proxy, so I will give that a go.

**Comment by jobisoft** [comment]
Can we close this?
