### ISSUE TITLE
Translating syncstate.preparing|syncstate.done

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/TbSync#283]
What is the point to have the keys for translation syncstate.done and syncstate.preparing, if the translated strings are identical?

**Comment by jobisoft** [comment]
Basically these two exists for historical reasons. Preparing is set when we loop throu the resources during sync and just switched to a new one (first, second and so on). 

Done is set when a resource is done. However "done" has also a programatically meaning, so I cannot just remove that syncstate. 

Now in most cases done is followed directly by preparing or by accountdone. I found, that "done" and "preparing" do not need different wordings, as one of them is probably never seen by the user. 

But I do need the preparing state in the view and cannot remove the done state...

**Comment by dilyanpalauzov** [comment]
It is cumbersome (suboptimal and raising doubts) to have to enter twice exactly the same string during localization.

What is the difference between **element** and **resource** in:
```
prompt.Unsubscribe=Sind Sie sicher, dass Sie dieses Element nicht länger abonnieren möchten? Alle lokalen Veränderungen, die noch nicht synchronisiert wurden, gehen dabei verloren!
syncstate.preparing=Bereite das nächste Element für die Synchronisation vor
status.notargets=Synchronisation abgebrochen da die Elemente zum Synchronisieren nicht erstellt werden konnten.
status.foldererror=Bei mindestens einer Resource trat ein Synchronisationsfehler auf. Bitte prüfen sie das Ereignisprotokoll für weitere Details.
status.no-folders-found-on-server=Auf dem Server wurden keine Resourcen gefunden.
```

**Comment by dilyanpalauzov** [comment]
Or rather, what means element in WebDAV terms and what means resource in WebDAV terms?

**Comment by jobisoft** [comment]
I switched from "elements" to "resources" when I updated to UI with the multiple tabs, I think beginning this year? I do not remember. For stuff from the server I want to use resources. For stuff in Thunderbird I actually want to use "target" or something like that, to indicate it being a sync target. But sometimes I still call these elements.

Someone has to go thru that with an axe.

**Comment by dilyanpalauzov** [comment]
```xml
<!ENTITY manager.catman.text "TbSync also syncs contact categories, which
  are a powerful replacement for the non-synchronizable contact lists. To be able
  to use them in the Thunderbird address book you can install the Category Manager
  add-on. It allows to manage overlapping category based contact groups and provides 
  a bunch of other category-related features. It can be found in the official Mozilla
  add-on repository:">
```
Here the terms “contact list” and “contact categories” are used interchangeably.

Speaking vCard, is a “contact list”, 
* a separate vCard with MEMBER, as defined by [vCard 4.0](https://tools.ietf.org/html/rfc6350#section-6.6.5), 
* a CATEGORY in terms of [vCard 3.0](https://tools.ietf.org/html/rfc2426#section-3.6.1), or
* something different?

What is an “overlapping category based contact groups” in vCard terms?

**Comment by dilyanpalauzov** [comment]
```xml
<!ENTITY manager.tabs.status.never "Eine Einstellung von 0 deaktiviert
  periodische Synchronisation. Push Synchronisation wird noch nicht unterstützt.">
```
Does this mean, that when there are local changes, the user agent (TB) does not push them to the server, before manual or periodical push is triggered, or it means, that the server does not push changes to the client, when chages are made on the server, or it means both?

**Comment by dilyanpalauzov** [comment]
If it means both, I think “Changing local or remote data does not trigger automatic synchronization.” is easier to understand.

**Comment by jobisoft** [comment]
1. "contact list" refers to the thunderbird contact lists. contact categories can be used as a replacement. they are overlapping, because a contact can be in different categories and that can be managed from the contact. Lists can also be overlapping, but you havbe to edit each list to change memberships and you have to know in which list a contact exists. It is just a feature description.

2. I indeed map the MEMBERSOMETHING feature introduced by apple in vCard 3.0 to lists anc CATEGORY to categories. I do not support vCard4

3. sync: It currently means both, I do not push to the server and the server cannot push to me (which is not possible at all with dav, but with eas)

4. rewording sounds good

**Comment by dilyanpalauzov** [comment]
So a contact is overlapping, if it belongs to at least two lists?

What is an overlapping list?

That said, “It allows to manage overlapping category based contact groups and…” should be “It allows to manage contacts belonging to several contact lists and…”

**Comment by jobisoft** [comment]
The contact groups can overlap. consider your "sports" friends and your "work" friends. a few could be in both. 

But as I said in the other issue: Everything is on fire at the moment (not your dns and no credentials stuff, that just has to wait), but the network stack of TB has changed dramatically without us noticing. lots of stuff is broken. I have no time for rewording stuff at the moment

**Comment by dilyanpalauzov** [comment]
en/tbSync.strings contains
```
info.sync=Synchronizing
status.syncing=Synchronizing
```
in German it is
```
info.sync=Synchronisation
status.syncing=Synchronisierung
```
So in Englsh info.sync and status.syncing are the same, while in German status.syncing would correspond to the English Synchonization, as in 
`status.disabled=Account is not enabled, synchronization is disabled.` ⇔ `Konto ist deaktiviert, Synchronisation ist ausgeschaltet.`

**Comment by jobisoft** [comment]
I would actually need to look that up in the code, where it is used. Maybe that can be merged.

**Comment by jobisoft** [comment]
info.sync is used in the status bar to indicate that he is doing something (also has idle and error)
status.syncing is also indicating, that something is going on. So info.sync should be the same as status.syncing. The german locale is wrong.

You next question will be, if it then can get removed. *thinking*

**Comment by jobisoft** [comment]
Removed.
