### ISSUE TITLE
Lightning autocomplete broke when updating from TB 60->68

### ISSUE THREAD

**Issue by o-schwartz** [jobisoft/TbSync#288]
## Your environment

TbSync version: 2.4.2
Thunderbird version: 68.1.0

[x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When using TB 60.8.0, syncing a personal calendar and address book via the caldav plugin works without errors and address-autocomplete works when writing emails and when inviting people to calendar events. Thank you for writing such a wonderful plugin.

## Actual behavior
When using TB 68.1.0, syncing works as expected and autocomplete of addresses when writing emails is still working, but when inviting people to events in lightning there is no autocompletion. Getting the free/busy info still works when typing a correct email address by hand.
This can be fixed by manually copying all addresses from the synced caldav-addressbook to the personal address book, but of course then they aren't in sync any more.

## Steps to reproduce
Install Thunderbird 68.1.0 + tbsync and caldav pluging (doesn't matter if release or beta channel).
Sync an address book and personal calendar. (I can give you an account on our server if you need to test it)
Open the calendar, right-click somewhere, press "new Event". Press "Invite Attendees", type the first few letters of any contact stored in the address book. There is no autocomplete/retrieving of the full Name.

Thank you for your time, I will send the debug.log.

Best regards!

**Comment by jobisoft** [comment]
That is my fault, yes. Has been reported already here:
https://github.com/jobisoft/DAV-4-TbSync/issues/111

The linked bugzilla gives explenation. Will be fixed soon.
