### ISSUE TITLE
TbSync is blocked by global policy

### ISSUE THREAD

**Issue by UnitedMarsupials** [jobisoft/TbSync#29]
I may have been overly optimistic, when I reported TbSync working in #28. It did report both `FOO.Calendar` and `FOO.Contacts` to have successfully synchronized, but both are _empty_ when I attempt to view them in Lightning and Address Book respectively.

So I went on to enable debug-log and attempted to disconnect/reconnect. Upon attempting to reconnect, I now get the below error:

![image](https://user-images.githubusercontent.com/1486340/34423345-4a9b0d94-ebe9-11e7-8b08-4daf2c94e900.png)

Disabling the debugging option does not help. The server was "autodiscovered" to use version 14 of the protocol and I can not change that -- not through the GUI, at least. I even tried to restart Thunderbird entirely -- nope, the error is still there and the data-sets aren't even pretending to synchronize as they did before.

**Comment by UnitedMarsupials** [comment]
Ok, I deleted the account completely and re-created it from scratch. I then unlocked the autodiscovered fields and forced ActiveSync version to 2.5. The synced data still empty -- the FOO.Calendar, for example, does not list any of the meeting, that Outlook shows...

Please, advise. Thank you!

(P.S. Is there a way to look, which server(s) the Outlook client is configured to talk to? Maybe, the autodiscover settings are subtly broken here...)

**Comment by jobisoft** [comment]
First of all, delete the account again, enable debug log, restart (which clears the log), re-add and connect your account (which will trigger some sort of error), open the debug log and send it to me.

Second, after autodicover finished, the found server (which will be used) is in field "server address", right next to the ActiveSync version selector.

Third, it should work with the auto settings, because that is what your server tells TbSync to use.

Fourth, you could try with the latest beta version, which I will upload shortly.

**Comment by jobisoft** [comment]
Latest beta: [TbSync v0.6.8.3 (2017.12.28)](https://github.com/jobisoft/TbSync/releases/download/v0.6.8.2/TbSync-0.6.8.3-2017.12.28.xpi)

**Comment by UnitedMarsupials** [comment]
Thank you for your quick response. Meanwhile I got the following automatic e-mail which seems to indicate, Thunderbird got mistaken for a mobile phone -- and rejected because of that. Maybe, TbSync can do something to avoid such misdetection?

```
Your phone won't be able to synchronize with the server via Exchange ActiveSync because of an access policy defined on the server.
Information about your mobile phone:

Device model: | Thunderbird
Device type: | Thunderbird
Device ID: | mztbb26xxxxx9970abf88036
Device OS: |  
Device user agent: | Thunderbird ActiveSync   Lightning/5.4.5.2
Device IMEI: |  
Exchange ActiveSync   version: | 14.0
Device access state: | Blocked
Device access state   reason: | Global
```

**Comment by jobisoft** [comment]
Oh, I think I am not able to do something about that. I HAVE to identify as what I am, this is how provision works. I really do not want to mess around with fake profiles.

You could ask your IT to add a policy for "Thunderbird". All the fields needed to identify TbSync are given in your last comment. If your company wants me to explicitly add "TbSync" in any of the above fields, I will do so.

This is the first time ever, that I run into a company that is actually using policies. If your company allows TbSync, it would be a dream to develop/test all the other policy related features (like remote wipe).

**Comment by UnitedMarsupials** [comment]
TbSync is not mentioned in the quoted message, is it? "Thunderbird" and "ActiveSync" are. I could ask for changes, but, given the size of this company, someone is much more likely to say "Thunderbird is not supported", then to make the trivial change required to let it through...

Maybe, I can convince Thunderbird to use a different User-Agent string though.

**Comment by UnitedMarsupials** [comment]
That said, you, probably, still want to deal with responses missing "mandatory" fields -- I'm fairly certain, the server's reply contained some sort of error message, which TbSync should've displayed...

**Comment by jobisoft** [comment]
That is indeed correct, please re-try with the latest beta, because I did improve the error handling. A debug log or general feedback on that retry would be interesting.

**Comment by jobisoft** [comment]
Regarding the other question about TbSync identification: You are correct, I did not explicitly add TbSync to the client ID, but just "Thunderbird". Of course we can try to change the ID, but to what? 

I could think about making the ID user define-able in the configs...

**Comment by jobisoft** [comment]
I [updated](https://github.com/jobisoft/TbSync/commit/33303979427651df4ae48aa3a227c09b27e66dcf) the latest beta (replaced the file, keeping the same name). It now allows to set

extensions.tbsync.clientID.type
extensions.tbsync.clientID.useragent

in the Thunderbird settings. You also have to clear 

calendar.useragent.extra

because that is added to the userAgent defined by TbSync. If you enable debug log, you can see, what userAgent and deviceID is beeing used, so you can verify your settings.

This is all I can do. I cannot help to find out what values you actually have to set, to gain access. And it does not feel right...

**Comment by JamesSHun** [comment]
Dear Jobisoft!

We have a same error message.
We try to use your app with Zentyal mail server (and SOGo).
(Linux and Windows thunderbird same error)
Any idea what can we do
We tried you last updated link but nothing help for us.

Imre Kovacs

**Comment by jobisoft** [comment]
First, remove your account completely from the TbSync manager, update to [beta8](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta8.xpi) if not yet done so and then re-add your account.

If the error stills pops up, you have to contact your server admin and ask him to add a policy for "Thunderbird ActiveSync". He may have to look at his logs to get more information.

**Comment by JamesSHun** [comment]
thank you I will try it soon :)
