### ISSUE TITLE
Question on Merging Contacts/Calendars

### ISSUE THREAD

**Issue by doodlemania2** [jobisoft/TbSync#290]
I have set up Sync to Nextcloud and Hotmail in Thunderbird

Currently, this creates a Nextcloud Calendar and a Hotmail calendar. This also does similar for Contacts.

What I'd like is to leverage TbSync to continuously merge these calendars continuously and contact groups together so I can have my data in all the places be the same.

Possible?

**Comment by jobisoft** [comment]
No. Inter-Sync is not implemented and is not on my list. Merge them once by yourself and get rid of one of the two accounts alltogether.
