### ISSUE TITLE
Invite Attendees dialog does not autocomplete addresses from CardDAV addressbooks

### ISSUE THREAD

**Issue by johndoe7000** [jobisoft/TbSync#291]
## Your environment

TbSync version: 2.4
DAV-4-TbSync version: 1.3
Thunderbird version: 68.x

[ x] Yes, I have installed the latest available (stable) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Starting to type a valid email address from cardDAV addressbook autocompletes matching addresses.

## Actual behavior
Only email addresses from "local" addressbooks are being autocompleted.

## Steps to reproduce
1. Press "Create a new event" via Lightning.
2. Press "Invite Attendees".
3. Start typing a valid address from CardDAV addressbook > no autocomplete.

I reported this issue already to mozilla, because I thought it was a problem with Lightning and not your provider. Here is the link to their bugzilla bugtracker...
https://bugzilla.mozilla.org/show_bug.cgi?id=1582040

**Comment by jobisoft** [comment]
I added a patch for this to my beta release channel (TB68). Works for me. Can you test and verify?
https://tbsync.jobisoft.de

**Comment by johndoe7000** [comment]
Yes, it's fixed in your beta. Thank you.
