### ISSUE TITLE
xml parsing error: manager/addonoptions.xul

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/TbSync#292]
Updating TbSync and DAV-4-TbSync to the latest version from the betta channel, restarting Thunderbird, going to Options - Addons - TbSync opens a window with xml parse error;

Error in processing towards an external entity.

Location:  chrome://tbsync/content/manager/addonoptions.xul
Line 3 Column 60
```xml
<!DOCTYPE window SYSTEM "chrome://tbsync/locale/tbSync.dtd">
-----------------------------------------------------------^
```

**Comment by jobisoft** [comment]
damn, which locale?

**Comment by dilyanpalauzov** [comment]
Maybe Bulgarian.  I cannot switch to another locale using `general.useragent.locale`: it gets ignored.

**Comment by jobisoft** [comment]
You forgot a closing "
I updated the beta, however that now also includes bg in DAV, so it could break again.

Status?

**Comment by dilyanpalauzov** [comment]
Now it works.
