### ISSUE TITLE
TBSync incompatible with Thunderbird 68.1.0

### ISSUE THREAD

**Issue by trourance** [jobisoft/TbSync#294]
## Your environment

TbSync version: 1.7.0.2
Thunderbird version: 68.1.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Steps to reproduce
I've installed the latest updates for my arch linux distro and the TBSync extension is disabled in Thunderbird.

**Comment by jobisoft** [comment]
Not true.

https://addons.thunderbird.net/addon/tbsync/versions/

Did you get TbSync fro your distro or directly from ATN? If your dirstro forgot to update, file a bug there.

**Comment by trourance** [comment]
The update in TB was not working, so the module was blocked at 1.7.0.2. As soon as I've installed the 2.4 version, everything has worked fine.
Sorry for the noise.
