### ISSUE TITLE
Hotmail.com

### ISSUE THREAD

**Issue by Kassidy68** [jobisoft/TbSync#3]
Hi John,
I recently discovered your great add on and have installed it to get my Hotmail agenda and adress brook synchronised. But unfortunately I cant get it work either using the Outlook.com settings or and customized settings. I was therefore wondering is there would be specific settings for hotmail.com type of adresses as my adress is indeed under the xxxx@hotmail.com and not xxx@outlook.com?

In advance many thanks for any help that you could provide and Congrats again for working on this and helping us 😀

**Comment by jobisoft** [comment]
Something I have read on other posts: Do you have an "initial" hotmail 
address, and the one you are using is just an alias? Could you try to 
autheticate with that initial hotmail address?

Good luck
John

**Comment by Kassidy68** [comment]
Hi John,

Thanks for your email.
I have my hotmail.com email address for ages (10 years or so) so I dont think it is an alias.
this is the one that I use  to log in on the outlook.com webamil or an other clients would it be on a PC, mac, iPhone etc.
To you think it is a dead end here for hotmail.com adresses?

Many thanks¨!

**Comment by jobisoft** [comment]
The only other help I can provide:

try server "m.hotmail.com" as listed here:

https://www.howto-outlook.com/howto/accountsettings.htm#outlookcom-eas

**Comment by Kassidy68** [comment]
Hi John,

Thanks for your help. Unfortunately it does not work.
I think I understand why. Likely the explanation lies here (this is from the "howto" link provided):

**Outlook.com (Hotmail)**
Outlook.com: Microsoft is currently migrating Outlook.com accounts to the new Office 365 powered Outlook Mail platform. This allows you to configure your Outlook.com account as an actual Exchange account in Outlook.

I guess most of the Hotmail.com accounts have effectively been migrated on the office 365 platform, which means that these accounts are not anymore working under the EAS protocols but truly behave like Exchange accounts.
In Outlook, when I try to configure it, indeed it is configured like a Exchange account. The server name is in the type of:
https://outlook.office365.com/mapi/emsmdb/?MailboxId=00070000-9bd7-6759-0000-000000000000@hotmail.com
Not sure though if this could actually be used outside Outlook. There is not solutions for whom want to have an Exchange email account dealt by another email client than Outlook. Thunderbird can't outside configuring it as a regular IMAP account.
Many thanks for all and thanks again for helping us out there!

Michel

**Comment by jobisoft** [comment]
If that is the case and your account can be accessed using EWS, try

https://github.com/Ericsson/exchangecalendar/wiki/Exchange-EWS-Provider

yours
John

Am 22.02.2017 um 09:33 schrieb Kassidy68:

**Comment by Kassidy68** [comment]
Bingo! :-)
The add on works! After some twiking, I was able to retrieve and sync (read and write) my Hotmail.com calendar with the Exhange EWS provider add on!
This is great.
Thank you John.
Michel

**Comment by jobisoft** [comment]
Could you check, if the latest release of TbSync in the Mozilla Add-On repository (0.6.8.2) is working with your hotmail account? Just for the record? TbSync should find all server details via autodiscover by itself. You can simply install it via the Add-On page of Thunderbird, just search for TbSync.

It is working with my own hotmail account, but as you said, there might be two different "versions" of hotmail accounts. Would be nice to know, if it works just for me, or for you as well.

Thanks for your time!

**Comment by jobisoft** [comment]
From further tests I assume TbSync is working with any hotmail account.
