### ISSUE TITLE
Translations have moved to crowdin.com

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/TbSync#302]
@ovari 
@sinya13 
@wanderleihuttel 
@AlessandroMenti 
@e-jim 
@dilyanpalauzov 

Dear Translators,

I have created an account on crowdin.com where all TbSync related translations will be managed from now. This will make translation a lot easier, as you do not have to manually edit the source files anymore, but have a nice web editor to work with.

https://crowdin.com/profile/jobisoft

I invite you all to join the translation team and thank you once more for your efforts.

To actually edit a locale, you have to log into crowdin, but you can do that with your github account. After that, I can grant you translation rights.

**Comment by jobisoft** [comment]
One usability information:

If a string is the same in your locale as in the original english, it will be listed as "untranslated". You cannot change that. So if a string will be the same in your locale, do not bother adding the same value as a translation, it will not get stored and it will remain "untranslated".

All untranslated strings automatically fall back to the english original.

**Comment by jobisoft** [comment]
I also would like to inform you about the proofreading tool, which includes a spellchecker and makes a few checks to make sure the translations are correct. For example it checks for unnecessary spaces or if the punctuation matches (colon or dots at the end and stuff like that)

You can reach it via the context menu shown below. If that entry is missing, I have forgotten to give you the proofreading permission. Just ping me.

![image](https://user-images.githubusercontent.com/5830621/65727960-a565e200-e0b9-11e9-9e58-1eb5d16845c1.png)

**Comment by AlessandroMenti** [comment]
@jobisoft Join requests sent!

**Comment by jobisoft** [comment]
Looks like I was wrong here:
https://github.com/jobisoft/TbSync/issues/302#issuecomment-535943672

You can indeed store an identical translation and reach 100% translation status.

FYI: I have URLs as translatable entries, to have the option to open different URLs based on locale, maybe to open a translated version of the original link target. However I currently do not do that.

The other case where I have URLs to be translated are descriptions of CalDAV/CardDAV providers, where I simply put in the providers homepage, instead of text.

**Comment by ovari** [comment]
Suggestions:

1. Add more languages on [Crowdin](https://crowdin.com/project/tbsync), even if they are 0% and you have no translators. People who search for project to translate in their language can then find your add-on.<br>
For example, [Phoenicis](https://github.com/PhoenicisOrg/) (aka [PlayOnLinux 5](https://www.playonlinux.com/)) added more languages and now has more translators as they can be found.
https://crowdin.com/project/phoenicis

2. Add an icon to your Crowdin.
Compare the difference between
https://crowdin.com/projects?q=tbsync
and
https://crowdin.com/projects?q=phoenicis

What do you think?

Thank you

**Comment by jobisoft** [comment]
What set of languages would you suggest?

**Comment by jobisoft** [comment]
Icons have been added.

**Comment by ovari** [comment]
@jobisoft why not have all languages available?

**Comment by jobisoft** [comment]
After thinking about this, I will keep it as it is. 

I would like to see, what translations are avail (and which is missing in just one provider). I added a note, that I will add any language on request. Also, most crowdin users know, that any language can be added, specially if they have added translations for that language to another project already.

I had such a case for the polish language just yesterday.

**Comment by qosobrin** [comment]
Hi, @jobisoft. I have already requested this within Crowdin but I haven't got any response from you (I know you're very busy these days adapting to TB 102) so I ask you here: could you please add support for Galician language and assign the crowdin projects to me? Thank you very much. Regards.

**Comment by jobisoft** [comment]
I added Galician to all three projects (TB-Sync + DAV + EAS). You should now be able to request to be listed as translator. Thanks for your help!

**Comment by qosobrin** [comment]
> I added Galician to all three projects (TB-Sync + DAV + EAS). You should now be able to request to be listed as translator. Thanks for your help!

I was able to access the Galician translation (actually two of the three projects are 100% translated but not doucble checked) but not the Spanish one. 

Thank you very much for your great job.
Regards.

**Comment by DevDef** [comment]
Hi John,

It I wrote a private message for you from Crowdin several weeks ago concerning the French translation. Could you please give me an answer?

Regards,

Davy
