### ISSUE TITLE
recurring event´s exceptions should be synched

### ISSUE THREAD

**Issue by gerhardmu** [jobisoft/TbSync#31]
I know that TBSync does synch now recurring events, but not the "exceptions". I guess with that is meant that (re)moved events within a recurring line won´t be synched, but that is really needed, otherwise the synched calendar is not reliable.  A not reliable calendar as good as my brain ;-)

**Comment by jobisoft** [comment]
It is on the to-do-list.

**Comment by jobisoft** [comment]
[ChrisJAllan](https://github.com/jobisoft/TbSync/pull/35) is working on this, so it will be part of the next release.

**Comment by gerhardmu** [comment]
oh good! Thanks a lot! I am glad about it.

Just a question, not an issue ;-) I am just eager to know it: I wondered how it is solved in the database, when one event out of a recurring events will be modified. Do the recurring event stop to the moment of the modified event and start a new after that? Or are there exception data records which should "cover" the modified? 

Anyway, TBsync has not to produce that all, it is just copying resp. synching, right?

**Comment by jobisoft** [comment]
all recurring events are actually "one" event with set recurrence info. also that same event can contain exceptions, which is an entire event stored as "blob" in an exception array.

**Comment by jobisoft** [comment]
It would be great, if you could test the latest [beta](https://github.com/jobisoft/TbSync/releases/download/v0.6.9.1/TbSync-0.6.9.2-beta2.xpi), which includes exceptions.

**Comment by jobisoft** [comment]
Just release [beta3](https://github.com/jobisoft/TbSync/releases/download/v0.6.9.1/TbSync-0.6.9.2-beta3.xpi)

It would be great, if you could test exceptions to recurring events with that version.
