### ISSUE TITLE
A Question rather than an issue - Does this work with Google Calendars?

### ISSUE THREAD

**Issue by smipx** [jobisoft/TbSync#312]
## Your environment

TbSync version:  1.7.0.1
Thunderbird version:  60.9.0

I wanted to know if the TbSync works with Google Calendars.  I tried installing the CALDAV addon but can't seem to get it to work.  I was also tesing another addon for this but that addon does not seem to preserve the "categories" or "Colours" in Google Calendar so went looking for alternatives.  I already use this for an outlook.com account so it made sense to consolidate if it was possible.

Thanks
Paul

**Comment by jobisoft** [comment]
Currently, there is no direct google support in TbSync. I plan to write a google provider as stated in this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1570933#c3

You can try to register your calendar directly in lightning via CalDAV:
https://apidata.googleusercontent.com/caldav/v2/example@gmail.com/events 
(where _example_ is replaced with your own address)

With the latest announcement for Thunderbird 72/78:
https://developer.thunderbird.net/add-ons/tb78

I need to first make sure, that TbSync itself will work with the next versions of Thunderbird, so any feature development has come to a standstill.

**Comment by smipx** [comment]
Hi,

Completely understand.  Keep up the good work :-)
Look forward to one day having Google CAlendar sync :-)

Cheers,
Paul


------ Original Message ------

**Comment by smipx** [comment]
just an FYI.

I did just try the caldav 
https://apidata.googleusercontent.com/caldav/v2/example@gmail.com/events 
method and while it works it too does not seem to sync the colours from 
Google Calendar down to Lightning and if I create a meeting in Lightning 
and assign a category that categories colur does not go up to Google 
Calendar either.

Ah well.  such a shame as I use the colours extensively.

Cheers,
PAul


------ Original Message ------
