### ISSUE TITLE
Simplify WebDAV account setup by reducing the number of required clicks

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/TbSync#316]
To setup a new WebDAV accont, the user has to click on “Account Actions”, "Add new account”, “CalDAV and CardDAV”. 

Currently there is no plethora of TBSync adapters.

I propose reducing the clicks by one, by replacing “Add new account” with “Add new CalDAV & CardDAV account” and “Add new Exchange ActiveSync account”.

In fact I would prefer if the “Exchange Active Sync” is not shown, until the “Exchange Active Sync” adapter is installed.

**Comment by jobisoft** [comment]
No.
