### ISSUE TITLE
Bundle DAV-4-TbSync into TbSync

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/TbSync#317]
For the sake of simplifying life of users, bundle the DAV-4-TbSync adapter in the TbSync plugin, so that users have to perform only one installation to get WebDAV integrated into Thunderbird.

**Comment by jobisoft** [comment]
No.

**Comment by dilyanpalauzov** [comment]
The current setup procedure (install two TB plugins, instead of one TB plugin) does complicate unnecessary users' ilfe.

What about triggering DAV-4-TbSync installaiton in the background, once the user requests funtcitonality from DAV-4-TbSync, so that the user does not have to install it explicitly?

**Comment by jobisoft** [comment]
That is against the addon terms, I did try that. The reason why they need to be separated is that TbSync is being integrated into core and I cannot have the DAV provider flying around there as well. Also I want to be able to give up responsibility for the DAV provider independent of TbSync.

This is a 100% no.

**Comment by dilyanpalauzov** [comment]
If TbSync is integrated into core, then the user will have to install indeed one plugin.

When will TbSync be integrated into core and on what does it depend?

What are the reasons against integrating DAV-4-TbSync in the core?  I mean, if TbSync is in the core and Lightning is in the core, and utilizing Lightning suggests availability of DAV-4-TbSync, what will be the reasons against having DAV-4-TbSync in the core?

**Comment by jobisoft** [comment]
I am in talks with the core dev team for over a year and it starts to spin a bit more right now. After TbSync is in core, the next step is to talk about DAV. But that is not even on the horizon. One step at a time. No ETA for TbSync in core.
