### ISSUE TITLE
TB Sync causing high CPU and blinking scrollbars on MacOS

### ISSUE THREAD

**Issue by FearNaBoinne** [jobisoft/TbSync#318]
## Your environment

TbSync version: **1.7**
Thunderbird version: **60.9.0 for MacOS**

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.
**(No, because the newest version is for TB 68, which isn't out yet!!!)**

## Expected behavior
**No change in idle behavior, low CPU**

## Actual behavior
**Scroll bars on folder list and email list continuously blink in to view, as if someone is scrolling up.
1 core of CPU fully loaded
(But only when TB is in the foreground. When in background or minimized, the CPU is low. I cannot tell then, obviously, whether the scrollbars would still blink!)**

## Steps to reproduce
**Install TB 60.9.0 on MacOS, install TBsync (even happens if I disable the Exchange Provider for TBsync!)**

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://download.mozilla.org/?product=thunderbird-68.1.2-SSL&os=osx&lang=de

**Comment by jobisoft** [comment]
I have no resources to support old versions of Thunderbird. Please update to TB68 and try again.

**Comment by FearNaBoinne** [comment]
I assumed 68 wasn't out yet, because TB is set for auto-update and hadn't updated yet... Weird!

Will try later today!

**Comment by PresGas** [comment]
@jobisoft this is good to know! It looks like *buntu is only using TB68 on their latest release. However, they are still supporting their other versions that are still on TB60. I know there is a stand alone installer for Linux, but I know I try to keep things in a package ecosystem. 

Maybe a snap/flatpack is available...

**Comment by FearNaBoinne** [comment]
Just manually upgraded to TB68, and it seems it is resolved... I will let you know once I am 100% certain!

**Comment by FearNaBoinne** [comment]
It now sits at ~ 6% when idling in the foreground... I am pretty confident it is resolved!
