### ISSUE TITLE
Issue when i try to sync with the exchange server

### ISSUE THREAD

**Issue by mastery82** [jobisoft/TbSync#319]
## Your environment

TbSync version: 2.5.1 [beta release channel]
Thunderbird version: 68.2.0 (64-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
"Enable and sychronize this account" should have connected with exchange and sync calendar and contacts

## Actual behavior
Getting the following error.
"The server does not provide information about the supported ActiveSync versions. Is EAS blocked for this user or this client (TbSync)? You could try to set the ActiveSync version manually."

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
From the test account you send me, it looks like you are running into a invalid cert issue. You need to import your cert on the new computer as well. I cannot test further, as the password/account you send me is invalid.
