### ISSUE TITLE
synchronisation of picture of a contact entry

### ISSUE THREAD

**Issue by TStein1984** [jobisoft/TbSync#322]
## Your environment

TbSync version: 2.6
Thunderbird version: 68.2.0 

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Transmission of the contact data, also with a picture of the contact, without Errors.

## Actual behavior
One single address entry is synchronize well. After I was adding a with around 60 kB size I got an error "Antwort enthält fehlerhaftes XML....".

![Fehlermeldung](https://user-images.githubusercontent.com/22123632/67643662-07fd0880-f91a-11e9-8713-766dbb490722.PNG)

In the Event-Protokoll I saw that the transmission of the picture was started, 

![Event_Protokoll_Start](https://user-images.githubusercontent.com/22123632/67643670-2a8f2180-f91a-11e9-9c4a-a0fbde631054.PNG)

but not completely finished.

![Event_Protokoll_End](https://user-images.githubusercontent.com/22123632/67643675-32e75c80-f91a-11e9-80d8-efbf41d604c6.PNG)

## Steps to reproduce
- create an contact
- synchronize
- add to the contact a photo of the Person
- try to synchronize and the Problem happens. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I didn't got an debug log.

**Comment by jobisoft** [comment]
synology?

**Comment by TStein1984** [comment]
Yes it. I use the Synology NAS DS718. Is it a problem there?
    Am Montag, 28. Oktober 2019, 02:46:18 MEZ hat John Bieling <notifications@github.com> Folgendes geschrieben:  
 
 
synology?

**Comment by jobisoft** [comment]
Yes, it’s a Synology issue. Either use http instead of https or try to follow instructions here:
https://github.com/jobisoft/DAV-4-TbSync/issues/104

**Comment by TStein1984** [comment]
Hello John,

Thank you very much for the support. The solution with the revert Proxy is working fine without any problems.
Best regards
Thomas
    Am Montag, 28. Oktober 2019, 08:30:12 MEZ hat John Bieling <notifications@github.com> Folgendes geschrieben:  
 
 
Closed #322.
