### ISSUE TITLE
Email adresses not synched.

### ISSUE THREAD

**Issue by JPRuehmann** [jobisoft/TbSync#323]
## Your environment Kubuntu 18.04 LTE (32Bit)

TbSync version: 2.6
Thunderbird version: 68

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
showing Email Addresses in Contact data
...

## Actual behavior
No Email Addresses
...

## Steps to reproduce
Try to enter a known Email Address
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That is a very poor error discription. Can you provide screenshots of what is not working?

**Comment by JPRuehmann** [comment]
No, Sorry Can´t Attach anything here.
Try to put it on my FTP-Server.

**Comment by JPRuehmann** [comment]
ftp://jpruehmann.dnshome.de/Screenshot_20191030_084741.png

**Comment by jobisoft** [comment]
Can you also send my a screenshoot from the editing window of that contact? If you do not want to post it in github, just send me an email.

**Comment by JPRuehmann** [comment]
Hello
Seems the Problem is not at tbSynchs side.
On my Phone i can see the Mail addresses
on the Server not, an so TBSynch can´t see them To.
Sorry.
