### ISSUE TITLE
Account Manager Display Broken in TB60

### ISSUE THREAD

**Issue by phr00t** [jobisoft/TbSync#33]
This is what happens when I try to open the Account Manager:

![account-manager](https://user-images.githubusercontent.com/5983470/35157965-9abac640-fd03-11e7-976a-683491b734aa.png)

I'm using Thunderbird Daily 64-bit, 59a1, with the latest Lightning 6.1a1. I'm using a high contrast theme. I understand this version may not be supported yet, but this will likely be a coming issue for those who keep up to date with Thunderbird releases. I appreciate any help!

EDIT: Using TbSync v0.6.9.1

**Comment by jobisoft** [comment]
What "triggers" this display error? The high contrast theme? The TB version? Did it work before? What did you change?

This looks srange, all tabs of the account manager are shown side by side...

**Comment by phr00t** [comment]
This is my first time trying this plugin for syncing with my Exchange Calendar, since I heard this one works with Thunderbird Beta 58 -- hoping it would work for 64-bit 59a1.

I haven't found what triggers the display error. The high contrast theme doesn't appear to be the problem. I suspect it is the latest version of Thunderbird & Lightning causing the problem. I suggest trying it yourself:

https://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-central/thunderbird-59.0a1.en-US.win64.installer.exe

https://ftp.mozilla.org/pub/calendar/lightning/nightly/latest-comm-central/lightning-6.1a1.en-US.xpi

**Comment by jobisoft** [comment]
Are you using windows?

**Comment by phr00t** [comment]
Yes.

**Comment by jobisoft** [comment]
Ok, I tried to get daily running, but is is very slow and not very stable. I will not spend any more time on this, I do not have the resources. 

I do test against beta from time to time, but I will not test against daily. If 59 moves to beta and the problem is still there, I will look into it.

If you find a solution to the problem, I am open for pull request of course.

Sorry, if that is not the desired answer...

**Comment by phr00t** [comment]
Odd, I switched to Daily 59a1 64-bit for its speed & haven't had any reliability issues. I understand not devoting time to this, though. I don't know where to begin to troubleshoot this, as I have no Thunderbird plugin development experience & am working on other projects... :-/

**Comment by jobisoft** [comment]
Odd indeed, I was not even able to install lightning and TbSync, because the AddOn Manager does not finish to load.

**Comment by phr00t** [comment]
I'm running Windows 10 x64, if that means anything. I've been using Daily 59a1 for 2+ months without issue, with Lightning & Google Calendar syncing working fine. Only Exchange isn't working, which I was hoping to use this plugin for :-(

**Comment by jobisoft** [comment]
I just tried Daily 60 and it still hangs when going to the AddOn Page. So I cannot install TbSync and/or Lightning. You do not have that issue?

**Comment by phr00t** [comment]
I do not have that issue. I've updated to Daily 60. AddOn page works fine for me. I tried loading TbSync on Daily 60 via the AddOn page & the same problem still exists: tabs are all displayed without a container across the screen. I can check that "Debug Log" box, but I don't know if it is generating any logs or where they would be.

**Comment by jobisoft** [comment]
I have not done any work on this issue, because - due to the AddOn page issue - I cannot set up my development environment with Daily yet.

I have that issue on two different Win10 computers, SSD only, one 32bit, one 64bit...



Am 28.01.18 um 19:06 schrieb Phr00t

**Comment by jobisoft** [comment]
The bug is finally confirmed: https://bugzilla.mozilla.org/show_bug.cgi?id=1428082#c15

Also, I understood, why it does not work with Daily anymore. That will be a lot of work...

**Comment by jobisoft** [comment]
Could you try [beta5](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta5.xpi)?

Can I have a screenshoot, how it looks? Does it work?

**Comment by phr00t** [comment]
Progress! The tabs work & things are contained within a window.

I can't seem to setup or add an account, though. Clicking "Add account" with a Custom Configuration didn't do anything. The debug log looked like this:


** Fri Feb 09 2018 19:48:45 GMT-0500 (Eastern Standard Time) **
[JavaScript Error: "uncaught exception: 2147746065" {file: "resource:///modules/activity/autosync.js" line: 210}]

** Fri Feb 09 2018 19:49:06 GMT-0500 (Eastern Standard Time) **
[JavaScript Error: "TypeError: window.opener.tbSyncAccountManager is undefined" {file: "chrome://tbsync/content/provider/eas/newaccount.js" line: 88}]
addAccount@chrome://tbsync/content/provider/eas/newaccount.js:88:9
onAdd@chrome://tbsync/content/provider/eas/newaccount.js:61:17
anonymous@chrome://global/content/bindings/dialog.xml line 407 > Function:3:1
_fireButtonEvent@chrome://global/content/bindings/dialog.xml:408:28
_doButtonCommand@chrome://global/content/bindings/dialog.xml:376:28
_handleButtonCommand@chrome://global/content/bindings/dialog.xml:364:18
addAccount@chrome://tbsync/content/manager/accounts.js:27:9
oncommand@chrome://tbsync/content/manager/accounts.xul:1:1

Using the automatic option did prompt me for a password on step 2/5, but no combination of "username"s or passwords worked. I would have liked to enter a different server name & e-mail address to troubleshoot...

**Comment by jobisoft** [comment]
fixed in [beta6](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta6.xpi)

may I have a screenshoot?

**Comment by jobisoft** [comment]
please try with [beta7](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta7.xpi)

beta7 no longer sends password during autodiscover on http connections (but tries to get redirects only) and has a timeout counter.

... do not forget the screenshoot please ...

**Comment by phr00t** [comment]
It works! Everything seems to be working! Automatic configuration seemed to try its best better, but I don't think our Exchange server is setup for autodiscovery. Custom configuration works great & all of my Exchange entries have been added. Thank you! Do you still need a screenshot? Everything looks as I'd expect,

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
