### ISSUE TITLE
TbSync keeps asking for password every few minutes. Can it remember password?

### ISSUE THREAD

**Issue by calypsori** [jobisoft/TbSync#330]
## Your environment

TbSync version: 2.7.6 beta
Thunderbird version: 68.2.2

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TbSync asks for O365 password once and stores it for later use.

## Actual behavior
TbSync keeps asking for O365 password.

## Steps to reproduce
N/A

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
The latest beta should not popup the standard password prompt, but should actually open a small browser window and lets you sign in directly at Microsoft. Do you get that window?

![grafik](https://user-images.githubusercontent.com/5830621/68858595-a5f81d80-06e5-11ea-9c52-18113765d691.png)

and

![grafik](https://user-images.githubusercontent.com/5830621/68858696-e3f54180-06e5-11ea-85ea-e1a8fadbe9f1.png)


And I just updated the beta (like 10s ago), so please let your TB68 check for updates.

**Comment by calypsori** [comment]
Yeah, those were the windows I was seeing. I just updated as you recommended, let's see if it will happen again.

BTW., wow - never seen such quick support!

**Comment by jobisoft** [comment]
I just learned (this is all new to me) that the server can expire such an authorization and I need to refresh. I currently do not do that but simply ask again. I have to fix that. I report back.

**Comment by calypsori** [comment]
This happened few more times in the past few hours. Window screen pops up with the request to log into O365 again.

**Comment by jobisoft** [comment]
I think I have the refresh stuff implemented now. Can you update your beta addons and try again? It could be, that the first refresh fails and you still get prompted, but it shoud work after your next permission grant.

**Comment by jobisoft** [comment]
There was another bug. Please update again.

**Comment by calypsori** [comment]
OK, updated. Now we wait. :)

**Comment by calypsori** [comment]
![image](https://user-images.githubusercontent.com/34311892/68898260-62c29c80-072f-11ea-8cbb-39ceb914b452.png)

This is what I got again. I'll observe if another one will pop up.

**Comment by jobisoft** [comment]
I am sorry, there was another typo/bug. Please update again. Having to actually wait until the refresh code is triggered makes it difficult to test.

**Comment by calypsori** [comment]
So far so good, I haven't seen the window popup asking for a password. Will observe for some more time.

**Comment by calypsori** [comment]
Didn't receive the popup window asking for O365 password. Looks like it's working! :)
