### ISSUE TITLE
EAS provider not found if SOGo Connector is installed

### ISSUE THREAD

**Issue by thoralf-tu** [jobisoft/TbSync#340]
## Your environment

TbSync version: 2.7
Thunderbird version: 68.2.2

[×] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
tbsync w/ Provider for Exchange ActiveSync installed can access exchange accounts

## Actual behavior
** Tue Nov 26 2019 16:04:30 GMT+0100 (Central European Standard Time) **
[Loaded provider] : eas::Exchange ActiveSync (1.7)

** Tue Nov 26 2019 16:04:30 GMT+0100 (Central European Standard Time) **
[EventLog] : FAILED to load provider <eas>
Method not implemented'Method not implemented' when calling method: [nsIAbDirectory::getStringValue]

## Steps to reproduce
this happened after an upgrade from tb 60 to tb 68 (yeah, we all love this). tbsync & eas provider worked fine before, now they don't. tried both stable and beta releases, to no avail.

## Solution

**Disable the SOGo-Connector Add-On**

**Comment by jobisoft** [comment]
They do work on my system, lets get this sorted out. Can I have the full log?

**Comment by thoralf-tu** [comment]
hi John,

(sent again with correct reply-to: address)

first of all: thank you very much for your work …

On 11/26/19 4:22 PM, John Bieling wrote:
> They do work on my system, lets get this sorted out. Can I have the full
> log?

sure thing:

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[TbSync init] : Start (2.7)

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Thunderbird] : 68.3.0 on Linux

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <db>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <abAutoComplete>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <addressbook>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <lightning>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <cardbook>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <eventlog>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <core>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <passwordManager>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <network>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <tools>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <manager>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <providers>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loading module <messenger>] : OK

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <db>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <abAutoComplete>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <addressbook>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <lightning>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Check4Lightning] : Start

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Check4Lightning] : Done

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <cardbook>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <eventlog>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <core>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <passwordManager>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <network>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <tools>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <manager>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <providers>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Initializing module] : <messenger>

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[TbSync init] : Done

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[EventLog] : Default timezone has been found.

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[Loaded provider] : eas::Exchange ActiveSync (1.7)

** Tue Nov 26 2019 16:23:39 GMT+0100 (Central European Standard Time) **
[EventLog] : FAILED to load provider <eas>
Method not implemented'Method not implemented' when calling method:
[nsIAbDirectory::getStringValue]

… please let me know if there is anything more i can do.

cheers,
t.

**Comment by jobisoft** [comment]
Could you retry with the latest beta and send me a debug log again? 
https://tbsync.jobisoft.de

If you like, you can use the report function inside TbSync to send the report directly to me.

**Comment by thoralf-tu** [comment]
no change with the latest beta :-( i sent you an email via the report function.

**Comment by thoralf-tu** [comment]
… disabling sogo connector fixes this issue.

**Comment by jobisoft** [comment]
Alright, I added a fix to the latest beta and it should work now even if SOGo is enabled and a SOGo addressbook exists. Could you give it a spin?

**Comment by jobisoft** [comment]
fix released to ATN

**Comment by thoralf-tu** [comment]
sorry for not replying earlier, i've been really busy. i can happily confirm that this is fixed, i checked with today's beta (20191129-13:32).

thank you very much for debugging and resolving this issue.

cheers,
t.
