### ISSUE TITLE
can TbSync sync 'g suit contacts with its groups' ?  it said so but

### ISSUE THREAD

**Issue by seanlu21** [jobisoft/TbSync#342]
## Your environment

TbSync version: where to find huhhh ?  do not know
Thunderbird version: 68.3.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Sadly google groups are not synced via google carddav API :-(
