### ISSUE TITLE
Problem or question: How to sync with Google only the address book

### ISSUE THREAD

**Issue by sfatula** [jobisoft/TbSync#345]
## Your environment

TbSync version: 2.9
Thunderbird version: 68.2.2

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Uncheck sync of Contact and google account, only address book should be synced. As an aside, it would be nice to only write changes to Google for me, never ever want to read them.

## Actual behavior
I uncheck calendar and my google account email name, I leave checked contacts on the available resources section, click sync now and instead, it tries to do them all again, i.e., it says the lightning add-on is not installed for contacts and my google email name and says calendars are not supported. I don't want to sync calendars nor do I want the lightning addon. 

## Steps to reproduce
Link to google account, and, try to sync ONLY address book in the available resources section. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
You found a bug. If a calendar has been checked/selected and you have run into tho "no lightning" error, you cannot uncheck the calendar anymore. Thanks for finding this.

I have never run TB without Lightning, so I never saw that error.

I will fix this.

**Comment by jobisoft** [comment]
Fixed in beta. Can you test?
https://tbsync.jobisoft.de/

**Comment by sfatula** [comment]
I have tested. The error part does indeed go away, but, it doesn't sync. Is it due to the timezone message?

![Screenshot from 2019-12-16 21-01-13](https://user-images.githubusercontent.com/17562551/70961492-9141d900-2047-11ea-8687-c9c996f5af12.png)

**Comment by jobisoft** [comment]
What do you mean it does not sync? Can I have a screenshoot from your TB addressbook?

The info you get in the event log is just an info, not related.

**Comment by sfatula** [comment]
I mean added contacts are not on Google Contacts. I have 2 address books with tbsync. I have iCloud, which brings my contacts down from iCloud to Thunderbird so I can use them for email, and, I have Google Contacts which sends the contacts from Thunderbird to Google. All of my icloud contacts (except added ones) are on Google from the initial sync via tbsync. It is set to automatically sync every 65 minutes. Ones I added in iCloud since that initial sync have not shown up in Google though. Thus, my comment that it is not syncing automatically. 

The iCloud contact list comes down in Thunderbird as iCloud (Contacts). "Personal Address Book" is empty, How can I get my previously synced address book from iCloud to Google? The very first time I added Google sync, it added them all (at the time) to Google Contacts. Just no changes since then.

In the end, am wanting contacts to go from iCloud (read only) -> Thunderbird -> Google

I could give a screen shot from my address book, but, don't want to post any names, email, phone #, etc. Not sure exactly what you are looking for??

**Comment by jobisoft** [comment]
That is not how TbSync operates.

If you add a contact to the "Google (Contacts)" addressbook and sync (manually or by auto sync every 65min), this contact will show up in your online google address book.

If you add a contact to your "iCloud (Contacts)" addressbook and sync, this contact will show up in your online icloud address book.

TbSync however is not a "bridge". It allows to access your remote addressbooks via 2-way-sync, but it does not merge all of your contacts together and makes them avail on all your remote addressbooks.

You can drag and drop a contact from your icloud address book to your google address book (in Thunderbird), but I would not reccomend that, as Thunderbird might not copy all the contact details.

**Comment by sfatula** [comment]
Ok, that's obviously how I want to use it, however, if I delete all contacts from Google Contacts (via Google), and, delete all from tbsync, then delete the tbsync setup for Google, add it back, it adds all icloud contacts to Google. Just the first time though.
