### ISSUE TITLE
sync all old EAS calendar events

### ISSUE THREAD

**Issue by FrancoisChaumont** [jobisoft/TbSync#346]
## Your environment
Ubuntu 18.04.3 LTS Linux 5.0.0-37-generic x86_64

TbSync version: 2.9
Provider for Exchange ActiveSync version: 1.9
Thunderbird version: 68.2.2 64-bit

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync all old events from EAS account by changing the setting **extensions.tbsync.eas.synclimit** to 0. I notice that there is other settings named extensions.eas4tbsync.*** and then tried setting **extensions.eas4tbsync.synclimit** to 0 as well.

## Actual behavior
Only syncs 6 months (default setting)

## Steps to reproduce
1. Load an EAS calendar that contains events older than 6 months and see that they don't appear in the calendar tab
2. Change the setting **extensions.tbsync.eas.synclimit** to any value
3. See that it makes no difference in the period of events displayed in the calendar

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
**debug.log sent**

**Comment by jobisoft** [comment]
In the version you are using, the mentioned preference is no longer used, you can select the desired sync limit in the options screen of your tbsync account.

Screen is in german, but I think you can see what I mean:

![grafik](https://user-images.githubusercontent.com/5830621/70820796-cea12f00-1dd9-11ea-8aee-93e7b0f2aabb.png)

**Comment by FrancoisChaumont** [comment]
Thank you very much! 
Thanks to your screenshot I was able to find the options and it works great.

For some reason on my environment those options don't appear as tabs but instead as simple text.
![tbsync](https://user-images.githubusercontent.com/19363964/70838738-461d9100-1dcf-11ea-905c-d198d797dfd7.png)

This issue has nothing to do with you as it appears in other parts of Thunderbird as well.
Thanks again and keep up the good work. Love TbSync!
