### ISSUE TITLE
TbSync stops syncing and requires toggling 'sync' feature to start working again

### ISSUE THREAD

**Issue by pd5rm** [jobisoft/TbSync#347]
## Your environment

TbSync version: 2.9
ActiveSync Provider: 1.9
Thunderbird version: 68.3.0

## Expected behavior
The sync behavior to continue without it automatically stopping, and requiring manual intervention.

## Actual behavior

Sync stops, my Exchange calendars don't appear anymore.

Also, I end up with local "duped" events. I then need to delete these as they're no longer associated with the Exchange calendar (perhaps saved to personal/local calendar)

## Steps to reproduce

1. I setup Calendar and Contact sync. Default 5 min interval (had used 1 min before), but thought maybe that was causing the issue.
2. Wait several hours (e.g I had to reset sync earlier today, and it stopped syncing maybe 2-3 hours later).

P.S This has been happening for a while (at least a month), don't have a known repro step, but it does happen very regularly.

I had debug log (error only) enabled. I don't see much, but I'll redact and attach todays logs.

**Comment by pd5rm** [comment]
The attached images contain what the preference panes looks after an initial sync (see all the available options), and what happens after the non-sync behavior starts (see two sync sources missing).

**Working**
![tbsync-after-disable-enable](https://user-images.githubusercontent.com/1731288/70836583-70faeb80-1db5-11ea-9975-e98bc0a9bab3.png)

**Not Working**
![tbsync-no-calendar](https://user-images.githubusercontent.com/1731288/70836582-6fc9be80-1db5-11ea-87c6-546c71e8937d.png)



I attached the full log, but seems like these might indicate a root cause.

```
[EventLog] : JavaScriptError
Provider <eas> is missing a TargetData implementation for <none>.

get targetData@chrome://tbsync/content/modules/public.js:449:15
remove@chrome://tbsync/content/modules/public.js:465:9
checkStatus@chrome://eas4tbsync/content/includes/network.js:636:32
folderList@chrome://eas4tbsync/content/includes/sync.js:125:21


** Fri Dec 13 2019 12:53:45 GMT-0800 (PST) **
[EventLog] : JavaScriptError
Provider <eas> is missing a TargetData implementation for <none>.

get targetData@chrome://tbsync/content/modules/public.js:449:15
remove@chrome://tbsync/content/modules/public.js:465:9
checkStatus@chrome://eas4tbsync/content/includes/network.js:636:32
folderList@chrome://eas4tbsync/content/includes/sync.js:125:21
```

[tbsync.log](https://github.com/jobisoft/TbSync/files/3962978/tbsync.log)

**Comment by jobisoft** [comment]
Thanks, that does look like a bug in TbSync.

**Comment by jobisoft** [comment]
I uploaded a new beta, which should give more info on this.
https://tbsync.jobisoft.de

Can you try?

It should log something like:

```
Provider <eas> is missing a TargetData implementation for <unknown type (?)>.
```

But in general, this issue is strange. The resources, which disappear, change their folder type to something that is not supported by TbSync. That should never happen.

What kind of server is that exactly?

**Comment by pd5rm** [comment]
Thanks, I just installed the beta plugins into a a seperate profile, and enabled the debug logs. Now I'm waiting for the repro.

I think it's 15.1.1713.5 which maps to: Exchange Server 2016 Cumulative Update 12 (CU12).

**Comment by pd5rm** [comment]
Here's a log from this morning. This dialog view appeared different. The items were listed (e.g contacts, calendar), but they were unchecked, and no events were showing in calendar view. When I clicked and enabled them, it started syncing again. Let me know if I should enable more verbose logging.
 
[no-sync-tbsync-debug.zip](https://github.com/jobisoft/TbSync/files/3976051/no-sync-tbsync-debug.zip)

**Comment by jobisoft** [comment]
There are multiple FolderSync 110 Errors in the log. The protocol states:

`The server encountered an unknown error, the device SHOULD NOT retry later.`

Got to dig into that.

**Comment by pd5rm** [comment]
Is that something I should dig into? ;-)

I'll note that I do log into this account on Outlook via an iOS device as well. I don't know if that matters re: syncing.

**Comment by marcinbojko** [comment]
I have same situation. If logs or config is needed - let me know.

**Comment by pd5rm** [comment]
Anything I can do to assist with this. It's still a recurring issue.

**Comment by jobisoft** [comment]
The log from 18th of Dec does not contain the original JavaScript Error. Also it seems the log verbosity is not set to max, can you do that? (under help in the tbsync manager). 

I need to see what happens before the account is being reset.

What dou you mee with "dupes" in your first post? Do you get backup/disconnected calendars? Could I have a screenshot?

**Comment by jobisoft** [comment]
With "I need to see what happens before the account is being reset." I mean before the error happens, that causes this.

**Comment by jobisoft** [comment]
Here is some more info on this: The error 110 is a severe **ServerError** with the following description:

> The server encountered an unknown error, the device SHOULD NOT retry later.

https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ascmd/95cb9d7c-d33d-4b94-9366-d59911c7a060

That is why I reset your account in this case and start from scratch, removing all subscriptions.

In the latest beta release (https://tbsync.jobisoft.de) I changed that. I no longer reset your account but simply abort the sync. I also disable automatic periodic sync for at least 30 minutes, so your server has a chance to recover. You can see in the event log, when and how often that happens.

Now the interesting question: Is your account able to recover at some point, or is this a "deadly" error and your account eventually has to be reset manually, to get it working again.

It would be a big help, if you could switch or update to the latest beta release and test this.

This is of course only dealing with the symptoms. Your server has an issue and there are already reports about this.

**Comment by jobisoft** [comment]
@marcinbojko 
@pd5rm 

Could you give feedback regarding the latest beta version and my last comment?

**Comment by marcinbojko** [comment]
> @marcinbojko
> @pd5rm
> 
> Could you give feedback regarding the latest beta version and my last comment?

Hi @jobisoft  
Did the upgrade, so far sync seems to be working. On Monday I'll create some (real) events and we'll see.
Thanks! ;)

**Comment by pd5rm** [comment]
@jobisoft Sorry, been super busy at work. I'll try to get to this later this week. Thanks for getting out another beta to test with.

**Comment by pd5rm** [comment]
I've had this working for more than 24 hour with latest releases of stable and beta, so its working better than before, but I did notice the "Calendar" option was unchecked on stable release, and but remain checked on the beta.

If I restart the the stable version (with unchecked calendar), my calendar disappears as it did in the past.

![calendar-deselected](https://user-images.githubusercontent.com/1731288/74873596-5c3a5700-5314-11ea-8bef-c34f645af040.png)

**Comment by jobisoft** [comment]
The fix is only in beta and has not been pushed to stable yet. So what you see is expected. I think it will be pushed to stable in a few days.

**Comment by jobisoft** [comment]
Released.
