### ISSUE TITLE
Address lookup for entries with German umlauts does not work

### ISSUE THREAD

**Issue by arnowelzel** [jobisoft/TbSync#348]
## Your environment

TbSync version: 2.9
Thunderbird version: 68.3.0 (32-Bit)

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I write a new e-mail and enter a name containing an German umlaut like "Jü", an entry with "Jürgen" as name will be found in the address book created by TBSync and suggested as recipient.

## Actual behavior
Names with German umlauts will not be found.  However - if you have the entry in a standard addressbook of Thunderbird, this will work. But this is not synced, so that does not help.

## Steps to reproduce

1. Add a contact entry containing the name "Jürgen" and an e-mail address to an adress book which is linked to a TBSync account
2. Create a new e-mail in Thunderbird and start typing "Jü" in the "To" field. The entry with the name "Jürgen" will not be found.

This also applies to entries synced from a server. I believe, there is some kind of unicode/non-unicode issue here.

**Comment by jobisoft** [comment]
Fixed in Beta, can you try?
https://tbsync.jobisoft.de

**Comment by arnowelzel** [comment]
Yes, the Beta fixes this. Now searching works with umlauts as well. Thank you!
