### ISSUE TITLE
Custom CardDAV configuration removes trailing slash

### ISSUE THREAD

**Issue by jposterloh** [jobisoft/TbSync#349]
## Your environment

TbSync version: 2.9
Thunderbird version: 68.3.1 

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I can add a user-defined CalDAV config of the form
https://www.example.de/cal/username/addressbook.vcf/

## Actual behavior
The textfield automatically removes the trailing / and requests are made to 
https://www.example.de/cal/username/addressbook.vcf
This fails, because the server requres the slash at the end to work. 

## Steps to reproduce
Enter a custom config that ends with / and observe how the / is removed when the textfield loses the focus. 

Best
Jan-Patrick

**Comment by jobisoft** [comment]
Thanks for reporting this.

**Comment by jobisoft** [comment]
I removed the slash manipulation in the latest beta:
https://tbsync.jobisoft.de

But
`https://www.example.de/cal/username/addressbook.vcf/`
is not a valid server URL, it is a resource URL. TbSync operates on server URLs, so it could be, that it still does not work with the URL.

Can you try with this?
`https://www.example.de/cal/username`

**Comment by jposterloh** [comment]
Ok, the slash manipulation is gone, thank you very much! 

If I now add this, I get an 403 forbidden error. But if I open these two URLs in my Browser, it downloads and ics or vcf file...

`URL:`
`https://www.example.de/cal/patrick/addressbook.vcf/ (PROPFIND)`
``
`Request:`
`<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>`
``
`Response:`
`<!DOCTYPE html>`
`<html lang="en">`
`<head>`
`  <meta charset="utf-8">`
`  <meta http-equiv="x-ua-compatible" content="ie=edge">`
`  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
`  <title>403 Forbidden</title>`
`  <link rel="stylesheet" href="/error_docs/styles.css">`
`</head>`
`<body>`
`<div class="page">`
`  <div class="main">`
`    <h1>Server Error</h1>`
`    <div class="error-code">403</div>`
`    <h2>Forbidden</h2>`
`    <p class="lead">You do not have permission to access this document.</p>`
`    <hr/>`
`    <p>That's what you can do</p>`
`    <div class="help-actions">`
`      <a href="javascript:location.reload();">Reload Page</a>`
`      <a href="javascript:history.back();">Back to Previous Page</a>`
`      <a href="/">Home Page</a>`
`    </div>`
`  </div>`
`</div>`
`</body>`
`</html>`

**Comment by jobisoft** [comment]
That does not look like a valid carddav resource. Your browser is doing a GET request, but the carddav standard is doing PROPFIND requests and that should never return a webpage.

You got a webpage. So something is wrong. You are not using the correct endpoint.

What kind of server is that? Can I have a test account? Credentials via email?

**Comment by jposterloh** [comment]
Thank you very much, now it works! Now it was a configuration problem in my server :-)
