### ISSUE TITLE
View address book as tab

### ISSUE THREAD

**Issue by mafanie** [jobisoft/TbSync#352]
As you asked "What is missing?" (https://github.com/thundernest/quicktext/issues/51#issuecomment-565836482): I am (only) missing some tab view for the address book like available for CardBook. I would really like to have such as working feels smoother this way, but in fact I can not really expalin why.

## Your environment

TbSync version: 2.9
Thunderbird version: 68.4.1

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

**Comment by jobisoft** [comment]
I think the Thunderbird address book is being reworked for summer 2020, maybe that will solve this.

**Comment by CardBook** [comment]
If you want address books in a tab, maybe consider using CardBook : https://addons.thunderbird.net/thunderbird/addon/cardbook/ :O)

**Comment by jobisoft** [comment]
I think @mafanie knows that (if you read the linked issue).

**Comment by mafanie** [comment]
Yes, I know about CardBook and in fact I am using that most of the time. Today I found several bugs in CardBook ([#793](https://gitlab.com/CardBook/CardBook/issues/793), [#794](https://gitlab.com/CardBook/CardBook/issues/794), [#795](https://gitlab.com/CardBook/CardBook/issues/795)) and then checked what prevents me from using TbSync more regulary.

**Comment by mafanie** [comment]
So I gave a "+1" for Thunderbird bug 457270 and I am using the add-on "TabAddressBook" for the moment.

But with this add-on the appearance of contacts is not the same:
- Only one E-mail address is shown
- Types of phone numbers are shown as text and not as symbols.

Maybe you could check (together with the add-on author) if it is possible to get the same appearance also with the mentioned add-on?

No tab version (standard):
![grafik](https://user-images.githubusercontent.com/19827673/72290475-9cd7ee00-364d-11ea-9baa-52427ca8f1a1.png)

Tab version (TabAddressBook):
![grafik](https://user-images.githubusercontent.com/19827673/72290532-b9742600-364d-11ea-8aa0-8a69b790f193.png)

**Comment by jobisoft** [comment]
TabAddressBook works with TB68?

**Comment by mafanie** [comment]
Yes, in fact this is a TB68 version of §Addressbook in Tabs". 

I have to say that I added it just one hour ago and did not yet check a lot of action (edition contacts, creating contacts, ...), but for what I have seen so far it works just fine.

**Comment by jobisoft** [comment]
Where did you get it? The official version only support TB60:
https://addons.thunderbird.net/addon/addressbook-in-tab/

**Comment by mafanie** [comment]
The name of the add-on is "TabAddressBook", but the author itself states that "This is a hack from mthaens "Addressbook in Tabs" for TB 60."

![grafik](https://user-images.githubusercontent.com/19827673/72322833-9bd3aa80-36a7-11ea-92a0-ca9e39fa9a46.png)

**Comment by mafanie** [comment]
So is there any chance that the interplay between TbSync and TabAddressbook will be optimized in the future?

**Comment by jobisoft** [comment]
I will have a look. (Reopen)

**Comment by jobisoft** [comment]
The reason this is not working: My overlay loader does not work for tabs. Which I did not know until now. So all my special code for the address book is not inserted in the tabbed address book.

I do not know, if I can fix this.

**Comment by mafanie** [comment]
Thanks for looking into this.

With a lot of changes in the Thunderbrid address book expected, it is in my opinion more important that TbSync still works with that - which maybe will include a tabbed address book and therefore eventuelly makes the add-on and this ticket obosolet.

**Comment by jobisoft** [comment]
Ok, switching from bug to wontfix.
