### ISSUE TITLE
could not authenticate

### ISSUE THREAD

**Issue by ChameleonScales** [jobisoft/TbSync#353]
## Your environment

TbSync version: 2.9
Thunderbird version: 68.3.0
OS: Debian 10.2

I just did a fresh install of Debian 10.2, whereas my colleagues only did an upgrade, so they kept all their previously installed packages and system files. On their side TbSync works fine but on my side I can't add an account and I can't figure out why. I thought I may need to install z-push but it turns out my colleagues don't have it installed either. We all have the same version for both thunderbird and TbSync, and I tried to authenticate to the same account as them.
I even re-did a fresh install just to be sure I didn't perform a bad manipulation but nothing changed, so I'm at a loss of ideas.

Here is my [debug log](https://pastebin.com/d23rWU4N) just in case.

**Comment by jobisoft** [comment]
I cannot see the eas provider being loaded. Do you connect to a EAS server or a CalDAV/CardDAV server? Asking because you mentioned z-push...

What i see is a 401, which means wrong creds or wrong endpoints. Compare your tbsync setting whith those of your colleagues.

**Comment by ChameleonScales** [comment]
It's CalDAV/CardDAV, and yes I looked at the settings on one of my colleague's machine and used the exact same.

**Comment by jobisoft** [comment]
Nothing I can do. 401 is pretty clear. Wrong creds or wrong endpoint. Can I have a test account on your server to test and verify you are using the correct endpoints? I can see that the first request send is going to a resource and not to the server itself ...

**Comment by ChameleonScales** [comment]
Sure. I sent you an email with credentials you can try.
One thing I noticed:  we actually can't add new accounts on my colleagues machines. Only those that were already connected before the Debian upgrade are still working.
Other note: I can however successfully connect to my calendar using thunderbird's built-in calendar with the same credentials.
However I guess address books can only be accessed with TbSync.

**Comment by jobisoft** [comment]
This is very strange. Thunerbird is breaking the auth handshake and I do not know why. Usually the first connection to a server is unauthenticated and the server returns a WWW-AUTH header. This is yours:

```
www-authenticate: Digest realm="BaikalDAV",qop="auth",nonce="5e1c96b73ce6a",opaque="d66d5f0524036afcb61420e358f990ce"
```

Which looks fine to me. In a second step, Thunderbird should pick the Digest authentication mechanism and send an authenticated request. It does not do that. It simply is not authenticating.

**Comment by jobisoft** [comment]
I need to correct my last comment. Thunderbird does send the correct header, but your server does not accept it:

```
header: Digest username="test", realm="BaikalDAV", nonce="5e1c9ca61bcd5", uri="/baikal/html/dav.php/principals/test/", response="d763ac972940fad818c34b195d9178f9", opaque="d66d5f0524036afcb61420e358f990ce", qop=auth, nc=00000001, cnonce="06d672752383e1d6"
```
This looks like a plain sabre/dav server and not a baikal to me. I have my own sabre/dav test server and i can auth with digest just fine.

Again, I am out of answers. Your server does not accept a valid digest auth request.

**Comment by jobisoft** [comment]
Any chance you can check the log files of your server?

**Comment by ChameleonScales** [comment]
Hurray, we found what caused the problem: we were using Baikal 0.4 when 0.6 fixed issues with thunderbird synchronizations. We updated and it works fine now. Sorry I wasted your time.
