### ISSUE TITLE
TBSync does not give Google Tasks

### ISSUE THREAD

**Issue by charliegc4** [jobisoft/TbSync#354]
## Your environment

TbSync version: 2.9
Provider for CalDAV & CardDAV version: 1.6
Thunderbird version: 68.4.1 (64bit)

## Expected behavior
Google Tasks to appear as with all Google Calendars.

## Actual behavior
All calendars appear, but no Tasks.

## Steps to reproduce
Install TB 68.4.1. 
Add TbSync and Provider for CalDAV addons.
Add Google account and sync.

**Comment by jobisoft** [comment]
Sadly, that is a known limitation. Google is not allowing access to tasks via CalDAV.

**Comment by charliegc4** [comment]
Thanks for the reply.

I was trying to reduce the number of addons connecting to Google. Previously I was using gContactSync and Provider for Google Calendar. Then I noticed that TbSync does both calendar and contacts.

But no Tasks. Oh well. ;-(

**Comment by jobisoft** [comment]
> I was trying to reduce the number of addons connecting to Google

That is exactly my goal, but google betrayed me ...
