### ISSUE TITLE
Compose autocomplete stops working for TBSync addressbook after <space> character

### ISSUE THREAD

**Issue by ChrisPurves** [jobisoft/TbSync#355]
## Your environment

TbSync version: 2.9
Thunderbird version: 68.4.1 (32-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Autocomplete suggestions for recipient should continue to offer suggestions after typing a space

## Actual behavior
Once what has been entered includes a space (i.e. first and last name are typed out) all TBSync suggestions disappear.  Contacts in native addressbooks continue to be displayed.

## Steps to reproduce
Compose new mail
Begin typing first name (I used Stephen in the example below, all matches from addressbooks appear)
![image](https://user-images.githubusercontent.com/6675015/72465646-f1927a80-37ad-11ea-8101-4ec4a1a0a0e9.png)
spacebar then first letter of last name (L in my example in order to get to specific Stephen)
All TBSync items disappear
![image](https://user-images.githubusercontent.com/6675015/72465769-20a8ec00-37ae-11ea-8411-2181bb179e2a.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I think I fixed in in the latest beta. Can you try?
https://tbsync.jobisoft.de

**Comment by jobisoft** [comment]
@ChrisPurves : Status?

**Comment by ChrisPurves** [comment]
@jobisoft I apologize; I was unable to test the beta release.  However, in the meantime, TBSync upgraded to version 2.10.  I can confirm that auto-complete is working properly in 2.10 and the issues is resolved.  Thank you for your hard work.
