### ISSUE TITLE
Where are my google tasks? 

### ISSUE THREAD

**Issue by edegraaff** [jobisoft/TbSync#357]
## Your environment
Windows 10 pro

TbSync version: 2.10
Thunderbird version: 68.4.1

NO, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
The Calendar is working, Adresbook is working, but Tasks are gone, empty 

## Actual behavior
Tasks are not synchronized

## Steps to reproduce
REinstalled, checked config, reinstalled again,

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
What server?

**Comment by edegraaff** [comment]
Google 

⁣Our Weblog is @ http://www.fishfreak.org​

Op 19 jan. 2020 22:30, om 22:30, John Bieling <notifications@github.com> schreef:

**Comment by jobisoft** [comment]
Google has not implemented the VTODO type of the CalDAV protocoll and only allows to access tasks via its own Google API. Sorry. I wish I could deliver a one-for-all solution, but google failed me here.

**Comment by edegraaff** [comment]
ok shit happens....
as far as i saw in the past id has worked or am i wrong here?

btw... thanks for your help and nice plugin!

⁣Our Weblog is @ http://www.fishfreak.org​

Op 20 jan. 2020 11:11, om 11:11, John Bieling <notifications@github.com> schreef:

**Comment by jobisoft** [comment]
it has and probably still works with this add-on:
https://addons.thunderbird.net/addon/provider-for-google-calendar/

This add-on uses the Google API.

However, it does not do contacts. I really wish I could provide a one-for-all solution ...
