### ISSUE TITLE
Show Birthdays in calendar

### ISSUE THREAD

**Issue by gerhardm5** [jobisoft/TbSync#358]
It would be gread, if I could see the birthdays of stored addresses in my calendar. Till the former version of TB I used Thunderbirthday. Unfortunatly the developer seems not to be active any more and the other tools (Reminderfox and Cardbook) are overcomplicated. 

I wonder if it is not a loss for many people that birthdays are not displayed. Maybe you have an easy way to integrate this into TBSync as the tool handles both addresses and calendars.

**Comment by jobisoft** [comment]
This will help you:
https://github.com/ingomueller-net/ThunderBirthDay/pull/11#issuecomment-529615343
