### ISSUE TITLE
Credentials not sufficient when 2 step verification is used for Office365

### ISSUE THREAD

**Issue by jwdorr** [jobisoft/TbSync#359]
## Your environment

TbSync version: 2.10
Thunderbird version: 68.4.2

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
2 step verification should work for me as my customer is using Office365

## Actual behavior
I installed TbSync yesterday and sync worked properly.
This morning I receive requests from TBSync to (re)enter my password.
I checked what changed if I logon to Office365 and found out that my customer now switched on 2 step verification (was expected).

## Steps to reproduce
Use TbSync with 2 step verification on email address.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can you remove your account in TbSync and set it up again using the dedicated Office 365 Option. Does that solve your issue?

**Comment by jwdorr** [comment]
It looks like it solves the issue. It looks like I overlooked the dedicated Office 365 option. It asked me once for the Microsoft authentication and it works. I will follow-up for another 24 hours to check if it's stable now. 
Thanks for your quick help!
