### ISSUE TITLE
When to support sync Tasks of outlook.com ?

### ISSUE THREAD

**Issue by zhjsun** [jobisoft/TbSync#36]
Generally it works well. But for now it seems that sync tasks is not supported.
When can this be supported?
![1](https://user-images.githubusercontent.com/25036446/35273245-e3c41f5e-0072-11e8-9bf2-21dba4ced4ee.jpg)

**Comment by jobisoft** [comment]
try [beta4](https://github.com/jobisoft/TbSync/releases/download/v0.6.9.1/TbSync-0.6.9.2-beta4.xpi)
