### ISSUE TITLE
Resources become unavailable and stop syncing when using TbSync on multiple devices

### ISSUE THREAD

**Issue by dusares** [jobisoft/TbSync#361]
## Your environment

TbSync version: 2.10
Thunderbird version: 68.4.1 (64-bit) Linux (Ubuntu 18.04)

TbSync version: 2.10
Thunderbird version: 68.4.2 (64-bit) Windows 10

I also use it on a Mac and the versions should match the Windows version. But I have to verify that.

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Resources (calendars, contacts, birthdays, tasks...) are available and continue syncing when used on different devices.

## Actual behavior
After switching from Linux (which syncs at the beginning fine for days) to Windows or Mac. The other machine step by step looses resources it syncs until all resources are gone. They appear again, after disabling and enabling the account, but need to be selected and a manual sync needs to be triggered. Now working on Mac or Windows works fine.

When switching back to Linux the same behavior appears. With each sync it looses resources until everything is gone. And the reappear again after disabling and enabling the account and forcing a manual sync. Also here the wanted resources need to be selected, because nothing is selected.

The behavior might vary. Sometimes all resources disappear at the same time. Sometimes all resources get disabled. Also different error messages are presented (I am paraphrasing from memory as I couldn't capture them all in time):

- Invalid synchronization key (status 3)
- Invalid synchronization key (status 9)
- There was an error from which we cloud not recover by resyncing the account. Please disable the account and try again. (Error: resync loop)

Also in the event log you can find a lot of forced folder resync messages.

## Steps to reproduce

1. Set up TbSync on one machine and select some resources for syncing.
2. Set up TbSync on another machine (not sure if the OS really matters in this case, but in my case I have to deal with three different machines and three different OSs) and select the same resources for syncing
3. Perform some changes to the resources (add calendar entry or dismiss calendar notifications).
4. Switch back to the first machine
5. If the resources are still there trigger syncs and you should see the resources disappear until all are gone

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
What server are you syncing with? 

Please make sure all your clients use the same TbSync version. Also make sure that none of your clients use a copied Thunderbird profile from one of your other clients, because each client must generate a unique Device ID (happens when a new account is created) which you bypass if you reuse a profile where the account has already been created, thus two clients using the same Device ID.

If none of the above applies, please update all your clients to the latest Beta of TbSync, where something related was fixed.

https://tbsync.jobisoft.de

Also please enable debug logging (TbSync Manager -> Help) to the highest level, so we have some details of what is happening next time the issue occurs. Debug log is cleared upon TB restart, so do NOT restart after it happens again, but send me a bug report (TbSync Manager -> Help)

**Comment by dusares** [comment]
The server is the outlook.office365.com, but I copied the profiles. I am just not sure if I did that before or after created the TbSync accounts.

And just to understand the problem better. Are you saying, that removing and adding the account would solve the issue, as a new device ID is created? Or is the device ID based on the profile and no matter what I do there the device ID will be the same? And lastly, can I manually change the device ID after account createion?

**Comment by jobisoft** [comment]
Deleting the account and creating it anew will fix the issue. You can check the device ID used in the settings tab:

![image](https://user-images.githubusercontent.com/5830621/74174707-b82a1f00-4c34-11ea-85b0-632d73099333.png)

It is the number starting with MZTB.

**Comment by jobisoft** [comment]
Is your issue solved? Can we close this?

**Comment by dusares** [comment]
Sorry for the delay. I had to make sure I really had re-created the accounts on all machines. And I can confirm it is working now. Thanks!
