### ISSUE TITLE
 Email address autocomplete suggestions have inconsistent ordering

### ISSUE THREAD

**Issue by conoroneill** [jobisoft/TbSync#363]
## Your environment

TbSync version: Latest Beta as of 15th Feb 2020
Thunderbird version: 68.4.1 (64-bit) (On Linux, Ubuntu)

[Tick ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
If I have multiple people in my address book called Dave, it should show these in some well-defined order.
I would prefer if it showed the entries which had been used most recently at the top, because this would normally a useful suggestion.
At the very least, given the same words typed into the 'To:' field, it should not randomise the list each time.

## Actual behavior
Thunderbird offers a set of matching names from the address book.
However, it seems to offer these in an inconsistent order; I don't get the same ordering each time I start a new email. This is awkward when the word(s) which I type match many entries from the address book.

I think that this is a regression; this used to work properly in the past, but perhaps not for the last few months. (i.e. it changed sometime in the autumn of 2019)

## Steps to reproduce
I type a name in the 'To' line within the message compose window.
Thunderbird offers a set of matching names from the address book.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

John, I initially raised this as a general Thunderbird bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1613243
However, it seems that this only happens when using a TbSync address book.
Therefore, I have raised this here. I apologise if this is not the correct location; if so I'll move it or raise it again elsewhere.

**Comment by jobisoft** [comment]
I would need some screenshots, to see the different sort order.

**Comment by conoroneill** [comment]
Thanks. I've sent you some screenshots via private email.

**Comment by jobisoft** [comment]
Are they all from the same tbsync address book, or do you have multiple tbsync address books and the results could be just swapped by the different address books?

**Comment by conoroneill** [comment]
I just have a single TbSync address book; it currently has something like 850 entries.

**Comment by conoroneill** [comment]
Hello @jobisoft . Is there any progress on this?

**Comment by Oxalin** [comment]
Related to https://github.com/jobisoft/TbSync/issues/363 ?

**Comment by jobisoft** [comment]
I have removed my own autocomplete implementation in TB102 and reverted to Thunderbird default. This should be fixed. If not, it is a bug in TB itself.
