### ISSUE TITLE
Manage Google Calendars shared with me

### ISSUE THREAD

**Issue by franz-xaver-hallhuber** [jobisoft/TbSync#364]
## Your environment

TbSync version:
Thunderbird version: 68.4.2

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I see all calendars that have been shared with me.
...

## Actual behavior
I only see calendars i own.
...

## Steps to reproduce
Add your Google Account via New Account > CalDAV & CardDAV and sync it.
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

The address https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F does not work.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/issues/169
