### ISSUE TITLE
Feature Request: Support for Office365 calendars without using ActiveSync

### ISSUE THREAD

**Issue by AndrewElz** [jobisoft/TbSync#365]
## Your environment

TbSync version: 1.7.02
Thunderbird version: 60.9.1

[x ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

My company blocks ActiveSync from TBsync, however the method used by the ExchangeCalendar  plug in works.
Unfortunately ExhangeCalendar updates are few and far between and it seems that it may never support the later Thunderbird releases.
Would it be possible to provide a plug in for TBsync which uses the same methodology for syncing calendars as that used by ExchangeCalendar.

**Comment by jobisoft** [comment]
ExchangeCalendar uses Exchange WebServices (EWS) which is a different protocoll than EAS. 
Try the owl addon, which supports EWS. I think tehy support calendar now.

Currently I do not plan to implement EWS on my own.
