### ISSUE TITLE
Suddenly the TB sync with Google has stopped working.  I get an "OAuth 2.0 server returned" message.  Does anybody know what the problem may be?

### ISSUE THREAD

**Issue by V-Man101** [jobisoft/TbSync#366]
## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please provide screenshoots and detailed error messages and if possible a debug log (you can activate that under Help in the TbSync Manager)
