### ISSUE TITLE
TbSync picks the wrong Outgoing SMTP server

### ISSUE THREAD

**Issue by bmarinov** [jobisoft/TbSync#372]
## Your environment

TbSync version: 2.11
Thunderbird version: 68.6.0 (latest as time of writing)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Hard to reproduce without spamming my colleagues.

## Expected behavior
TbSync uses the correct outgoing SMTP server for each configured account. For example by matching the recepient / TbSync username with the STMP server username. Actually this should be explicitly configurable.

## Actual behavior
TbSync sent a meeting confirmation via an unrelated (and non-default) SMTP server used for a different account.

## Steps to reproduce

- Set up TbSync for Office365 using IMAP + Outgoing SMTP for **foo@company.com** (office 365).
- Add and remove the "Outgoing SMTP" server a couple of times while debugging connection problems (hard to tell what caused it). This might have caused the configuration issue.
- All works fine.
- Now add configuration for a second Email account with its own outgoing SMTP server that goes against a different (private) domain e.g. **user@privatedomain.com**
- Receive invitation on foo@company.com and accept it. 
- TbSync sends the RSVP / confirmation via user@privatedomain.com even though the receiver does not match the outgoing server username (amongst others).
- Blocking the SMTP server for **user@privatedomain.com** results in a timeout, TbSync refuses to use the other Outgoing SMTP server.

Removing and adding the TbSync configuration entry seems to have fixed the problem for now. It is hard to test as it involves me responding to company invitations with RSVP's from my private account.

**Comment by jobisoft** [comment]
Try changing the associated email account in the calendar setting in lightning. TbSync is not engaging any SMTP connection on its own, that is done by Lightning. Be warned, that TbSync/EAS does not have a good invitation/meeting support as it is written for home users, not business. You want to use the OWL add-on probably.

**Comment by jobisoft** [comment]
Status?

**Comment by jgato** [comment]
Hi @jobisoft , what did you mean by using OWL add-on ? do you mean instead of tb-sync? I have a lot of issues with invitations using tbsync+Exchange Activesync

**Comment by jobisoft** [comment]
Yeah, I cannot provide professional support. If you need professional software, I think you should try out the owl add-on.
