### ISSUE TITLE
Compatibility with TB74+

### ISSUE THREAD

**Issue by paulkudla** [jobisoft/TbSync#373]
## Your environment

TbSync version: Beta (latest)
Thunderbird version: Daily Beta X64 - 76.0a1

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
pull down menus to configure

## Actual behavior
pull down menus missing from tools menu

## Steps to reproduce
basic first time install, all three plugins are installed ?

Can not access tb account sync manager as per above

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Not yet compatible. I will release a version for TB78 (next ESR) but I will probably skip all betas.
