### ISSUE TITLE
O365: Editing event works, creating new one fails (status 6)

### ISSUE THREAD

**Issue by Paule2020** [jobisoft/TbSync#376]
## Your environment

TbSync version:2.11
Provider für Exchange ActiveSyn: 1.13
Thunderbird version: 68.6.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

Hello,
I'm trying to sync my O365 calender with Thunderbird. Unfortuntely it is ony possible to edit an existing event. Creating a new one fails with the error: "EAS recjects 1 event - status 6"
As editing works, I'm quite sure that I've got the right permissions set.
Error-Help-Text: https://github.com/jobisoft/EAS-4-TbSync/wiki/Error:-Bad-item-skipped
Andy ideas?
Best regards,
Paul

**Comment by jobisoft** [comment]
Please enable debug logging (at help in the tbsync account manager) to the highest level, restart TB, and sync again (so the error is logged) and send me a bug report (again under help).

**Comment by jobisoft** [comment]
Thanks for the report. Nothing obvious however. Could you switch to the beta release channel of TbSync? There was a change which might affect your issue:
https://tbsync.jobisoft.de

**Comment by Paule2020** [comment]
Hi,
using the beta solves the issue- thanks a lot
