### ISSUE TITLE
Yandex support CardDav/CalDav

### ISSUE THREAD

**Issue by AlexTalker** [jobisoft/TbSync#377]
## Your environment

TbSync version: 2.11
Thunderbird version: 68.6.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Synchronization of address book works.

## Actual behavior
```status.could-not-get-stable-tag```

## Steps to reproduce
After successful setup, when the book is checked out and button "Sync now" pressed,
in a while I get an error shown above.
Instructions for connection setup is here: https://yandex.com/support/mail/web/abook.html#sync-carddav
Look into Android section.

I have debug logs, so I can send them over if needed to.

Also, Yandex support feature of "App password" meaning that for separated services(contacts or calendar for example) user can use automatically generated password. Since there's just one field for password in the setup menu, I suggest to add more customization. Since I checked the contacts only, I used only the password which were generated for this service.

**Comment by jobisoft** [comment]
I think, that is a violation of the CardDAV protocoll. I will look up the RFC later.
They send a different CATG on consecutive requests, even though the data did not change. I cannot fix that.

**Comment by AlexTalker** [comment]
If it is so, could you contact the support then?
i bet you have more deep understanding of what CardDAV is than me,
so your problem description would be more useful likely.

**Comment by jobisoft** [comment]
I will check if my understanding of the protocoll maybe wrong and try to fix it on my side. 

I probably will not have the time to contact your provider. If I am not able to fix this (I will report here), I suggest you get in contact with your provider and link to this issue. Maybe they respond here.

You can of course do that now already.

**Comment by jobisoft** [comment]
I cannot fix that.

**Comment by polinom11** [comment]
It is unfortunate that there is no way to correct this error (
