### ISSUE TITLE
Shows "Organization" in the Name column

### ISSUE THREAD

**Issue by ihackurmind** [jobisoft/TbSync#378]
## Your environment
W10 64x
TbSync version: 2.11
Thunderbird version: 68.6.0 32 bit

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Show "Name" in the Name column.

## Actual behavior
Show "Organization" in the name column, even if a name is available in the "name" field of the contact card. 

## Steps to reproduce
Followed this guide (https://guide.hosting.aruba.it/email/configurazione-email-pc-dispositivi-mobili/sincronizzare-calendario-e-rubrica-su-thunderbird.aspx#), Import contacts from an aruba.it email account, Installed Tbsync and Provider CalDAV e CardDAV. Opened the address book and saw the issue. 
![thunderbird](https://user-images.githubusercontent.com/25226744/78366304-97d96980-75c0-11ea-86b7-e42168c1dd6f.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That is a bug in Thunderbird. If you clear the field "Displayname", it will use the organization, regardless if a name is given or not.
