### ISSUE TITLE
Google: Connection refused - Daily Limit exceeded

### ISSUE THREAD

**Issue by maudel15** [jobisoft/TbSync#381]
## Your environment

TbSync version: 2.11
Thunderbird version: 68.7.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
... Occasionally, especially at night, TbSync stops working. I am receiving a connection failure message (refused) with the Google Dav server. This happens for both accounts posted. After a few hours, without reasonable explanation, the synchronization returns to work. What can I do to fix it?

## Steps to reproduce
...
![Schermata del 2020-04-21 06-36-01](https://user-images.githubusercontent.com/39669980/79846957-5d910a00-83bf-11ea-8b98-12214717404b.png)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
We arecurrently running into a Request Limit imposed by google. TbSync has too many users. There is a patch in the making, that will allow expert users to create their own "app" and not use the default app TbSync is using to interact with google.

https://github.com/jobisoft/DAV-4-TbSync/pull/211

I am also trying to get the limit raised. But I will not pay google, as this is a free service.

**Comment by maudel15** [comment]
Thank you. I would gladly move contacts and calendars to another provider but it does not seem to me that at the moment there are any that offer the same widespread integration. Hopefully the problem will be solved.

**Comment by jobisoft** [comment]
Google sucks and "integration" depends on which device you are on. Android is the ONLY mobile device, which has no CalDAV/CardDAV integration (for obvious reasons of course). I can suggest any of the build in providers in TbSync. For Android you need caldav and carddav apps, but then it is integrated pretty good.

**Comment by maudel15** [comment]
It's true. As for the cloud, I moved it to Megasync and I am very happy. However, Megasync does not offer the services in question. Tutanota has a proprietary platform ... Any advice on choosing between the services provided in TbSync?

**Comment by jobisoft** [comment]
fruux.com

They are the one behind the caldav/carddav protocol and have a free starter account.

**Comment by maudel15** [comment]
Thank you very much. I immediately try to transfer

**Comment by jobisoft** [comment]
The next version (currently in beta) will reduce requests to google to once per hour, so it should not happen so often (I hope).

**Comment by maudel15** [comment]
Thanks a lot, even though I'm moving on to using Fruux. Decision following your advice and also the surprise that yesterday, when sending an email to a mailing list, I saw myself refusing to forward. It seems in fact, reading in the forums, that even outgoing mail is likely to be considered by Google as spam ... :(

**Comment by jobisoft** [comment]
All fine. Just wanted to add this info as others who may find this issue, get info on why this happens and what I plan for mitigation.

**Comment by maudel15** [comment]
Hello. I wanted to inform you about a problem. While using Fruux with satisfaction at the moment, I had considered that, having a personal domain and associated email addresses, it would have been appropriate to use carddav from that source. My domain's webmail uses RoundCube and address book and calendar can be imported to my provider's carddav server. I then proceeded to configure with this criterion. I then configured TbSync without problems but, unfortunately, the result is not what I expected. As you can see from the attached screenshots, while Fruux consistently synchronizes all the data, my domain server synchronizes only one item per item in the records.
Sigh. Not even my provider's assistance has been able to resolve for now. I send only for information.
Good evening.
![Schermata del 2020-04-24 15-15-38](https://user-images.githubusercontent.com/39669980/80225708-b543a580-864b-11ea-9604-0e4667660de5.png)
![Schermata del 2020-04-24 15-16-02](https://user-images.githubusercontent.com/39669980/80225718-b70d6900-864b-11ea-97ba-ca9871144577.png)

**Comment by jobisoft** [comment]
You are referring to multiple phone numbers not being there? Can you check, that the import actually got them into roundcube? Do you see the full contact information in roundcube?

**Comment by maudel15** [comment]
Multiple numbers and multiple email addresses.
From the Roundcube web interface I see the correct data both in the default and in the carddav address book.
In Thunderbird, if I sync, I receive partial data.

**Comment by jobisoft** [comment]
Then please do the following:
* activate debug logging in TbSync Manager -> Help (highest level)
* disable the roundcube account in TbSync
* restart Thunderbird
* enable your roundcube account and syncö

**Comment by jobisoft** [comment]
Updated my last comment, send too early...

**Comment by maudel15** [comment]
synchronization remains partial
![Schermata del 2020-04-24 17-18-03](https://user-images.githubusercontent.com/39669980/80228898-f1790500-864f-11ea-8bbe-4cb568c7c525.png)
![Schermata del 2020-04-24 17-19-01](https://user-images.githubusercontent.com/39669980/80228900-f2aa3200-864f-11ea-8298-6bc9cc1e4b54.png)
![Schermata del 2020-04-24 17-19-25](https://user-images.githubusercontent.com/39669980/80228902-f342c880-864f-11ea-8fdf-0aeccad25877.png)
[debug.log](https://github.com/jobisoft/TbSync/files/4529824/debug.log)

**Comment by jobisoft** [comment]
Please delete your last comment and do not post debug logs here

**Comment by jobisoft** [comment]
You need to check that with your provider. The server is sending only one information:

```
BEGIN:VCARD&#13;
VERSION:3.0&#13;
UID:A6E8491F-C5DC-40C9-AB86-8FBF502DB357&#13;
FN:Alberta Iannuzzi&#13;
BDAY:1978-12-18&#13;
PHOTO;ENCODING=<removed photo binary data>;
LABEL;TYPE=HOME:374 Via Guglielmo Quattrucci\nRocca di Papa\, RM 00040&#13;
EMAIL;TYPE=INTERNET:alberta_iannuzzi@yahoo.it&#13;
TEL;TYPE=HOME,VOICE:+39 06 941 0772&#13;
N:Iannuzzi;Alberta;;;&#13;
ADR;TYPE=HOME:;;374 Via Guglielmo Quattrucci;Rocca di Papa;RM;00040;Italy&#13;
END:VCARD&#13;
```

**Comment by maudel15** [comment]
Thank you even if I fear that the provider's interest in solving the problem will be low. Bad that goes I will continue with Fruux. I'll update you on the subject. Thanks for now.

**Comment by maudel15** [comment]
Hello,
I am referring to ticket # 381 in which you replied to me following the debug.log I sent, that the problem was with the provider's server. However, if I sync my phone using Davx5, the records are structured and complete. Is it a Thunderbird problem?

**Comment by jobisoft** [comment]
Ah, ok. Nothing I can add however. I do standard requests and your server is not sending everything. Maybe your other app is using a different technique, I do not know. All other server respond correctly. The log contains all the information the server admin needs to have to be able to analyze the issue. Nothing I can do at the moment.

**Comment by maudel15** [comment]
Ok. In any case, I interested my provider to contact the cPanel managers to check the situation. If I have news, I'll update you. Good evening.

**Comment by jobisoft** [comment]
I appreciate your efforts. Thanks!
