### ISSUE TITLE
Ticket #381

### ISSUE THREAD

**Issue by maudel15** [jobisoft/TbSync#386]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.7

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

Good morning,
I had contacted you about the problem of partial synchronization of my address book with ticket # 381.
As recommended by you, I interested my provider to check for any problems on his CardDAV server.
In truth, however, yesterday I installed app Davx5 on the smartphone and attempted synchronization on the phone and the data is synchronized correctly.
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Can you add this to the issue you are referring too? Issue #381 is the google issue. I have no idea what you mean.
