### ISSUE TITLE
add If-None-Match

### ISSUE THREAD

**Issue by jotisk** [jobisoft/TbSync#388]
## Your environment

TbSync version: 2.12 beta
Thunderbird version: 68.8.0

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync carddav on zimbra server
...

## Actual behavior
zimbra server returns 409 because If-None-Match header is missing (even it is not mandatory in RFC)
...

## Steps to reproduce
put contact to zimbra server
...

Is possible to add If-None-Match header for contact create requests? Zimbra server requires it in older version (8.0.6 and I dont have possibility to update server at moment) . Thank you.

**Comment by jobisoft** [comment]
Can you contribute a patch?

**Comment by jotisk** [comment]
I will try to.

**Comment by jotisk** [comment]
unfortuantely I'm unable to patch it, When I modified DAV-4-TBSync file sync.js , line 862  then TBsync reports that DAV4TBsync is not installed.  Anyway change would be : 
`let headers = {"Content-Type": "text/vcard; charset=utf-8, If-None-Match": vcard.etag};`

**Comment by jotisk** [comment]
header is required for both, updated and new items.

**Comment by jobisoft** [comment]
Shifted to TB78

**Comment by jobisoft** [comment]
Switching to native CardDAV sync and removing my own sync code.
