### ISSUE TITLE
Thunderbird 68

### ISSUE THREAD

**Issue by Salamandar** [jobisoft/TbSync#389]
The TBSync preferences just don't show in Tools -> Modules preferences. There already is Enigmail here.
I tried installing TBSync in a brand new profile, same : Enigmail's preferences are visible, not TBSync.

I'm using TB68.8.0 on Manjaro.

**Comment by jobisoft** [comment]
There are 3 options to open the tbsync settings window:
https://github.com/jobisoft/TbSync/wiki/How-to-get-started#1-open-tbsync-account-manager

One should work at least.

**Comment by Salamandar** [comment]
I don't know if it was a TBSync bug or a thunderbird bug, but it's now showing in the menu. closing.
