### ISSUE TITLE
TbSync & Its Partner Addons - No  Access to iCloud/iPhone Birthday Calendar Subscription

### ISSUE THREAD

**Issue by rmc-va** [jobisoft/TbSync#390]
My Environment:
TbSync version: 2.12
Provider for CalDAV & CardDAV version: 1.12
Provider for Exchange ActiveSync version: 1.14
Thunderbird / Lightning version: 68.8.0
Windows version: 7 Home Premium

I want to thank John Bieling for creating TbSync and it associated Partner Add-Ons.   This wonderful collection of software is the best in code quality, scope of functionality and end-user documentation that I have seen in my 40+ years as an IT professional.  Your software has allowed me to get closer to my objective of a seamless and bi-directional integration of the calendars residing on my iPhone and Windows PC.

There is one calendar on my iPhone that I have been unable to access within Thunderbird & Lightning + Add-Ons.   That calendar is the birthday calendar that Apple software creates when you add a person's birth date in their contact entry.  After adding iCloud for Windows software to my PC, the associated Calendar App shows two calendars called Home and Work plus a subscription called Birthdays.  The Birthdays subscription are the only entries in my iCloud calendar.  I was hoping that these entries would appear in Thunderbird after I installed and configured TbSync and the Provider for CalDAV & CardDAV Add-ons.  Four iCloud resources were listed that can be sync'd with Thunderbird - Contacts, Home, Reminders and Work.  Birthdays calendar was not listed.  Is there something else that I need to do that would enable access to this calendar?   Any help would be greatly appreciated.

**Comment by jobisoft** [comment]
Due to the current pandemic situation my time for this is greatly reduced. Hope it will get better second half of June.

**Comment by rmc-va** [comment]
Thank you for replying.   Hope you, your family and friends can stay safe and healthy.

**Comment by jobisoft** [comment]
Coming back to this, if the calendar is not advertised over the caldav protocoll, tbsync cannot see it. I do not see that calendar with my own icloud account. So that is a no-show. Since the last iOS update the reminders also do not fully work anymore. Apple is moving away from standards, sadly.

You can try out the addon ThunderBirthDay (https://github.com/ingomueller-net/ThunderBirthDay/pull/11#issuecomment-529615343) which regenerates those entries from your Thunderbird addressbook.
