### ISSUE TITLE
Google contacts tags (groups?) and TB address book lists?

### ISSUE THREAD

**Issue by mlaverdiere** [jobisoft/TbSync#393]
Hi, 

Everything is working fine with syncing my Google calendars and address book with TbSync + CalDAV extension (on Linux/Ubuntu and Windows 10 machines), except for one thing: Google Contacts tags.

In the TbSync options/parameters for my Google account, I have activated the checkbox for syncing groups/lists, but without results...

Am I missing something?

Thanks for this extension!

**Comment by jobisoft** [comment]
https://github.com/jobisoft/CategoryManager/issues/38

not supported by google (they block it)
