### ISSUE TITLE
Zimbra's shared calendars events displayed with same color

### ISSUE THREAD

**Issue by bastien30** [jobisoft/TbSync#394]
After adding a shared calendar into Zimbra Webmail, the events from this calendar are displayed into the calendar synced by TBSync on Thunderbird, but with same color and in same calendar.

When adding the ActiveSync account into my Android phone (Samsung S10e), the Android calendar app show the events from the shared calendar with another color (i.e. another calendar). It's the same on Outlook.
So I think it is possible to differenciate the events/calendars.

Let me know if you need more details.
I can provide you Zimbra accounts and calendar for testing if needed.

## Your environment

TbSync version: 2.12 with EAS provider 1.14
Thunderbird version: 68.9.0
Zimbra OSE: 8.8.15

I haven't tested with beta version because it seems that it's the same version number that the stable (but I can test if needed).

## Expected behavior
The events from the shared calendar should be a different color.

## Actual behavior
The events from the shared calendar are the same color.

**Comment by jobisoft** [comment]
Active Sync (EAS) has no native support for shared resources. What your server probably does is to add the shared elements into your own calender while sending it out via EAS.

Your Andoid is probably connecting to your server using EWS (Exchange WebServices), which supports shared resources.

**Comment by bastien30** [comment]
Hello and thanks for your answer.

We are using Z-Push to provides ActiveSync. It does not support EWS, only EAS.

Both Outlook and Android display the shared calendar beside the normal calendar.
TbSync display the events of the shared calendar, but in the same calendar.

So the only thing it miss is the differenciation between the events/calendars... maybe based on the events author ?

**Comment by jobisoft** [comment]
If that is truly the case, than I would need a full log from an initial sync. Please follow the instructions below. The order of the given tasks matters!

* enable debug logging in TbSync AccountManager -> Help
* disable your zimbra account in tbsync
* restart thunderbird (each restart resets the log)
* enable your zimbra account, activate the two calendars in question and sync
* create a bug report in TbSync AccountManager -> Help

**Comment by jobisoft** [comment]
Imprtant, while activating debug logging, set the log level to the highest level!

**Comment by bastien30** [comment]
Thanks for your answer.
I've just performed the requested actions.
I've set the github issue number in the subject.

**Comment by bastien30** [comment]
The events from the shared calendar are named "TEST depuis test" (today) and TEST2 (tomorow).
