### ISSUE TITLE
TBsync with collected addresses

### ISSUE THREAD

**Issue by swaasje** [jobisoft/TbSync#395]
## Your environment

TbSync version:
Thunderbird version: 68.9.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing between Google contact and TB collected addresses

## Actual behavior
No collected addresses appar in Google contact

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
No time for oneline issues.
