### ISSUE TITLE
Only Inbox is synchronized with Office365, not other folders

### ISSUE THREAD

**Issue by Valeryan24** [jobisoft/TbSync#397]
## Your environment : Ubuntu Linux 20.04
TbSync version : 2.12
Thunderbird version : 68.8.0

Hi, thanks for your work. I'm not sure if I've to post here or in EAS-4-TbSync issues :

My company uses Office365 and Outlook on Windows 10, with its own domain, and I want to get a copy of the mails on my home computer ( which runs on Ubuntu) to get them on evening and week-end.

## Expected behavior
I should have in Thunderbird an exact replication of Outlook box, with all emails and (sub)-folders.

## Actual behavior
Contacts and calendar synchronizations are working, I get all events and relations. But mail is only half successful :
I well have in Thunderbird my Office365 Inbox with all the emails, and it synchronizes well with Outlook : new mails are received, if I read one of them on Outlook or Android it quick appears as read also on Thunderbird, the same if I read it first on Linux, and deletion works, too.

But I don't have all the Inbox subfolders nor the "Sent" folder that are present on Outlook and Android. If I move a mail from Inbox to a subfolder in Outlook, it well disappears from Inbox in Thunderbird, but I don't see the subfolder...

This is not a critical issue, as the most important works fine (receiving new mails when not connected to Windows / Android), but I'd like to get all if it's possible.

Last, I can't send an email with my Office365 address and smtp, it fails.

Thanks in advance for your help !

**Comment by jobisoft** [comment]
My addon is not doing email.

You need to setup an IMAP/SMTP connection (where you can subscribe to differnt folders as well) or - if your company is blocking IMAP/SMTP - you need to use the owl addon to get your emails (owl is using the EWS and the OWA protocoll)
