### ISSUE TITLE
Thunderbird hung in loop for calendar sync after initial sync

### ISSUE THREAD

**Issue by frankgould** [jobisoft/TbSync#398]
## Your environment
RPi4B:4GB, Arch Linux ARM 4.19
TbSync version: 2.12
Thunderbird version: 68.9.0

[ ] Yes, I have installed the latest available beta version from https://tbsync.jobisoft.de and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After syncing my iCloud calendar with TbSync, Thunderbird initially worked on my ALARM system. But after restarting Thunderbird, it gets hung in a loop apparently doing calendar operations as can be seen in the attached CPU utilization graphic and Thunderbird locks up for close to a minute, does one operation, and gets hung in the loop until another minute passes. I can restart Thunderbird in safe mode allowing me to use email; otherwise, Thunderbird is unusable due to this degradated performance.
![CPU-utilization](https://user-images.githubusercontent.com/11017534/84684978-758c9200-af07-11ea-839e-ca5bc559f6df.png)
I'm not sure if the "size" of my calendar makes any difference but it starts in 1992. That alone took a few hours to digest during synchronization and as I said worked great until I restarted Thunderbird.

Also, to get the TbSync debug logging to work, I have to disconnect from the internet so that Thunderbird doesn't start this calendar loop degradation. Then I go back into Safe Mode where I can use email again.
## Actual behavior
Thunderbird degradated to one minute user input and operations for less than a second.

## Steps to reproduce
Disable Safe Mode.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email). Done 15 June 2020 3PM.

**Comment by jobisoft** [comment]
To find the cause of this, just disable/remove TbSync in safe mode. What happens if you restart in normal mode?

Background: Calendar Syncing is done by Lightning, TbSnyc is just setting up the icloud calendars in lightning, but the actual sync is done by lightning. This is different for contact sync, where TbSync is doing everything.

So if the issue goes away after you disabled tbsync, i am to blame, if it stays, lightning is to blame.

**Comment by frankgould** [comment]
Thanks jobisoft for the quick response. I tried your suggestion and you're right, it's still locked up syncing. I submitted the following bug, in link below, based on this. Same problem happened before I tried TbSync which was why I was trying to see if TbSync would fix the Lightning problem.

https://bugzilla.mozilla.org/show_bug.cgi?id=1645884
