### ISSUE TITLE
Can't dismiss out of date calendar reminders

### ISSUE THREAD

**Issue by shibacomputer** [jobisoft/TbSync#399]
## Your environment
Windows 10 Pro
TbSync version: Beta channel 
Thunderbird version: 68.9.0

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
- Events in the past shouldn't display as calendar reminders
- These event reminders should dismiss when you click "Dismiss" or "Dismiss all"

## Actual behavior
- A collection of past events display in Thunderbird's calendar reminder dialog
- Clicking "dismiss" or "dismiss all" has no observable behaviour (and does not generate debug information) 

## Steps to reproduce
- Create G-Suite account with TBsync
- Click all calendars to enable them, then click "sync now"
- Receive a collection of random past events in the Thunderbird reminders window.
- Attempt to dismiss, nothing happens.
- Close window with X, and await the same collection arriving the next time the sync occurs.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jasonblewis** [comment]
I tried to generate a debug log but it comes out as 0 bytes in size. Any idea how to get a debug log?

**Comment by kienli** [comment]
Same here with

Windows 10 Pro
TbSync version: Beta channel
Thunderbird version: 78.2.2

[debug.log](https://github.com/jobisoft/TbSync/files/5216464/debug.log)

**Comment by lorenzk1** [comment]
Agree to kienli and shibacomputer.

Windows 10 Pro
TbSync version: Beta from 16/09/2020
Thunderbird version: 78.2.2
Google Calender and Google Contacts

"Dismiss" seems to work with single dates, not with repeated dates.
Nothing unusual in debug.log. (No upload, because this will be deleted by GitHub)

Edit window for addresses look ok now. Last Names show up in suffix-field instead of name-field.

**Comment by Oxalin** [comment]
Just discovered TbSync a few days ago. I'm in the same boat though with some recurring events that are not being properly dismissed.

Windows 10 Pro 2020
TB 78.3.1
TbSync 2.16
CalDAV and CardDAV extension 1.19

And while I'm not 100% sure, I think that dismissing these problematic events could be related to the fact that I was unable to completely display some calendars at first: I'm using TbSync for work and, for some reason, I had to restart Thunderbird a few times so it could display all the calendars properly. The calendars were said to be synced correctly, but they were not being displayed. And I think it could be related to the fact I was dismissing some events at the same time. I could test it again on another computer or system.

**Comment by Oxalin** [comment]
Well, I would have been surprised of the contrary, but just in case I tested it: the same happens under Linux (using Arch).

**Comment by Oxalin** [comment]
I could provide some debug info from TB's debug console. From what I see, the snooze/dismiss command is sent and received, but when the updated event is sent back, TB sees no modification.

**Comment by Oxalin** [comment]
Also, from what I've seen so far, this bug only affects recurring events. Is it the same for others. This bug and https://github.com/jobisoft/TbSync/issues/436 seem related.

**Comment by lorenzk1** [comment]
Thunderbird 78.3.3
Newest Beta from Oct 16

Sorry to say: Problem dismissing recurring events still exists. No change in behavior.

**Comment by cweiske** [comment]
Thunderbird itself has a similar bug that may be related: https://bugzilla.mozilla.org/show_bug.cgi?id=948507

**Comment by jobisoft** [comment]
I no longer support Google.
