### ISSUE TITLE
TbSync Credential Request Could not authenticate (HTTP Error 401)

### ISSUE THREAD

**Issue by braven1612** [jobisoft/TbSync#401]
## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...

## Actual behavior
...this has been working for a year.  It just won't accept my password as authentic.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by braven1612** [comment]
Sorry needed to say this has been working for a year. Once it did it before and I don't remember how I solved it. It just won't accept my password as authentic.

**Comment by jobisoft** [comment]
Which provider?

**Comment by jobisoft** [comment]
Ah, EAS. I had a simmilar issue with some other user. Try to remove your account in Tbync Manager and re-add it again. (Not just disable but fully remove)

**Comment by braven1612** [comment]
Thank you so much for your help! If I remove my account in Tbsync, it won't remove my email account, will it? sorry for the stupid question...

**Comment by jobisoft** [comment]
no it will not remove our emails. that is independent

**Comment by braven1612** [comment]
THANK YOU! It took several combinations to get TbSync Account added again but finally it is all synced.
can't thank you enough.

**Comment by jobisoft** [comment]
Feel free to support me with a donation.

[![](https://www.paypalobjects.com/en_US/DK/i/btn/btn_donateCC_LG.gif)](https://www.paypal.me/johnbieling)
