### ISSUE TITLE
Request for Google Contacts Group...

### ISSUE THREAD

**Issue by Maikhi** [jobisoft/TbSync#403]
## Windows 10

TbSync version: 2.12
Thunderbird version: 68.10

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

It would be fine to also synchronize the Google Contacts Groups (it's Etichetta (=Label) in Italian).
Imho, that address-book may have the largest use in the world because of Android!

**Comment by jobisoft** [comment]
Google did not implement the full CardDAV API and does not expose its groups via CardDAV. I reached out to them. They do not care. Dead end. Switch to a real CardDAV provider.

**Comment by entodoays** [comment]
There is a chrome extension called Contacts Editor that shows Google Contacts in spreadsheet form and there's a column labelled "Groups" that contains a comma separated list of the labels of the contact. Maybe even though the CardDav API in not fully implemented in Google Contacts, but it would be very useful to be able to sync lists from the most popular email provider on the planet.

**Comment by jobisoft** [comment]
Throw your money/support at
https://github.com/jdgeenen/gcontactsync/issues/163#issuecomment-755041995

who is creating a dedicated google provider for tbsync.

I will not do anything in that direction.
