### ISSUE TITLE
Getting link to "Microsoft Outlook Web Access" instead of invite

### ISSUE THREAD

**Issue by digulla** [jobisoft/TbSync#404]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.8.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

I'm using Office 365 which was set up by my company.

Since a few days, I'm no longer getting invite mails. Instead, invitations looks like this:

> Microsoft Outlook Web Access: https://outlook.office365.com/owa/...
> 
> To receive meeting invitations as .iCalendar attachments instead of Outlook Web App links, go to https://outlook.office365.com/owa/.../?path=/options/popandimap and select Send meeting invitations in iCalendar format.

Thunderbird treats that as a normal mail.

Any suggestions how I can fix this?

Would it help to switch to .iCalendar?

**Comment by digulla** [comment]
Has anyone else the same problem?

**Comment by lnxus** [comment]
> Has anyone else the same problem?

same happens to me, were you able to find a solution?

**Comment by jobisoft** [comment]
I have no idea, sorry.
