### ISSUE TITLE
Can not activate remote calendar

### ISSUE THREAD

**Issue by taich001** [jobisoft/TbSync#405]
## Your environment

TbSync version: 2.12
Provider TbSync 1.12
Thunderbird version: 68.10.0

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
calendar sync

## Actual behavior
I can enable connection to my owncloud server and all calendars can be syncronized but then they are deactivated.
I can not activate the calendar and therfore no tasks are shown.
![Picture0001](https://user-images.githubusercontent.com/9916454/86573990-6e402d80-bf75-11ea-821e-84d123c1dbd3.png)

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by taich001** [comment]
I found this error in log:

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: groups in 'addressbooks'</s:message>
</d:error>

**Comment by GUAYMI** [comment]
I have bo idea how this works I onlybsee errors and till now I haven't talked to no-one 🤔😁 please help.

**Comment by PopeRigby** [comment]
I was also having this issue, but then a restart fixed it for me. I'll report back if it happens again.
