### ISSUE TITLE
automatic sync option (feature request)

### ISSUE THREAD

**Issue by jdpipe** [jobisoft/TbSync#407]
## Your environment

TbSync version: 2.12 (with Provider for Exchange ActiveSync 1.14)
Thunderbird version: 68.8.0

## Expected behavior

I installed TbSync and I expected local changes to be synced automatically, as soon as a local or remote change has been made.

The local system knows when changes have been made (as I can see in the TbSync settings dialog), so it should be 'pretty trivial' for the TbSync add-in to initiate a sync whenever a local change has been made, or eg after some short nominal delay, eg of 10 seconds. If this were being done, and assuming TB is the users primary calendar, then this might be enough, and it would be fine to have a much longer sync period, just to allow for remote changes that might have happened, eg via phone or webmail)

Perhaps another option would be for TbSync to synchronise whever Thunderbird is focussed after a period of inactivity, or something like that?

## Actual behavior

The default behaviour is that I must manually request a sync. Or, I can set periodic sync, which seems like it will be inefficient with bandwidth.

May I also suggest that the new user is somehow encouraged to enable automatic (see above) as well as periodic sync when they first install the add-in? Otherwise the behaviour is not what most users would expect. This software only really becomes useful for everyday work, I feel, if automatic sync is enabled. I saw the bug discussion about this, and I understand the 'play it safe' idea, but it is still not what users would expect, I think.

## Steps to reproduce

NA

PS I have tried davmail and OWL, and while both of them work well in certain ways, they both ultimately have annoying bugs that prevent effective day-to-day use. Hoping the TbSync is finally the one!!

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Biblio25** [comment]
Hello,

For my part, I find that it would be practical to be able to indicate, during the configuration of the account, if we want the synchronization to take place when Thunderbird is launched and when closing (two checkboxes, for example ... ).

In addition, yes, the possibility also to force, at any time, the synchronization directly in the contextual menu of the account (right click on the name of the address book and click on "synchronize" ...)

Thanks and congratulations for this excellent plugin which also gives me complete satisfaction!
Regards,

**Comment by jackyohh** [comment]
+1

**Comment by piet8stevens** [comment]
+1
Thank you for TbSync (see donation). Works flawlessly on both my windows and Ubuntu machines. Automatic sync would be great.

**Comment by mconca-kube** [comment]
It would be very nice to have it to automatically push local changes (and then download server changes every x minutes).
Also, I don't know if it is a bug, the Sync button in the Lightning interface does not trigger TbSync sync. It is quite confusing...

**Comment by fonic** [comment]
This can be achieved by applying a simple patch:

```
--- a/content/modules/public.js	2021-04-09 10:56:18.577423576 +0200
+++ b/content/modules/public.js	2021-04-09 10:43:01.921486288 +0200
@@ -401,8 +401,11 @@ var FolderData = class {
       status = TbSync.getString("status." + this.getFolderProperty("status"), this.accountData.getAccountProperty("provider")).split("||")[0];
 
       switch (this.getFolderProperty("status").split(".")[0]) { //the status may have a sub-decleration
-        case "success":
         case "modified":
+          if (!this.isSyncing()) {
+            this.accountData.setAccountProperty("lastsynctime", 0);
+          }
+        case "success":
           try {
             status = status + ": " + this.targetData.targetName;
           } catch (e) {
```

This will trigger/schedule a sync within the next minute (*) after a change occurred if periodic synchronization is enabled (i.e. not set to 0).

(*) see this code part:
https://github.com/jobisoft/TbSync/blob/5d6d032bded1e0e1a0da8dfe1c4631bcfaee7639/content/tbsync.jsm#L136

**Comment by jobisoft** [comment]
Can you turn this into a proper pull request? I will merge that. Thanks!

**Comment by fonic** [comment]
@jobisoft: sure can, I didn't expect anyone would actually be interested ;) I'll create a pull request for this later today.

**Comment by piet8stevens** [comment]
Excellent. I am very happy about this. Of course I am interested. Thank you so much! 

On April 9, 2021 11:28:40 AM GMT+02:00, fonic ***@***.***> wrote:
***@***.***: sure can, I didn't expect anyone would actually be

**Comment by fonic** [comment]
Seems to work quite well, haven't had any issues with it thus far.
