### ISSUE TITLE
"too much recursion"

### ISSUE THREAD

**Issue by Farbmond** [jobisoft/TbSync#413]
## Your environment

TbSync version: 2.15.3
Thunderbird version: 78.0

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I tried to synchronize Google Contacts and Calendar.

## Actual behavior
The sync fail on every time with:
status.[JavaScript Error: "too much recursion" {file: "resource://modules/CalDavCalendar.jsm" line: 124}]' when calling method: [callCalendar::id]

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
[X] Done

**Comment by jobisoft** [comment]
Thanks for reporting. I am working on that.

**Comment by jobisoft** [comment]
Fixed in latest beta? Click on "check for updates" in the add-on manager gear menu to update your betas.

**Comment by Farbmond** [comment]
Yes, it works fine with 2.15.5,
Thank you!
