### ISSUE TITLE
Not working in TB 78.0

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/TbSync#415]
## Your environment

Windows 10 2004

TbSync version:
2.12

Thunderbird version:
78.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I still see the TbSync button at bottom right of main window so I can still open TbSync window

## Actual behavior
No TbSync button  at bottom right of main window, can't find it in any menu so cannot open TbSync Window. It's either not working at all, or it's not displaying any way to access it.

Also, while TbSync and EAS for TbSync show as still being enabled in the Add-ons Manager, DAV for TbSync shows as auto-disabled and is labelled as incompatible with TB 78.0

## Steps to reproduce
...
Update from TB 68.10 to 78.0, start TB.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Cannot access TbSync to do this.

**Comment by jobisoft** [comment]
tbsync.jobisoft.de

**Comment by DavidBE-UK** [comment]
OK, thanks. It's working now. (I've been on the betas for some time, so assumed if there was an update for 78 I'd have got it when I forced extension update checks.)
