### ISSUE TITLE
Cannot configure - add-on options not showing

### ISSUE THREAD

**Issue by quickfold** [jobisoft/TbSync#417]
## Your environment

TbSync version: 2.15.5
Thunderbird version: 78.0.1

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
... Under `Tools` menu, the item `Add-on options` is present below `Add-ons` and I can select it to configure TbSync

## Actual behavior
... Under `Tools` menu, the item `Add-on options` is NOT present so I cannot configure TbSync

## Steps to reproduce
... N/A

> To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
I can't access the Account Manager.

Other info: I have disabled all other add-ons and restarted/rebooted. Win 10. Thanks for your help troubleshooting - I really rely on this extension.

**Comment by jobisoft** [comment]
There is no Add-On options menu in TB78 at the moment. We are lobbying to get it back. There are two other option to open the TbSync Manager:

https://github.com/jobisoft/TbSync/wiki/How-to-get-started#1-open-tbsync-account-manager

**Comment by quickfold** [comment]
Thanks! You may want to remove the numbers from the documentation headlines or reword it. I thought they were 4 steps in setting things up rather than 4 separate options for setup.

**Comment by m2nis** [comment]
Same problem, but worse... :-)

Thunderbird 80.0b4 (64 bits) french
TbSync 2.16

and I don't have any of the three options announced to access TbSync configuration...

If it could, I haven't TbSync before I move from TB68 to TB78/80.
