### ISSUE TITLE
Unable to define and open new calendar

### ISSUE THREAD

**Issue by DPS304** [jobisoft/TbSync#419]
## Your environment

TbSync version: 2.16
Thunderbird version: 78.1.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Gmail calendar shared, but am not able to define and open it in TB.  It can be seen in Google Calendar. 

## Actual behavior
...
![ScrnCapture-error](https://user-images.githubusercontent.com/54893137/89725242-05642f00-d9d3-11ea-9c93-a527d71bbfdb.jpg)

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/DAV-4-TbSync/issues/169

?

**Comment by jobisoft** [comment]
It looks like you are not using the google option to setup your google calendar. `calendar.google.com` is not a CalDAV endpoint.

![grafik](https://user-images.githubusercontent.com/5830621/92993054-55ad4000-f4ef-11ea-8ccd-fc304b60c844.png)
