### ISSUE TITLE
No access to TbSync configuration

### ISSUE THREAD

**Issue by m2nis** [jobisoft/TbSync#421]
Thunderbird 80.0b4 (64 bits) [french]
TbSync 2.16

According to that page
https://github.com/jobisoft/TbSync/wiki/How-to-get-started#1-open-tbsync-account-manager

there are three possibilities to access to TbSync configuration.

Unfortunately, I don't have any of these !

If it could help, I haven't TbSync before I move from TB68 to TB78/80.

And thank you very much for these extensions who works perfectly under Debian/TB68 !

**Comment by gryffyn** [comment]
TbSync doesn't support Thunderbird 80 yet, unfortunately.
