### ISSUE TITLE
TbSync doesn't appear in 78.2.0

### ISSUE THREAD

**Issue by gryffyn** [jobisoft/TbSync#423]
## Your environment

TbSync version: 2.12 (beta)
Thunderbird version: 78.2.0 RC1

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Expected to see the usual ways to configure TbSync.

## Actual behavior
I can't seem to find any of the options to configure TbSync, despite this plugin working correctly on Thunderbird 78.1.1.

## Steps to reproduce
Download 78.2.0-RC1 and attempt to use TbSync

Debug log from TB:
`1598304550854	addons.webextension.tbsync@jobisoft.de	WARN	Loading extension 'tbsync@jobisoft.de': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.`

**Comment by jobisoft** [comment]
cannot confirm

![grafik](https://user-images.githubusercontent.com/5830621/91102630-d5bb5500-e669-11ea-8e65-8cd59e7962e6.png)

**Comment by jobisoft** [comment]
The correct version of TbSync would be 2.16. But if you use the AddonManager to search and install TbSync it will give you the correct one. Did you do a manual file install?

**Comment by gryffyn** [comment]
Yes, I downloaded the beta because I assumed I needed it to use with 78. Downloaded from the Addons, it works great now, thanks
