### ISSUE TITLE
Sync on two devices deactivates ressources when being synced on the other device - after copy of TBSync folder

### ISSUE THREAD

**Issue by gerhardm5** [jobisoft/TbSync#425]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.11 on notebook and desktop

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
both devices should sync without problem. I had to reinstall W10 on both and copied on and the same TBSynch folder on both devices. 

## Actual behavior
Now when I sync on one device on the other device all ressources disappear, probably now on both devices there is the same ActiveSync Geräte ID? I already deinstalled on one device TBSync and reinstalled, but entries was been remembered. How can I fix that?

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
You need to remove the account from the TbSync Manager in one of the installations. The DeviceId is generated when a new account is being created.
