### ISSUE TITLE
Exchange Task not listing

### ISSUE THREAD

**Issue by trajan17** [jobisoft/TbSync#426]
## Your environment

TbSync version: 2.16
Thunderbird version: 78

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Exchange task should display in the Task window

## Actual behavior
Exchange task from Exchange server are not showing in the Task Tab/Window.  Under Tbsync task are sync'd

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Did you enable the task folder for sync in the TbSync Manager? Any errors? Could I have a screenshot of the manager after a completed sync?
