### ISSUE TITLE
Login to Google Calendars Required after every restart

### ISSUE THREAD

**Issue by funkygirlauca** [jobisoft/TbSync#428]
## Your environment

TbSync version: 2.16
Thunderbird version: 78.2.1
Provider for CalDAV & CardDAV version: 1.16

Thanks for the great tools!  I love TB/Lightning and have just switched all my calendars to Google.  Your TBSync tool works great with Lightning.

However, each time I restart my PC, all my Google Calendars that previously appeared in the Calendar Tab are greyed out and none of the events show up in the calendar.

In order to fix this, I need to go to the Synchronization Settings (TBSync) > Synchronization Status, uncheck (and click OK) for each calendar, recheck each calendar, click Syncronize Now, then enter my google login, password and "Allow" for each calendar.  I have eight different calendars so this process quite lengthy.  

I have tried to enter my Google credentials into Synchronization Settings (TBSync) > Account Settings but the Username is greyed out
Each time I enter my Google credentials in the popup box, I check the box "Stay Signed In".  This keeps me signed in as long as the machine is not restarted.  If I do a restart, I have to login to all the calendars again.

I guess I was expecting the calendar(s) to reconnect automatically after a restart.  Is this the intended behaviour?  And if so, can you please help me troubleshoot.

If this isn't the intended behaviour, can this be integrated into TBSync at some point in the future?  And in the mean time, can we get some kind of notification that the calendars are disconnected?  Currently, I just have to realize that all the calendars, events (and most importantly, reminders) are gone.

Finally, my Google credentials are actually the same for all eight calendars, even if this issue can't be fixed, is it possible just to enter my credentials once and then apply them to the other calendars rather than having to enter everything again for each calendar?

Happy to provide you with any other info you need.

**Comment by thomsbe** [comment]
Hello!
I have exactly the same problem. The synchronization always stops after a restart of the PC and maybe even after a restart of Thunderbird.

All data from the calendars disappear, but they are still in the account settings. The debug log of the received data also contains correct names of the calendars and so on. Only all entries are gone.

The data will not come back until you deactivate and reactivate all calendars. For this you have to enter the Google account data for each calendar separately. I use 2FA and that makes it even more complicated.

The easiest way to solve the problem at the moment is to delete the account from TBSync and use the other AddOn for Google Calendars: https://addons.thunderbird.net/de/thunderbird/addon/provider-for-google-calendar/

**Comment by maa23** [comment]
I have exactly the same Problem, after a restart of Thunderbird the calendar entries are gone. 
I use Thunderbird 78.2.2 and TbSync 2.16 with a google calendar. There are no errors or warnings in the debug log.

**Comment by jobisoft** [comment]
Should work in latest beta, that also fixes the Edit dialog.
https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version

**Comment by funkygirlauca** [comment]
Working well so far - thank you!!!

After a Thunderbird restart all the Google Calendars were greyed out.  I installed the beta xpi's and all the calendars were back without needing to login.

THANK YOU!!!!

**Comment by thomsbe** [comment]
I can confirm that. It now works as expected. After restarting Thunderbird and in the settings dialog.

**Comment by funkygirlauca** [comment]
Thank you very much!  It is working well for me too.

Thanks for your hard work!
