### ISSUE TITLE
Install fails on Thunderbird 81.0b2 (32-bit), Windows 10

### ISSUE THREAD

**Issue by JanaJarecki** [jobisoft/TbSync#429]
## Your environment

TbSync version: 2.16
Thunderbird version: 81.0b2 (32-bit)
Windows 10

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
tbsync installs

## Actual behavior
after installation neither the lower sidebar nor the Tools > Add On Option menu shows the tbsync add on.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I updated the max version settings. TbSync only runs in TB78.
