### ISSUE TITLE
TbSync Settings not easily accessible in TB 78.x

### ISSUE THREAD

**Issue by richardleger** [jobisoft/TbSync#430]
This bug was created following:
https://bugzilla.mozilla.org/show_bug.cgi?id=1664014

## Your environment
TbSync version: as per version search and installed via add-ons Manager available in the following TB version on 10th september 2020.
Thunderbird version: TB 78.2.1 (64-bit) 

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
 TbSync settings accessible easilt via UX

## Actual behaviorIn 
After adding the add-on I don't see any way to access the TbSync extension settings... to add a CalDAV account...
- not via the Extension tab three-dot menu next to enable/disable button (see attached) - no "Options" available
- not via Hamberger menu > add-ons (like in previous TB version)
- not via Tools menu
- not via TB Options tab

It seems only accessible by clickng on TbSync text that appears at the bottom righ of TB UX in status bar! Found following suggestion from another user...

## Steps to reproduce
In TB 78.2.1 (64-bit) open Add-ons Manager, search and find/add TBSync and calDAV provider extensions... try access TbSync settings...

**Comment by jobisoft** [comment]
Hi,

TbSync is using a special migration strategy where most of its legacy code is still working in TB78. A downside of this is, that its options does not appear in the usual places:

Not showing up in the "MailExtension" standard locations:
 - not via the Extension tab three-dot menu next to enable/disable button

Not showing up in the "TB68" standard locations:
- not via Hamberger menu > add-ons (not supported in TB78)
- not via Tools -> Add-On Options menu

It never showed up in the TB Options tab. 

However, it does show up in the Tools Menu like it has been in TB68:
![grafik](https://user-images.githubusercontent.com/5830621/92992681-edf5f580-f4ec-11ea-88b8-0224cfbabfd3.png)

I do work on getting all add-ons using this migration strategy to show up in the 3 dot menu. But I have not succeeded so far. I will keep this issue open and report back. It could however end up in a wontfix, if I am not able to get it done. I also work on getting it back into the Tools -> Add-on options menu.

**Comment by richardleger** [comment]
Fyi,

I have TB 78.2.2 installed on my Windows 10 machine with TbSync(2.16)+ CalDav provider(1.16) add-ons added and enabled.

- The Tools menu is not visible by default preventing direct access to TbSync settings - but if I display it manually (right click Tabs bar and select Menu bar) I can still access the "Synchronisation Settings (TbSync)" via this menu...  as suggested in previous comment... not the most evident nor intuitive for access... but it works as a possible alternative quick work around for now :-)
- The Hamburger menu > Tools do not show the "Synchronisation Settings (TbSync)" entry either

![image](https://user-images.githubusercontent.com/6603379/93001658-865d9b80-f528-11ea-9198-25e6db60dca1.png)

**Comment by richardleger** [comment]
The other possible current solution (workaround/quickfix), in case someone else is looking for it, is to click on the TbSync text appearing in the status bar (at the bottom right corner). While is is not very intuitive nor a s standard way of accessing add-on settings in TB, in this particular case of TbSync it is much faster than to use the menu entry and does not require the menu bar to be visible... a nice to keep feature but that shall not be the only way to access TbSync settings long term... hopefully things will work out better in the future :-)

![image](https://user-images.githubusercontent.com/6603379/93001994-3d5b1680-f52b-11ea-9688-93f59f1a4d81.png)

**Comment by richardleger** [comment]
> I do work on getting all add-ons using this migration strategy to show up in the 3 dot menu. But I have not succeeded so far. I will keep this issue open and report back. It could however end up in a wontfix, if I am not able to get it done. I also work on getting it back into the Tools -> Add-on options menu.

My suggestion for all add-ons would be to move the "Options" entry out from the 3-dots menu and put it in another location as a button directly accessible next the the enabled/disabled button like the below mock-up (it shows "Settings" which I understand better but it can be re-labelled as "Options" if more appropriate for TB terminology). After installation of an add-on accessing its settings would likely be the next step of the end-user... so showing directly the button would make it very easy... even to come back to it later as it would have been seen during the install... more directly accessible and more user friendly...

![image](https://user-images.githubusercontent.com/6603379/93002172-bad35680-f52c-11ea-8eb7-5c8538bfdb1c.png)

**Comment by Mer0me** [comment]
> However, it does show up in the Tools Menu like it has been in TB68:

I'm using TB 78.2.2 (32 bits) on Windows 10 and the Tools Menu ("Outils" in french) doesn't show TBSync settings item.
 
![image](https://user-images.githubusercontent.com/6248852/93307407-3836e980-f801-11ea-8133-2cb3e4c7821b.png)

**Comment by Mer0me** [comment]
Ok, nevermind, after uninstalling TBSync Beta Channel and reinstalling regular TBSync, the item is now in the Tools Menu
