### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by jimrome** [jobisoft/TbSync#431]
## Your environment

TbSync version: 2.16
Thunderbird version: 81.0b3 (64-bit)
MacOS Mojave
[ x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de    But that is 2.15.5
and my issue is not yet fixed, I can still reproduce it.
![TBTools](https://user-images.githubusercontent.com/1304327/92954401-639c8b80-f431-11ea-949a-aed9a6a58cf6.png)
TBsync is not on any of my menus or in lower-right corner.

## Expected behavior
Should work

## Actual behavior
See nothing in tools menu or lower-right status

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I adjusted the max version setting. It only works in ESR 78. Sorry.
