### ISSUE TITLE
New calenders in Icloud do not show up at sync

### ISSUE THREAD

**Issue by mackesa** [jobisoft/TbSync#433]
## Your environment

TbSync version: 1.18
Thunderbird version: 7.8.2.2 (32-bit)

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Newly created calender should show up at sync

## Actual behavior
Do not show up, if calender is selected in Icloud events do not show up.

## Steps to reproduce
Create a new group in existing calender
Sync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Unclear, what the issue is, groups or entire calendars? For group support, you must activate group support in the options tab of your tbsync account.
