### ISSUE TITLE
"Could not connect to server (UNKNOWN_NETWORK_ERROR)" with Nextcloud

### ISSUE THREAD

**Issue by PopeRigby** [jobisoft/TbSync#434]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.12.0-1

~~[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.~~
The beta version isn't compatible with my version of Thunderbird

## Expected behavior
TbSync successfully sync calendar and contacts with Nextcloud

## Actual behavior
TbSync gets an unknown network error.

## Steps to reproduce
1. Install TbSync and the CalDAV and CardDAV provider.
2. Setup TbSync with Nextcloud account.
3. Use TbSync successfully for awhile

**Comment by jobisoft** [comment]
Sorry. I cannot support TB68 anymore. Please check with TB78.
