### ISSUE TITLE
When adding event invitees, email addresses on contact not displayed during autocomplete

### ISSUE THREAD

**Issue by brad2014** [jobisoft/TbSync#437]
When typing invitees into a calendar event I am editing, the auto-complete choices are not quite correct, and difficult to decipher.

## Your environment

TbSync version: 2.16
Thunderbird version: 78.2.2 
MacOS: 10.15.6

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Steps to reproduce:
1. I have a contact on a CardDav server, with multiple email addresses (e.g. multiple work addresses).  Here is how it shows up in Thunderbird:

<img width="308" alt="Screen Shot 2020-09-25 at 2 45 32 PM" src="https://user-images.githubusercontent.com/6502462/94268901-2b6f6f80-ff3e-11ea-8414-bff37b3ea019.png">

2.  I edit a calendar invitation to add an invitee by starting typing in the 3rd email address "joe@joeot".

<img width="421" alt="Screen Shot 2020-09-25 at 2 47 29 PM" src="https://user-images.githubusercontent.com/6502462/94269330-d1bb7500-ff3e-11ea-8e1c-aaec2bf74e85.png">

## The issue:
1. The completion address displayed does not correspond to the prefix I typed (`joe@joehome.com` is not a completion of `joe@joeot`)
2. The words "private" and "business" stumped me, they are not consistent with the words used in the TBSync address book UI, "home" and "work". (I understand "private" to be a sharing/permissions quality, not a place associated with an address).
3. The email addresses corresponding to the multiple addresses are not displayed, so I can't see which to pick.

## Expected Behavior
1. If I type the prefix "joe@joeot", the completion should be exactly and only `Joe Blow <joe@joeotherwork.com>`.  I've already indicated by my typing I'm not interested in other non-matching addresses.
2. If my typing matches multiple email addresses (e.g. `Joe` or `joe@`), then the drop down menu should indicate the possible addresses explicitly. The words "private" and "business" by themselves don't tell me what I need to know to make a choice, especially when there are multiple of each.  Each line of the drop-down menu could be the text that would actually be filled in were I to select that item (which would match the style of completion use with local non-tbsync address books). If you felt fancy, you could append the icons you have in the addressbook UI that indicate the type of address.
```
>> Joe Blow <joe@joehome.com> 🏠
>> Joe Blow <joe@joework.com> 🏢
>> Joe Blow <joe@joeotherwork.com> 🏢
>> Joe Doe <joe@joe-doe.com> 🏠
```

**Comment by dilyanpalauzov** [comment]
DAV-4-TBSync only tells Thunderbird the list of calendars and addressbooks offered by your server. 

You shall repeat you observations towards the Thunderbird developers, as they manage the dialog in question.

**Comment by jobisoft** [comment]
Oh no, that is a bug in the autocompele API. I thought I worked arouns that. Dang, something changed again ....

Unrelated: TbSync 2.16 has broken sync and has been withdrawn. Please update.

**Comment by xndr** [comment]
I can confirm a similar issue with Thunderbird 78.5.0. When creating a new event, and adding invitees, only the first 2 invitee fields do a lookup in my TbSync address books, the moment I try to add a third or more invitee, it does not do autocompletion on the contact name anymore. If I manually type-in the full email address, it still does the free/busy lookup, and I am still able to send the meeting request.

**Comment by jobisoft** [comment]
I have removed my own autocomplete implementation and reverted to the standard one.
