### ISSUE TITLE
Bug in cardav

### ISSUE THREAD

**Issue by michelwend** [jobisoft/TbSync#438]
Hello,
The synchronization between cardav and nextcloud is not done
## Your environment windows 10

TbSync version: 2.16
Provider pour CalDAV & CardDAV version: 1.19
Thunderbird version: 78.3.1

The journal log:
```
`Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-privilege-set/><d:resourcetype /><d:displayname /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: groups in 'addressbooks'</s:message>
</d:error>


```

You can see this post for more explainations, [https://forum.yunohost.org/t/synchronisation-contact/12775](url)
tank you

**Comment by jobisoft** [comment]
I assume tbsync takes this as a "softfail" and does not further use that information. I would need the next log lines which show how tbsync reacts to that response.

**Comment by michelwend** [comment]
[debug.log](https://github.com/jobisoft/TbSync/files/5288053/debug.log)

**Comment by jobisoft** [comment]
right the next line
[EventLog] : softerror::404

Nothing to worry about, your server is simply not supporting a feature TbSync is checking for.
