### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ricleal** [jobisoft/TbSync#44]
While trying to add an event from my email I came up with the sync error. The debug info is here:
https://github.com/jobisoft/TbSync/issues/37#issuecomment-362417751

**Comment by jobisoft** [comment]
What server are you syncing to? Can I have the full log via email? Without anything removed?



Am 01.02.18 um 23:15 schrieb Ricardo Ferraz Leal

**Comment by ricleal** [comment]
Yep!
Just sent it to you. I went to trash (I added the event on the web) and tried to add it again. The error is in the end of the file.

**Comment by jobisoft** [comment]
Are you able to identify the event(s), which causes this error?

If so, can you export all those events as single ics file? 

Next, after exporting, can you delete these event and check, if TbSync runs fine?

(CrossCheck:) Next, re-import your ics files and check that TbSync fails again.

Send me the ics files. I should than be able to reproduce this here.

What server are you connecting to? Office 365, Horde, Kopano?

**Comment by ricleal** [comment]
Just emailed you. Sorry but there's stuff I cannot share here...

**Comment by jobisoft** [comment]
I can reproduce the error, but have not yet an idea, why it is failing...

**Comment by ricleal** [comment]
Glad you can reproduce it. I wonder if it's the attachment causing problems....

**Comment by jobisoft** [comment]
Attachements are not supported (needs ES 16.0), so that is not the error. I assume it is the UID. Try [beta3](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta3.xpi).

**Comment by jobisoft** [comment]
Please try with new created events but also the with one you send me as ics.

**Comment by ricleal** [comment]
All good with the with one I sent you as ics (tried directly from the email).
Not sure with new events. I should get a few in the next couple of days.

**Comment by jobisoft** [comment]
Ok, closing this. Re-open this issue, if it pops up again.

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
