### ISSUE TITLE
Thunderbird 82 - no config for TBSync

### ISSUE THREAD

**Issue by charliegc4** [jobisoft/TbSync#440]
## Your environment

TbSync version: 2.16
Thunderbird version: 82.0b1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Be able to configure TBSync using Tools > Addon Options > etc.
Calendars should sync

## Actual behavior
There is no option to configure TBSync.
Calendars that were already setup when using an older version of TB do not sync

## Steps to reproduce
Install TB 82
Add TBSync and provider addons

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I have not even finished full support for TB78... I will look at anything beta next year. Maybe.

**Comment by charliegc4** [comment]
Thanks. It installs on without error on 82. Is there not a way to limit which versions of TB it can be installed on? So if it is not compatible, or even remotely ready for the TB 82 version, it does not install?

I was sure addons used to be like that.

**Comment by jobisoft** [comment]
Can you file a fix?

**Comment by charliegc4** [comment]
I thought that opening this issue was the way to ask for a fix. Confused.
