### ISSUE TITLE
Some releases / tags are missing

### ISSUE THREAD

**Issue by Oxalin** [jobisoft/TbSync#442]
Under GitHub > Code > Tags | Releases, the latest available version is v2.11

Since then, there should have been at least v2.12 (commit 6fa3efcabd5ef0120afa64abf16f651b81f677c3) tagged and probably v2.16 (which is still in beta, but where it appears as a stable version under TB extensions).

Ideally, as a good practice, I would suggest to tag each beta version (which are not always identified in the commits):
- v2.15.1 (21b12b28163fd6a78a81962062fca2819b8d804e)
- v2.15.2 (63a498602e6202c2f6a2c9b39bd0a765995f5ff7)
- v2.15.3 (9d67c4cf5b0d2465ab2ba2a1d2ab0e7f336d8f8d)
- v2.15.4 (18f4c683a457ba85028156febd52aebeb2c4199d)
- v2.15.5 (7992c5c2389e86d433683a7408b877c2f6e88111)
- v2.16.1 (1ba9979066a0d2657701722ca125f933980f6e10)
- v2.16.2 (600de23f9776ef36e4f74a5dddec428a8739530b)

**Comment by jobisoft** [comment]
I added tag v2.12, thanks for reminding me. I only add tags for versions which are also on ATN.

v2.16 is a mess, I have to clean that up. Probably there will never be a tag, because the exact version v12.6 is not on github, it has cherry picked commits.
