### ISSUE TITLE
Not compatible with Firefox > 78

### ISSUE THREAD

**Issue by Dimas-sc** [jobisoft/TbSync#445]
## Your environment

TbSync version: 2.16
Thunderbird version: Thunderbird 82 Beta

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

Didn't tried the beta version because it seems to be for Firefox 78, not 80 or 82.

## Expected behavior
Access to TbSync Account Manager from Tools menu

## Actual behavior
No TbSync item appears on the Tools menu or any other.

**Comment by micwoj92** [comment]
Possibly related
https://github.com/jobisoft/TbSync/issues/440#issuecomment-700211807

**Comment by unbeatable-101** [comment]
I have this issue too.

**Comment by jobisoft** [comment]
I only support ESR for now.
