### ISSUE TITLE
GSuite "Could not find your google account"

### ISSUE THREAD

**Issue by TJCCKM** [jobisoft/TbSync#446]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.12.1 (64-bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.
Nope: Don't have time at the moment

## Expected behavior
...
I am trying to set up CardDav sync, installed Provider for CalDav & CardDav 1.2
The account is a gmail GSuite account. If I select gmail when adding the account
I get the Sign in with Google window and enter my GSuite email address

## Actual behavior
...
Getting message 'Couldn't find your Google Account"
I think this may be because it is a gsuite email, and domain is not gmail.com?

## Steps to reproduce
...
Tried manual set up, but can't figure out what server to use for a gsuite account,
if that is the problem.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That probably means the admin of your suite has disabled access. It works for me.

**Comment by TJCCKM** [comment]
I AM the gsuite admin . I will check the settings there when I have a chance

**Comment by jobisoft** [comment]
then i have no idea, sorry
