### ISSUE TITLE
Missing TbSync options on clean TB, version 78.3.1, not beta

### ISSUE THREAD

**Issue by vovata** [jobisoft/TbSync#447]
## Your environment

TbSync version: 2.16
Thunderbird version: 78.3.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Open Tools/Addon options/TbSync and configure the account

## Actual behavior
No such menu in Tools/Addon options

## Steps to reproduce
On clean TB 78.3.1 install latest TbSync 2.16 in the case

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by brianread108** [comment]
I also have this problem, having selected tbsync to replace my previous google contacts sync tool which no longer works with T78

**Comment by NoirAmnesiac** [comment]
Also having this issue. Tried several different version of thunderbird on two different computers

**Comment by sfhowes** [comment]
It's not under Tools/Add-on Options.  It's Tools/Synchronization Settings (TbSync).
![Image1](https://user-images.githubusercontent.com/71197580/95494257-4345eb00-0963-11eb-9f9c-e28a3f9c56c9.png)

**Comment by Oxalin** [comment]
It was available under top menu Tools > Add-on Options submenu prior to 78. This submenu was removed with TB 78 (long story short, things are being made different because of WebExtension).

This entry is nowhere to be found under Thunderbird menu (the three stacked horizontal bars icon @ the hamburger icon), only through the top menu bar... (for now?)

**Comment by waclaw66** [comment]
And completely missing in 82b. I know it's just beta, just reporting.

**Comment by jobisoft** [comment]
The original issue in TB78 has been explained. Closing, as I currently only support ESR (and that only in my beta release channel, as the released version on ATN has been withdrawn).
