### ISSUE TITLE
New address not synced to owncloud or google  ('cardnotfoundbutinchangelog').  

### ISSUE THREAD

**Issue by Costor** [jobisoft/TbSync#448]
## Your environment
Windows 10 Pro.  Owncloud hosted on www.owndrive.com, version unknown.
TbSync connects to an Owncloud account with 2 address books.

TbSync version: 2.16   
Thunderbird version: 78.3.2 (32-bit)
Provider for CalDAV & CardDAV: 1.19

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
If a new address is added to a TB address book provided by TbSync, this new address should be synced to the owncloud account. If this fails, there should be an error message to the user. In further sync runs the mismatch should be identified and the new address should be synced, or the failure to do so again should be reported to the user. 

## Actual behavior
New address is NOT synced to owncloud account, no error message to the user appears, however message 'cardnotfoundbutinchangelog' appears in error log at first sync run after the addition.
Further sync runs do also not sync the new address, but the message 'cardnotfoundbutinchangelog does no longer appear in the log. The user is not informed that the address books are NOT in sync.
Note: Changes of existing addresses are synced ok.
Synchronisation with owncloud works well using Android DavX5 including addition of new addresses, so owncloud account seems fine.
The same behaviour has already been reported by multiple users of google address book, also with TB 78:
https://www.thunderbird-mail.de/forum/thread/85392-neue-adressen-werden-nicht-mit-google-adressbuch-synchronisiert/

## Steps to reproduce
Install a owncloud address book into TB using TbSync. Add an address to the address book in TB. Sync. Check the address book at owncloud for the new address, and check the error log for 'cardnotfoundbutinchangelog'. Repeat syncs.

Relevant part of debug log (account name replaced by XXXX):
It shows 'cardnotfoundbutinchangelog' message during sync of the 2nd address book. 
If the sync is repeated (manually or automatically) this message no longer appears in the log but the address is not synced.

** Fri Oct 09 2020 13:16:37 GMT+0200 (Central European Summer Time) **
[TbSync init] : Done

** Fri Oct 09 2020 13:16:37 GMT+0200 (Central European Summer Time) **
[Loaded provider] : dav::CalDAV & CardDAV (1.19)

** Fri Oct 09 2020 13:17:19 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:19 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:19 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/principals/users/XXXX/

** Fri Oct 09 2020 13:17:20 GMT+0200 (Central European Summer Time) **
[Found CalDAV authRealm for <my.owndrive.com>] : OwnDrive

** Fri Oct 09 2020 13:17:20 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: eval.folders, Account: OwnDrive

** Fri Oct 09 2020 13:17:20 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:20 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/calendars/XXXX/

** Fri Oct 09 2020 13:17:21 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:21 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:21 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/principals/users/XXXX/

** Fri Oct 09 2020 13:17:21 GMT+0200 (Central European Summer Time) **
[Found CalDAV authRealm for <my.owndrive.com>] : OwnDrive

** Fri Oct 09 2020 13:17:22 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: eval.folders, Account: OwnDrive

** Fri Oct 09 2020 13:17:22 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.getfolders, Account: OwnDrive

** Fri Oct 09 2020 13:17:22 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/addressbooks/users/XXXX/

** Fri Oct 09 2020 13:17:22 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.request.remotechanges, Account: OwnDrive, Folder: Allgemein

** Fri Oct 09 2020 13:17:22 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/addressbooks/users/XXXX/Allgemein/

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: eval.response.remotechanges, Account: OwnDrive, Folder: Allgemein

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: prepare.request.localchanges, Account: OwnDrive, Folder: Allgemein

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: done, Account: OwnDrive

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.request.remotechanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/addressbooks/users/XXXX/Privat/

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: eval.response.remotechanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: prepare.request.localchanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[EventLog] : cardnotfoundbutinchangelog::ldap_2.servers.OwnDrivePrivat&Peter  (OwnDrive)#6#DelayedCreation/added_by_user

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: prepare.request.localchanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: send.request.remotechanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[URL Request #1] : https://my.owndrive.com/remote.php/dav/addressbooks/users/XXXX/Privat/

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: eval.response.remotechanges, Account: OwnDrive, Folder: Privat

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: done, Account: OwnDrive

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: done, Account: OwnDrive

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: done, Account: OwnDrive

** Fri Oct 09 2020 13:17:23 GMT+0200 (Central European Summer Time) **
[setSyncState] : State: accountdone, Account: OwnDrive

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.

**Comment by dimejo** [comment]
@jobisoft:

> I uploaded a new version for TB78 via my beta release channel. Please give it a good spin.

I haven't thoroughly tested it yet, but the new beta release has resolved the issue for me (using Nextcloud as server).

**Comment by Costor** [comment]
Seems ok now. I checked the following cases ok with a owncloud server:
- entering new item on TB -> replicated fine now 
- editing item on TB -> replicated changes ok
- deleting item on TB -> replicated ok
- deleting item on remote addressbook -> replicated to TB ok
No warning/errors showed up in the log.

Thx for the great work.
