### ISSUE TITLE
.ics calendar file import silently fails

### ISSUE THREAD

**Issue by Costor** [jobisoft/TbSync#449]
## Your environment
Windows 10 Pro, owncloud account hosted on www.owndrive.com, Version unknown
Multiple calendars from owncloud connected to TB Lightning via TbSync.

TbSync version: 2.16
Thunderbird version: 78.3.2. (32-bit)
Card/Caldav-Adapter: 1.19

[x ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Importing an .ics calendar entry using TB->Events and Tasks->Import  should import the calendar entry into the selected calendar. If there is a problem there should be an error message to the user.

## Actual behavior
Importing an .ics calendar entry into a TbSync'ed calendar using the standard approach TB->Events and Tasks->Import -> choosing the target calendar and clicking "Import Event" button seems to work alright (no error message), but the calendar entry is not added. It can not be found looking at the calendar in TB, nor in the owncloud account.
This can be repeated multiple times.
Note: The .ics import does work ok into a local calendar, so the .ics file is ok.

## Steps to reproduce
see above

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email):  I have copied it in. Log does not show any activities related to the import.

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[TbSync init] : Start (2.16)

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Thunderbird] : 78.3.2 on WINNT

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <db>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <abAutoComplete>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <addressbook>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <lightning>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <cardbook>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <eventlog>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <core>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <passwordManager>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <network>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <tools>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <manager>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <providers>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loading module <messenger>] : OK

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <db>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <abAutoComplete>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <addressbook>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <lightning>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <cardbook>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <eventlog>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <core>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <passwordManager>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <network>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <tools>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <manager>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <providers>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Initializing module] : <messenger>

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[TbSync init] : Done

** Fri Oct 09 2020 14:34:28 GMT+0200 (Central European Summer Time) **
[Loaded provider] : dav::CalDAV & CardDAV (1.19)

**Comment by jobisoft** [comment]
Issue with TB itself (it does not work regardless of TbSync being installed or not).

**Comment by Costor** [comment]
Correct; I found this is actually the open bug 1652984 in TB/Lightning,
so watch here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1652984
