### ISSUE TITLE
Timezone (CET) causes events shown 1h later

### ISSUE THREAD

**Issue by estradis** [jobisoft/TbSync#45]
We faced an issue about tb-sync. When a new event is created, it will sync with timezone "CET" but "Europe/Berlin" is expected. This leads to all events showing wrong times (1h later) in groupware and all other syncing clients.

To be sure that tb-sync causes the problem, we testet several other clients:
1. Smartphone (Android) => OK
2. Windows Active-Sync (Mail, Calendar, Tasks, Contatcs) => OK
3. Microsoft Outlook => OK
4. Thunderbird with tb-sync installed => ERROR!

As I don't know the behaving using other timezones, I would strongly recommend to make the timezone user configurable. (Especially when server and clients are located in different time zones.)

If you need further information, feel free to contact me.
And by the way, Great addon! 

![2018-02-02 12_53_33- admin-684 1h zeitversatz eines termins zwischen tbsync und tine](https://user-images.githubusercontent.com/30801486/35732161-b918f8f8-0818-11e8-8232-adbcaa94b365.png)

**Comment by jobisoft** [comment]
I send the timezone used during the creation of the event. Maybe the default timezone of your thunderbird is not set to Europe/Berlin?

You can enable the display of the timezone field:

![image](https://user-images.githubusercontent.com/5830621/35737220-18158e5e-082b-11e8-89d0-c0a3743c6196.png)

Are you sure TbSync is sending a different timezone from what is set in the event?

**Comment by jobisoft** [comment]
What I also do not understand: CET and Berlin/Europe share the same UTC offset and I am not able to create an event with CET timezone at all (it is not in the list). Can you share a screenshoot and how you where able to create such an event in Thunderbird?

**Comment by estradis** [comment]
Thank you for your quick reply. Meanwhile we also had another major issues with tb-sync randomly changing events data, so there was a decision made by the CTO to immediately ban tb-sync. Therefore I'm not longer able to share screenshots, but I'm willing to help as much as possible on this issue.

Thank you also for providing the screenshot. I didn't mind on that setting, so I'm unable to say what it was set to.

By the way CET is not automatically the same as "Europe/Berlin". Indeed it is only one part of it. The other part ist CEST, depending on summer or winter time.

And for your information:
- Our groupware is tine20 (Demo at https://demo.tine20.net/)
- We used active sync on thunderbird with tb-sync as well as with android

**Comment by jobisoft** [comment]
Could you give more details on the "changing data" issue, so that this could be fixed? In 0.7.3 I think I changed the title of tasks which where placed in event folders and of events that where placed in tasks folders. This has been reverted in the 0.7.4 (which is not yet released) to an error report. Is this what you are talking about or is it something else?

Feedback on this topic would be great.

Just to make sure: This is "TbSync" not "tb-sync".

**Comment by jobisoft** [comment]
CET has a different daylight saving behavior than Europe/Berlin? You sure about that?

**Comment by estradis** [comment]
Sorry for misspelling TbSync. 
There were several issues on changing events:
1. Start- and/or end times were changed (randomly?)
2. The organisator was captured
3. The attendees were deleted

Unfortunatly I have only the debug.log from the last issue (#3), but it will take a terrible long time to anonmyze. Is the account in line 2 still active? (I will send it there, without anonmyzing)

**Comment by jobisoft** [comment]
I just released [0.7.4-beta4](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta4.xpi), which does not alter titles of wrong items anymore. I do not know of any other situation, where TbSync does change data.

**Comment by estradis** [comment]
> CET has a different daylight saving behavior than Europe/Berlin? You sure about that?
Technically not, but per definition CET is not CEST and both are Europe/Berlin. (Learnd at flight school)

**Comment by jobisoft** [comment]
use john.bieling@gmx.de to send me an email

**Comment by estradis** [comment]
Ok, the account is active. => Email sent

**Comment by jobisoft** [comment]
For the record: There is something wrong with my timezone methods and summer/winter-time.

1. Created in Outlook.com

** Tue Mar 13 2018 20:54:41 GMT+0100 **
[Recieve TZ] : Before DST
utcOffset: -60
standardName: W. Europe Standard Time
standardDate: 0-10-5, 3:0:0.0
standardBias: 0
daylightName: (UTC+01:00) Amsterdam, Berlin, B
daylightDate: 0-3-5, 2:0:0.0
daylightBias: -60

** Tue Mar 13 2018 20:54:41 GMT+0100 **
[Recieve TZ] : After DST
utcOffset: -60
standardName: W. Europe Standard Time
standardDate: 0-10-5, 3:0:0.0
standardBias: 0
daylightName: (UTC+01:00) Amsterdam, Berlin, B
daylightDate: 0-3-5, 2:0:0.0
daylightBias: -60



2. Modified in Thunderbird, synced back to outlook.com

[Send TZ] : After DST2
utcOffset: -120
standardName: (GMT+02:00) Europe/Zaporozhye
standardDate: 0-0-0, 0:0:0.0
standardBias: 0
daylightName: (GMT+02:00) Europe/Zaporozhye
daylightDate: 0-0-0, 0:0:0.0
daylightBias: 0

** Tue Mar 13 2018 20:56:19 GMT+0100 **
[Send TZ] : Before DST2
utcOffset: -60
standardName: (GMT+01:00) Europe/Berlin
standardDate: 0-0-0, 0:0:0.0
standardBias: 0
daylightName: (GMT+01:00) Europe/Berlin
daylightDate: 0-0-0, 0:0:0.0
daylightBias: 0



3. Synced fresh from Outlook back to Thunderbird

** Tue Mar 13 2018 20:57:34 GMT+0100 **
[Recieve TZ] : After DST2
utcOffset: -120
standardName: South Africa Standard Time
standardDate: 0-0-0, 0:0:0.0
standardBias: 0
daylightName: (UTC+02:00) Harare, Pretoria
daylightDate: 0-0-0, 0:0:0.0
daylightBias: 0

** Tue Mar 13 2018 20:57:34 GMT+0100 **
[Recieve TZ] : Before DST2
utcOffset: -60
standardName: W. Central Africa Standard Time
standardDate: 0-0-0, 0:0:0.0
standardBias: 0
daylightName: (UTC+01:00) West Central Africa
daylightDate: 0-0-0, 0:0:0.0
daylightBias: 0

**Comment by jobisoft** [comment]
I *think* it is fixed now (could not test against Tine yet), but it was not limited to Tine. I could observe the change of times for events in the summer time, if they where synced back and forth. 

I did not separate the basic utcOffset and the daylightBias, but stuffed both into the utcOffset. Tbsync than than added the bias to changed incoming events, so everytime an event was edited and synced, TbSync added 1 hour to the event time.

**Comment by jobisoft** [comment]
I do not know, who is to blame, but timezone support in Tine is very strange:

![image](https://user-images.githubusercontent.com/5830621/37646295-91986c02-2c29-11e8-9da7-88c214995e25.png)

This was created just within Tine, TbSync was not involved. 
1. Set default TimeZone of Tine to Rome
2. Create Event
3. Set default TimeZone of Tine to Moskau
4. Create Event

You can see, that Tine will use the LOCAL time of the event in the global view, which is not clever. Thunderbird always calculates the time of the event in the default timezone of the user and only displays the timezone specific time in the edit window (as Tine does).

I keep investigating.

**Comment by jobisoft** [comment]
The above finding results in "moving events" if the timezone is changed. Which is again a bad idea.

**Comment by jobisoft** [comment]
Also, Tine does not obey timezones of incomming events. This is what I send:

[Send TZ] : Lord-Howe
utcOffset: -630
standardName: Australia/Lord_Howe
standardDate: 0-4-1, 0, 2:0:0.0
standardBias: 0
daylightName: Australia/Lord_Howe
daylightDate: 0-10-1, 0, 2:0:0.0
daylightBias: -30

And this is how it comes back:

[Recieve TZ] : Lord-Howe
utcOffset: -180
standardName: 
standardDate: 0-0-0, 0, 0:0:0.0
standardBias: 0
daylightName: 
daylightDate: 0-0-0, 0, 0:0:0.0
daylightBias: 0

Which is Moskau, the default TZ of Tine at that moment. Tine may use its default TZ to display the times in the global view, but it may not change the TZ itself. Furthermore, it would be nice, if Tine would actually include Europe/Moskau in the standardName/daylightName (Tine is using IANA names internally, so why not send them?). Above could also be, India/Mayotte... without a name it is hard to know...

**Comment by estradis** [comment]
Opened an issue at https://forge.tine20.org/view.php?id=13804. I'm curious to see how it goes on.

**Comment by crisoo** [comment]
Hi,
we have a similar issue. 
We are using TbSync 0.7.7 to sync calendars from Thunderbird to WebTop (Nethserver). Our TZ is Europe/Vienna (=CEST, set on all Thunderbird clients and on all WebTop accounts).

Example:
Event is scheduled from 2:00pm to 3:00pm TZ: Europe/Vienna on Thunderbird
Event shows up from 12:00pm to 1:00pm TZ Europe/Paris (= same TZ as Vienna) in WebTop web interface.
Event shows up from 12:00pm to 1:00pm TZ Europe/Vienna in other Thunderbird clients.

**Comment by jobisoft** [comment]
That is odd, this issue is still open because of the attendees stuff, the timezone should be fixed by now. I also have confirmation of another webtop user. 

Can you please disable your webtop account in the TbSync account manager and enable debug log? 

After debug log is enabled, re-enable your webtop account and start a fresh sync. How are the event coming in? Please send me the entire debug log vie email.

**Comment by crisoo** [comment]
In my case (TbSync syncing against Nethserver/WebTop5) it wasn't a bug in TbSync.
There was a timezone setting missing. After setting the correct timezone (see link below), everything looks correct. 

I found the solution at:
https://community.nethserver.org/t/webtop-5-calendar-sync-problem/7200/22 

Thanks for providing this tool and for your really fast response.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#14
