### ISSUE TITLE
Wiki to be updated for TbSync Menu entry for TB 78+

### ISSUE THREAD

**Issue by Oxalin** [jobisoft/TbSync#450]
With version 78.0, some changes were introduced and there is no more submenu under _Tools_ > _Add-ons_ (from the top bar menu). Instead, TbSync menu entry "Synchronization Settings (TbSync)" directly ends up under _Tools_ from the top menu bar: the entry doesn't appear under _Thunderbird menu_ (the three stacked horizontal bars icon) > Tools.

Also, I'm wondering if the wiki should identify the differences from OS to OS: it's not under the same menu entry under Windows than under Linux. I can't say for macOS.

**Comment by jobisoft** [comment]
Would you be interested in doing the wiki update? I have no time.

**Comment by Oxalin** [comment]
Yes. Should I just fork the wiki and send a pull-request when it's done?

**Comment by jobisoft** [comment]
I would make you a temp collaborator.

**Comment by Oxalin** [comment]
Sorry, I hadn't had the time to fix it yet. But it's on my to-do list.
