### ISSUE TITLE
400 Error received attempting sync with Google Contacts

### ISSUE THREAD

**Issue by StreamingMeeMee** [jobisoft/TbSync#451]
## Your environment

TbSync version:
Thunderbird version: 68.12.1 32bit

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
No 400 errors and continue to successfully sync contacts with 1 Google account

## Actual behavior
I've been using TBsync, sucessfully, for some time.  Recently, not sure when exactly, this error appears in the log and the sync fails.  I have anonymized some of the data.

URL:
https://www.googleapis.com/carddav/v1/principals/XXUSERNAMEREMOVEDXX@gmail.com/lists/default/187f8618dXXXXXX (PUT)

Request:
BEGIN:VCARD
VERSION:3.0
REV:2018-01-20T14:25:07Z
UID:187f8618dXXXXXX
EMAIL;TYPE=OTHER:XXCONTACTXX@XXCONTACTDOMAINXX.com
END:VCARD

Response:
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}

## Steps to reproduce
Initiate a sync.

A debug report has been sent via the HELP menu in TBsync.

Thanks for a great tool!

**Comment by jobisoft** [comment]
I no longer support google, new accounts can not be created anymore. This is a personal decision.
