### ISSUE TITLE
trouble when updating thunderbird to 78.3.2

### ISSUE THREAD

**Issue by md7373** [jobisoft/TbSync#452]
## Your environment

TbSync version: 2.16
Thunderbird version: 78.3.2

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

tbsync has been working flawlessly with thunderbird 68, accessing calendars from google, nextcloud, exchange. Then my distribution (opensuse tumbleweed) updated thunderbird to 78.3.1 (then 78.3.2), and tbsync stops working.

## Expected behavior
When I click with right mouse button on some existing calendar item, I can see details of that existing calendar item. When I click with RMB on some empty cell of the calendar, I can enter a new calendar item into the calendar.

## Actual behavior
When I click with RMB on some existing calendar item and then attempt to open it, a dialog window appears which is completely empty (its window title depends on the nature of that calendar item: whether it is a single event or a periodic event). When I wish to enter a new calendar entry, again a dialog window appears that is completely empty.

## Steps to reproduce
See above.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by admered1** [comment]
I too have been using this excellent tool for ages on TB 68 and before. Could you please comment on whether this is now the end of the line or if there's another version coming. Thanks.

**Comment by jobisoft** [comment]
Working on it.

**Comment by admered1** [comment]
Oh good. If you need a test site, please let me know.
