### ISSUE TITLE
TbSync does not sync Lightning contacts to baikal, but from baikal (after disabling/enabling).

### ISSUE THREAD

**Issue by SchwarzerA** [jobisoft/TbSync#453]
## Your environment

TbSync version:  2.16, September 2, 2020
Provider for CalDAV & CardDAV:  1.19, September 21, 2020
Thunderbird version:  78.3.2 (64-bit), Install Date: So 11 Okt 2020 16:27:59 CEST, Build Date: Sa 10 Okt 2020 06:19:15 CEST

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

No, it is a productive environment and currently beyond my possibilities.

## Expected behavior

Contacts should be synced in both directions (as tasks and calendar do).

## Actual behavior

You work on your contacts in Lightning (the sample with "schwarzer" contained 5 changed items and only ONE was synced to baikal.

## Steps to reproduce

What I did: Originally all contacts had been stored in outlook.com and I wanted to leave M$ due to EU-DSGVO. So I had M$ contacts and baikal contacts parallel in Lightning. Then moved them in batches or one-by-one from M$ to @home (selected them with the mouse and moved them), while editing most of them at the new location. After two days working on 241 worldwide accounts I realized that nothing was synced to my smartphone and I investigated further. Newly added contacts were indeed synced and appeared on my smartphone but none of those transferred from outlook.com (M$) to baikal (@home). Disabling @home (myAddressBook) and enabling it again synced the newly created contact back to Lightning removing all other contacts which were kept in an abook-?.sqlite locally. Fortunately I could recover from a backup. At the same time tasks and calendar entries worked as expected (tasks edited on the smartphone and with Lightning do not receive the default color, which is not an issue). 

## To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

I did, but TbSync saw no problems… Please allow that I attach some more files as they contain personal data.

## From prefs.js

user_pref("ldap_2.servers.history.uid", "d6772104-c8d6-4e44-ba37-d8120631b0fa");
user_pref("ldap_2.servers.homemyAddressBook.description", "@home (myAddressBook)");
user_pref("ldap_2.servers.homemyAddressBook.dirType", 101);
user_pref("ldap_2.servers.homemyAddressBook.enable_autocomplete", false);
user_pref("ldap_2.servers.homemyAddressBook.filename", "abook-1.sqlite");
user_pref("ldap_2.servers.homemyAddressBook.gContactSyncSkipped", "true");
user_pref("ldap_2.servers.homemyAddressBook.tbSyncAccountID", "5");
user_pref("ldap_2.servers.homemyAddressBook.tbSyncIcon", "davcustom");
user_pref("ldap_2.servers.homemyAddressBook.tbSyncProvider", "dav");
user_pref("ldap_2.servers.homemyAddressBook.uid", "e611a048-616f-42f2-81d5-67a6249074c0");
user_pref("ldap_2.servers.pab.uid", "859b77ad-1a9a-4832-83f7-b5bb55a78aa1");
user_pref("ldap_2.servers.sirwizmyAddressBook.enable_autocomplete", false);
user_pref("ldap_2.servers.sirwizmyAddressBook.gContactSyncSkipped", "true");
user_pref("ldap_2.servers.sirwizmyAddressBook.tbSyncAccountID", "6");
user_pref("ldap_2.servers.sirwizmyAddressBook.tbSyncIcon", "davcustom");
user_pref("ldap_2.servers.sirwizmyAddressBook.tbSyncProvider", "dav");

Is there anything that would help in that matter?

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.
