### ISSUE TITLE
Problem synchronizing Office365 calendar

### ISSUE THREAD

**Issue by szazs89** [jobisoft/TbSync#454]
## Your environment
TbSync version: 2.16.2
Thunderbird version: 78.3.1

[X ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I have added an Office365 account with shibboleth auth (it redirects to outside of Office365). Then the account appears in the list with unchecked Enable checkbox under the General session.
When checking the box "Enabling and synchronizing the account"(or similar because it is in hungarian)
then it produces the following Javascript error:

## Actual behavior
this.folders is undefined

addFolder@chrome://tbsync/content/modules/db.js:345:9
createNewFolder@chrome://tbsync/content/modules/public.js:264:50
folderList@chrome://eas4tbsync/content/includes/sync.js:155:58

## Steps to reproduce
Clear the account and go to Expected behaviour.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.
