### ISSUE TITLE
Not able to install in TB 78.3.2 on Win10

### ISSUE THREAD

**Issue by Carpspb** [jobisoft/TbSync#455]
TbSync version: tbsync-2.12-tb
Thunderbird version:78.3.2 64 bit
Windows10 Pro

## Actual behavior
...TbSync not able to install because not compatible with TB 78.3.2.
What can I do to get it installed?

Thanks for your work!

**Comment by jobisoft** [comment]
You have to wait till I fixed it :-(

**Comment by Carpspb** [comment]
OK, thank you so much for your work

**Comment by jobisoft** [comment]
I uploaded a new version for TB78 via my beta release channel. Please give it a good spin. 

https://github.com/jobisoft/TbSync/wiki/Get-the-latest-TbSync-version#beta-release-channel

I will close this issue. Open a new one if you run into errors, but please check first, if someone else has already created a new issue.
