### ISSUE TITLE
No menu entry shown for TbSync - cannot open "TbSync Account Manager"

### ISSUE THREAD

**Issue by Rumbelstilzchen** [jobisoft/TbSync#456]
## Your environment

TbSync version: 2.18
Thunderbird version: 78.4.0 (32-Bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Under "extra"- "Ad-on-Einstellungen" there should be an entry for TbSync

## Actual behavior
There is no such menu item for TbSync 
![Error](https://user-images.githubusercontent.com/8233580/96863546-54185580-1467-11eb-97fb-b37aeb22b698.png)
Thus I cannot open the "TbSync Account Manager"

## Steps to reproduce
Uninstalling and reinstalling of all TbSync adons did not help

To help resolving your issue, enable debug logging (TbSync Account Manager
 -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please check the 14th entry below the current selected entry.
