### ISSUE TITLE
Quitting/Closing Thunderbird removes Google Calendar entries for all open reminders

### ISSUE THREAD

**Issue by lipitz** [jobisoft/TbSync#457]
## Your environment
MacOS 10.15.7

TbSync version: 2.18 (Provider for CalDAV & CardDAV 1.21)
Thunderbird version: 78.4, but it was also happening with 78.3

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Create a calendar entry via Thunderbird (make it for happening an hour ago). The entry correctly shows in Google calendar, and the Thunderbird calendar interface. The reminder shows up successfully within Thunderbird. Keep the reminder open; do not snooze, do not dismiss it. Quit/close Thunderbird. When Thunderbird is reopened, the calendar entry should still be in Google calendar and the Thunderbird calendar interface. The reminder should still be active, meaning it should show up at some point after re-opening Thunderbird.

## Actual behavior
After reopening Thunderbird following the above steps, the calendar entry remains in Google Calendar (correctly), but it is not in the Thunderbird calendar interface and the reminder is gone. I would expect the the entry to show in the Thunderbird calendar interface and the reminder to show immediately after opening Thunderbird or after some time passes and the calendar is synced.

## Steps to reproduce
Details are above.

As for the debug log, the only logging I get is for when I restart Thunderbird, not while quitting/closing. I will send it your way.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/issues/466
