### ISSUE TITLE
TbSync is not showing up

### ISSUE THREAD

**Issue by TieumTieum** [jobisoft/TbSync#458]
## Your environment

TbSync version: Beta Release Channel
Thunderbird version: 78.4.0

[ X ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Some menu to start TbSync 

## Actual behavior
TbSync is not availbale anywhere in the menus

**Comment by micwoj92** [comment]
Have you tried solution from https://github.com/jobisoft/TbSync/issues/456 ?

**Comment by TieumTieum** [comment]
My Tools menu is not that long:
![image](https://user-images.githubusercontent.com/17684176/97101751-384bc400-16a0-11eb-9302-9d89ba1de070.png)

**Comment by jobisoft** [comment]
That is not the tools menu discussed in the linked issue. Please recheck or just click on the TbSync entry in the Thunderbird Status bar as described here:
https://github.com/jobisoft/TbSync/wiki/How-to-get-started

**Comment by TieumTieum** [comment]
Thanks. The menu is quite hidden and not very discoverable.
