### ISSUE TITLE
Calendar sort order messed up after restart

### ISSUE THREAD

**Issue by helmar74** [jobisoft/TbSync#459]
## Your environment

TbSync version:
Thunderbird version: 78.4.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I sorted my Calendars in the left panel, to my wishes. It should be the same after restart.
Also tried to set setting "calendar.list.sortOrder" manually, doesn't help at all...
## Actual behavior
After restarting TB the defined sort order is gone, the calendars are sorted random

## Steps to reproduce
1. Create "a few" Webcal Calendars (I'm using 15 Google Calendars)
2. Sort the calendars to your favor.
3. Restart TB
4. Check, if sortorder is the same as before.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I no longer support google, new accounts can not be created anymore. This is a personal decision.
