### ISSUE TITLE
Enable autocomplete for newly added CardDav address books.

### ISSUE THREAD

**Issue by brad2014** [jobisoft/TbSync#461]
## Your environment

TbSync version: 2.18
Thunderbird version: 78.4.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I sync (via carddav) a new address book, it should be used for address autocomplete (calendar invite, mail compose).
Internally, I expect that user_pref `enable_autocomplete` for new address books is initially set to true.

Note: It is probably a Thunderbird bug that this setting is no longer available on the Preferences->Composition->Addressing form. It used to be that one could select the address books that would be used for autocompletion.  Now, there is simply a checkbox for "Use Local Address books".

## Actual behavior
Newly added tbsync/carddav address books are ignored for autocomplete.

## Steps to reproduce
On a clean profile, carddav sync an address book.  Then create a calendar event, add invitees, and start typing a name in that addressbook.

## Workaround
After syncing a carddav address book, In Preferences->General->Config Editor, find the entry `ldap_2.servers.<nameOfServer>Contacts.enable_autocomplete` and set it to true.

**Comment by quentinDupont** [comment]
Hello,
Same issue here. It seems that some contacts are found in TbSync adress book but not all the time...

Thanks for the workaround by enabling it on config editor ! :100:

**Comment by sillyrat** [comment]
This same issue emerged for me when I upgraded to version 102 -- CardDAV contacts (on a radicale server) stopped being offered for autocomplete, and no option presented in Settings would bring that functionality back.  I too had to use the Config Editor to correct the problem.

**Comment by jobisoft** [comment]
I have not released a version for 102 yet.

In TB78-TB91 I disabled the built-in autocomplete for TbSync address books and shipped my own autocomplete, because I wanted to make things better. So that did not work. I will remove my custom autocomplete in the version for 102.
