### ISSUE TITLE
TbSync not in "both" menus

### ISSUE THREAD

**Issue by ccoenen** [jobisoft/TbSync#462]
## Your environment

TbSync version: 2.18
Thunderbird version: 78.4.0

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

[x] No, I did not

## Problem
I was trying to find the tbsync menu entries, and was not easily able to find them. It took me two restarts and a few full sub-menu-by-submenu sweeps to actually find the thing i was missing. I only found it by accident. Other places I looked for: TB's settings, TB's account settings.

![where!?](https://media.giphy.com/media/gngO1gmBhS9na/source.gif)

## Actual behavior

TbSync appears to only be in the legacy menu (upper picture) at the top border of the window, which is deactivated by default. It is not part of the burger-menu (lower picture).

![2020-11-05 17_16_09-Window](https://user-images.githubusercontent.com/124909/98267169-5f9d6d80-1f8b-11eb-8779-c4a40f68c682.png)

![2020-11-05 17_15_25-Window](https://user-images.githubusercontent.com/124909/98267225-6d52f300-1f8b-11eb-971d-704f80181f75.png)

## Steps to reproduce

- have thunderbird
- install tbsync
- search for the menu

**Comment by Darkmagister** [comment]
Same here, after the update of thunderbird with new ui i can not find the tbsync menu option to open the manager window

**Comment by DavidBE-UK** [comment]
The TbSync status/button at the right end of the TB main window bottom status bar opens the TbSync manager window and is always visible and available, so why would you need it in the hamburger menu too?

**Comment by ccoenen** [comment]
two seperate reasons:
- until you mentioned it just now, I hadn't taken a look at that. It's not a place I'd have expected it
- it's not a common interaction type as other things in that status bar (counts, for example) can not be interacted with. I think of this as a status display.

**Comment by barolo** [comment]
I've encountered the same issue, due to two reasons:
- as mentioned already it's not a common place to look for an addon's options
- thunderbird's status bar is pretty useless and is commonly hidden

**Comment by LukasKlement** [comment]
I'm using the latest beta channel release of this module in combination with Thunderbird 87.0b3 (64-bit). Unfortunately, the link to the configuration is shown in neither menu. Is there a third way to open the tbsync configuration window?

**Comment by jobisoft** [comment]
There is a version update pending for review. I am the main reviewer on ATN, and the mean review time is down to 1-2 days, but I cannot review my own add-ons :-(

The options will be in the add-on manager after the next update has landed:
![image](https://user-images.githubusercontent.com/5830621/111607250-5beee280-87d8-11eb-94e6-c43339425d1e.png)

I probably should push this out the beta channel as well...

**Comment by jobisoft** [comment]
Miraculously it has been reviewed moments ago. You will also notice that the new version has a toolbar button which opens the manager and in some later version TbSync's status bar entry will be removed and the information will be added as "badge" text to that toolbar button.

Can we close this?

**Comment by LukasKlement** [comment]
That's great! Did you push it to the beta channel already? On Thunderbird 87.0b3 with the Beta Release Channel the link is not there in none of the three supposed places.
