### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by BillH99999** [jobisoft/TbSync#464]
## Your environment
Windows 10 2004

TbSync version: 2.18
Thunderbird version:  78.4.1 (64-bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
No errors

## Actual behavior
Starting at 9:11 PST tonight I started getting a JavaScript error every time TBSync tries to sync.  I am syncing with Gmail.  The only thing I am syncing is the Address Book.  Here is a print of the error from my event log.

![image1](https://user-images.githubusercontent.com/26846819/98507272-1c086500-2212-11eb-9ba2-7b997973255c.jpg)

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Bill

**Comment by BillH99999** [comment]
John... I was just wondering why the issue was closed with no explanation of what is causing my error and how to fix it.  

Thanks,
Bill

**Comment by jobisoft** [comment]
1) I removed official google support (existing accounts will cont. to work, but cannot create new)
2) Your issue has been fixed.

**Comment by BillH99999** [comment]
May I ask why?  I sometimes have to open new accounts on Google and just wondered. 

Thanks for fixing the problem.

Bill

**Comment by jobisoft** [comment]
Because I personally cannot take the hate from google users anylonger (not you). Their we-want-everything-for-free-and-we-want-it-now attitude is just insane. You may re-enable support by activating the dav4tbsync.googlesupport option in the advanced TB config. But I removed it entirely from the add-on description and will not provide support.

**Comment by BillH99999** [comment]
Thanks for the option information.

I am sorry to hear you have been treated poorly by other google users.  I don't understand people who do that.

TBSync works great for me.  With gContactSync seemingly dead and CardBook having issues that make it unusable for google, I would really hate to lose TBSync as well.  

Thanks,
Bill

**Comment by jobisoft** [comment]
It looks like it is not fixed. I removed the broken version from ATN, so the last working one should install now, if you install dav-4-tbsync anew.

**Comment by BillH99999** [comment]
Hi John,

I was just going to bed when you replied about activating the dav4tbsync.googlesupport in the advanced TB config.  I just woke up and was about to do so, and I got this message from you.  So I updated TBSync to 2.19 and Provider for CalDAV & CardDAV to 1.24 and it seems to be working.  Do I still need to activate the dav4tbsync.googlesupport option? 

You mention here about installing dav-4-tbsync.  Is that an extension?  I don't see it on ATN.

Thanks!
Bill

**Comment by jobisoft** [comment]
dav-4-tbsync is the internal name of the CalDAV & CardDAV Provider, sorry for the confusion.

If you want to be able to create new google accounts, you need to enable dav4tbsync.googlesupport, otherwise the google option is not shown in the creation wizard.

**Comment by BillH99999** [comment]
Thanks for the explanation.

I know this probably isn't any of my business and I respect your right to decide not to support Google, but I do hope you reconsider at some point.  For every person that uses TBSync with Google and behaves poorly, there are probably hundreds if not thousands who do not act that way.  We all would like to continue to use TBSync and hope that one day you change your mind.

Thanks for all your help.
Bill
