### ISSUE TITLE
TbSync claims provider for CalDAV is not installed

### ISSUE THREAD

**Issue by bora77** [jobisoft/TbSync#465]
## Your environment

TbSync version: 2.18
Thunderbird version: 78.4.1

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TBSync should recognize the installed CalDAV Provider

## Actual behavior
Since 78.4 release the caldav adressbook disappeared and synchronizing would not work.
TBSync does not recognize the installed extension and asking for it to be installed. 
I retried several times also with beta release branch, purged the prefs, tried with admin privileges etc.
The extension is listed as installed but TBSync just does not recognize it.

## Steps to reproduce
this is the debug:

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Start (2.18)

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Thunderbird] : 78.4.1 on WINNT

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <db>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <abAutoComplete>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <addressbook>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <lightning>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <cardbook>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <eventlog>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <core>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <passwordManager>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <network>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <tools>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <manager>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <providers>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <messenger>] : OK

** Mon Nov 09 2020 10:03:50 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <db>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <abAutoComplete>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <addressbook>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <lightning>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <cardbook>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <eventlog>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <core>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <passwordManager>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <network>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <tools>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <manager>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <providers>

** Mon Nov 09 2020 10:03:53 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <messenger>

** Mon Nov 09 2020 10:03:54 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Done

** Mon Nov 09 2020 10:03:58 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loaded provider] : dav::CalDAV & CardDAV (1.21)

** Mon Nov 09 2020 10:03:58 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : FAILED to load provider <dav>
Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIPrefBranch.getComplexValue]

**Comment by jobisoft** [comment]
I removed the broken version from ATN. Can you remove your current add-on and install fresh from ATN?

**Comment by bora77** [comment]
Hi John,

I removed the beta and reinstalled both extension from ATN, but the issue remains.

WHen trying to add a new CalDAV account it claims the provider is not installed.

**Comment by jobisoft** [comment]
Can you update tbsync and dav-4-tbsync to the latest versions on ATN? Both have been updated a few minutes ago to tbsync 2.19 and dav 1.24

**Comment by jobisoft** [comment]
and maybe restart TB

**Comment by bora77** [comment]
I restartet several times and manually triggered the extensions update. It says they were updated but version is still at 2.18? The problem remains even with the updated version from today.

**Comment by bora77** [comment]
Ok now it updated to 2.19 and 1.24 - the problem remains.

See debug:

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Start (2.19)

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Thunderbird] : 78.4.1 on WINNT

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <db>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <abAutoComplete>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <addressbook>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <lightning>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <cardbook>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <eventlog>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <core>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <passwordManager>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <network>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <tools>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <manager>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <providers>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <messenger>] : OK

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <db>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <abAutoComplete>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <addressbook>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <lightning>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <cardbook>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <eventlog>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <core>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <passwordManager>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <network>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <tools>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <manager>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <providers>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <messenger>

** Mon Nov 09 2020 12:35:41 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Done

** Mon Nov 09 2020 12:35:42 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loaded provider] : dav::CalDAV & CardDAV (1.24)

** Mon Nov 09 2020 12:35:42 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : FAILED to load provider <dav>
Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIPrefBranch.getComplexValue]

**Comment by jobisoft** [comment]
I do not use that getComplexValue function. Can you disable all other addons (besides tbsync, restart and try again?) I have no idea what error you are seeing....

**Comment by bora77** [comment]
![error](https://user-images.githubusercontent.com/4234050/98543633-1010b780-2293-11eb-82db-41056b1d6f5a.jpg)

No other extensions are installed. The message comes from the TBSync Event log.

**Comment by bora77** [comment]
This problem remains, even with a fresh profile and nothing else installed. It keeps claiming caldav is not installed

**Comment by jobisoft** [comment]
I assume you no longer use TbSync, if this has not been resolved by an update.
