### ISSUE TITLE
TBSync with Outlook.com

### ISSUE THREAD

**Issue by jack1010-star** [jobisoft/TbSync#468]
## Your environment

TbSync version: 2.19 and beta
Exchange Active Syn: 1.20 and beta
Thunderbird version: 78.4.3
Windows 10 

[YES] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
TB calendar should write to outlook.com calendar

## Actual behavior
TB Calendar is not writing to outlook.com calendar. Outlook.com calendar entries are read by TB and can also edited/deleted with TB
Sometime entries on TB calendar get duplicated

## Steps to reproduce
Updated to beta channel but both issues persists

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jack1010-star** [comment]
Found a solution to the TB sync problem with outlook.com. In the TB calendar, use the outlook.com (calendar) instead of home. The entries made on outlook.com (calendar) are synced with outlook.com

**Comment by Hennsi** [comment]
I am glad that someone found a solution! Could you provide a guide or something because I have the same Issue you mentioned but I do not understand your solution 100%.

**Comment by jack1010-star** [comment]
My TB calendar looks like this on the left side. Make your calendar entries on the "Outlook.com (Calendar)" instead of "Home" by selecting it. 
![image](https://user-images.githubusercontent.com/74437196/99888229-61606580-2c08-11eb-8512-02b5e93056b7.png)

Alternatively, when you make a new calendar entry, choose "Outlook.com (Calendar)". 
![image](https://user-images.githubusercontent.com/74437196/99888274-d0d65500-2c08-11eb-929e-a7ac217cbf63.png)

This effectively means that you will not use the "Home" but that is ok with me.

**Comment by Hennsi** [comment]
thank you very much it now works for me aswell :+1:

**Comment by jack1010-star** [comment]
Glad it worked.
