### ISSUE TITLE
Lightning in thunderbird 78 does not sync NextCloud calendar

### ISSUE THREAD

**Issue by xanathon** [jobisoft/TbSync#470]
## Your environment

TbSync version: 2.18 (version as shown on TB addon page)
Thunderbird version: 78.4.3 32bit

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Sync Nextcloud Calendar

## Actual behavior
calendar data does not show up in Lighning

## Steps to reproduce
Install tbsync and DAV4TbSync
new account, enter account credentials
TbSync say everything is fine and sync successful
Nothing shown in lightning calendar

From the messages in debug log everything looks fine,, TbSync does not let me create an error log, because there are no errors (it says).

Yes, I restarted Thunderbird.

**Comment by jobisoft** [comment]
Can I have a screenshot of the tbsync manager of your account?

**Comment by xanathon** [comment]
I do not understand what exactly you mean? The windows that shows up via Extras -> tbsync? 
![image](https://user-images.githubusercontent.com/24546760/99409396-9bbcc080-28f1-11eb-96b3-4d840d771b58.png)

**Comment by jobisoft** [comment]
Yes, that one. Can you create a new calendar (not import) in your NextCloud interface and add a event there and see if that is getting synced?

**Comment by xanathon** [comment]
Yes, that works

**Comment by jobisoft** [comment]
can you verify that your imported calendar works with other clients?

**Comment by xanathon** [comment]
Yes, I can verify that. It works on Android and iOS.

**Comment by xanathon** [comment]
A little background: before TB78 I was able to use Thunderbird/Lightning directly with Nextcloud. That stopped working with TB78. I exported the calendar from TB78 as ical, imported that into a NC instance and then tried to connect to it via tbsync.

**Comment by jobisoft** [comment]
I have no idea what is going on. TbSync is adding true carddav support, but for caldav it just uses the internal lightning functions (and discovers calendars for you). So if lightning itself is not able to sync your calendar, TbSync is of no help :-(

**Comment by xanathon** [comment]
Thank you for your efforts.

I have no idea what the folks at Mozilla thought when they released this highly buggy and unfinished TB78 crap that has lots of problems everywhere. 

If I discover a solution I'll  let you know.
