### ISSUE TITLE
website address is not synced

### ISSUE THREAD

**Issue by mr10008** [jobisoft/TbSync#471]
Windows 7, 64 bit Ultimate

TbSync version: 2.18
Thunderbird version: 78.4.3

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
To get the website address from google contacts synced with TBird
...

## Actual behavior
Website address is missing  
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/issues/466
