### ISSUE TITLE
Options? Configuration?

### ISSUE THREAD

**Issue by grayik** [jobisoft/TbSync#478]
## Your environment
Windows 10
TbSync version: 2.18
Thunderbird version: 78.5.1

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I expect to be able to configure tbSync

## Actual behavior
I can't find anywhere to do so! Sorry, am I being completely dense? I suspect this is a TB 78 issue rather than tbSync, but I'm utterly baffled by this...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by rayfun** [comment]
Same for me on Ubuntu 20.04 with 78.5.1+build1-0ubuntu0.20.04.1 from http://ppa.launchpad.net/ubuntu-mozilla-security/ppa/ubuntu

**Comment by jobisoft** [comment]
Options are currently only in the old school tools menu (not the ≡ menu). Right Click in the tab ribon area of TB and enable "menu bar".

**Comment by grayik** [comment]
Yes, and then? I mean, I can get to Tools - Options - Extensions & Themes - TBSync Beta Release, but then what? There are no options to configure there. Am I going to the wrong place, or missing something obvious?
![image](https://user-images.githubusercontent.com/75635017/103404579-06495900-4b4c-11eb-9ce6-f6f7e25ca19e.png)

**Comment by grayik** [comment]
Ah, wait, found it - I was looking under "address book - tools" instead of on the main TB screen...

**Comment by grayik** [comment]
... And it works! Hurray, brilliant, such a relief to get my Google contacts back in sync! Many thanks John.
