### ISSUE TITLE
No Sync to Nextcloud of a New Created contact

### ISSUE THREAD

**Issue by jpalcantara** [jobisoft/TbSync#479]
## Your environment

TbSync version:2.19
Thunderbird version:78.5.0 (64-bit)

[ X  ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

**## Expected behavior From Thunderbird I create a new contact and then Sync with TBSYNC Account manager and it should be synching to  Nextcloud 18.0.4 and then down to my other device using Dav5.**

**## Actual behavior I am unable to create a New contact and synch it across.  I can append to an existing contact synch across from Thunderbird OK
I can create new contact from devices and sync down to Thubnderbird OK
Calendar OK** 

## Steps to reproduce

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Switching to native CardDAV sync and removing my own sync code. If this still happens in the to-be-released version for TB102, it is a bug in Thunderbird itself.
