### ISSUE TITLE
Contacts not sync

### ISSUE THREAD

**Issue by mifas** [jobisoft/TbSync#48]
I'm using Office 365. When I subscribed to contacts. Under the Address, everything looks empty. Only name of the folders is there

**Comment by jobisoft** [comment]
First update TbSync to the latest [beta](https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta4.xpi) and also update your Thunderbird to the latest standard release (52.6). Please also enable debug logging (TbSync Account Manager -> Help). 

Disconnect and re-connect the account. If the error remains, please send me the debug.log (via email)

**Comment by jobisoft** [comment]
Closing due to missing feedback.
