### ISSUE TITLE
Settings lost

### ISSUE THREAD

**Issue by sebastienserre** [jobisoft/TbSync#482]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.10
Ubuntu 20.04

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

I had 2 Cardav/caldav account setup for months and today they disappear. Link are broken

I will activate debug log and then recreate my setup and will send it to you asap.

**Comment by MikaYuoadas** [comment]
I am getting the same issue after an upgrade of thunderbird.
The files accounts68.json, changelog68.json and folders68.json in `.thunderbird/****.default-release/TbSync` are all empty. looks like they got overwritten after the upgrade.

**Comment by jobisoft** [comment]
For the update from TB68 to TB78 last summer I did make an announcement that settings will probably get lost during update.
