### ISSUE TITLE
Disabled Calendars

### ISSUE THREAD

**Issue by rapidman49** [jobisoft/TbSync#483]
## Your environment

TbSync version: 2.19
Thunderbird version: 78.6.1

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Actual behavior
i can find no errors in tbsync log. but all calendars (and task calendars) are disabled. Enabling results in disabling after a moment. Sync seems to work, all Calendar entries are visible for this moment.

## Steps to reproduce
reproducable with openxchange(1) and nextcloud(2). different servers, different client pcs, different networks
i was able to fix (2) with uninstalling Thunderbird 78, installing 68, delete profile, create profile, install tbsync addons, configure tbsync, update thunderbird. (1) is still not working

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Debug Log is empty (only the usual initialization...)
possibly a thunderbird problem?

**Comment by mayanimation** [comment]
Had the exact same issue. Enabling the calendar the entries showed up for a second and disappeared again on PC Win10, Thunderbird 32-bit: 78.6.1. TbSync: 2.19 and on Centos8, Thunderbird 64-bit: 78.5.1. TbSync: 2.19.
Solution:
I had a Yubi-Key connected for my Nextcloud account. Getting rid of hardware security key made the account calender synch and stay again. A dum workaround for any two factor authentification. Create a new user with access to your calendar and reference this user's calendar. So you can use any two factor authentification.

**Comment by johnjohnk2** [comment]
HI @rapidman49 and @mayanimation did you find a solution ?
I have a similar issue ( but not sure it is exactly the same problem) ---> I can synchronize my tasks but not my calendar

**Comment by mayanimation** [comment]
Hi johnjohnk2,
when I wrote that I didn't know I could create an app password only for an app like calendar. You keep two-factor untouched, which is good. You want to keep security. For synchronizing apps like calendar you create another password apart from your user access pw. This connects eg your iOS calendar app with your nextcloud calendar without the need to verify yourself with a second factor. Calender keeps updating ever since. Never had that issue again.
Hope I could help somebody

**Comment by johnjohnk2** [comment]
Hi @mayanimation OK I understand. Thanks a lot. I finally managed to recover all my agenda by reimporting all from scratch ...
