### ISSUE TITLE
Some contacts NOT found by autofill

### ISSUE THREAD

**Issue by aaeneas** [jobisoft/TbSync#486]
## Your environment

TbSync version: 2.12
Thunderbird version: 68.12.1 (64bit)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
... Expect contacts to be included in auto-fill

## Actual behavior
... Some contacts are missing from the auto-fill list

## Steps to reproduce
... This issue also submitted to Thunderbird forum as found [here](http://forums.mozillazine.org/viewtopic.php?f=39&t=3069886).

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
? What email address?

**Comment by Oxalin** [comment]
Do they have any special characters? Accented characters (seen on my side) seem to fail.

**Comment by aaeneas** [comment]
No!
I've now used a test system to install what, I think, is the latest release of TB (78.6.1) and TBsync (4) and verified that the same problem exists there.

**Comment by schmauder** [comment]
hi aaeneas,
the problems is reported to be solved in the mozillazine forum. did the solution help you too?
also did you notice that the auto-complete list might have a scroll bar? regards

**Comment by aaeneas** [comment]
[This post](http://forums.mozillazine.org/viewtopic.php?f=39&t=3070034&p=14884006#p14884006) was about a different problem but it lead me to recognize a discrepancy in my profiles.ini file.  Once I straightened that out the problem reported here seemed to go away.  Have no idea about cause and affect.
