### ISSUE TITLE
TBsync sync empty address book 

### ISSUE THREAD

**Issue by PrzemekSkw** [jobisoft/TbSync#489]
## Your environment

TbSync version: 2.20
Thunderbird version: 78.6.1

## Expected behavior
Sync my address books

## Actual behavior
sync new empty Address Book

Hi, I install TBsync and CalDav plugins for my Thunderbird. I connect to my Nextcloud server and everything looks OK but I have new address book for Nextcloud that is Empty. I cannot copy any contacts from my working Thunderbird Address Book to Nextcloud address book so I install Cardbook plugin. I copy all contacts from Address Boook to Nextcloud Address Book and also sync Nextcloud with Cardbook but still noting sync on my Nextcloud server. I see Cardbook sync only old Address Books.

![Zrzut ekranu z 2021-01-25 13-37-53](https://user-images.githubusercontent.com/25219988/105707061-a9567e00-5f12-11eb-9f3d-b29d2257fee0.png)

Regards,
Przemek

**Comment by jobisoft** [comment]
TbSync is not designed to copy data from one address book to the other within Thunderbird. Export your local TB addressbook and import that in your Nextcloud web interface which will make it availabe to all connected devices, including TbSync.
