### ISSUE TITLE
Make TBSync/Exchange address book default in Thunderbird

### ISSUE THREAD

**Issue by xj25vm** [jobisoft/TbSync#49]
It would be really useful if at some point in the future it will be possible to tell TBSync during setup to make the address book it is syncing with the back-end the default one in Thunderbird - so that all new contacts in Thunderbird are saved there and shared with other devices using the same back-end. I think Thunderbird doesn't support this at the moment - but maybe one to keep an eye on in case the TB inner workings get an update at some point?

**Comment by jobisoft** [comment]
You can also set in tools -> options -> composition -> addressing which address book it should save addresses from sent mail to. 

Does that help?

**Comment by jobisoft** [comment]
Added it to my [roadmap](https://github.com/jobisoft/TbSync/wiki/Roadmap), closing this for now since I currently cannot do anything about it.

**Comment by xj25vm** [comment]
> You can also set in tools -> options -> composition -> addressing which address book it should save addresses from sent mail to.

Not quite the same. That is the default address book for automatically added/collected addresses, when sending an email. The default main address book comes into play when clicking on the email address of the sender, in an open email message, and selecting "Add to address book". Also, maybe it will be possible at some point in time to hide the "Personal Address Book", so that the Exchange address book is the only visible and usable one - to guarantee new contacts don't end up in the wrong address book by mistake.

Thank you for adding it to the list of things to consider in the future.

**Comment by ovari** [comment]
Perhaps if you save the contacts in the CardBook add-on, you could make the TBSync/Exchange address book default in Thunderbird.
https://gitlab.com/CardBook/CardBook
https://addons.thunderbird.net/addon/cardbook/

What do you think?

Thank you
