### ISSUE TITLE
List not found in the composer window

### ISSUE THREAD

**Issue by pi3141** [jobisoft/TbSync#490]
## Your environment

TbSync version:2.20
Provider for cardDav:1.24
Thunderbird version:78.6

[x] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior

When typing the name of a list in address field of composer window, TB add the address of the list in the address field.

## Actual behavior

When typing the name of a list in address field of composer window, TB shows me "<>__" instead of the list name. If I select it, no address are added to the address field.

## Steps to reproduce

* create a list called "myList" with associated contacts.
* write a new email, and type "myList" in the address field, it shows me "<>__" in the field. If I select this entry, no email address is added to the address field.

## Possible workaround

* To write an email to the list I need to open address book, select the list, and push "write" button. It way less convenient than using autofill.

**Comment by jobisoft** [comment]
I cannot reproduce this. Is this related to TbSync (does it only happen with lists in TbSync address books?) What happens if you alter nickname, description and or listname?
