### ISSUE TITLE
Asking for Google password even without google account

### ISSUE THREAD

**Issue by tigerjack** [jobisoft/TbSync#492]
## Your environment

TbSync version: 1.24
Thunderbird version: 78.7

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...
No google account shown.

## Actual behavior
I keep seeing this each time I open Thunderbird.
![image](https://user-images.githubusercontent.com/8199216/106390941-212d1880-63eb-11eb-8da7-2aea6b9b6133.png)

As you can see, however, I don't have any Google account.
![image](https://user-images.githubusercontent.com/8199216/106390962-3dc95080-63eb-11eb-981a-eb04c92921d2.png)

I think it's there from a previous version of TbSync and it wasn't deleted during the update.

I also have an analogous issue with fruux. As you can see from the previous image I still didn't set up my fruux account. However, I had this previously and both Calendar and Tasks are showing up in the Calendar tab.

...

## Steps to reproduce
...

Just open Thunderbird.

**Comment by jobisoft** [comment]
Check if the google calendar is still enabled in the calendar view of thunderbird (lightning).

**Comment by tigerjack** [comment]
Yep it is enabled (and also fruux for what it's worth). I have the Provider for Google Calendar extension to manage Google Calendars, while I use TbSync for all the others. Even like this there's always that form popping up at the application boot.

**Comment by jobisoft** [comment]
Are you sure, the calendar you see in lightning is managed by the Google Calendar and not by TbSync (during the update you could have removed the tbsync account but the calendar could have remained). What happens to that calendar, when you disable TbSync and the dav provider (the entire add-ons)?

**Comment by tigerjack** [comment]
Google calendar is still there (and it's somehow expected). The strange thing is that also fruux remains there :/ 
Btw, when I disabled TbSync, I found the culprit. There was a Google Contacts calendar and an `Enable` button near it. Unsubscribing from it resolved the original issue.

Still, I can't figure out where the fruux account is coming from. I didn't configure it yet in the add-on. Is it there from before the update?

**Comment by jobisoft** [comment]
The calendars you see in lightning only have a weak connection to the TbSync manager. If you remove TbSync , it will not delete the calendars. If an update fails and the TbSync database is cleared, TbSync forgets about your calendars/accounts, but does not delete them.

You can just remove the calendar or keep it. It is disconnected from the TbSync Manager, but continues to work, as it is a standard caldav calendar, which lightning knows how to handle.

For the google calendar, if TbSync and its DAV provider are disabled, but the calendar was originally setup by TbSync, lightning no longer knows how to handle that calendar, and it should get disabled or at least should no longer sync.

**Comment by tigerjack** [comment]
Thanks for the clarifications. So, basically, to reconnect to my fruux account, I have to do the whole setup procedure from scratch, am I right? There is no way to "import" the lost values from Lightning to TbSync?

**Comment by jobisoft** [comment]
The values are not lost. Check your fruux online account / web interface. Everything should be there.

After you have checked that, you could remove the calendar from lightning and setup fruux via tbsync again. But there is no gain, if you only need that one calendar. TbSync is just adding the found calendars to lightning. Only if you need contacts as well, it is worth setting up everything again.
