### ISSUE TITLE
Inactive Calender with CalDAV Nextcloud "Devices & sessions" Password

### ISSUE THREAD

**Issue by kebechsenuef** [jobisoft/TbSync#493]
## Win10

TbSync version: 2.20
Thunderbird version: Thunderbird 78.7.0 (64-Bit)

## Expected behavior
-Storage of CalDAV Password in Thunderbird
-View of Calender with all events in it

## Actual behavior
- No active calender with view of all events
<kbd>![02_aktivieren](https://user-images.githubusercontent.com/6011872/106610502-28793100-6567-11eb-94ec-2d4e8e400984.JPG)</kbd>
- it is possible to "activate" calender (however why)
- Password from Nextcloud must be typed every time when you start Thunderbird (no storage)
<kbd>![03_errorLoginAfterStartThunderbird](https://user-images.githubusercontent.com/6011872/106610823-8148c980-6567-11eb-8bfc-a5f91513dad7.JPG)</kbd>

## Steps to reproduce
- Usage of a Nextcloud 20.0.0 Server instance
- Building a password in the "Devices & sessions" area

<kbd>![01_Nextcloud](https://user-images.githubusercontent.com/6011872/106610324-ef40c100-6566-11eb-821c-3ac9b06746ee.jpg)</kbd>

- Building a standard CalDAV calender and useage of the "Devices & sessions" password
- Integration in thunderbird 78.7.0 (64-Bit) with TbSync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Yes, i did it.

**Comment by kebechsenuef** [comment]
I thought maybe the path could play a role, but i can use a Calender with the format

https://[DOMAIN]/remote.php/dav/calendars/[USERNAME]/personal

Right now I'm feeling desperate 😔

**Comment by jobisoft** [comment]
I currently do not know what your issue really is. Did TbSync detect your calendars? Can you see them in the TbSync manager? Can you enable them there? What happens?
