### ISSUE TITLE
tbSybnc Repeated Credential Request 2021-02-10

### ISSUE THREAD

**Issue by ganakee** [jobisoft/TbSync#496]
## Your environment

TbSync version:2.12
Thunderbird version:68.10.0 x64
Lightning: 68.9.0
OS: elementary OS 5.1 (Ubuntu 18.04LTS)

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
tbSync will continue to function properly as it has for months by saving login credentials for outlook.com/live.com accounts so Calendar works.

## Actual behavior
Starting 2021-02-10, tbSync repeatedly demands login credentials on every sync attempt for the Calendar outlook.com/live.com account. The correct credentials are entered (3x). tbSync does not connect, sync., or save the correct credentials.

## Steps to reproduce
None. Simply started to fail. Enter correct credentials but TbSync does not save them nor is able to sync.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
outlook.com is probably forcing you to switch to the modern oauth2 authentication mode. remove your account from tbsync and set it up again using the 3rd option in the serup-type list (o365, modern)

**Comment by ganakee** [comment]
Thank you and thanks for the quick reply!

Your suggestion worked. For others who encounter this:
using outlook.com/live.com account

Suddenly, tbSync requests the account username and password on each sync attempt. Repeats request three times per sync but fails to login without any error message.

Go to the tbSync in the lower right corner of Lightning/Thunderbird and Open TbSync Account Manager. (If you previously setup logging using the Help Tab, you may see a 401 status denoting the login error.)

In the TbSync Account Manager window, select Account Settings tab.

Select the outlook.com/live.com account.
Use the Account actions dropdown to Delete Account.
Confirm deletion.
Now, use the Account actions drop down to Add New Account.
Select the Exchange ActiveSync type.
I used Automatic Configuration as the option.
Enter an account name, your outlook.com/live.com user name email address, and password.
Then use the Autodiscover settings and add account button.
Select the sync options (e.g., Contacts, Calendar, US Holidays.)
Select Sync Now.

Now the account syncs again.
