### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by wandth** [jobisoft/TbSync#5]
First of all. Great that you are putting life in this plugin again! I used the old one which stopped to work properly and so far was the only good way to get ActiveSync support in Thunderbird.

I was following your progress over the last weeks. Is there any roadmap or do you have a plan to release it officially one day?

**Comment by jobisoft** [comment]
I did send the latest version of the AddOn to Mozilla:

https://addons.mozilla.org/de/thunderbird/addon/tbsync/

However, they take very long to check new AddOns at the moment, I do not 
know, when it will be officially listed. Furthermore, this is a XUL 
AddOn, and I do not know, if the restriction for Firefox AddOns will 
also apply to Thunderbird AddOns. I may have to rewrite the GUI part.

My roadmap is here (what I want to do till v1.0):

https://github.com/jobisoft/TbSync/#roadmap

Future releases will be as follows:

v0.7.0: all calendar stuff done
v0.7.5: tasks
v0.8.0: rewrite contacts part (this is the only place, where TzPush code 
is used, but I want to use a different method, which is more easy to 
maintain)
v0.8.5: global address book (if possible)

v0.9: release candidate for productive use - get user feedback, fix bugs
v1.0: stable release

I have no idea, what I might add after v1.0 - and when this will be.

**Comment by wandth** [comment]
Thx for the update! I saw the points on the project page but was interested if there is any schedule behind. And yes, stupid time for XUL GUIs as a lot of things might break in the future...

**Comment by jobisoft** [comment]
Closing, since I added the roadmap to the README.md
