### ISSUE TITLE
Status bar shows "TbSync: Idle" but events sidebar is updating

### ISSUE THREAD

**Issue by cweiske** [jobisoft/TbSync#500]
## Your environment

TbSync version: 2.20
Thunderbird version: 78.8.0
Provider for CalDAV: 1.24

[ ] Yes, I have installed the latest available beta version from https://tbsync.jobisoft.de and my issue is not yet fixed, I can still reproduce it.
[x] No, because the only commit seems to change a different part of the extension.

## Expected behavior
The status bar indicates that TbSync is doing something.

## Actual behavior
The status bar always shows "TbSync: Idle" (rough translation; I only see the German "TbSync: Leerlauf").
I've never seen it change.

But what I see is that the events sidebar is updating (thunderbird is pretty slow at that time; i have 19 calendars) and events are constantly appearing, disappearing and re-appearing.
I assume that TbSync is syncing in the background, and that this leads to the event list updates.
But still the status bar says that nothing is happening.

## Steps to reproduce
1. Let Thunderbird run
2. Wait until Thunderbird syncs and see events in the calendar sidebar appear and disappear
3. Look at the status bar

The same behavior can be triggered by opening the calendar view, right-clicking on a calendar and then "sync now".

**Comment by jobisoft** [comment]
CalDAV calendars are not managed by TbSync, only setup. So when they update, TbSync is not involved, but the native caldav implementation of Thunderbird. Only the EAS provider is really managing eas calendars. Are you using TbSync with the EAS or with the DAV provider?

**Comment by cweiske** [comment]
I use https://github.com/jobisoft/DAV-4-TbSync/

Then this ticket is invalid. Thanks for the explanation.
