### ISSUE TITLE
Tbsync cache format

### ISSUE THREAD

**Issue by gthieleb** [jobisoft/TbSync#502]
Hi, I want to use LibreOffice Mail Merge functionality with Thunderbird addressbook as a source. Addressbook data is provided by Nextcloud using TbSync Carddav provider.

Due to the changes introduced since TB78 the native ("Thundebird") LibreOffice addressbook is currently broken. A workaround to direct access via using sqlite odbc is described [here ](https://www.libreoffice-forum.de/viewtopic.php?f=2&t=32971) (german LO forum).

Is TbSync also caching its data in sqlite format in a seperate db file? Can I use the described approach?

**Comment by jobisoft** [comment]
Oh meine Güte, das ist ja übel. Ihr habt direkt mork Adressbücher eingebunden und die unabhängig von Thunderbird manipuliert? Von hinten durch die Brust? *schauder*

Ich würde euch das nicht mit dem neuen SQL Format empfehlen, das Format kann sich jederzeit ändern.

TbSync arbeitet mit den standard Thunderbird APIs und dem ist das völlig egal, was Thunderbird da intern als Speicherformat benutzt.

VG
John

**Comment by gthieleb** [comment]
Hey John, danke für deine Antwort. 

Nunja ich habe den Workaround rudimentär überflogen und der Ansatz funktioniert soweit. Es soll als Workaround dienen bis eine Anpassung der nativen ThunderBird Integration im LibreOffice erfolgt. 

Da Du tief in der Materie steckst: Kennst Du eine Übersicht welche Api-Calls sich bzgl. des TB Adressbuchs geändert haben?

Beste Grüße,
Gunnar

**Comment by jobisoft** [comment]
Ich denke nicht das er hier um die APIs geht. Wenn ich euch richtig verstanden habe, öffnet ihr die Daten-Datei des Adressbuchs und fummelt da selber drin rum und manipuliert somit hintenrum das Thunderbird Adressbuch. Und weil sich das Format geändert hat, geht das nun nicht mehr.

**Comment by gthieleb** [comment]
> 
> 
> Ich denke nicht das er hier um die APIs geht. Wenn ich euch richtig verstanden habe, öffnet ihr die Daten-Datei des Adressbuchs und fummelt da selber drin rum und manipuliert somit hintenrum das Thunderbird Adressbuch. Und weil sich das Format geändert hat, geht das nun nicht mehr.

Nein, mir geht es um den Aufwand der auf Seite von LibreOffice besteht, die Änderungen dort zu proposen bzw. einen RFE zu erstellen.

**Comment by jobisoft** [comment]
Da habe ich leider keine hilfreichen Informationen, weil ich nur die APIs benutze und nicht die Daten-Dateien (weder die alten mork, noch die neuen SQL) von Hand öffne und bearbeite.

**Comment by gthieleb** [comment]
OK, ich danke dir für deine Zeit.
