### ISSUE TITLE
Period synchronization not working?

### ISSUE THREAD

**Issue by Rotaryracer** [jobisoft/TbSync#507]
## Your environment

TbSync version: 2.20
CalDAV/CardDAV version: 1.24
Thunderbird version:  78.8.1 64-bit

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

No, checked beta directory and beta appears to be older than stable version installed.

## Expected behavior

I have entered a number in the "Periodic Synchronization (in minutes)" field, but it does not seem to auto-synchronize.  I have tried different numbers on the chance there was a min/max amount, but no luck.  If I hit the "Synchronize now" button, it syncs perfectly, but will not do so on a periodic basis.

## Actual behavior

Nothing - does not synchronize on a periodic basis, regardless of what is entered.

## Steps to reproduce

Enter number into field, wait appropriate amount of time, check for sync error "Account needs to be synchronized, at least one item is out of sync".

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

Aside from periodic sync issue, this add-on works beautifully!  Thank you very much for your hard work making this available to Thunderbird users.

**Comment by jobisoft** [comment]
I cannot reproduce this. If I enter `1` into the `Periodic synchronization` field, it syncs every minute. Anything in the logs?

**Comment by Rotaryracer** [comment]
> I cannot reproduce this. If I enter `1` into the `Periodic synchronization` field, it syncs every minute. Anything in the logs?

Thank you.  I have the logs running on one of my machines and will send/upload that log this weekend.  I just enabled logging on the 2nd machine as well to see if I can come up with something. 

Looking at the logs on the first machine, it does appear to be sync'ing, so it may just be an error message I was seeing stating that something was out of date.  Does synchronization actually push/pull updates between the server and the client, or is it basically just advising that something is different and you have to push the sync button manually?  The latter seems to work and returns me to an 'ok' state; the former, I'm not sure...hopefully you can find something in the logs.

I do have another odd issues that has popped up - I can open a separate ticket if needed, but I created a new contact in my iPhone, which has all it's contacts sync'd to Google.  TBSync is only syncing contacts with Google (not calendars), and multiple automated syncs have occurred (I think) across both machines.  If I go directly to Google Contacts, I can see the contact has uploaded; however, it is not appearing in the Thunderbird address book created by TBSync/Provider for CardDAV/CalDAV.  I've tried manually hitting the sync button a few times to no avail.  Any thoughts?

Thanks again...

Jason

**Comment by jobisoft** [comment]
> Looking at the logs on the first machine, it does appear to be sync'ing, so it may just be an error message I was seeing stating that something was out of date. Does synchronization actually push/pull updates between the server and the client, or is it basically just advising that something is different and you have to push the sync button manually? The latter seems to work and returns me to an 'ok' state; the former, I'm not sure...hopefully you can find something in the logs.

The periodic sync is doing the same thing as you clicking the sync button.

> I do have another odd issues that has popped up - I can open a separate ticket if needed, but I created a new contact in my iPhone, which has all it's contacts sync'd to Google. TBSync is only syncing contacts with Google (not calendars), and multiple automated syncs have occurred (I think) across both machines. If I go directly to Google Contacts, I can see the contact has uploaded; however, it is not appearing in the Thunderbird address book created by TBSync/Provider for CardDAV/CalDAV. I've tried manually hitting the sync button a few times to no avail. Any thoughts?

I am no longer supporting google. See
https://github.com/jobisoft/TbSync/issues/466

**Comment by jobisoft** [comment]
Supporting this developer could get you all back on track:
https://github.com/zanonmark/Google-4-TbSync

**Comment by Rotaryracer** [comment]
Thanks again - that extension looks like what I'm looking for.
