### ISSUE TITLE
HTTP 500 error when trying to sync all / large number of events

### ISSUE THREAD

**Issue by xj25vm** [jobisoft/TbSync#508]
## Your environment

TbSync version: 2.21
Thunderbird version: 78.9.0
Server is Horde 5.2.10 / Lighttpd 1.4.52

## Expected behavior
Sync all calendar events

## Actual behavior
If I select to sync only the last 6 months of events (about 300 in my case) - syncing works fine. If I configure to sync all events (about 11 000 in my case), no event is synced and I get the following error: "Communication error (HTTP Status 500)"

## Steps to reproduce
I do not know if the above happens because I configured to sync all events - or because I have a large number of events to sync.

I tried to enable debugging - but I get "cannot find any useful debug messages" when I try to view the log. If I sync only the last 6 months, there is a proper log being generated.

**Comment by jobisoft** [comment]
Contact your service provider, an HTTP 500 indicates, that there are some issues on the server side.

**Comment by xj25vm** [comment]
Thank you for looking into this. I am my service provider :-) In case it helps anyone else - in the Horde logs I get the following:

ERR: HORDE Returning HTTP 500 while handling Sync command. Error is: SQLSTATE[54001]: Statement too complex: 7 ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.

I increased max_stack_depth in postgresql.conf to from 2MB to 7MB (max 8MB system stack limit on this server) - and it has just started to sync all the 11260 items. Interestingly, there was no problem uploading exactly the same data set to the server - the issue only surfaced when I tried to download them from the server into Thunderbird.

I wonder what would be the solution when someone doesn't have access to their backend and can't convince the service provider to change settings?

**Comment by jobisoft** [comment]
> Thank you for looking into this. I am my service provider :-) In case it helps anyone else - in the Horde logs I get the following:

Great, so they will most likely listen to your needs! :-)

> I wonder what would be the solution when someone doesn't have access to their backend and can't convince the service provider to change settings?

Nothing much. Except a more expensive "premium service contract", probably.

**Comment by xj25vm** [comment]
Do you think it would be possible to restructure that query so that it pulls less data - or maybe splits it into smaller chunks?

**Comment by jobisoft** [comment]
No, the protocol has a dedicated "chunk-up" implementation, but your server does not seem to use it.

**Comment by xj25vm** [comment]
Ok - thank you again for taking the time.
