### ISSUE TITLE
Unable to expand mailing list nickname in Compose window

### ISSUE THREAD

**Issue by miskovics** [jobisoft/TbSync#509]
## Your environment

TbSync version: 2.21
Thunderbird version: 78.7.1

- [ ] Yes, I have installed the latest available beta version from https://tbsync.jobisoft.de and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After typing mailing list nickname into `To` and hitting <kbd>ENTER</kbd>, the list is expanded into the list name or into the email addresses on it.

_In the Compose window, type the nickname for the mailing list in the "To" field and press the Enter key. The name shown in the "To" field should change to the full name of the mailing list._ 
-- http://kb.mozillazine.org/Thunderbird_:_FAQs_:_Create_Mailing_List

## Actual behavior
After typing mailing list nickname into `To` and hitting <kbd>ENTER</kbd>, the list is replaced with a grey empty box.

## Steps to reproduce
1. Add a new mailing list in an Address Book with a nickname.
2. `Message` » `New Message` in Inbox.
3. Type nickname and hit <kbd>ENTER</kbd>.

**Comment by jobisoft** [comment]
I think TB78 does not expands lists. For me, entering the nick of a list resolves to `listname <description>`. Is this related to TbSync adressbooks only? Does it still happen with TB78.9?
