### ISSUE TITLE
ActiveSync protocol violation: Mandatory field <Provision.Status> is missing in server response.

### ISSUE THREAD

**Issue by gabrieletassoni** [jobisoft/TbSync#51]
Hi,
I'm trying to sync Zentyal server 5.0.10 with calendar and address book of Thunderbird, whenever I click on Connect I get as an answer that error.
Googling I found that some suggest to remove the check on provision in TBSync configuration, but I cannot understand where to find that checkbox since I can't see it in the GUI.

```
TbSync version: 0.7.3
Thunderbird version: 52.6.0 (64-bit)
```

## Expected behavior

Sync calendar and address book.

## Actual behavior

No sync and the error on the subject. 

## Steps to reproduce

1. Install Zentyal activate ActiveSync and create a user.
2. Install TBSync
3. Configure TBSync

**Comment by jobisoft** [comment]
That is a bug in 0.7.3. Should be fixed in the latest beta. Please retry:
https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta8.xpi

**Comment by gabrieletassoni** [comment]
Thank you very much, I found also that using 0.6.8.2 version of TBSync, in which I found a checkbox for disabling provisioning, the sync process works.
Tried the beta 0.7.4 and it works also!
Thanks.

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
