### ISSUE TITLE
Events disappear and reappear when syncing a Nextcloud calendar

### ISSUE THREAD

**Issue by cnmicha** [jobisoft/TbSync#512]
## Your environment

TbSync version: 2.21
Thunderbird version: 78.10.1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Having opened the "today pane" or the calendar tab, syncing happens in the background. No calendar events disappear.

## Actual behavior
Having opened the "today pane" or the calendar tab, all calendar events disappear and reappear after 1-2 seconds, when a sync has been done.

## Steps to reproduce
1. Add a Nextcloud CalDAV calendar that has some events
2. Do an initial sync
3. Open the "today pane" or calendar tab
3. Wait until TbSync syncs automatically or hit the "Synchronize now" button in the addon preferences, keep an eye on the "today pane" or calendar tab

**Comment by NicolaiRuckel** [comment]
I have the same problem with my Posteo calendar.

**Comment by jobisoft** [comment]
This should be independent of TbSync, because I use Thunderbirds native CalDAV sync. Maybe play with offline support.
