### ISSUE TITLE
Not (yet) compatible with TB 89

### ISSUE THREAD

**Issue by vdanjean** [jobisoft/TbSync#516]
Hi,

I upgraded TB from 78.11 (unstable) to 89.0b2 (experimental) in Debian hopping to solve other TB problems, but I just saw that TbSync extension is not marked as compatible with this TB version. I do not know if some developments are required or not to make it compatible (but, for now, new events created by other people in shared calendars do not show up).

Regards,
   Vincent

**Comment by meichthys** [comment]
For reference i can also confirm that TBSync is not yet compatible with TB 92 (Daily) as of 7/27/2021

**Comment by jobisoft** [comment]
Working in on it right now (TB91)

**Comment by jobisoft** [comment]
Which provider are you using? I have test versions for TbSync + DAV. Could you try them in a new profile?
[TbSync-beta.zip](https://github.com/jobisoft/TbSync/files/6888914/TbSync-beta.zip)
[DAV-4-TbSync.zip](https://github.com/jobisoft/TbSync/files/6888917/DAV-4-TbSync.zip)

Tested in TB91. You can just install the ZIP files (via the gear icon in the add-on manager -> Install Add-on From File...) , no need to rename them to XPI.

Thanks.

**Comment by meichthys** [comment]
@jobisoft I'm using DAV with Nextcloud. I'll give it a try tomorrow. 👍

**Comment by meichthys** [comment]
@jobisoft Everything appears to work as expected. The only thing I noticed was that the new DAV account form layout broke:
![image](https://user-images.githubusercontent.com/10717998/127344720-2f3a1a36-cf68-42fd-b3f8-9b50d8e127ea.png)

One other thing i noticed (it may have happened in the past as well, but i cant remember: When setup a DAV account and it imports my tasks, it also creates an associated calendar in TB even though the server doesn't show that the calendar exists (I'm using Nextcloud)

**Comment by meichthys** [comment]
Perhaps this is expected with this test version, but i noticed that after restarting TB the DAV accounts are removed from TBSync:
![image](https://user-images.githubusercontent.com/10717998/127351881-1f703540-370a-4703-871c-2863415aff71.png)

**Comment by jobisoft** [comment]
1. it is not expected to discard all account when going from 78 to 91, will check that

2. I forgot to update the create new account wizard, will do

3. not sure about the calendar duplication, I am pretty confident that I do not do that. Maybe it is just the fact that the task calendar is shown in both views? In the calendar view and in the task view? Do you know from logs, if the task calendar is announcing itself as supporting VEVENT and VTODO? I thought I had code added to hide them in the unsupported views.

**Comment by meichthys** [comment]
> 
> 1. it is not expected to discard all account when going from 78 to 91, will check that 2. I forgot to update the create new account wizard, will do 3. not sure about the calendar duplication, I am pretty confident that I do not do that. Maybe it is just the fact that the task calendar is shown in both views? In the calendar view and in the task view? Do you know from logs, if the task calendar is announcing itself as supporting VEVENT and VTODO? I thought I had code added to hide them in the unsupported views.
> […](#)
> Am 28.07.2021 um 17:35 schrieb MeIchthys ***@***.***>: Perhaps this is expected with this test version, but i noticed that after restarting TB the DAV accounts are removed from TBSync: — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

On 1, i didn't loose my accounts when I upgraded TB, I lost them when I restarted TB.
On 3, that could be the case. I did run into something similar in Nextcloud where I needed to have "show tasks in calendar" disabled in order to be able to create a stand-alone task list (without it creating/displaying an associated calendar). The setting was disabled when I setup the DAV accounts in TBSync, so it seems like that wouldn't be the issue, but I'm not sure how things work on the back-end.

**Comment by jobisoft** [comment]
This is version 2.0.1 of the DAV provider. It should fix the create new
account wizard and a few other UI glitches. Could you give it a a spin?

Thanks,
John

**Comment by jobisoft** [comment]
Looks like I cannot attach files via email here. So you would need to
download the current master branch and zip it yourself :-( I currently
do not have access to my github account...

https://github.com/jobisoft/Dav-4-TbSync/

John

**Comment by meichthys** [comment]
I probably won't get around to testing it until Monday. I'll follow up here if/when I get to test it.

**Comment by jobisoft** [comment]
You also have to build your own version of TbSync itself from its master branch, because I had to fix something there as well.

**Comment by meichthys** [comment]
Unfortunately I don't have time to test this at the moment since we deployed a different solution. I will follow up here if I re-visit TBSync soon. Keep up the great work!

**Comment by meichthys** [comment]
@jobisoft I'm going through some loose-end issues and wanted to help close this one. 
Could you clarify what i would need to zip up to install as an addon, or could you provide a zip for me to test?

**Comment by skrap** [comment]
@jobisoft I'm happy to build from `master` and test for you on TB91.  Are there build instructions somewhere?

**Comment by jobisoft** [comment]
The versions for TB91 have been uploaded to ATN. So once you updated to TB91, you will get the new versions automatically.

John

**Comment by skrap** [comment]
Works great! :rocket: awesome, thanks!
