### ISSUE TITLE
Address Book generated by TbSync does not work in TB 90.0b1

### ISSUE THREAD

**Issue by lpyoung01** [jobisoft/TbSync#517]
## Your environment

TbSync version: 2.21
Thunderbird version: 90.0b1

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
...Addresses contained in TbSync generated address book should be searchable from TB.

## Actual behavior
...Addresses contained in TbSync generated address book are not searchable from TB Beta.

## Steps to reproduce
...Had upgraded from TB release version to latest Beta version and contacts contained in the address book generated by TbSync from my Google contacts were not searchable when I typed their contact information in the To: field of TB.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Should be fixed now.
