### ISSUE TITLE
 Outlook"s Middle Name and Thunderbird's Display Name

### ISSUE THREAD

**Issue by JacquesBelge** [jobisoft/TbSync#52]
Your environment: French Windows 10 Professionnel
TbSync version: 0.7.3
Thunderbird version: 52.6.0 (32 bits)

1) Initially, I wanted to know how to define the “Display Name” as «First Name» «Last Name» because, after synchronization, I saw  «Last Name», «First Name».
Is there an option to choose this presentation?

2) After investigation, I understand the process:
Contacts from Outlook.com have: “First Name”, “Middle Name”, “Last Name”
And in Thunderbird Address Book: “First Name”, “Last Name”, “Display Name”
When I synchronize new contacts:
Outlook-»Thunderbird: “Display Name” = «Last Name», «First Name» «Middle Name»
Thunderbird -» Outlook: “Display Name” is lost.
With existing contacts:
Outlook-»Thunderbird: “Display Name” is not modified
Thunderbird -» Outlook: “Display Name” is ignored, «Last Name» and «First Name» are synchronized and «Middle Name» doesn’t change.
Is it possible to parameterize the synchronization for those fields?

Thank you for this module that gave me the possibility to move from Windows Live Mail to Thunderbird with my contacts in Outlook.com.
Jacques.

**Comment by jobisoft** [comment]
Thanks for the detailed report. I am going to fix this as soon as I started to work on the v0.8.x branch.

The current contact sync code is a black box to me. I took it from the TzPush plugin and used it as a starting point. I added the manager UI, autodiscover, and calendar/task sync using a different programming method. After the v0.7.x  branch is [done](http://github.com/jobisoft/TbSync/wiki/Roadmap), I am going to rewrite the contact sync code using my own method and fix all the reported contact sync bugs.

However, I cannot give you a timeframe.

**Comment by JacquesBelge** [comment]
Thank you for the quick answer.

My target is to have the contacts reference in Outlook.com so I can share them between PC and iPhone.
I’ll continue to investigate.

**Comment by jobisoft** [comment]
But do not waste time on this. I will rewrite the contact sync code from scratch, so the findings of your investigation will probably not apply to "my" version.

I am unable to fix the current version because it is not my code and I decided to take it "as is" without spending time on trying to understand it.

**Comment by jobisoft** [comment]
Thunderbird does not have a middle name field. Can I just parse the FirstName field, and if it contains a space (so more than one word) send the last word as "middlename" and the remains as "firstname"?

**Comment by jobisoft** [comment]
Nevermind, I just added a dedicated MiddleName field to the Thunderbird address book.

![image](https://user-images.githubusercontent.com/5830621/40284761-184807d6-5c94-11e8-98da-6940e8bae143.png)

This issue is a subset of issue #6. Thus closing.
