### ISSUE TITLE
"Could not connect to server (UNKNOWN_NETWORK_ERROR)"

### ISSUE THREAD

**Issue by Svedrin** [jobisoft/TbSync#520]
## Your environment

TbSync version: 2.22
Thunderbird version: 78.11.0 (64-bit)

> [ ] Yes, I have installed the latest available beta version from 
> https://tbsync.jobisoft.de
> and my issue is not yet fixed, I can still reproduce it.

not yet, are there relevant changes in there that might address this?

## Expected behavior

TbSync with Nextcloud should still work after a restart of Thunderbird.

## Actual behavior

When I set up everything for the first time, it works beautifully.

After I restart Thunderbird, I only get `UNKNOWN_NETWORK_ERROR` as seen in #434.

## Steps to reproduce

1. Set up TbSync with NextCloud.
2. Observe that it works.
3. Restart Thunderbird.
4. The calendar is now unavailable and TbSync displays `UNKNOWN_NETWORK_ERROR`.

`debug.log` shows this:

```
** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[setSyncState] : State: send.getfolders, Account: Nextcloud

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[setSyncState] : State: send.getfolders, Account: Nextcloud

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[URL Request #1] : https://example.com/nextcloud/remote.php/dav/principals/users/my_user/

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[EventLog] : network::UNKNOWN_NETWORK_ERROR
URL:
https://example.com/nextcloud/remote.php/dav/principals/users/my_user/ (PROPFIND)

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[EventLog] : network::UNKNOWN_NETWORK_ERROR
URL:
https://example.com/nextcloud/remote.php/dav/principals/users/my_user/ (PROPFIND)

** Fri Jun 25 2021 12:25:03 GMT+0200 (CEST) **
[setSyncState] : State: accountdone, Account: Nextcloud
```

**Comment by Svedrin** [comment]
When I create the calendar manually, Thunderbird displays "Authentication error". This is also what I suspected. Is it possible that the password didn't get stored correctly? Unfortunately it doesn't prompt me again though.

**Comment by Svedrin** [comment]
Removing the entry from the password store didn't help; also I can't recreate the account in TbSync because basically any communication to that server fails now. Other servers "work" in the sense that I get different errors (I don't have any other nextcloud instance to test with).

**Comment by Svedrin** [comment]
It started to work again after a week or two - maybe rebooting helps? :thinking:

**Comment by jobisoft** [comment]
Maybe this is due to some fail2ban rule on your server, which blocks TbSync?

**Comment by Svedrin** [comment]
@jobisoft in this case I should be seeing errors with all my other nextcloud clients on the same network too though, because they all go through the same endpoint - they work just fine though.

For some reason I can't get it to break by restarting Thunderbird anymore either, which reliably broke it back when I reported this issue. :man_shrugging: Feel free to close, not sure what's up with this...
