### ISSUE TITLE
[SOLVED] Could not connect to server (NS_ERROR_NET_TIMEOUT)

### ISSUE THREAD

**Issue by Jefunne** [jobisoft/TbSync#524]
## Your environment

Server
- Debian 10
- kernel 4.19.0-17-amd64
- NextCloud 20.0.2
- Apache 2.4.382.4.38

Client
- Debian testing
- Thunderbird 78.12.0 (64bit)
- TbSync 2.22
- DAV-4-TbSync 1.24

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Testing configuration data and creating an account after entering the configuration data in TbSync Account Manager.

## Actual behavior
Testing configuration data and receive error message.
Could not connect to server (NS_ERROR_NET_TIMEOUT). Details in attached screenshot.

## Steps to reproduce
- Account actions -> Add new Account -> Call Dav & Card Dav -> Automatic Configuration
- Entering configuration data

I will reproduce this issue and send the debug log as described.
 
![TbSync_error_2021-08-07](https://user-images.githubusercontent.com/88597085/128613531-ee5b2886-1185-47ca-95fa-f36d667b413d.png)

**Comment by Phileosopher** [comment]
I've had the exact same issue for weeks. Not sure how it happened, but once I completely uninstalled TbSync and the CalDAV/CardDAV provider, then reinstalled, it worked fine. I'm assuming it was something that "unfactored" in an update.

**Comment by Jefunne** [comment]
@Phileosopher 
Thank you for your information, I will test the uninstallation / installation.

**Comment by Jefunne** [comment]
I was able to solve my problem. 
Within the nextcloud gui as admin user there is a an automatic scan of your installation when you enter the overwiew section. 
Here I go the output that my configuration for .well-known/carddav and .well-known/caldav is not correct. 

I have checked the Nextcloud documentation and searched a bit via google. I was able to fix these configuration part. Now Tbsync is working :-)

**Comment by Jefunne** [comment]
Solved. Missing configuration about .well-known/caldav and .well-known/carddav

**Comment by AminDar** [comment]
I have the same issue.
I manage to add my email with Tbsync but the calendars are not showing up, except the default calendar.
re-installing it again didn't help either.
![Screenshot from 2023-09-13 13-22-39](https://github.com/jobisoft/TbSync/assets/64411515/259554b4-7fa9-4867-bbbe-aa021da52a83)
