### ISSUE TITLE
tbsync options does not work.

### ISSUE THREAD

**Issue by MrErr** [jobisoft/TbSync#525]
## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Go to "Tools"->"Add-on Options"->"TbSync[Beta Release Channel]"  and an option box to appear. 

## Actual behavior
Go to "Tools"->"Add-on Options"->"TbSync[Beta Release Channel]"  and an option box does not come up. I also don't see a "spanner" icon when looking at the "Add-ons Manager" in thunderbird. 
![Screenshot from 2021-08-14 08-35-14](https://user-images.githubusercontent.com/39841986/129448026-016ba366-7e19-428a-9684-dc769ea8a421.png)
![Screenshot from 2021-08-14 08-36-43](https://user-images.githubusercontent.com/39841986/129448031-4bf91744-f96d-4b7e-9386-bdb76983fcce.png)

## Steps to reproduce
Add TbSync from beta channel to Thunderbird.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
The Beta version is currently not maintained and old. It fell of the table and I probably have to discard it altogether. Please switch to the released version on ATN.
https://addons.thunderbird.net/addon/tbsync/

The current ways to open the TbSync account manager are listed on the getting started wiki page:
https://github.com/jobisoft/TbSync/wiki/How-to-get-started#1-open-tbsync-account-manager
