### ISSUE TITLE
TbSync 3.0.1 Cannot Be Verified

### ISSUE THREAD

**Issue by FBobbioC** [jobisoft/TbSync#526]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.0 (64-bit)

[X] Yes, I have installed the latest available beta version from 
https://tbsync.jobisoft.de
and my issue is not yet fixed, I can still reproduce it.

After installing Mozilla Thunderbird 91.0 (64-bit) TbSync stops working.  I download TbSync 3.0.1 from https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/versions/?page=1#version-3.0.1 as an xpi file.  The file cannot be installed since it cannot be verified.

## Expected behavior
TbSync 3.0.1 xpi file installs without any issues

## Actual behavior
TbSync 3.0.1 xpi file cannot be verified

## Steps to reproduce
Install Mozilla Thunderbird 91.0 (64-bit)
Download xpi file from https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/versions/?page=1#version-3.0.1
Install xpi file -- Issue presents itself

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Right-click on the download link and save the XPI to disc and install it in Thunderbird, not Firefox (which happens if you left-click on the download link).

The most simple way however is to open Thunderbird`s add-on manager and install it from there directly.

![grafik](https://user-images.githubusercontent.com/5830621/129599431-dee83bd4-6012-4cda-8c19-3ab47aea4653.png)

**Comment by FBobbioC** [comment]
John,

I downloaded the xpi to the disc and installed it from Thunderbird. I 
have a video that shows the issue, if you want it

Regards,

F. Bobbio C.

**Comment by jobisoft** [comment]
Yes, the video would help.

Thanks
John

**Comment by FBobbioC** [comment]
Video sent.  I also checked on *xpinstall.signatures.required *which was 
already set to "False"

**Comment by jobisoft** [comment]
I do not see your video. You have to attach the file directly on the GitHub issue. Attachments of emails are not added.

**Comment by FBobbioC** [comment]
I have uploaded the mkv video file as a zip file.  Please let me know if you can open it on your side.  The 3.0.1 version of the xpi file is not under https://github.com/jobisoft/TbSync/releases but under https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/versions/?page=1#version-3.0.1
Could that be why the file is not signed?

[TbSync-2021-08-16_12.04.07.zip](https://github.com/jobisoft/TbSync/files/6995174/TbSync-2021-08-16_12.04.07.zip)

**Comment by jobisoft** [comment]
I do not know what is going on there.

1. Thunderbird does not sign add-ons (and does not verify them)
2. You already have TbSync installed, but disabled, without the enable slider, which means something is totally broken with that profile

Please try a fresh profile. Please also check if you have Enterprise policies enabled, which enforce signing-verification for some reason.

**Comment by FBobbioC** [comment]
John,

I finally got the time to try a new profile, which was unsuccessful.  
This machine is my personal machine, thus not having any Enterprise 
policies enabled.  I checked the xpinstall.signatures.required and it is 
set to false.  Even the tbsync addon that can be found within 
Thunderbird cannot be installed, with the same error

Regards,

F. Bobbio C.

**Comment by jobisoft** [comment]
Could you open the trouble shoot page (hamburger menu -> help -> trouble shoot information) and click on the send via email button? You can use my work address john@thunderbird.net

**Comment by jobisoft** [comment]
Other question, how did you install TB91? Do you have a tool, which informed you about the update for Thunderbird 78 and which installed it for you, or did you go to thunderbird.net and manually downloaded Thunderbird 91?

**Comment by jobisoft** [comment]
More questions: 
What OS are you using? 
Can you install the 32bit version of TB91 (from thunderbird.net) in parallel and check if that changes anything?

**Comment by FBobbioC** [comment]
OS is Slackware64-current and the TB91 version came from an official 
Slackware repository
