### ISSUE TITLE
rename account doesn't reflect in addressbook/calendar

### ISSUE THREAD

**Issue by azrdev** [jobisoft/TbSync#527]
## Your environment

TbSync version: 2.22
Thunderbird version: 78.12.0

## Behaviour
I can rename an account in the UI (see #91), by deactivating sync for that action.
I'd expect the previously synced address books and calendars to reflect this name change, but they retain their old name prefix.

**Comment by jobisoft** [comment]
The idea is to keep local names. You can change the calendar name and a name change of the account will not revert that. It is like that by design.

**Comment by azrdev** [comment]
Indeed I can rename calendars as described. Didn't expect that, thanks for pointing it out!
