### ISSUE TITLE
FTR: add account name as suffix instead of prefix to calendars

### ISSUE THREAD

**Issue by azrdev** [jobisoft/TbSync#528]
## Your environment

TbSync version: 2.22
Thunderbird version: 78.12.0

## Expected behavior
1. Create a TbSync account, named e.g. "Nextcloud", syncing some calendars (e.g. using caldav) named e.g. "A" and "B"
2. Create a new calendar event (or edit an existing one).
3. In the event editing mask, set keyboard focus to the calendar-selection drop-down
4. type A or B to select the calendar of that name

## Actual behavior
Since the TbSync account name is prefixed instead of suffixed to the (caldav) calendar name, typing only reacts to the tbsync name. e.g. N would select all "Nextcloud" calendars in turn.

<!--
## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I will accept a PR, but will not consider working on this on my own.
