### ISSUE TITLE
double calendar will be created

### ISSUE THREAD

**Issue by gerhardmu** [jobisoft/TbSync#53]
TbSync version: 0.7.3
Thunderbird version: 52.6.0

It happens with SOGO account that the app creates double calendar without visible reason. This second calendar is not existing in SOGO. The second receives another calendar icon and is empty. The second calendar cannot be removed, just unpublished.

[Persönlicher Kalender (Annett) #1.zip](https://github.com/jobisoft/TbSync/files/1778342/Personlicher.Kalender.Annett.1.zip)

![tbsync double calendar](https://user-images.githubusercontent.com/35499060/36944285-1d5435c0-1f99-11e8-953a-b0a1ef971f77.png)

**Comment by jobisoft** [comment]
Hi, the icon identifies the "second" "Persönlicher Kalender" as a tasks folder. The file you send indeed containes a few todo entries. They should show up in Thunderbird Aufgaben if you sync that folder. What looks strange, is the name of course.

Thunderbird itself does not distinguish between calendar and tasks folders, so you could add todo entries and calendar entries to the same "calendar". However, active sync does not support mixed folders. When syncing such a mixed folder to SOGo, maybe it split them up and created a dedicated task folder containing only the todo items? 

We can switch to german, if you want. We could also talk about this on the phone, just drop me an email.

Questions:
- what version of TbSync are you using? (Do not upgrade yet, please)
- can you log into SOGo webinterface and check for the task folder? Can you rename it?
- after renaming the task folder, can you try to reproduce this by adding a todo item to "Persönlicher Kalender (Annett)" (the calendar foder) and sync that to SOGo? Is SOGo creating a new task folder with the same name containing the new todo item?

BUT, I recently added checks to prevent just that, the latest version of TbSync is not syncing todo items to calendar folders and also does not allow to sync event items to tasks folders.

Yours,
John

**Comment by jobisoft** [comment]
As guessed, this is a "feature" of SOGo (or of your SOGo installation). The "Persönliche Kalender" in the WebUI can store both, events and todos. The EAS backend is actually using a calendar folder and a task folder for that, both named "Persönlicher Kalender". This is of course a bad naming convention, but that is what SOGo sends out.
