### ISSUE TITLE
Auto Sync Google Contacts hangs Thunderbird

### ISSUE THREAD

**Issue by josemata00** [jobisoft/TbSync#532]
## Your environment

TbSync version:
Thunderbird version: 91.0.3
Windows 10 21H1 x64

## Expected behavior
... Sync Google Contacts

## Actual behavior
... auto sync hangs thunderbird, no matter how long you wait.

## Steps to reproduce
... nothing, only wait auto sync TBSync with Google Contacts

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Using my caldav/carddav provider?
