### ISSUE TITLE
Project status post-TB91?

### ISSUE THREAD

**Issue by Victor239** [jobisoft/TbSync#533]
[I see that TB91](https://www.thunderbird.net/en-US/thunderbird/91.0/releasenotes/) is adding native CardDAV support, I'm curious if that means [DAV-4-TbSync](https://github.com/jobisoft/DAV-4-TbSync/) will be deprecated in favour of the native CalDAV/CardDAV support and if it'll allow you to focus instead on specialised integrations like Google/Exchange/EteSync support?

**Comment by jobisoft** [comment]
The integration for CalDAV and CardDAV is getting better and better in TB91, so I thionk at one point I will drop the provider. But for now, my provider still has some advantages (icon in address book, better contact edit UI) and in general the central managment.

**Comment by jobisoft** [comment]
Uups, missed the second part. Together with the google provider by Marco, I am working on a rewrite of the entire provider mechanism as WebExtension. This is a lot (as in huge) of work. After that basic "new" provider work is done, I can work on EteSync. I currently have no plans for EWS. But want to improve my EAS provider (meeting stuff).

**Comment by metlinux** [comment]
I hope you will continue DAV-4-TbSync, because the CardDav in Thunderbird (91) is still immature. It can e.q. not handle mutiple phone numbers of the same type (like 2 mobile work numbers, or 2 regular home numbers). They will just not be shown.

I for one will continue to be depended on DAV-4-TbSync as well as TbSync itself of course. I hope you keep supporting it!

**Comment by jobisoft** [comment]
TbSync will switch to native CardDAV Sync in Thunderbird 102. TbSync will still do the autodiscover of resources and central management, but my own sync code will be removed (it no longer works with the changed contact storage in 102 and I do not have the man power to rewrite my code).

If there are bugs in the new address book, they have to be filed and fixed.

**Comment by m10d** [comment]
> Uups, missed the second part. Together with the google provider by Marco, I am working on a rewrite of the entire provider mechanism as WebExtension. This is a lot (as in huge) of work. After that basic "new" provider work is done, I can work on EteSync. I currently have no plans for EWS. But want to improve my EAS provider (meeting stuff).

@jobisoft - sorry for the necropost, but this is the closest thing i found to "news" of etesync/tbsync integration.  I imagine this means it never came to fruition, but if you could share any info you know of status or plans it would be greatly appreciated!
