### ISSUE TITLE
Changing the schedule of events for the whole day

### ISSUE THREAD

**Issue by Miccio-AN** [jobisoft/TbSync#534]
I will try to explain this strange problem in detail:

O.S. Ubuntu 21.04 - Thunderbird 78.13 - Tbsync 2.22 - 
Synchronization with Google calendar - 
Timezone of Rome set both on the PC and on the Google calendar.

Everything "seems" to work perfectly.

1) If I add a new event, the time and date of the event is correctly stored. OK
2) If I change the time of a previous event (which had a specific date and time), the change is correctly recorded. OK

BUT: If I try to change a previous event that is set to "full day" by changing it to an event with a specific time, the time I set is increased by 2 hours. (I then have to change it - as in point 2 - then it is correct)

This thing is driving me crazy.

I do not know if it is correct to ask for the solution here, if it is not, I apologize in advance.
In case this is the right place to ask for assistance, thank you for any help.

**Comment by jobisoft** [comment]
I no longer support google.
