### ISSUE TITLE
Thunderbird 91.1.1 TbSync 3.0.1 with Nextcloud 405 method not allowed

### ISSUE THREAD

**Issue by pierrehenrymuller** [jobisoft/TbSync#536]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.1.1
NextCloud : 21.0.4

## Details
Today with the latest Thunderbird 91.1.1 update, TBSync can't connect from 3 computers with differents accounts to 2 differents NextCloud with message status: 405.
The two NextCloud works good with DaVx5 on Android for calendars and contacts.

On the Nextclouds servers logs, I don't see authentication for requests from TBSync : 
```
PROPFIND /remote.php/dav/principals/users/xxxx/ HTTP/2.0" 405 150 "-" "Thunderbird CalDAV/CardDAV"
```

## Steps to reproduce
The only thing who have changed since friday is Thunderbird from 91.1.0 to 91.1.1 (but I'm not sure about that, Thunderbird is updated automaticaly in background to the latest version, so maybe 91.0.3 if the update have not launched).

## The debug
```
** Mon Sep 20 2021 12:11:03 GMT+0200 (heure dété dEurope centrale) **
[setSyncState] : State: send.getfolders, Account: Perso

** Mon Sep 20 2021 12:11:03 GMT+0200 (heure dété dEurope centrale) **
[URL Request #1] : https://XXXX/remote.php/dav

** Mon Sep 20 2021 12:11:03 GMT+0200 (heure dété dEurope centrale) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

** Mon Sep 20 2021 12:11:03 GMT+0200 (heure dété dEurope centrale) **
[RESPONSE] : 405 (Method Not Allowed) : <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


** Mon Sep 20 2021 12:11:03 GMT+0200 (heure dété dEurope centrale) **
[EventLog] : 405
URL:
https://XXXX/remote.php/dav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
<html>
<head>
<title>405 Not Allowed</title>
</head>
<body>
<center>
<h1>405 Not Allowed</h1>
</center>
<hr>
<center>nginx</center>
</body>
</html>
```

I have tried to remove an account and reconfigure but I have the same response 405.

**Comment by pierrehenrymuller** [comment]
Ok I have find the problem.

When Nginx catch 401 error for php of NextCloud and don't forward the request to NextCloud, TBSync get an 405 error and never resend request with authentication.
But when NextCloud return 401, TBSync make a request with credentials for webdav access.

Davx5 launch directly request with credentials and works with error catch.

**Comment by fruffy** [comment]
Hello, I am running into the same issue. What exactly was the fix to this problem?
