### ISSUE TITLE
Exchange Active Sync stopped working

### ISSUE THREAD

**Issue by jcs0596223** [jobisoft/TbSync#539]
## Your environment

TbSync version:2.22
Thunderbird version: 78.14.0 (64-bit)

## Expected behavior
I use TbSync with the Exchange Active sync. This has been updating my Microsoft Outlook.com calendar which in turn updates my Android phone calendar

## Actual behavior
Today it is prompting me to enter a password to my Microsoft account and when I put the password in it still fails to connect
...

## Steps to reproduce
Open Thunderbird with Exchange Active Sync and TbSync...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
That happens from time to time, do not know why. Remove the account from TbSync and set it up anew.

**Comment by misar1** [comment]
I have the same problem but sometimes removing the account from TbSync does not work. There are two other fixes which I have found to work at different times.
Remove and reinstall EAS.
The TbSync account settings tab has a drop down menu for the EAS version. The options are Best available, v 2.5 and v 14.0. If it is on Best available try v 2.5.
