### ISSUE TITLE
Calendar updates not syncing to Office 365

### ISSUE THREAD

**Issue by nitro322** [jobisoft/TbSync#54]
## Your environment

```
TbSync version: 0.7.3
Thunderbird version: 52.6.0
```
## Expected behavior
Bi-directional calendar synchronization between Thunderbird and Office 365

## Actual behavior
Synchronization from Thunderbird to Office 365 fails with the following error message:
Sync failed. Server responds with status <Sync.Collections.Collection.Responses.Add[0].Status = 6>.

## Steps to reproduce
1. Connect Account
2. Unsubscribe from Tasks and Contacts syncing (only sync calendar)
3. Synchronize and verify success - all calendar events are synchronized to Thunderbird
4. Accept meeting invite
5. Synchronize and receive error - updated meeting is not synchronized back to Office 365

**Comment by jobisoft** [comment]
Before I dig into this, can you please check, if the error remains with the latest beta?

https://github.com/jobisoft/TbSync/releases/download/v0.7.3/TbSync-0.7.4-beta8.xpi

Thanks
John

**Comment by jobisoft** [comment]
I just released v0.7.5. Please re-try with that version:
https://github.com/jobisoft/TbSync/releases/download/v0.7.5/TbSync-0.7.5.xpi

Thanks,
John

**Comment by nitro322** [comment]
Hello.  Sorry for the slow reply - didn't get a chance to test until this afternoon.  It appears that the 0.7.5 release did fix this issue.  Thanks for the incredibly fast response!  I'll close this request.

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).

**Comment by nitro322** [comment]
Already done.  :-)

FYI (just some general feedback) - I was troubleshooting an issue this morning where synchronization began failing again and completely disconnected/uninstalled/reinstalled the extension to see if 0.7.6.8 fixed that problem.  After setting up with the new version, it seemed to be syncing properly, but was not pulling any data down for my calendar.  After letting it sit for a while, it eventually synchronized my calendar data.  I ran into this once before myself, and also see it mentioned in issue 61.  Not sure if this is being triggered on your side or Office 365 (I'd expect the latter), but may be worth investigating and, at least for now, calling out in your documentation.

Thanks for your ongoing work with this.

**Comment by jobisoft** [comment]
1. I re-added the menuitems, do you get an update notification? Does the direct update work? 

2. Are you sure, TbSync has finished sync, when you observed "nothing is being pulled down"? If he is finished, all account have a green tick and the overall status (lower right corner / status bar) is "Idle".

The account manager gives detailed information on what he is doing at the moment. For O365 I see him waiting for responses from time to time for about 30s. In these wait states, the overall status is still "syncing". Sometimes, he even runs into a timeout, which aborts the sync. If you have setup a sync intervall, he will try again later. Could that explain "eventually synchronized my calendar"?

![image](https://user-images.githubusercontent.com/5830621/38270894-2008e87a-3785-11e8-9157-eb64f9aa25a3.png)

Also, if you have lots of data to sync, it will take a while, usually TbSync grabs data in chunks of 50 elements, this progress is also shown in the account manager: 0/24 in the above picture.

**Comment by nitro322** [comment]
1. I don't see anything prompting me to update the extension right now, but I'm not certain of where to look.  I'm also on a firewalled network behind an explicit proxy, so depending on how that update check works I may not be a good test case.  If it taps into Thunderbird's normal update mechanism then it should work fine, but if it makes its own calls out to the internet and doesn't respect my proxy settings then the update check will likely fail.

2. Yeah, that's the behavior I observed - everything reported it had completed synchronizing and was Idle.  I re-synchronized multiple times with the same result.  Uninstalled and re-installed two older versions (0.7.4 and 0.7.6) with the same result.  Deleted all of the "thunderbird" activesync associated with my O365 account and restarted thunderbird with the same result.  Came across the comment in that other post about waiting and remembered that I had seen something similar previously, so tried leaving it alone for a while, and after a while events started populating on their own.  It's really weird.

I do have an awful lot of meetings, but again, it didn't indicate that it was synchronizing and taking a while; it reported that it successfully synchronized (with 0 events) and was idle.  I'm reluctant to mess with it too much now since it's working again, but if this is something you're actively trying to investigate I can try to schedule some time to try to intentionally break this again to provide additional details.

**Comment by jobisoft** [comment]
Once you restarted Thunderbird, he will get the new version information and inside the account manager, there will be a new "Update TbSync" Icon:

![image](https://user-images.githubusercontent.com/5830621/38271880-f07dff66-3787-11e8-91ba-9b6e3781e768.png)

Does it work?

**Comment by nitro322** [comment]
Ahh, yes.  After restarting I do see the update icon now showing 0.7.6.9.  Some feedback (assuming you're interested):

* Clicking the version number directly opened the extension in Thunderbird and allowed me to first save the file or anything like that.  Very handy.

* After the update completed, I don't see any message indicating that Thunderbird needs to be restarted like after a normal update.  Viewing 'More' on the TbSync extension page also shows the new version.  Again, slick.

* However, if I then click on the TbSync button, I get a message that, "TbSync has not yet finished its init sequence!".  Restarting Thunderbird yields the same result. As of now it doesn't appear that I have any way to get it working again without uninstalling and reinstalling the extension.

I happened to have debug logging enabled from the previous issues and found the following output after a fresh Thunderbird restart:

** Tue Apr 03 2018 14:52:58 GMT-0500 (CDT) **
[JavaScript Error: "A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Apr 03 2018 14:52:56 GMT-0500 (CDT)
Full Message: Node was not found
Full Stack: JS frame :: chrome://tbsync/content/tbsync.jsm :: tbSync.init< :: line 104
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl_run :: line 319
JS frame :: resource://gre/modules/Task.jsm :: TaskImpl :: line 277
JS frame :: resource://gre/modules/Task.jsm :: createAsyncFunction/asyncFunction :: line 252
JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/jbreland/.thunderbird/sy5mwa82.default/extensions/tbsync@jobisoft.de.xpi!/bootstrap.js :: onLoadObserver.observe :: line 18
JS frame :: chrome://messenger/content/msgMail3PaneWindow.js :: completeStartup :: line 603" {file: "chrome://tbsync/content/tbsync.jsm" line: 104 column: 0 source: "104"}]

**Comment by jobisoft** [comment]
Thats a bug, injecting the TbSync Menu failed. What OS are you on? What TB version?

**Comment by nitro322** [comment]
Linux (gentoo amd64).  Thunderbird 52.6.0.  I can leave it in this state for the rest of the afternoon if there's anything you'd like me to test.

**Comment by jobisoft** [comment]
I hope I can send you a fix within a couple of minutes...

**Comment by jobisoft** [comment]
Can you try this:
https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.9.xpi

I did not change the version number, it is still 0.7.6.9, but something fixed. If it does not work, can I have the full debug log? (via email)?

**Comment by nitro322** [comment]
That did the trick.  Thanks!  I know I've commented on this before, but it's just astonishing how quickly you respond to, and fix issues.  I hope you're able to keep up that pace.  :-)

**Comment by jobisoft** [comment]
If you ever see some pattern in the other "not syncing" issue, report back. Would be nice to get that sorted out.

FYI:

TbSync is actually asking the server for an estimate of the changes (used for the max value of the progress indicator) but is always asking for the changes, even if the estimate was zero. 

If he does not sync anything, than the server does not have any items for the client at that moment. The server could have a temp issue. Furthermore, if you disable the account, all sync related information are cleared (so called sync keys). On next re-enable, the account is synced fresh. If you know there is data in there, but nothing comes down (and even the estimate is zero), something is very strange.

The only thing that sticks during disable/re-enable is the deviceID. If you delete the account and set it up again, TbSync will also use a new deviceID. Deleting the entire AddOn should not help any better than deleting the account.
