### ISSUE TITLE
[Wishlist] Using TBSync to receive/send email

### ISSUE THREAD

**Issue by davidbercot** [jobisoft/TbSync#543]
Hello,

In my organization, the only protocol accessible on Internet is ActiveSync.
So, it's OK for contacts and calendar.

Is there a solution to use TBSync to receive/send emails?

Thank you.
David.

**Comment by Rosmaninho** [comment]
Maybe Exquilla?

**Comment by jobisoft** [comment]
I have no idea why they disabled autodiscover for outlook.de (as it seems). Use manual setup and enter "eas.outlook.com" as server.

**Comment by jobisoft** [comment]
Wrong ticket. Sorry.

**Comment by davidbercot** [comment]
Hello,
I've contacted OWL (Beonex) and they've updated their solution which is now OK!
About Exquilla, do you have more informations in ordre I try it to compare?
Thank you.
David.

**Comment by Rosmaninho** [comment]
Not much. I used it when it had a free option and it worked well. Then they moved back only to paid option.
Never used Owl.
