### ISSUE TITLE
How to get TB to recognize TbSync downloaded contacts

### ISSUE THREAD

**Issue by duhmel** [jobisoft/TbSync#547]
I've installed TbSync and Provider for Exchange ActiveSync and synced to my Hotmail account.  Now I need to figure out how to get TB recognize the downloaded contacts when I start an email.

**Comment by jobisoft** [comment]
Do you see the Hotmail contacts in your Thunderbird addressbook?

**Comment by duhmel** [comment]
I am good.  I had to select the hotmail contacts.
