### ISSUE TITLE
during syncing thunderbird hangs 

### ISSUE THREAD

**Issue by ferdiga** [jobisoft/TbSync#548]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.2.1 (64-bit) on Macbook M1

## Expected behavior
sync without blocking thunderbird

## Actual behavior
during syncing thunderbird hangs (spinning wheel), can not type or any other operation as long as "syncing" is displayed.
after finishing syncing (TbSync "idle") operation resumes normal.

## Steps to reproduce
install TbSync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by ferdiga** [comment]
I have send you the debug file.
on Thunderbird 91.3.0

**Comment by nzebikes** [comment]
Same here. When I delete the local address book and sync once it's working, but next sync (especially if there were local changes) locks up TB when the sync process has finished and it does not recover. Have to kill process hard. Did work fine before update. Can't even create debug report as while I try to write a report the window freezes!

**Comment by Sesimonsen1** [comment]
I have the exact same issue as nzebikes..

**Comment by seandarcy** [comment]
Me too. TB 19.6.0. TBSync 3.0.1. I have a intel i5 11th gen. 8 cores. When syncing TBSync takes all of 1 core. 7 are idle.

**Comment by jobisoft** [comment]
DAV or EAS?

**Comment by jdpipe** [comment]
I believe that this is a Thunderbird-wide problem, not limited to calendars, see [this discussion](https://discourse.mozilla.org/t/tb-eventually-in-rust-and-multi-threaded/61190).
I think that for outgoing tbSync, the solution is event-based synchronisation (when a local change is made, it should queue up a sync action with an eg 5 sec delay). This might have been fixed, but I'm not sure. (see bug #529).
For initiation of incoming synchronisation, I wonder if there is a push notification system of some sort implemented, in particular for Microsoft Exchange if not for CalDAV. I found this [Push Notifications Web Server Protocol](https://interoperability.blob.core.windows.net/files/MS-OXWSPSNTIF/%5bMS-OXWSPSNTIF%5d.pdf) for example, not sure it's relevant...? Some discussion also about [CalDAV push notifications](https://github.com/nextcloud/server/issues/22379) from the nextcloud project.

**Comment by Fabrice35** [comment]
Same thing for me.
Thunderbird 102.3.0 (64 bits), TbSync 4.3, Google-4-TbSync 0.4.2.
I did not have the problem before with Thunderbird 9x.

Is this a Thunderbird, TbSync or Google-4-TbSync problem?

**Comment by jobisoft** [comment]
There are reports, that Google-4-TbSync is a bit slower. I have not yet received complaints that EAS-4-TbSync in 102 is slower than in 91. And TbSync-4-DAV no longer syncs, so that is out of the loop.

**Comment by 512cg** [comment]
I'm experiencing the same in Ubuntu Tb102.4 and TBSync 4.3 + EAS 4.1.5.

I have been experiencing a similar issue in 3 computers with a similar setup, they looked like random freezes of the whole interface and I realised the pattern where when it happens the lower right corner says "Synchronizing"

**Comment by Traace** [comment]
how to debug thunderbird if it hangs?
