### ISSUE TITLE
Exchange server connection issue

### ISSUE THREAD

**Issue by ced75** [jobisoft/TbSync#55]
TbSync version: 0.7.5
Thunderbird version: 52.6.0 (64 bits)

Hi,

I'm trying to connect to my Exchange Outlook web interface, but I still get a connection issue with invalid username or password.
When I connect to my webmail server, the address is https://hamac.ign.fr/owa.
I've also tried the following addresses:
- https://hamac.ign.fr
- hamac.ign.fr/ews/exchange.asmx (address I'm using with the EWS exchange provider TB extension, which works fine).

I've tried several usernames:
- CDuprez
- CDuprez@IGN.FR (username I'm using with success in EWS exchange provider)
- cedric.duprez@ign.fr (my webmail username)

Here are the logs produced:

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[setSyncState] : State: syncing, Account: test

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[setSyncState] : State: prepare.request.options, Account: test

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[Sending] : OPTIONS https://hamac.ign.fr/ews/exchange.asmx/Microsoft-Server-ActiveSync

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[setSyncState] : State: send.request.options, Account: test

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[setSyncState] : State: eval.request.options, Account: test

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[finishAccountSync(test)] : Could not authenticate, check username and password.

** Tue Mar 13 2018 12:34:30 GMT+0100 (CET) **
[setSyncState] : State: accountdone, Account: test

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[setSyncState] : State: syncing, Account: test

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[setSyncState] : State: prepare.request.options, Account: test

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[Sending] : OPTIONS https://hamac.ign.fr/ews/exchange.asmx/Microsoft-Server-ActiveSync

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[setSyncState] : State: send.request.options, Account: test

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[setSyncState] : State: eval.request.options, Account: test

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[finishAccountSync(test)] : Could not authenticate, check username and password.

** Tue Mar 13 2018 12:34:35 GMT+0100 (CET) **
[setSyncState] : State: accountdone, Account: test

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[setSyncState] : State: syncing, Account: test

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[setSyncState] : State: prepare.request.options, Account: test

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[Sending] : OPTIONS https://hamac.ign.fr/ews/exchange.asmx/Microsoft-Server-ActiveSync

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[setSyncState] : State: send.request.options, Account: test

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[setSyncState] : State: eval.request.options, Account: test

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[finishAccountSync(test)] : Could not authenticate, check username and password.

** Tue Mar 13 2018 12:34:40 GMT+0100 (CET) **
[setSyncState] : State: accountdone, Account: test

Thanks in advance for your help.
Regards,

Cedric

**Comment by jobisoft** [comment]
Hi,

if you where not able to setup your account using autodiscover, you need to ask your server admin the following:
- does your exchange server support EAS (Exchange ActiveSync)?
- if so, what is the server url? 

The urls you tried let me assume, that your exchange server only supports EWS (Exchange WebServices), which is a different protocol.

**Comment by ced75** [comment]
Thanks for you quick answer.

You're right. My exchange server only supports EWS.
Is it possible to connect TbSync through EWS ? If not, would it be planed in a future version?

**Comment by jobisoft** [comment]
Not in 2018. My main goal this year is to get EAS [done](https://github.com/jobisoft/TbSync/wiki/Roadmap) and release v1.0. The Add-On is however designed to support multiple providers in the future. But i cannot give any estimate about what will be next.

There are however AddOns for EWS, like ExQuilla (i think the author will drop the licence fee soon).

**Comment by ced75** [comment]
OK. Thanks for your answers.
