### ISSUE TITLE
RFE: Outlook Office 365 confidentiality

### ISSUE THREAD

**Issue by efa** [jobisoft/TbSync#551]
## Your environment

Provider for Exchange ActiveSync: 2.0.1
TbSync version: 3.0.1
Thunderbird version: 91.3.1 (64-bit)
Windows 10 64-bit

Our company started to require a confidentiality classification for all emails.
This is generated by the Outlook icon in compose email, see attached image.
![Outlook_confidentiality](https://user-images.githubusercontent.com/1578980/142007629-2933e915-091a-437b-b6c4-ea71585243ed.png)

As now we have three levels: Public, Internal, and Confidential
The Thunderbird Security Icons has the ability of sign and encrypt emails, but no classification.

I do not think it is related to Exchange ActiveSync, but maybe to TbSync component only.

In terms of standard email protocol, Outlook add e new header line as so:

```
msip_labels:
	MSIP_Label_<hash00>_ActionId=<hash01>;MSIP_Label_<hash00>_ContentBits=0;MSIP_Label_<hash00>_Enabled=true;MSIP_Label_<hash00>_Method=Privileged;MSIP_Label_<hash00>_Name=<NAME>;MSIP_Label_<hash00>_SetDate=2021-11-16T09:18:33Z;MSIP_Label_<hash00>_SiteId=<hash02>;
```

where:
```
<hash00> is same for all email of a kind, eg. every Confidential email has the same hash.
<hash01> is different for each email
<hash02> is always the same for every company plant
<NAME> is the selected level
and the `ISO8601dateTtimeZ` is set on email sent
```

so this is not a difficult hack

## Expected behavior
Thunderbird compose email, in Security menù, should has the option to classify the emails, that add the header described above.
Maybe a dialog box to enter the `<hash02>` and a configurable list of couples `"name","<hash00>"` to be general
A default level should be selectable

**Comment by jobisoft** [comment]
TbSync is not handling emails.

**Comment by efa** [comment]
Cannot be a TB or TbSync add-ons?
I have to open an RFE on Bugzilla?

**Comment by jobisoft** [comment]
I do not understand this issue at all. TbSync is only syncing contacts and calendars via EAS. Thunderbird itself has no EAS support whatsoever. 

I have no idea how you setup your O365 account in TB. If you used IMAP to get your emails, you cannot file a bug on Bugzilla, as IMAP does not support the things you request.

**Comment by efa** [comment]
O365 is a standard IMAP server, so work without TbSync. I use EAS/TbSync to have access to company address book autocompletion and meeting/calendar.
I'm not sure if the confidentiality classification function is part of O365 or EAS, but think related to EAS for the prev reason.
Is there something I can do to verify that?

**Comment by jobisoft** [comment]
Thunderbird will not support non-standard headers. But I assume, this information is not shared via IMAP / headers, but only via OWA, EWS or EAS. Try the owl add-on, which is doing emails.
https://addons.thunderbird.net/addon/owl-for-exchange/

**Comment by efa** [comment]
I made a try and send a mail from company account to a personal account using Public classification.
I see in the 'msip_labels:' header line identical in both the sent company email folder and the Inbox on personal account.
So maybe it is enough to add the "non standard" header. Can be done in a TB or TbSync add-ons?

**Comment by jobisoft** [comment]
> Can be done in a TB or TbSync add-ons?

No, because I do not handle emails at all.

Have you tried owl?

**Comment by efa** [comment]
no, but I will try to ask also there

**Comment by efa** [comment]
I opened a RFE also on TB: https://bugzilla.mozilla.org/show_bug.cgi?id=1741519
and same requesto to this add-on: https://github.com/alexmurray/thunderbird-security-classifier/issues/6

**Comment by efa** [comment]
all hashes are in the form: 'hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh'

I saw that OWL is not open source, they haven't a place where file a bug or RFE like github, only a contact email, write to that. Thank you
