### ISSUE TITLE
Top menu doesn’t work well with system or internal dark theme

### ISSUE THREAD

**Issue by unclechu** [jobisoft/TbSync#553]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 91.3.1 (64-bit)

## Expected behavior

The top menu inherits the used theme. Or at least the foreground color is darker.

## Actual behavior

The background color seems to be hard-coded in the plugin but foreground color seems to be inherited from the system theme. Thus the contrast is very low, both foreground and background are light colors.

![2021-12-01 19-04-50](https://user-images.githubusercontent.com/799353/144280607-85d4ba5c-d6a4-45d7-8da7-23b0dfb4431b.png)

## Steps to reproduce

Open TbSync plugin settings.

**Comment by panther7** [comment]
Agree, it is usable... 
![Image-2022-01-26 10 47 36](https://user-images.githubusercontent.com/3808250/151140657-604209dd-5f07-4466-bb12-921620cd56fd.png)
