### ISSUE TITLE
O365 account sync error

### ISSUE THREAD

**Issue by Lalilalulalam** [jobisoft/TbSync#554]
## Your environment
Issue occurs regardless environment change

TbSync version: 3.0.1
Thunderbird version:

## Expected behavior
Working calendar sync

## Actual behavior
Javascript error:
item is null
getItem@chrome://tbsync/content/modules/lightning.js:412:11

## Steps to reproduce
Add company Exchange account do tbsync.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
Debug log is empty.

**Comment by TomJansen** [comment]
I can confirm this error with TBsync and Provider for Exchange ActiveSync on Thunderbird version 96.0b2 (64-bit)

**Comment by DavidBE-UK** [comment]
This would be the same problem I reported with outlook.com calendars https://github.com/jobisoft/EAS-4-TbSync/issues/159
