### ISSUE TITLE
swich "preferres html" missing

### ISSUE THREAD

**Issue by ReiGf** [jobisoft/TbSync#555]
## Your environment

TbSync version: 3.0.1
Thunderbird version: 95.0.2 (also on 78.x.x)

## Expected behavior
HTML composed emails should be sent as "HTML" (or "plaintext plus HTLM") as a default.
X-MOZILLA-HTML should be "unknown" or "HTML" unless set in a different way

## Actual behavior
HTML cpmposed email is sent as plaintext only. default X-MOZILLA-HTML is "plaintext"
Every entry in an adressbook pulled from a WebDAV source (profil "customized" for owncloud at https://ocloud.global) is treated by thunderbird 95 and 78 as "preferes plaintext". There does not seem to be a switch to change this behavior in TbSync or thunderbird.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
See:
https://searchfox.org/comm-central/rev/68c2c1641ee0e1c9f320ff304fb8276d540a18ea/mail/components/addrbook/content/aboutAddressBook.xhtml#181-184

And:
https://github.com/jobisoft/DAV-4-TbSync/blob/master/content/includes/tools.js#L542

And:
https://github.com/jobisoft/DAV-4-TbSync/blob/master/content/includes/tools.js#L753-L757

If your contacts have plaintext set after loading them via TbSync, they have the flag set in the vCard and TbSync obeys that. If your contacts have the "unknown" setting and TB picks plaintext for those, you need to change the default in your Tb profile.

An export of your contacts directly from your ownloud would be interesting. 

Closing this as we have the discussion already in the forum.
