### ISSUE TITLE
"Override display name" can not be unchecked

### ISSUE THREAD

**Issue by lgradl** [jobisoft/TbSync#557]
TbSync version: 3.0.1
Thunderbird version: 91.2.1
Provider for ActiveSync: 2.0.1

Server: SOGo 5.0.1 on Zentyal Server

OS: Windows

## Expected behavior
The address book entries should show the display names from the SOGo entries or at least first and last name. The "override display name" option (as well as the "enforce provisioning" option) should be able to be unchecked.

## Actual behavior
The address book entries show the part before the @ as Name, not the display name or first and last name.
The "override display name" option (as well as the "enforce provisioning" option) can not be unchecked

## Steps to reproduce
Install TB 91.2.1, TBSync 3.0.1 and Provider for ActiveSync 2.0.1, configure the adress book from SOGo and sync. Check the address book entries.
Check the options - no matter what you configure there two options will be checked.

regards
Lukas

**Comment by desuvinaykumar** [comment]
#563
