### ISSUE TITLE
 TB Lists do not transfer to Google Labels

### ISSUE THREAD

**Issue by Andrew-Lohmann** [jobisoft/TbSync#558]
## Your environment

TbSync version: ? Google-4-TbSync  ?
Thunderbird version:  78.14 to 91.5 Linux or Windows

## Expected behavior
My TB address book is organised into lists I pasted each list into the Google-4-TbSync and expected those contacts to have google labels added. 

## Actual behavior
The lists are all empty in Google and then subsequently the lists in the Andrew-Google-4-Tb are empty in TB.  But all the contacts are present.  If I add labels to the contacts in google the contact successfully moves into the list named in TB.

## Steps to reproduce
Tried CARDBOOK previously recently. this put contacts in google contacts.  That was removed so it will not conflict with TbSync.
Create the personalised API as described
Created new lists and copied contacts into those lists from the TB Personal Addressbook to the Andrew-Google-4-TbSync address book. This looked okay at first.
Closed and opened TB found that all the  Andrew-Google-4-TbSync lists were empty.
Looked at Contacts.google.com similarly the lists (Labels not marked) were empty.
Added a few labels to some contacts in Contacts.google.com and found the contacts then appeared in TB Andrew-Google-4-TbSync  the few Lists I changed in google.

Note I do not use Contacts.google.com but wish to use TB contacts.  Therefore if someone sends to me from a mail list I will add a new list to TB but this now won't work. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
You should probably file that at 
https://github.com/zanonmark/Google-4-TbSync
