### ISSUE TITLE
unable to connect exchange server

### ISSUE THREAD

**Issue by sram012** [jobisoft/TbSync#559]
## Your environment

TbSync version: 3.0.1
Thunderbird version:91.5.0

## Expected behavior
... login to web based authentication

## Actual behavior
... The current browser is not supported, please use Microsoft Edge, Internet Explorer or Chrome to access this application.

## Steps to reproduce
... it has to except it but due to browser issue its not working and i am using Windows 10 OS with Edge browser but this tbsync is not using Edge rather using its own so its causing issues

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
![de](https://user-images.githubusercontent.com/98270090/150684045-e447b86a-8306-4a12-8f7e-41c49d8c2390.PNG)

**Comment by jobisoft** [comment]
It is a limitation enforced by your administrator. I can perfectly connect.

**Comment by sram012** [comment]
but same is working in Owl for Exchange!!!

**Comment by jobisoft** [comment]
I think owl is not using eas but ews or owa. So different protocol.
