### ISSUE TITLE
Not working with 365

### ISSUE THREAD

**Issue by ebonweaver** [jobisoft/TbSync#56]
Before you post a new issue, please update TbSync to the latest release (or beta, if there is one) and also update your Thunderbird to the latest stable release. Can you still reproduce your issue?
To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

## Your environment

TbSync version: 0.7.5 (also tried 0.7.3)
Thunderbird version: 52.6

## Expected behavior

Connect to 365 and sync calendar, etc.

## Actual behavior

Can't talk to outlook.office365.com.  It reports 503.

## Steps to reproduce

Install plugin.  Create account.  Set server to outlook.office365.com (or https://outlook.office365.com/EWS/Exchange.asmx as used in Outlook).  Try to connect.  Get 503 failure.  Unclear why it can't talk to the server.

**Comment by jobisoft** [comment]
This is difficult to debug. The URL "outlook.office365.com" is correct and is working for me. 

Did you use autodiscover to setup your account?

Please do the following:
- completly remove the account from the TbSync Manager
- enable the debug log
- restart Thunderbird
- re-add your account in TbSync account manager using autodiscover (if possible)
- connect the account

After that, open the debug log and send it to me via email (do not post it here).

**Comment by ebonweaver** [comment]
After multiple attempts I think I figured out the issue.  If you try to use autodiscover and it fails (which in our case it always will due to the account name differing from the domain name because of institutional SSO) then that account is in some way corrupted and will never work.  Also, if you make a typo and it fails, you can't simply correct it and have it work, because again something is corrupted.  Once I added the account manually with all settings correct on first attempt, it finally connected just fine.  Hopefully that gives you something to go off of for an improvement in a future release.
On a separate note, is there any support for shared calendars?  There are several I need access to, but this plugin does not see them.  I can't add them as separate accounts as the calendar itself (account name that shows in Outlook when connecting to the shared calendar in its properties) does not have a password, and your plugin has no way to set an authentication account separate from the account name.  It would be great if the plugin detected calendars shared with the user and made them available for sync, but I understand that may be challenging.
Thanks!

**Comment by ebonweaver** [comment]
Ah, bummer that's not supported, I'll take another look around for EWS options.  Happy to help if you need anything else on the setup issue!

**Comment by jobisoft** [comment]
There is a flaw in 0.7.3, where an internal setting ("provision") was enabled by default and some servers do not send the command to switch it off, but simply fail. This setting was still set, even if updated to 0.7.5.

Only deleting the account and re-adding it, would solve the problem.

However, with 0.7.5, creating a new custom configuration account, I am not able to get "stuck" by starting with wrong settings. As soon as I correct all settings, I can connect.

Can you reproduce your finding with 0.7.5? If so, could you give me a step-by-step description?

**Comment by ebonweaver** [comment]
Huh... try as I might, I can't reproduce it now.  I did the same series of things as before, which was actually two layers of wrong settings attempts, but once I corrected it this time it connected up fine.  Random fluke of something left over that got cleared?  Falling back on a previous success works once corrected?  Grasping at straws now, and it gets real hard to try to diagnose and reproduce from this point.  Maybe we call it leftover bad behavior from trying .7.3 first and say if https://addons.mozilla.org/en-US/thunderbird/addon/tbsync/ is updated to .7.5 it's fixed and close this out  :)
Thanks for the follow up!

**Comment by jobisoft** [comment]
I think that is probably true. Thanks for your efforts to reproduce this.

I cannot release 0.7.5 to Mozilla, because it has other flaws itself, which I need to work out. However, I just released 0.7.4 to Mozilla, which fixes just this issue. It will take a few days to pass review.

Thanks again for reporting this.
