### ISSUE TITLE
Cannot sync ALL google contacts

### ISSUE THREAD

**Issue by joansubiros** [jobisoft/TbSync#561]
## Your environment
Windows 11 64 bit
TbSync version: 3.0.1
Thunderbird version: 91.5.1 (64-bit)

## Expected behavior
Sync Google contacts

## Actual behavior
I only see 33 contacts from google account, but i have more than 400

## Steps to reproduce
i did steps as here: 
[debut log.txt](https://github.com/jobisoft/TbSync/files/7934887/debut.log.txt)
https://ekiwi-blog.de/en/16081/thunderbird-synchronize-google-contacts-and-calendar-with-tbsync/#comment-157935

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I do not support google anymore. Try
https://github.com/zanonmark/Google-4-TbSync

**Comment by joansubiros** [comment]
Thanks.

It's strange Thunderbird has no connection with contacts with Hotmail or 
Google........


j*o*an sub*i*rós
“Fill your Soul, Free your Mind”
