### ISSUE TITLE
Primary eMail address not respected

### ISSUE THREAD

**Issue by exapplerep** [jobisoft/TbSync#562]
Windows 10 (latest release channel, fully updated)

TbSync version: 3.0.1
Thunderbird version: 91.5.0 (release channel)

## Expected behavior
First eMail address in contact record should be the first one suggested when addressing an outgoing eMail.
For example: Contact "John Smith" has three addresses - ccc@gmail.com, aaa@yahoo.com, bbb@mac.com listed in that order. When typing in "john" in the TO field (assuming no other "john" is present in the Contacts), ccc@gmail.com should be the first presented (and highlighted), then the aaa@... and then the bbb@...
...

## Actual behavior
eMail addresses are suggested in alphabetical order
Assuming the same "john" in the Contacts, the eMails are presented in alphabetical order:
aaa@yahoo.com (and it's highlighted)
bbb@mac.com
ccc@gmail.com
...

## Steps to reproduce
Follow my "expected behavior" steps.
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
EAS or DAV provider?

**Comment by exapplerep** [comment]
Thanks, John, but I've decided to abandon TBird as sync issues keep cropping up. All my addresses were sync'd with my Google contacts.

**Comment by jobisoft** [comment]
Perfect. Glad you are happy.
