### ISSUE TITLE
Can't add events to calendar that matches primary email address

### ISSUE THREAD

**Issue by JasonSanDiego** [jobisoft/TbSync#566]
Apologies in advance if this is a Thunderbird issue not a TbSync issue. It only seems to affect TbSync calendars, so that's why I'm guessing it might be a Tbsync issue, or maybe just user error.

## Your environment
Windows 10

TbSync version: 3.0.1 + Provider for Caldav & Carddav 2.0.2
Thunderbird version: 91.6.0

## Expected behavior
When I accept a calendar invite, I should be able to add it to a TbSync calendar.

## Actual behavior
When I receive an email sent with my primary email address (the same and only one I see when looking at Manage Identities in Account Settings) in the To line, I'm unable to add it to any TbSync calendar. If I have multiple non TbSync calendars, I will get a dialog to choose, but the TbSync calendars will not be listed.

When I receive an email sent to a different email address from my primary email address (such as one that is auto forwarding to my primary one), I see a dialog to select which calendar to add to, and writable TbSync calendars are listed.

## Steps to reproduce
Send myself an invite from another account. Send one to my primary email, send another to a forwarder. Reproduces consistently and on two different machines.

**Comment by AxelBuck** [comment]
Same issue here, this is actually quite problematic in daily use.
Thunderbird 91.8.1 (Windows 10)
TbSync 3.02
Provider for Exchange ActiveSync 2.01

**Comment by JasonSanDiego** [comment]
I actually "resolved" this issue. I don't remember the exact steps now because it was a couple of months ago, but there was a discrepancy between email addresses in the calendar sync configuration and my email account. I had to remove and readd the calendar in some way with the email address matching my email account, and then that calendar magically became available when accepting invites.

It doesn't make sense to me why non-matching email address should prevent adding it to a particular calendar, but at least it works now.

**Comment by AxelBuck** [comment]
I also managed to fix my issue. Under Calendar -> Properties (of my TbSync calendar) there was no email assigned to it.
After choosing the correct email address, it now works as expected.

**Comment by jobisoft** [comment]
Good to know. Thanks.
