### ISSUE TITLE
Event sync TB to Horde encoding problems (äöü)

### ISSUE THREAD

**Issue by crbble** [jobisoft/TbSync#57]
```
TbSync version: 0.7.5
Thunderbird version: 52.6
```
Synchronizing an event from Thunderbird to Horde causes a mess with german umlauts (öüä). Syncing from Horde to Thunderbird works as expected.

Converted characters are shown as "testÃ¶Ã¼Ã¤" für testöüä in Horde.

This behaviour was not observed with prior versions. Synclog can be provided as needed.

**Comment by jobisoft** [comment]
Does it happen with all fields? Subjekt? Location? Body?

Also with tasks and contacts?

Thanks for reporting this.

**Comment by jobisoft** [comment]
Confirmation. It is not limited to Horde.

**Comment by jobisoft** [comment]
Should be fixed in [0.7.5.1](https://github.com/jobisoft/TbSync/releases/download/v0.7.5/TbSync-0.7.5.1.xpi).

Could you give it a try?

**Comment by crbble** [comment]
Works for me, thanks.

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).
