### ISSUE TITLE
TBSync does not recognize password when Enabling and synchronizing newly added Outlook account

### ISSUE THREAD

**Issue by Rosmaninho** [jobisoft/TbSync#572]
## Your environment

Provider for Exchange ActiveSync: 2.0.1
TbSync version: 3.0.2
Thunderbird version: 91.6.1

## Expected behavior
When selecting "Enable and synchronize this account" TBSync enables it.

## Actual behavior
On the Status step "Prompting for credentials" TBSync request password again and does not accept the password used to establish the account.
Event Log gives following errors: Could not authenticate, check username and password (HTTP Error 401).

## Steps to reproduce
1 - Account Actions -> Add new acount -> Exchange Activesync,
2 - Select "Automatic configuration",
3 - Enter Account name, email address and password,
4 - go to "Synchronization status" tab and select "Enable and synchronize this account",
5 - On the Status step "Prompting for credentials" TBSync request password again and does not accept the password used to establish the account.

6 - After it fails I change to Activesync version 14.0 in "Account Settings" tab and it reads Status OK. I then try Synchornize and it fails again in the same way. This is connecting to eas.outlook.com server.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Rosmaninho** [comment]
When I try to connect directly to eas.outlook.com it does not work.

**Comment by jobisoft** [comment]
Nothing much I can do, works for me. I have read, that outlook no longer allows using alias accounts to authenticate. Maybe you are using an alias?

**Comment by Rosmaninho** [comment]
I am adding my outlook e-mail account. It is connected to a Gmail account. Maybe that's the issue?

**Comment by Rosmaninho** [comment]
Apparently what I thought was my primary e-mail wasn't. I made it my primary e-mail, and now TBSync works. Freaking Microsoft. Ugh.
