### ISSUE TITLE
How to display a Global Calendar?

### ISSUE THREAD

**Issue by BGMcoder** [jobisoft/TbSync#573]
## Your environment Windows 10

TbSync version:  Thunderbird version: 91.7

In our 365 tenant, I have created a global calendar inside one of the public folders.  I can add it in my OWA, and used to know how to add it via pre TB-60's EWS Calendar extension.  

How do I add it using tbsync?  It does not appear in the tbsync account settings for my 365 account.

The path would be something like this:   /Global Calendars/mycalendar

**Comment by jobisoft** [comment]
Not possible with EAS. That protocol does not support global shares.
