### ISSUE TITLE
Synchronization of tasks does not work

### ISSUE THREAD

**Issue by uuroveits** [jobisoft/TbSync#577]
## Your environment
TbSync version: 3.0.2
Thunderbird version: 91.8.1 (64-Bit)

## Expected behavior
Synchronization of tasks

## Actual behavior
After successful installation of TbSync (and Google-4-TbSync) and activation and synchronization via People API of Google (status is green) the synchronization of tasks is not possible.

## Steps to reproduce
<none>

Questions:
1) Are there any instructions on what to consider regarding the synchronization of tasks?
2) What can I do to solve the problem?

regard

Jochen

**Comment by jobisoft** [comment]
Wrong Repo. Please report with the Google-4-TbSync provider.
