### ISSUE TITLE
Google advises "migrate your OAuth...before Oct 3, 2022"

### ISSUE THREAD

**Issue by saleslogistix** [jobisoft/TbSync#586]
## My environment
Windows 10 with all updates
TbSync version: 3.0.2
Thunderbird version: 91.10.0

## Comment / Question
All is well for me at the moment.  However, I received a cheery little email from Google (text below) indicating the deprecation of "OAuth-out-of-band (OOB) flow" on 3 October 2022.

Supposedly, if you have your OAuth project set up in "testing mode", everything will continue to work as it does now.  **Is this true?**

And supposedly, you can keep things in testing mode for an indefinite period of time.  **Is this true?**

But if you have the project set up in Production Mode (aka "Published"), some things may have to change.  Their help page is not very clear, but my reading of it is "for TBird, OAuth2 will continue to work."  **Is this true, and what configuration changes might be required to keep it that way?**

## Text of Google's mail
Our records indicate you have OAuth clients in test mode that are using the OAuth OOB flow.

Hello Google OAuth Developer,

We are writing to inform you that **OAuth out-of-band (OOB)** flow will be deprecated on October 3, 2022, to protect users from phishing and app impersonation attacks.

Please check our recent blog post about [Making Google OAuth interactions safer](https://notifications.google.com/g/p/AD-FnEyNMmS0ElhoyvT_36hgD7azGKbqeSUIvajeaV2UBStSkSLWGlxHS3Dc3okgHFgCARUqc9URGX1QX7mAKrQGiFODX0Rb9fxiEHjJyb0cR5S6-xQdcav2kP9d9_nV2Oaf866W0kyC3VvPJAD0) for more information.

**What do I need to do?**

**No action is required on your part as apps using OOB in [testing](https://notifications.google.com/g/p/AD-FnEwz4TFFTuJYnfzAn0Km2zzF65Y9whDGi0ROI1_IckeIrxFdsM3AA2bBNk2gzblaZWGnf7HpOUKPOxRtSw_zQuOivkfTLudRUNPlxeKZrH1G5A-HDG8hJDkSdkKJTOi5HBUjsmxJu9v4Y5S2k6FT5NKUxjFnayXg) mode will not be affected by this change.** However, we strongly recommend you to migrate to safer methods as these apps will be immediately blocked when switching to [in production](https://notifications.google.com/g/p/AD-FnEyrmUghqpUo8HDyWiMHv7oC5KepEkMBSC1EIcECmi8mQDUzLRH9pJIqU13Jjai2Uc05_JYugL47JU7wJkmn1hZ4QGdpwsE0UnAEoXl2jjqrJWwB-5wfXdlsSSrtxiTe_ws5x6H5FC8xepzAvSl2W_4ekWYW5byjjToj) status.

If you want to publish your app(s) to production, follow these instructions:

1. Determine your app(s) [client type](https://notifications.google.com/g/p/AD-FnExQ1L0vX7eM5NzgznT5mfq6QBMClTCCM9aRD0jlz8c4czpqGKCj7TQwvZFhLR_QjZ6GKwZxlMMuKvShv2xTi8xlDr2-rM3biZ6SMNwUY0aRYDXuJkk0JoTcBNu3iWmKGZF-n2wa4Tk9SzvesR3h56ry0wpmyF_bpRPbyT9rxz3WL5Px) from your Google Cloud project by following the client links below.
2. Migrate your app(s) to a more secure alternative method by following the instructions in the blog post linked above for your client type.

The following OAuth client(s) are using the OOB flow in test mode.

Your OAuth client list:

    Project ID: (suppressed)
        Client: (suppressed)

Thanks for choosing Google OAuth.

**— The Google OAuth Developer Team**

**Comment by jobisoft** [comment]
I have removed google support in the version for 102 entirely.
