### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by enthalpie91** [jobisoft/TbSync#589]
## Your environment

TbSync version: 0.3.0
Thunderbird version:91.4.0

## Expected behavior sync
...

## Actual behavior error 400
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by enthalpie91** [comment]
Le contenu de cette section a été fourni par le développeur de l'appli. Google ne l'a pas examiné ni validé.
Browser window closed before the authorization code was retrieved.

AuthorizationCodeError@chrome://google-4-tbsync/content/includes/AuthorizationCodeError.js:18:9
getNewAuthorizationCode/promise</authenticationWindow.onclose@chrome://google-4-tbsync/content/includes/PeopleAPI.js:145:28

**Comment by jobisoft** [comment]
I no longer support google.
