### ISSUE TITLE
JavaScript error with TB60b1 and v0.7.6

### ISSUE THREAD

**Issue by bonanza123** [jobisoft/TbSync#59]
Hello,

I guess since the beta has been updated to TB60, I cannot sync anymore. As usual, I removed the old account and added it again (with TB restart) and hit sync. It produces the below mentioned error.

## Your environment

```
TbSync version: 0.7.6
Thunderbird version: 60 beta 1
```

## Expected behavior
Sync working

## Actual behavior
JavaScript error, debug log output:

> 
> ** Tue Mar 27 2018 09:47:06 GMT+0200 (CEST) **
> [JavaScript Error: "XMLHttpRequest is not defined" {file: "chrome://tbsync/content/provider/eas/eas.js" line: 1229}]
> getServerOptions/<@chrome://tbsync/content/provider/eas/eas.js:1229:94
> getServerOptions@chrome://tbsync/content/provider/eas/eas.js:1227:16
> eas.start<@chrome://tbsync/content/provider/eas/eas.js:97:27
> TaskImpl_run@resource://gre/modules/Task.jsm:326:42
> TaskImpl@resource://gre/modules/Task.jsm:275:3
> asyncFunction@resource://gre/modules/Task.jsm:247:14
> syncAccount@chrome://tbsync/content/tbsync.jsm:218:13
> requestSync@chrome://tbsync/content/provider/eas/accountSettings.js:37:82
> oncommand@chrome://tbsync/content/provider/eas/accountSettings.xul?id=1:1:1

## Steps to reproduce
Download above mentioned versions, remove accounts, add accounts again, hit sync.

**Comment by jobisoft** [comment]
That is a bug in thunderbird, have seen it before with the 60 branch. The xhr object is missing. I file a report.

**Comment by jobisoft** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1449122

**Comment by jobisoft** [comment]
It looks like it is not a bug in thunderbird, but indeed a bug in tbSync, due to poor documented API changes. It is fixed in master, which is unstable. I release something stable soon.

**Comment by jobisoft** [comment]
Ok, I got master into something stable, I just released a new beta: [0.7.6.2](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.2.xpi)

Give it a try, feedback on the new UI would also be very helpful.

**Comment by bonanza123** [comment]
Thanks so much! Its working fine for me.
Also the new UI is great. But would it possible to add some information what "AutoSync (minutes)=0" means?

**Comment by jobisoft** [comment]
Autosync is an automatic periodic sync. If set to zero, it is disabled, any other value causes tbsync to check the server for updates every x minutes (x is the value you set). If it is set to 5, tbsync will sync every five minutes.

Thus will go away in 0.9 branch, after push sync is implemented.

How can i improve the setting? Add tooltip? Change label? Suggestions?

**Comment by bonanza123** [comment]
Ahh ok. I thought AutoSync=0 means push, good to know that it isn't (yet) :-)
I just saw that it already has a tooltip / mouse-over but I missed it. Would it be possible to add just a "(0 means disabled)" text below "AutoSync (minutes)" (Two row label for the input field)?

**Comment by jobisoft** [comment]
Please update to https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.3.xpi

**Comment by jobisoft** [comment]
Sorry, please update to https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.5.xpi

I renamed it to "Sync interval" and extended to tooltip. I would not like to go for two lines...

**Comment by jobisoft** [comment]
Please update your beta version of TbSync to [0.7.6.8](https://github.com/jobisoft/TbSync/releases/download/v0.7.6/TbSync-0.7.6.8.xpi) or any later version available at the [release page](https://github.com/jobisoft/TbSync/releases).

This version now includes an update notification, so I no longer have to contact all beta users, to update their TbSync versions:

https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update_notification.png

While on the beta release channel, I strongly suggest to update, if a newer version is available. Once a new stable version gets released, you automatically switch back to the stable release channel (you no longer receive update notifications for beta versions).

**Comment by bonanza123** [comment]
Thanks! I just upgraded and restarted, but couldn't find the TBsync settings in the "Tools" menu anymore. Am I blind or did it move somewhere?

**Comment by jobisoft** [comment]
Does it work?

**Comment by bonanza123** [comment]
Yes, I was able to open the settings with clicking on the status bar. Thanks!

**Comment by jobisoft** [comment]
So this is a first test for the update notification. I re-added the the menu items and released a new version.

Do you get the update notification? Does the direct update work?

**Comment by bonanza123** [comment]
When I started thunderbird this morning, there was no update notification (pop up). But when clicking on the status bar icon to open the settings, the new tab "update tbsync" was there. I then clicked there on the "latest beta" button/link and a new tab opened which seemed to trigger the download. Then there was a pop up to confirm the installation of the new addon. The new addon was successfully installed.

**Comment by jobisoft** [comment]
Nice, you should now have the menu item back. I did not implement a popup but only the passive icon notification, to not annoy anybody.

Thanks for your feedback.
John

**Comment by bonanza123** [comment]
Would it maybe possible to put a notification mark to the status bar as well? I just think maybe beta-users (like me) are not regularly checking the settings page of TbSync for updates.

**Comment by jobisoft** [comment]
Done, if you update now (to 0.7.6.10), you will see it for the first time once the next update is out (0.7.6.11).

The menu may have moved also, it is now always above the Account Settings entry, on windows this is in Tools, on Linux this is in Edit. But since Thunderbird does not show the menu bar by default, there are not many users who actually use the menu item (the "how to use guide" in the wiki only talks about clicking on the status bar).
