### ISSUE TITLE
EAS providor won't load and doesn't work with TB 102 Release -' TbSync.lightning.cal.getCalendarManager is not a function'

### ISSUE THREAD

**Issue by DavidBE-UK** [jobisoft/TbSync#590]
So, as TB 102 is now the release version, time to bring up again ....

## Your environment

TbSync version: 3.02 with max_version in manifest changed to 102.*

Thunderbird version:

102.0 Release

## Expected behavior

EAS Provider works to allow connection to outlook.com calendars

## Actual behavior

Originally, some way back in the betas the syncing with the outlook.com calendars showed as errors. After trying deleting the account and then trying to re-create it, TbSync just says the EAS Provider isn't installed (although it is), error message as below. Reinstalling the EAS provider makes no difference, TbSync just says it is not installed.

(Note, I can't say what happens with other providers as I have none installed - I used to connect to Google address book and calendars with TbSyjc, but switched to use TB's native support for them once I very belatedly realised it was there and uninstalled the CAL and CARDdav provider.)

## Steps to reproduce

Delete any outlook.com account you have, which won't work anyway. Then try to create a new  one.
...

Excerpt from TbSync debug.log

** Wed Jun 29 2022 00:03:05 GMT+0100 (British Summer Time) **
[TbSync init] : Done

** Wed Jun 29 2022 00:03:05 GMT+0100 (British Summer Time) **
[EventLog] : Default timezone has been found.

** Wed Jun 29 2022 00:03:05 GMT+0100 (British Summer Time) **
[Loaded provider] : eas::Exchange ActiveSync (2.0.1)

** Wed Jun 29 2022 00:03:05 GMT+0100 (British Summer Time) **
[EventLog] : FAILED to load provider <eas>
TbSync.lightning.cal.getCalendarManager is not a function

**Comment by jobisoft** [comment]
ETA : 2 weeks

**Comment by thorstenk** [comment]
> So, as TB 102 is now the release version, time to bring up again ....

@DavidBE-UK Do you think creating another issue will speed up the solution of the already existing #583?

**Comment by DavidBE-UK** [comment]
i originally raised the issue when TbSync (modified so TB would install it despite the max_version in the manifest saying 91) stopped working in TB 98 beta, having worked with the TB betas from 92-98, and reporting the actual error messages with an existing EAS account. I was told then it would be fixed in 102 stable release. Now we are at TB 102 I was reporting the actual error message that shows up as TbSync tries to load the EAS provider module (after having previously deleted the EAS account) so that TbSyjnc doesn't accept that the EAS provider extension is even installed. I thought that might be useful specific information on the actual problem, as opposed to that other issue simply saying you're getting the 'incompatible' error that solely means the max_version in the manifest is still set to 91, which it would show even if TbSync actually worked fine with 102. So, yes, I did think reporting the actual error might save a few seconds.

**Comment by jobisoft** [comment]
Thanks for your feedback! Working on it.

**Comment by thorstenk** [comment]
@DavidBE-UK Thanks for your clarification! That sounds reasonable.

I just missed the connection to your original issue and think it's more effective to keep discussion about incompatibilities with a new TB release in one place.

**Comment by DrYak** [comment]
> Thanks for your feedback! Working on it.

Is there any branch that we could help testing?
(or tweaking?)

**Comment by jobisoft** [comment]
As this is a dupe for 102 issues, I close it in favour of
https://github.com/jobisoft/EAS-4-TbSync/issues/167#issuecomment-1249030422
