### ISSUE TITLE
Possibility to sync two CalDAV accounts

### ISSUE THREAD

**Issue by ar-ml** [jobisoft/TbSync#595]
## Your environment

TbSync version: 3.0.2
Thunderbird version: 91.11.0

## Expected behavior
I would like to sync TWO different CalDAV servers (e.g. two different Nextcloud instances) with ONE local calendar.
It should work like this:
1. I create a new appointment in Nextcloud A calendar.
2. The appointment should be automatically synced to my local TB calendar.
3. Then the appointment should be automatically synced to Nextcloud B calendar.

## Actual behavior
If I create a new account setting in TbSync, there will be automatically crated a new Thunderbird calendar. Even if I create another TbSync account with exactly the same Account name, there will be created another local Thunderbird calendar.
I would like to have both CalDAV serveres synced to the SAME local Thunderbird calendar. Is this possible?

## Possible workaround
If this is not possible, I would like to ask for the possibility to automatically sync two different local Thunderbird calendars with eachother. This would also solve my problem. 
Thank you for pointing me in the right direction!

**Comment by jobisoft** [comment]
It does not work and that is not what syncing should do. Try setting up a third calendar with the information user A and user B should see and share it with both.

The DAV provider is approaching EOL, as Thunderbirds built-in DAV support is almost on par.
