### ISSUE TITLE
NS_ERROR_NET_TIMEOUT

### ISSUE THREAD

**Issue by GrizzlyAK** [jobisoft/TbSync#596]
## Your environment

Win10 x64

TbSync version: 3.0.2
Provider for CalDAV & CardDAV: 2.0.2
Thunderbird version: 91.11.0

## Expected behavior
When I set this all up a week or so ago, sync was working. 

## Actual behavior
Today I noticed a TbSync: Error in the Thunderbird status bar. When I checked it out, I see the screen shown in the image below. The iCloud accout works fine, but the account on my Site5 hosting platform no longer does. I've tested the URL domain for the DAV server in a CMD window using NSLOOKUP, and it resolves quickly and correctly.  When I try to sync in TbSync, it counds down from 88s to 70s while **Requesting folder list** before the error shown pops up.

## Steps to reproduce
Click Synchronize now.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

![image](https://user-images.githubusercontent.com/4411963/179334502-1fb6d854-452f-4be6-97e7-b2bedf46ed04.png)

**Comment by GrizzlyAK** [comment]
Hi John, you can ignore this issue. After more testing, I determined that my CalDav Synchronizer add in for Outlook was also failing to sync, so I tried to log into my hosting service's cPanel, and found that I could not. After chatting with them, I discovered that my server along with many others were in the midst of a THREE DAY "maintenance" outage, so not only was my DAV service down, but so was all of my web sites and domains. I sent you log files via email, so you can ignore them. I'll close this now.

BTW, I appreciate what you do, and the TbSync app. It is just what I needed. Thanks, and cheers.

**Comment by jobisoft** [comment]
Thanks for letting me know! I am working on TbSync for 102, but it will take more time.
