### ISSUE TITLE
downgrade to TB91 without losing data

### ISSUE THREAD

**Issue by efa** [jobisoft/TbSync#599]
## Your environment
Win10
TbSync version: 3.0.2
Thunderbird version: 102.0.3 (64-bit)

## Expected behavior

I had trouble accessing Office365 account on server outlook.office365.com for calendar and people/addressbook.
With TB <100 worked, but I read downgrade is not strightforward, as in another issue you sayd:
"There is data being migrated from TB91 to TB102 (vCard storage in 102!!!!!) which is not reverted on downgrade, which can lead to massive data loss"

In the meantime of release TBSync compatible with TB102, I cannot stay without use the account calendar and address book, so can you please describe the right procedure to downgrade to TB91 without losing data?
thank you

**Comment by nklamann** [comment]
I tried this just now and TB 91 requires to create a new profile. I use IMAP so I will lose no mail but it is a lot of trouble . No more Autoupdate of Thunderbird for me. TBsync is a dealbraker becaus I use nextcloud for calendars etc.

**Comment by jobisoft** [comment]
You do not need TbSync for CalDAV/CardDAV in TB102. Both is supported natively.

**Comment by efa** [comment]
I'm not sure office365 use that protocol, as now with TB 102.1.0 I cannot sync the calendar and address book anymore.

**Comment by jobisoft** [comment]
> I'm not sure outlook.office365.com use that protocol, as now with TB 102.1.0 I cannot sync the calendar and address book anymore.

My comment was for @nklamann , who has a nextcloud. For O365, you indeed need to wait for the updated TbSync.

**Comment by nklamann** [comment]
Nextcloud runs native indeed.

**Comment by efa** [comment]
> For O365, you indeed need to wait for the updated TbSync

in the mean time can you please list the steps to
downgrade to TB91 without losing data?
thank you

**Comment by fp66** [comment]
I simply installed TB91 over TB102. I then started TB with `thunderbird.exe -P -allow-downgrade`. Thus I was able to choose the current profile again.

**Comment by lectrode** [comment]
While this doesn't help if you're already affected by this, I avoid this specific issue by launching thunderbird with the following script. It compares the profile version to the installed package version, and if the major.minor version changed, it refuses to launch thunderbird until you manually run it directly (preferably after backing up the `.thunderbird` folder).

If you backup your `.thunderbird` folder before running the latest version, you can replace the updated folder with the old one to revert to that state.

Please note:
* the "replaceMe" in the script needs to be replaced with the profile id you want to compare
* this is specifically written for Arch Linux and its derivatives, it will need to be tweaked for other package managers

```
#!/bin/bash

#Detect if thunderbird was updated since last run, notify and exit if true

#Settings#

thunderdir="/home/$USER/.thunderbird/<replaceMe>.default"


#Functions#

msg(){ notify-send -i thunderbird "Thunderbird Version Check" "$1"; }


#Main#

profvsn="$(cat "${thunderdir}/compatibility.ini" |grep "LastVersion"|cut -d'=' -f2|cut -d'_' -f1|grep -Eo "^[0-9]+\.[0-9]+")"
if [[ "$profvsn" = "" ]]; then msg "Error: Profile vsn not found"; exit; fi

pkgvsn="$(pacman -Q thunderbird|cut -d' ' -f2|grep -Eo "^[0-9]+\.[0-9]+")"
if [[ "$pkgvsn" = "" ]]; then msg "Error: Package vsn not found"; exit; fi

if [[ ! "$profvsn" = "$pkgvsn" ]]; then msg "ALERT: Backup required:\nUpdated from $profvsn to $pkgvsn"; exit; fi

echo Starting thunderbird...
nohup thunderbird >/dev/null

sleep 5; disown -ah; exit 0


```

**Comment by tikacp** [comment]
> I simply installed TB91 over TB102. I then started TB with `thunderbird.exe -P -allow-downgrade`. Thus I was able to choose the current profile again.

Nice one! This also worked for me under linux.
Still, an update of TBSync for 102.* would be highly appreciated!

**Comment by Drgz001** [comment]
> I simply installed TB91 over TB102. I then started TB with `thunderbird.exe -P -allow-downgrade`. Thus I was able to choose the current profile again.

FYI, deleting the Compatibility.ini file in the profile also worked fine for me

**Comment by jobisoft** [comment]
Preview of the EAS update is linked in the first comment of this issue:
https://github.com/jobisoft/EAS-4-TbSync/issues/167

Working on the DAV provider.
