### ISSUE TITLE
Extended addressbook fields

### ISSUE THREAD

**Issue by wandth** [jobisoft/TbSync#6]
Does it support the same extended addressbook fields/backend like TZPUSH? I use these fields also for my local addressbooks and would be afraid I lose those details when switching to your WIP plugin.

**Comment by jobisoft** [comment]
At the moment, no.

I took it out to have a clean start and to find out, what code is needed 
for sync and what I can ignore.

I have not yet an idea on how to bring it back. I keep it in mind.

**Comment by wandth** [comment]
Ok, good to know. So I will stick with TZPUSH for now. It is really nice being able to enter the extra fields that are supported by ActiveSync but I understand the lower priority right from start.

**Comment by jobisoft** [comment]
They are back!

![image](https://user-images.githubusercontent.com/5830621/40396400-27342488-5e2d-11e8-9ee1-1e3599614ecf.png)

It is part of the latest beta, but only if you [activate the new sync method](https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code). Test with care, its beta...
