### ISSUE TITLE
 Please add a TbSync icon to the Thunderbird Spaces Toolbar

### ISSUE THREAD

**Issue by ovari** [jobisoft/TbSync#604]
Thunderbird version 102 has a Spaces Toolbar.
https://blog.thunderbird.net/2022/09/thunderbird-tip-customize-colors-in-the-spaces-toolbar/

Can a TbSync icon please be added to the Thunderbird Spaces Toolbar?

Perhaps code pointers from the CardBook add-on can help as a CardBook icon shows in the Spaces Toolbar.
https://addons.thunderbird.net/thunderbird/addon/cardbook/
https://gitlab.com/CardBook/CardBook/

The webextension API is:
https://webextension-api.thunderbird.net/en/102/spacesToolbar.html#functions

What do you think?

Thank you

**Comment by jobisoft** [comment]
It does not open in a tab and therefore does not qualify for the spaces toolbar (which at a later point will group tabs into spaces).
