### ISSUE TITLE
How do I install v4.1?

### ISSUE THREAD

**Issue by NB574** [jobisoft/TbSync#608]
## Your environment

TbSync version: 4.1
Thunderbird version: 102.3.0

Hi, I downloaded the latest release, but when I try adding the extension in Thunderbird it asks me for the api.file, which I can't find. Can you tell me where this is located please. As the newest version is not listed in the add-ons manager in Thunderbird, I cannot download it directly from there.

**Comment by jobisoft** [comment]
I have added the XPI files to the releases.
