### ISSUE TITLE
TbSync not working with Thunderbird 102.3.1 (Linux version)

### ISSUE THREAD

**Issue by pwozniak89** [jobisoft/TbSync#609]
## Your environment

TbSync version: 3.0.2
Thunderbird version: 102.3.1

## Steps to reproduce
Install version 102.3.1

TbSync is disabled
Got a message saying : "TbSync is incompatible with Thunderbird 102.3.1"

**Comment by jobisoft** [comment]
There is a pinned issue at the very top, which deals with the update.
