### ISSUE TITLE
Lack of Email Support

### ISSUE THREAD

**Issue by LajiBasura** [jobisoft/TbSync#611]
Hi, this is a really great add on. Would it be possible to add support for email through ActiveSync EAS? This would make it much more helpful. I'm a Mac user, and there are no other email clients that support EAS (similar to Windows Mail or even mail apps on iOs). Not sure how much work that would be though. Thank you for the really excellent add on and the work you put into it.

**Comment by Zombie-Ryushu** [comment]
I am a Linux user in the same position, and I have to use the Pay Plugin Owl as part of my job.

**Comment by jobisoft** [comment]
Not on my roadmap. OWL does what you need.
