### ISSUE TITLE
All TbSync on Thunderbird 102 does is add a regular CalDav/CardDav entry to Thunderbird.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [jobisoft/TbSync#613]
<div class="change-set" id="c0"><div class="comment-text markdown-body " id="ct-0" data-comment-id="16101832" data-ismarkdown="true"><p>User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0</p>
<p>Steps to reproduce:</p>
<p>Mozilla Thunderbird 102 will not connect to CalDav and Card Dav 
Resources. I use eGroupware to connect to manage Address book, Calendars
 and Task resources. Upon updating to 102, The TbSync was disabled and 
when I tried using a beta from github for connecting Thunderbird 102 to 
TbSync, it seemingly succeeded but no Contacts were Synced.</p>
<p>I thought that maybe it had purged my eGroupware contacts database. 
This turned out not to be the case. I then tried using Thunderbird's 
native method, this failed too.</p>
<p>I use the eGroupware-docker package. I have removed the plugin to 
attempt to use Thunderbird's CardDav and CalDav Sources. The same thing 
happens. Thunderbird acts as if its going to connect, hangs there as if 
it is processing, and after a while gives up.</p>
<p>TbSync is listed as incompatible with Thunderbird 102. (the version 
on the Thunderbird Addon Page says that), but you can side load a beta 
XPI from github produced by the author. It doesn't work either. It 
downloads Zero contacts.</p>
<p>I can confirm it works with Evolution - it also works if I roll back to Mozilla Thunderbird 90.15 or whatever.</p>
<p>I've recently found out that I can add new entries to the address 
book, but not retrieve any. My CardDav Resource is a Dockerized 
eGroupware instance.</p>
<p>Actual results:</p>
<p>Thunderbird spends a long time trying to connect but retrieves no records.</p>
<p>Expected results:</p>
<p>600+ Address Book Records should have been Synced.</p>
</div></div><div class="change-set" id="c1"><div class="comment" data-id="16101955" data-no="1" data-tags="">
 
Is there any way that TbSync could go back to using its own implementation of CardDav and CalDav?

**Comment by jobisoft** [comment]
> Is there any way that TbSync could go back to using its own implementation of CardDav and CalDav?

I do not have the time. You should file a bug with Thunderbird and have its implementation fixed. Do not mention TbSync. Just report that Thunderbird fails to sync with your server.

**Comment by Zombie-Ryushu** [comment]
I have.

https://bugzilla.mozilla.org/show_bug.cgi?id=1794080

**Comment by jobisoft** [comment]
You derailed that bug report by mentioning TbSync.
