### ISSUE TITLE
Address Book truncates VCARD `CATEGORIES` field ==> Solved

### ISSUE THREAD

**Issue by virse** [jobisoft/TbSync#614]
`To avoid dataloss, I will release TbSync for Thunderbird 102 only after https://bugzilla.mozilla.org/show_bug.cgi?id=1792399 has been backported to Thunderbird 102.`

Just to let you know. The issue/bug is solved:
https://hg.mozilla.org/releases/comm-esr102/rev/63256dcf0c4a

Maybe you can now update to Thunderbird addon-repo plz?

greets

**Comment by jobisoft** [comment]
That is why I released v4.2 this morning. We need a few more days until TB 102.3.3 is shipped.

**Comment by jobisoft** [comment]
Had to revoke v.4.2 (#616) and released v4.3 and send it to ATN for review.
