### ISSUE TITLE
The 4.2 release is identical to the 4.1 release

### ISSUE THREAD

**Issue by SergeLalonde** [jobisoft/TbSync#615]
I downloaded the 4.2 release that was announced from here: https://github.com/jobisoft/TbSync/releases/tag/v4.2
I updated Thunderbird and the version of the add-on was still 4.1.
I thought that was odd, so I diff'ed the 4.1 release and the 4.2 release and found that they are identical.
Was the wrong xpi file posted by any chance?

**Comment by jobisoft** [comment]
Thanks for catching that. Fixed. The releases are in fact almost identical: For the official release which will go on ATN I raised the min required TB version to 102.3.3.
