### ISSUE TITLE
tbSync 4.3 doesn't work with Thunderbird 102.2.x (Ubuntu 20.04 current)

### ISSUE THREAD

**Issue by jdpipe** [jobisoft/TbSync#617]
TbSync version: 4.3 (attempted -- can't install it)
Thunderbird version: 102.2.2 (the latest version distributed with Ubuntu 20.04)

Just wondering if there is a reason why 102.2.2 can't be supported in tbSync + components? It is the version that Ubuntu is currently shipping on current/stable releases, and we can't be sure they'll bring out 102.3.x any time soon.

https://launchpad.net/ubuntu/+source/thunderbird

**Comment by jobisoft** [comment]
There is a bug in Thunderbird, which eats your categories. Fixed in 102.3.3. Everybody should always use the latest release of TB. Ping your maintainers. I do not want to be responsible for clearing users categories, so I disallow it.

**Comment by jdpipe** [comment]
OK, done. https://bugs.launchpad.net/ubuntu/+source/thunderbird/+bug/1993064

**Comment by jdpipe** [comment]
Less than 24 hours later, we have a new version of Thunderbird in Ubuntu (at least via a PPA) and it's all working again. I had to remove and re-sync a couple of items, but all looks good now. Many thanks!
