### ISSUE TITLE
Can't login after upgrade to 4.3

### ISSUE THREAD

**Issue by gkresic** [jobisoft/TbSync#618]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.3.3 (64-bit)

## Expected behavior
TbSync connects to my Google acc and sync contacts.

## Actual behavior
On sync attempt, TbSync asks for credentials (`User` field is blank and disabled) and my password doesn't work (password is valid for sure). I have 2FA enabled on my Google acc, so I did try generating new "App password", but that doesn't work either. Before upgrading Thunderbird to 102 and upgrading TbSync to 4.3 (after #591 is fixed and released) TbSync worked. I wanted to try disabling/enabling this account in TbSync settings, but was presented with a warning *Are you sure you want to disable this account? All local modifications, which have not been synced yet, will be lost!* which made me ask here for advice first.

## Steps to reproduce
Upgrade Thuinderbird to 102 and TbSync to 4.3 and try to synchronized **existing** Google account.

**Comment by jobisoft** [comment]
I have dropped support for Google long ago. It was possible to still use it in 91 via a hidden preference. Purged that as well now.

**Comment by jobisoft** [comment]
Original statement when I decided to drop the support:
https://web.archive.org/web/20201123152455/https://github.com/jobisoft/DAV-4-TbSync/issues/240

That issue now just points to alternatives.

**Comment by gkresic** [comment]
I remember that post and hidden property, but wasn't aware that it was dropped from 4.3.

It's unfortunate, but I understand your position here.

**Comment by jobisoft** [comment]
For contacts, there is google-4-tbsync, but needs a few extra steps because it does not ship with a global google app.

https://addons.thunderbird.net/addon/google-4-tbsync/

**Comment by jobisoft** [comment]
Using your own google app, saves you from the rate issue, which the standard built-in google-carddav support currently is affected by.

**Comment by gkresic** [comment]
`google-4-tbsync` works perfectly, thanks.

**Comment by jobisoft** [comment]
🥳

**Comment by NeilH37** [comment]
Apologies, I do have Goggle-4-TbSync installed.
