### ISSUE TITLE
Sync against Horde for contacts with large data in phone number fields fails silently

### ISSUE THREAD

**Issue by xj25vm** [jobisoft/TbSync#62]
TBSync 0.7.6.8
Thunderbird: 52.3.0
Horde 5.2.22

It seems that Thunderbird supports much longer fields for phone numbers than the Horde back-end does. The problem is that the current sync code silently ignores any contacts which have larger phone fields than the Horde back-end.

I suppose a robust solution would be a way to detect such incompatibility during sync, and warn the user. Just checking the Thunderbird phone field data against a set maximum string length might not be robust enough - as Horde allows customizing the back-end database and field lengths - so it is not guaranteed that all Horde installs will have the same size limits for phone number fields.

Steps to reproduce:

1. Add a contact to Thunderbird, and input a large amount of data int he phone field, for example:
    "+44 (0)151 334 49 90 (direct office number, but only after 12pm)"
2. Attempt to sync to the back-end.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/Troubleshooting

**Comment by jobisoft** [comment]
May I also point to this:
https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code

I would appreciate your feedback on the new sync method!
