### ISSUE TITLE
The meeting description empty

### ISSUE THREAD

**Issue by DavidFerne** [jobisoft/TbSync#623]
Hello,

## Your environment
Office 365
TbSync version: 4.3
Thunderbird version:102.4.0 (64-bit)

## Expected behavior
to keep the meeting description

## Actual behavior
The meeting description is empty (link, details,...)
...

## Steps to reproduce
Create a meeting in thunderbird, accept it by thunderbird, the meeting descrption is empty (general problem)

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by DavidFerne** [comment]
The status  meeting after accepting stays in tentative and not accepted

**Comment by jobisoft** [comment]
TbSync/EAS has no full meeting support, there is a dupe of this somewhere.
https://github.com/jobisoft/EAS-4-TbSync/wiki/About:-Provider-for-Exchange-ActiveSync

Use OWL if you need business features.
