### ISSUE TITLE
TBSync no longer syncing Google Contacts-Asks for password

### ISSUE THREAD

**Issue by NeilH37** [jobisoft/TbSync#626]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.4.1

## Expected behavior
I followed the instruction for a standard install of CardBook etc  and Thunderbird was syncing my email, calendar and address book ok but now asks for a password. This started sometime in the last week or two so V4,3 may or may not have prompted it (V4.3  update was installed 16 Oct. 

## Actual behavior
Every thing works OK except Contacts no longer sync and prompt for password appears.  I don't recall ever creating an account , user ID or password 

## Steps to reproduce
Happens every time. Debug report pasted below
** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[TbSync init] : Start (4.3)

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Thunderbird] : 102.4.1 on WINNT

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <db>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <addressbook>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <lightning>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <eventlog>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <core>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <passwordManager>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <network>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <tools>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <manager>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <providers>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Loading module <messenger>] : OK

** Fri Oct 28 2022 10:39:40 GMT+0100 (British Summer Time) **
[Initializing module] : <db>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <addressbook>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <lightning>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <eventlog>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <core>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <passwordManager>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <network>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <tools>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <manager>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <providers>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Initializing module] : <messenger>

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[TbSync init] : Done

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Loaded provider] : dav::CalDAV & CardDAV (4.3)

** Fri Oct 28 2022 10:39:41 GMT+0100 (British Summer Time) **
[Loaded provider] : google::Google's People API (0.4.2)

** Fri Oct 28 2022 10:40:36 GMT+0100 (British Summer Time) **
[setSyncState] : State: send.getfolders, Account: Main Sync'd

** Fri Oct 28 2022 10:40:36 GMT+0100 (British Summer Time) **
[setSyncState] : State: send.getfolders, Account: Main Sync'd

** Fri Oct 28 2022 10:40:36 GMT+0100 (British Summer Time) **
[URL Request #1] : https://apidata.googleusercontent.com/caldav/v2/haskettneil%40gmail.com/user

** Fri Oct 28 2022 10:40:36 GMT+0100 (British Summer Time) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

** Fri Oct 28 2022 10:40:37 GMT+0100 (British Summer Time) **
[RESPONSE] : 401 (Unauthorized) : <?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>loginRequired</code>
  <internalReason>Login Required.</internalReason>
 </error>
</errors>

** Fri Oct 28 2022 10:40:37 GMT+0100 (British Summer Time) **
[setSyncState] : State: passwordprompt, Account: Main Sync'd

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[Error adding loginInfo] : [Exception... "[JavaScript Error: "Can't add a login with a null or empty password." {file: "resource://gre/modules/LoginManager.jsm" line: 266}]'[JavaScript Error: "Can't add a login with a null or empty password." {file: "resource://gre/modules/LoginManager.jsm" line: 266}]' when calling method: [nsILoginManager::addLogin]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://tbsync/content/modules/passwordManager.js :: updateLoginInfo :: line 42"  data: yes]

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[URL Request #2] : https://apidata.googleusercontent.com/caldav/v2/haskettneil%40gmail.com/user

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[setSyncState] : State: send.getfolders, Account: Main Sync'd

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[REQUEST] : PROPFIND : <d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[RESPONSE] : 401 (Unauthorized) : <?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>loginRequired</code>
  <internalReason>Login Required.</internalReason>
 </error>
</errors>

** Fri Oct 28 2022 10:40:44 GMT+0100 (British Summer Time) **
[setSyncState] : State: passwordprompt, Account: Main Sync'd

** Fri Oct 28 2022 10:40:46 GMT+0100 (British Summer Time) **
[EventLog] : 401
URL:
https://apidata.googleusercontent.com/caldav/v2/haskettneil%40gmail.com/user (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>loginRequired</code>
  <internalReason>Login Required.</internalReason>
 </error>
</errors>

** Fri Oct 28 2022 10:40:46 GMT+0100 (British Summer Time) **
[EventLog] : 401
URL:
https://apidata.googleusercontent.com/caldav/v2/haskettneil%40gmail.com/user (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="UTF-8"?>
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>loginRequired</code>
  <internalReason>Login Required.</internalReason>
 </error>
</errors>

** Fri Oct 28 2022 10:40:46 GMT+0100 (British Summer Time) **
[setSyncState] : State: accountdone, Account: Main Sync'd

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/issues/618

**Comment by jobisoft** [comment]
I deleted your post in the other issue, as it did not belong there.

If you encounter issues with google-4-tbsync, you better file an issue there :-)
https://github.com/zanonmark/Google-4-TbSync/issues

But make sure that there are no dangling settings in your profile. Before creating a new issue, make sure it also does not work in a fresh profile.
