### ISSUE TITLE
Version 4.3 still incompatible? 

### ISSUE THREAD

**Issue by VasiliyArkhipov2** [jobisoft/TbSync#627]
I've been waiting for your release but TB 102.2.2 (runs on LM21) gives me an "incompatible" warning. Trying to install from file results in an incompatible notification. Same thing applies to the Caldav and Cardav Provider.

According to the file information provided on ATN TBSync 4.3 should be compatible to TB102.* :-/ 

[Version 4.3](https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync/versions/4.3) Released Oct. 12, 2022 294.7 KiB Works with Thunderbird 102.3.0 - 102.*
 
Do you have any ideas what's wrong?

TIA. 

        Released on ATN.

_Originally posted by @jobisoft in https://github.com/jobisoft/TbSync/issues/591#issuecomment-1279946402_

**Comment by jobisoft** [comment]
> Works with Thunderbird 102.3.0 - 102.*

That does not include 102.2.2

Update your Thunderbird to 102.3.3 or 102.4. I have no idea why linux distros are leaving their users on old broken versions.

**Comment by VasiliyArkhipov2** [comment]
I activated temporarily the PPA for Ubuntu Mozilla Security Team. Both extensions installed flawlessly. Thanks for the hint.
