### ISSUE TITLE
Not compatible with Thunderbird 102.2.2

### ISSUE THREAD

**Issue by jotkah** [jobisoft/TbSync#628]
Hi Folks,

after my distributor upgraded to Thunderbird 102.2.2 (Linux Mint), i got an error message that tbsync cannot be started because it is not compatible with this version of Thunderbird.

Greetings from Germany,
Joerg

**Comment by JezhikLaas** [comment]
Hi,
same here on Ubuntu 22.04.1 LTS.

Also greetings from Germany,
Uwe

**Comment by jobisoft** [comment]
I really cannot help you. I have no idea why your distro is shipping an old version of Thunderbird. Current is 102.4.1. I deliberately do not allow TbSync to run with TB 102.2.* because that version is broken and has a data-loss bug in the address book component.

**Comment by mklingn** [comment]
@JezhikLaas , @jotkah , you could get a recent Thunderbird via the ubuntu-mozilla-security PPA:

sudo add-apt-repository ppa:ubuntu-mozilla-security/ppa 
sudo apt-get update
sudo apt-get install thunderbird

But you might also get a recent Firefox the next time you apt-get dist-upgrade ;-)

**Comment by jotkah** [comment]
I don't want to use "foreign" repositories as this is a high risk (security, system integrity).

Some days ago Thunderbird 102.4.2 was delivered with the Ubuntu repositories. The add-on still doesn't work.

I have switched to Evolution - CalDAV, CardDAV etc. will work "out of the box" so that is no need to switch back to Thunderbird in the moment.

Thank you for your assistance!

**Comment by JezhikLaas** [comment]
For me it is now working (again) on (K)Ubuntu.

Thanks for this project! (Donation sent)
