### ISSUE TITLE
TBSync does not work on MAC with Provider for ExchangeAktiveSync [SOLVED]

### ISSUE THREAD

**Issue by leopoldstammler** [jobisoft/TbSync#629]
## Your environment

TbSync version: 4.3
EAS 4.1.5
Thunderbird version:

## Expected behavior
Syncing should work as ist does under Windows and Linux 
## Actual behavior
TbSync does not accept my password when connecting to the ExchangeServer
Im "Ereignisprotokoll" findet sich "Authentifizierung fehlgeschlagen, überprüfen sie Benutzernamen und Passwort"
Dem zuvor geht eine Litanei an Warnmeldungen bezüglich timezones:
* Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Start (4.3)

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Thunderbird] : 102.4.2 on Darwin

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <db>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <addressbook>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <lightning>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <eventlog>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <core>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <passwordManager>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <network>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <tools>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <manager>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <providers>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loading module <messenger>] : OK

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <db>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <addressbook>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <lightning>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <eventlog>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <core>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <passwordManager>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <network>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <tools>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <manager>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <providers>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Initializing module] : <messenger>

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[TbSync init] : Done

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : Default timezone has been found.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Argentina/Buenos_Aires> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Argentina/Catamarca> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Argentina/Cordoba> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Argentina/Jujuy> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Argentina/Mendoza> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Indiana/Indianapolis> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Kentucky/Louisville> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <America/Nuuk> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Antarctica/Troll> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Asia/Ho_Chi_Minh> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Asia/Kathmandu> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Asia/Kolkata> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Asia/Yangon> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Atlantic/Faroe> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Europe/Kyiv> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : The IANA timezone <Pacific/Kanton> cannot be mapped to any Exchange timezone.

** Sat Nov 05 2022 18:42:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[Loaded provider] : eas::Exchange ActiveSync (4.1.5)

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Microsoft is disabling old authentication methods. Remove the TbSync Account and create it anew using the modern authentication (o365/oauth)

**Comment by leopoldstammler** [comment]
Thanks a lot - worked for me!
