### ISSUE TITLE
TbSync 4.3 won't install with TB102.2.2

### ISSUE THREAD

**Issue by pH142857** [jobisoft/TbSync#630]
## Your environment
TbSync version: none now...
Thunderbird version: 102.2.2 (64-bit)

After the latest Thunderbird update (version 102), I needed to upgrade my TbSync from v2 to v4.3. I'm on Ubuntu and the repositories weren't updated. In Addons and Themes, TbSync was deemed incompatible and no update was found. I deleted it and typed TbSync in the searchbox to install v4.3.

## Expected behavior
On [the website](https://addons.thunderbird.net/en-US/thunderbird/addon/tbsync), it is said that TbSync 4.3 "Works with Thunderbird 102.3.0 - 102.*", so I would expect the same from within my TB addons browser and I would expect a seamless install.

## Actual behavior
However, this is was I get:
![Capture d’écran de 2022-11-07 16-33-19](https://user-images.githubusercontent.com/11050141/200350446-0f6d4335-afe2-4c1d-96bf-7cb67ff47d82.png)
And indeed, when I download tbsync-4.3-tb.xpi, TB refuses to install it:
![Capture du 2022-11-07 16-37-09](https://user-images.githubusercontent.com/11050141/200351128-0ea571a5-f3bc-43fc-8196-09f51bfa0035.png)

## Steps to reproduce
If it does not appear like that from within your TB, I have no idea.

**Comment by jobisoft** [comment]
Your version of TB is to old. It is not included in  the acceptable version range quoted by you.

Check out:
https://www.ubuntuupdates.org/ppa/ubuntu_mozilla_security

**Comment by pH142857** [comment]
Oops, you're right, I pasted the range without checking, I couldn't imagine there would be a gap in the compatible versions... So now I've got to update my thunderbird via a new PPA that I had never heard of before, otherwise I can't find back my initial setup. :( I'm appalled by how we failed at making a newbie-friendly process for software updates on Linux...
Thanks anyway.

**Comment by pH142857** [comment]
I just realized there were already three issues on this subject. I'm sorry for the useless load, I should have looked the recently closed issues.

**Comment by jobisoft** [comment]
Going to reopen this to help others to find it faster.

**Comment by gavanfantom** [comment]
Given that Ubuntu is still shipping Thunderbird 102.2.2, is it possible to backport support for this version?

**Comment by jobisoft** [comment]
> Given that Ubuntu is still shipping Thunderbird 102.2.2, is it possible to backport support for this version?

No, because TB 102.2 is broken and I deliberately deny my addon to work with that version, to prevent data loss.

**Comment by gavanfantom** [comment]
That's fair, thank you for explicitly stating the reason.

**Comment by chaos-prevails** [comment]
> Given that Ubuntu is still shipping Thunderbird 102.2.2, is it possible to backport support for this version?

I think the better solution is to simply add the mozillateam ppa as a source for apt, so you get a more up to date version of Thunderbird (same version as offered to download on thunderbird.net)

I use it for more than a year (first 20.04, now 22.04) and it works great, as I'm not dependent on the update schedule for Thunderbird by the ubuntu team. Due to various issues with Firefox via snap on 22.04, I also use this repository now for Firefox.

more info: https://launchpad.net/~mozillateam/+archive/ubuntu/ppa

**Comment by pcause** [comment]
I am on windows 102.5.1 and after the install of the addon I don't see a way to get to the addon.  There is no icon and nothing to go to options in the extension settings

**Comment by jobisoft** [comment]
I assume this is no longer an issue now?

**Comment by pcause** [comment]
yes
