### ISSUE TITLE
Step by step  TBSync

### ISSUE THREAD

**Issue by SimonCalibra** [jobisoft/TbSync#631]
First of all a big thank you to Jobi.

I am not an IT specialist and I have lost my way a bit, even though I have been following the topic for 2 months. From the moment of problems with the new version.

What is the right way for a Clean Installation. New Windows 10 new Thunderbird? Step by step ? What first ?

## Your environment

TbSync version:
Thunderbird version: 102.4.2 (32 bit)

**Comment by jobisoft** [comment]
You do not need to re-install Thunderbird and/or Windows. Open your add-on manager. Do you have TbSync installed? If so, click on the gear icon and select "check for updates":

![image](https://user-images.githubusercontent.com/5830621/201094069-594c7a97-0b72-41fb-b013-f53830f1e90e.png)

It should then find the latest version of TbSync.

**Comment by SimonCalibra** [comment]
Thank you for your help. I just got a new laptop. So I have to do everything all over again. :)

**Comment by SimonCalibra** [comment]
do I need other add-ons besides TbSync to synchronize gmail.com contacts?

**Comment by BillH99999** [comment]
To use TbSync with gmail.com you need Provider for CalDAV & CardDAV and Google-4-TbSync.  This will only sync address books and not calendars.

 An alternative to using TbSync is Cardbook. This also only syncs address books.

**Comment by SimonCalibra** [comment]
Big Beer for You :)

**Comment by jobisoft** [comment]
> To use TbSync with gmail.com you need Provider for CalDAV & CardDAV and Google-4-TbSync. This will only sync address books and not calendars.

For google, only TbSync and  Google-4-TbSync is needed. The Provider for CalDAV & CardDAV (DAV-4-TbSync) is not needed,

**Comment by SimonCalibra** [comment]
Thank you jubi for your hard work!
