### ISSUE TITLE
Tbsync in TB 102 keeps asking for password

### ISSUE THREAD

**Issue by Rbss7** [jobisoft/TbSync#633]
TbSync version:4.3
Thunderbird version:102.4.2 (64bit)

     After updating to TB 102 and then getting the updated compatable Tbsync file, I am still getting the  "Please update the credentials for the following Tbsync account:" and asks for my password. When I insert it, it won't accept it and asks for it again in an endless cycle.
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Rbss7** [comment]
Here is the debug report.
[debug.log](https://github.com/jobisoft/TbSync/files/10013763/debug.log)
[debug.log](https://github.com/jobisoft/TbSync/files/10013771/debug.log)

**Comment by CoolSpot** [comment]
Same here.
I suspect this might be related to MS not accepting password auth anymore, it must be OAuth 2.x now.

**Comment by jobisoft** [comment]
TbSync supports OAuth, but you have to delete your TbSync account and set it up anew, using the third setup option.

**Comment by jinlee386** [comment]
> TbSync supports OAuth, but you have to delete your TbSync account and set it up anew, using the third setup option.

I have same issue.
What is the third setup option?

**Comment by jobisoft** [comment]
> What is the third setup option?

OAuth / modern

![image](https://user-images.githubusercontent.com/5830621/202380636-ede04782-6270-4f28-8fe9-110068e279b5.png)

**Comment by jinlee386** [comment]
> 

I'd like to use tbsync for Google contact sync. But I know Google doesnot support this third option.

**Comment by jobisoft** [comment]
This issue is not about Google. OP should have filed it with the EAS provider.

Since 102 I personally no longer support Google. I have dropped it over a year ago, but allowed existing accounts to keep working, but did not allow to create new google accounts. I have now dropped support entirely. 

https://web.archive.org/web/20201123152455/https://github.com/jobisoft/DAV-4-TbSync/issues/240

You could try out the dedicated google provider:
https://addons.thunderbird.net/de/thunderbird/addon/google-4-tbsync/

**Comment by jinlee386** [comment]
> This issue is not about Google. OP should have filed it with the EAS provider.
> 
> Since 102 I personally no longer support Google. I have dropped it over a year ago, but allowed existing accounts to keep working, but did not allow to create new google accounts. I have now dropped support entirely.
> 
> https://web.archive.org/web/20201123152455/https://github.com/jobisoft/DAV-4-TbSync/issues/240
> 
> You could try out the dedicated google provider: https://addons.thunderbird.net/de/thunderbird/addon/google-4-tbsync/

Ok Understood.
google-4-tnsync working well.
Many Thanks.
