### ISSUE TITLE
CardDAV contacts updated every time an email is sent

### ISSUE THREAD

**Issue by bnavigator** [jobisoft/TbSync#637]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.5.0
Provider für CalDAV & CardDAV: 4.3
CardDAV Backend: Nextcloud 25.0.1

## Expected behavior
Only update contacts with real changes

## Actual behavior
Every time I write a message to a recipient found in a writable CardDAV Addressbook, that contact is updated. This creates a "changed contact" event on Nextcloud, which pushes a notification to all users with whom the addressbook is shared and who have activated such notifications (on by default). The change is also visible in the "Activity" log. That is not only an annoyance for users getting numerous push notifications but also violating my privacy, because it makes public when and with whom I communicate.

**Comment by jobisoft** [comment]
You will need to file a bug with Thunderbird. Since 102, I use native Thunderbird CardDAV sync. The add-on still existsbecause my discovery code is still a bit better and users want to keep using my UI.

**Comment by bnavigator** [comment]
Understood. Thank you.
