### ISSUE TITLE
Question: Is there a way to increase the window of sync (dav4tbsync)

### ISSUE THREAD

**Issue by jobst** [jobisoft/TbSync#638]
TbSync version: latest
Thunderbird version: latest
dav4tbsync: latest

Is there a way I can increase the sync window, is seems I only get 5 weeks or so when initializing a new calendar?
Is this maybe the issue of the DAV server on the other side?

**Comment by jobisoft** [comment]
Not that I am aware of. Contact your server admin and check the configs. I do not think CalDAV/CardDAV has an official extension which allows the *client* to set a sync window.
