### ISSUE TITLE
Error preventing syncing icloud calendars

### ISSUE THREAD

**Issue by TommyOe1** [jobisoft/TbSync#641]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.6.1

## Expected behavior
Syncing calendar

## Actual behavior - Sync fails, see below
** Wed Dec 21 2022 07:58:43 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : [JavaScript Error: "this.mOfflineStorage is null" {file: "resource:///modules/CalDavCalendar.jsm" line: 280}]'[JavaScript Error: "this.mOfflineStorage is null" {file: "resource:///modules/CalDavCalendar.jsm" line: 280}]' when calling method: [calIChangeLog::offlineStorage]

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by TommyOe1** [comment]
Solved by deactivating "offline-support" under options

**Comment by francks-git** [comment]
> Solved by deactivating "offline-support" under options
Hi,
Thank's @TommyOe1 !
Same solution for contacts synchronization with nextcloud contacts.
TBsync said : "au moins une ressource a rencontré une erreur".
TbSync version: 4.3
Thunderbird version: 102.6.0
Nextcloud 25.0.3 + Contacts 5.0.3
Regards
