### ISSUE TITLE
Minor Typos in German Localisation

### ISSUE THREAD

**Issue by Andreas-Kromke** [jobisoft/TbSync#642]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.6.1

## Typos

"Es sind aktuell noch keine Konten konfiguriert." must be "Es sind noch keine Konten konfiguriert" or similar. Note the misplaced filling word "aktuell" (English "actual" is German "tatsächlich").

"Konto Aktionen" must be "Konto-Aktionen" or similar. Note the missing hyphen.

"Neues Konto hinzufügen" should be "Konto hinzufügen". There is no need that the account is new, in fact the account should already exist.

"Thunderbird Adressbuch" should be "Thunderbird-Adressbuch" (combined noun) or "Thunderbirds Adressbuch" (genitive).

"Wikiseiten des TbSync Projektes" should be "Wikiseiten des TbSync-Projektes". Note the missing hyphen.

In "Sync Status" the term "Serverzugriff nur lesend (verwerfe lokale Änderungen)" is ambiguous. Most probably there is a misspelling, and it should be "verwirf" (imperative singular of "werfen" is "wirf"). However, I would prefer something like "lokale Änderungen ignorieren" (infinitive) which is easier to understand.

"ActiveSync Server Konfiguration" must be "ActiveSync-Server-Konfiguration". Note the missing hyphens.

"ActiveSync Version" must be "ActiveSync-Version". Note the missing hyphen.

"Server Adresse" must be "Server-Adresse". Note the missing hyphen.

Same with "ActiveSync Geräte ID" with two missing hyphens.

"Allgemeine Optionen" should be "Allgemeine Einstellungen".

"Kontakt Optionen" must be "Kontakt-Einstellungen" or "Kontakteinstellungen".

"Kalender Optionen" must be "Kalender-Einstellungen" or "Kalendereinstellungen".

## Actual behavior
see above

## Steps to reproduce
The issues are visible just after intallation, at first start.

**Comment by jobisoft** [comment]
Translations are managed here:
https://crowdin.com/project/tbsync

I cannot merge this ticket manually. Could you update the locale files via crowdin?
