### ISSUE TITLE
Microsoft has permanently disabled the Basic Authentication on Office365/Exchange as of Jan 14, 2023 and TbSync is no longer working. Please help ...

### ISSUE THREAD

**Issue by dundee111** [jobisoft/TbSync#644]
## Your environment

TbSync version: 4.3
Provider for Exchange ActiveSync version: 4.1.5
Thunderbird version: 102.6.1 (IMAP, Authentication Method: OAuth2). It no longer works using the 'Normal Password'

## Expected behavior
...
## Actual behavior
...Microsoft has permanently disabled the Basic Authentication on their Office365 and TbSync can't log in anymore; it's being asked to enter the password repeatedly

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
TbSync supports modern authentications (OAUTH). Remove your TbSync accont and create a new one, using the 3rd option.

**Comment by dundee111** [comment]
Thank you. It's working now.
