### ISSUE TITLE
Adding account to TB that uses Microsoft Exchange error

### ISSUE THREAD

**Issue by Rbss7** [jobisoft/TbSync#646]
## Your environment- Windows 10

TbSync version: 4.3
Thunderbird version: 102.7

## Expected behavior-
 When adding an account, I receive the error message "Supplied value not in allowed list". Attached is a screenshot.
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
![error message2](https://user-images.githubusercontent.com/116846574/215592142-2a21d886-fe3a-4c01-a5bd-e9a5262c0390.jpg)

![error message2](https://user-images.githubusercontent.com/116846574/215592247-d4c5abaa-2e98-4dba-9e09-8e21743bb62e.jpg)

**Comment by jobisoft** [comment]
That is not TbSync. That is Thunderbirds account wizard. I assume you get the same error, when TbSync is disabled?

**Comment by Rbss7** [comment]
You're right. Same error with TbSync disabled.
 I had put the question in TB forum before, but nobody has replied to it.



    On Tuesday, January 31, 2023 at 02:44:36 AM EST, John Bieling ***@***.***> wrote:  
 
 


That is not TbSync. That is Thunderbirds account wizard. I assume you get the same error, when TbSync is disabled?

**Comment by stheine** [comment]
Same issue here.
For the moment I downgraded Thunderbird to 102.6.1 and TBSync is working again.
