### ISSUE TITLE
Adding EAS M365 account attempts to load auth URL with 'undefined' as the hostname

### ISSUE THREAD

**Issue by pkopacz** [jobisoft/TbSync#647]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.7.1 (64-bit)

## Expected behavior
When adding an new Microsoft 365 account, I enter my email address and use autodiscover to load the authentication page.

## Actual behavior
The authentication URL that it tries to load doesn't work:
https://undefined/?response_type=code&client_id=undefined&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize&login_hint=pkopacz%40uoguelph.ca

## Steps to reproduce
Attempt to add a new EAS account to TBSync and choose M365 and an @uoguelph.ca address... I don't have any other domain to test.

Debug file only contains this:

** Wed Feb 01 2023 14:36:01 GMT-0500 (Eastern Standard Time) **
[Querry EAS autodiscover V2 URL] : https://autodiscover-s.outlook.com/autodiscover/autodiscover.json?Email=pkopacz%40uoguelph.ca&Protocol=ActiveSync

**Comment by btaroli** [comment]
Existing accounts, at time of upgrade, similarly fail to login or sync. I tried to remove accounts and fully reinstall and then ran into the issue reported here. I presume it is the same cause, as of TB 102.7.1

<img width="494" alt="Screenshot 2023-02-01 at 7 12 22 PM" src="https://user-images.githubusercontent.com/662620/216222768-3b06baec-7c1d-49ff-b38f-99e8eaedd424.png">

**Comment by xmentos** [comment]
Same here, same thunderbird and tbsync versions.

**Comment by stheine** [comment]
Same issue here.
For the moment I downgraded Thunderbird to 102.6.1 and TBSync is working ok.

**Comment by smmehta1822** [comment]
I ran into the same issue and had to revert back to TB 102.6.1

**Comment by alex-metcalfe-358** [comment]
Same.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608
