### ISSUE TITLE
TbSync forgett the CalDav and CardDav provider after Thunderbird restarts

### ISSUE THREAD

**Issue by tualatin** [jobisoft/TbSync#648]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.7.1

## Expected behavior
The synchronization between Thunderbird and the cloud calendar/ contacts should work again.

## Actual behavior
See Steps to reproduce.

## Steps to reproduce
Start Thunderbird, TBSync brings an error message, that no synchronization provider should be exists. In the Extension view of Thunderbird all necessary extensions available. Reinstall a calendar/contact provider, TbSync works now. Close Thunderbird and restart Thunderbird, a error message from TBSync comes again.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Andrzej-W** [comment]
I have found a little bit easier solution than reinstalling the CalDav/CardDav provider. You can go to extension management in Thunderbird and disable/enable CalDav/CardDav extension. TbSync error disappears immediately after this operation. Unfortunately it is still annoying.

**Comment by Andrzej-W** [comment]
It looks that it is similar to https://github.com/jobisoft/TbSync/issues/622 but not the same. I have 3 computers with TB and TbSync+CalDav/CardDav+Category Manager. These are the only extensions installed in TB. TB version is 102.7.2. TbSync is 4.3, CalDav/CardDav is 4.3, Category Manager is 6.3. They are used to sync contacts and calendars from my iCloud account (I have only one account registered in CalDav/CardDav).

My computers:
- Apple MacBook Air 2020 with M1 processor.
- Laptop Lenovo with Windows 10 Pro 21H2 and Intel Core i7-6500U (2 cores, 4 threads).
- Brand new laptop MSI Raider with Windows 11 Pro 22H2. I have just installed it from scratch. It has Intel Core i7-12700H (14 cores, 20 threads).

So far I have the following observations:
1. EVERY TIME I start Thunderbird TbSync displays error that CalDav/CardDav is not installed.
2. I can disable/re-enable TbSync OR CalDav/CardDav provider and everything starts working (till next TB restart).
3. I can reproduce this sequence all the time - it always works exactly the same (I see the problem after every TB restart).
4. I have enabled debugging in TbSync->Help and restarted TB a few times. There are no errors in log file.

**Comment by tualatin** [comment]
Same here, no errors in log file.

**Comment by Basti-Fantasti** [comment]
Same issue here. 
After disabling / enabling the Provider for CalDav addon it works like a charm until restart of Thunderbird.
Then the error pops up again.

Thunderbird version 102.8.0 (64-Bit)

**Comment by jobisoft** [comment]
This should be fixed now, with the latest update from a few days ago. Can you confirm?

**Comment by Andrzej-W** [comment]
Works like a charm. Thank you very much @jobisoft for your time and hard work.
