### ISSUE TITLE
Weird CardDAV Sync Issues

### ISSUE THREAD

**Issue by GrizzlyAK** [jobisoft/TbSync#652]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.8.0

## Expected behavior
TBH, I don't know if this is a TbSync issue, a Thunderbird (sync) issue, or a CardDAV server issue. This has been working, but I recently changed Hosting Providers (still cPanel/Horde/CardDAV), but after recreating the accounts on the Host and setting them up on Thunderbird, I'm getting some weird sync issues.

What's Happening:
* I can create a contact or add something to an existing contact on the Host and it syncs to Tbird.
* I can create a contact or add something to an existing contact on Tbird and it syncs to the Host.
* I CANNOT delete something from an existing contact on Tbird (it pops right back), even tho my sync is set to 30 mins.
* I CAN edit something in Tbird that was created on the Host (e.g., a Note) and it syncs, but I can't delete the note by deleting the contents and saving. It pops back. However, if I replace the contents with a SINGLE SPACE, then the Note disappears completely, and Syncs (without the SPACE in either location!)
* I CAN delete the same element from the existing contact on the Host and it syncs correctly to Tbird.
* Incidentally, this behavior also occurs on my iPhone when I set up the same account, so unless Tbird is working to keep things "as they were", then that would point to a Host or Permission problem, but why only certain things not being allowed, like deleting part of a contact (I AM able to delete the entire contact on Tbird - that does work). Very odd.

Note that this occurs with TbSync enabled and when TbSync is disabled (it appears that I can sync both my CardDAV and iPhone CalDAV now natively in Tbird without TbSync. Is that the case?) Not sure if the log would help if this occurs when TbSync is disabled, but I can send it if it would help.

I've checked the permissions for the Address Books on the Host and they are all set to allow Show, Read, Edit, and Delete for All Authenticated Users, Guests, and Object Creator (basically everything).

I saw a post of something similar, and their solution was to use the full, long version URL specified by the CardDAV server instead of relying on autoconfig. I deleted the Accounts in Tbird and recreated them using the long URL, and there was no improvement.

Would you have any idea where this problem might originate?

## Actual behavior
See above

## Steps to reproduce
As indicated above

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Your observation is correct. For DAV, TbSync is now only a better setup wizard. Once the resources are created, you can disable TbSync, because the actual sync is done by the native DAV support by Thunderbird.

If you encounter sync issues, it might be worth to try to set up the resources without TbSync (maybe I am doing something wrong). If the issue still remains, then you need to file a bug with Thunderbird. Do NOT mention TbSync in your report, as that will only derail the issue (as they might say it is an add-on issue - simply do not mention it at all)

**Comment by GrizzlyAK** [comment]
Thanks John. Will do. Cheers.
