### ISSUE TITLE
Feature Request: Configure synchronization target

### ISSUE THREAD

**Issue by jr-com** [jobisoft/TbSync#657]
It would be great if it were possible to configure a synchronization target so that a given remote calendar e.g. nextcloud can be synchronized to another given target e.g. exchange. This would be one-way of course but would provide a solution for many common problems like merging multiple sources to one common destination. CalDavSynchronizer can do this, but is only available on windows platform for the outlook client. 

Is this a feasible feature for TbSync?

**Comment by jobisoft** [comment]
No, that is one of the main rules I will never break. The chance to mess something up is way to big.
