### ISSUE TITLE
Issue sending meeting

### ISSUE THREAD

**Issue by jretxaniz** [jobisoft/TbSync#658]
## Your environment Windows 10 proffesional 64 bits
 
TbSync version: 4.3
Thunderbird version: 102.9

## Expected behavior
Sending meetings invitation, 

## Actual behavior
Don't work

## Steps to reproduce
First time you click save and send, don't do anything. If you close, meeting is saved for you, but don't sends invitations 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Not supported. No resources to implement that feature.
