### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by joptvoje** [jobisoft/TbSync#659]
## Your environment

TbSync version:4.3
Thunderbird version:111.0.1

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...
I have Thunderbird installed on several computers an when I sync on one of them then all others lose sync and vice versa.

**Comment by jobisoft** [comment]
It looks like you cloned profiles and all your tbsync instances share the same device id. You need to remove the tbsync account on all your computers and need to set them up fresh on each (which generates a new device id)

**Comment by joptvoje** [comment]
Hi!

I think you are right. I wanted to do this the  easy way and copied portable thunderbird to all computers.
