### ISSUE TITLE
TBSync out of sync when using Thunderbird/TBSync on multiple computers.

### ISSUE THREAD

**Issue by dundee111** [jobisoft/TbSync#661]
## Your environment

TbSync version: 4.3
Thunderbird version: 102.9.1

## Expected behavior
...

## Actual behavior
... Whenever I launch Thunderbird on a different computer where I have TB installed, TBSync gives an error and I have to disable/enable the account to perform a successful sync. It seems like TBSync can only work successfully on 1 instance of Thunderbird.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).
![TBSync Errors](https://user-images.githubusercontent.com/122742187/228903044-68589cbf-f73f-4cc4-8855-f0cf551a1d53.jpg)

**Comment by jobisoft** [comment]
You probably cloned your profile? You need to delete your tbsync accounts on all computers and set them up fresh, which generates a unique device id on each.

**Comment by dundee111** [comment]
Per your advice, I deleted the TBSync account, and now I can't add it back. Keep going in the loop .... Searching for settings .....
(Using Microsoft Office 365 configuration option)
![Looping](https://user-images.githubusercontent.com/122742187/228997604-4afecb09-c031-4969-a056-649b106fa35c.jpg)

**Comment by dundee111** [comment]
Everything is working great now. Thank you for your help.
