### ISSUE TITLE
I randomly get sync errors every month or so on all of 5 of my machines, have to sign out and back in again to fix. 

### ISSUE THREAD

**Issue by rthfhgyhy567** [jobisoft/TbSync#667]
## Your environment
Windows 10 Pro
TbSync version:
3.02
Thunderbird version:
91.6.1
## Expected behavior
...
Its supposed to sync my office 365 account callendar and contacts without manual intervention.
## Actual behavior
...
I get the error: "At least one resource encountered a synchronization error.  Check the event log."

Event log link: https://justpaste.it/417pn
## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

It's also important to note that I am using the same thunderbird profile on all of these computers.  I was told this was the way to go to transfer all of your mods, addons, and settings over to your different PC's.  Could that be the problem?

**Comment by jobisoft** [comment]
Did you clone the profile from one machine to the other 4, or did you setup the TbSync accounts on all 5 machines individually, giving them all a unique deviceId?
