### ISSUE TITLE
Accepting calendar event in Google, removes meet link

### ISSUE THREAD

**Issue by MSBlueVn** [jobisoft/TbSync#675]
## Your environment

TbSync version: Latest
Thunderbird version: Latest

## Expected behavior
When I accept a meeting from TB, the event would be saved correctly to the calendar.
Meeting link would be saved correctly.

## Actual behavior
When accepting a meeting from the email part of TB, the event is saved to the calendar, but the meeting link to google meet is removed from the event.

## Steps to reproduce
Get a meeting invite to your google workspace email in TB, accept it from that bar on top of the email, see if the meet link is saved.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Wrong Repo. This is TbSync, the Manager UI. Syncing is done by the different providers.
