### ISSUE TITLE
Update for Thunderbird v. 115 (Supernova)

### ISSUE THREAD

**Issue by vvirtues** [jobisoft/TbSync#680]
## Your environment

TbSync version: N/A
Thunderbird version: 115 (supernova

## Expected behavior
addon loads

## Actual behavior
Addon cannot be turned on, incompatible with thunderbird version

## Steps to reproduce
1. Update thunderbird
2. Go to addons page
3. Addon permanently disabled
==

**Comment by panther7** [comment]
Duplicate with #669.

**Comment by vvirtues** [comment]
Sorry, closing
