### ISSUE TITLE
TBSync not compatible with TB115

### ISSUE THREAD

**Issue by PotatoCarl** [jobisoft/TbSync#682]
## Your environment

TbSync version: current
Thunderbird version: 115

## Expected behavior
Working

## Actual behavior
Not Working

## Steps to reproduce
always

Looking how to support getting a working version for TB115+
Thanks

**Comment by scollovati** [comment]
Duplicate of https://github.com/jobisoft/TbSync/issues/669

**Comment by PurpleZ2023** [comment]
[TbSync115.1.zip](https://github.com/jobisoft/TbSync/files/12239040/TbSync115.1.zip)

**Comment by PotatoCarl** [comment]
I installed the one from #669 which works. But the one posted above is not working (incompatible)

**Comment by PurpleZ2023** [comment]
ok strange, in my TB it works ....

**Comment by jobisoft** [comment]
Compatible versions have been submitted to ATN for review. ETA: a few days.
