### ISSUE TITLE
No scroll bars in resource list in TB 115, and also "columns" are not honored

### ISSUE THREAD

**Issue by jobisoft** [jobisoft/TbSync#683]
![image](https://github.com/jobisoft/TbSync/assets/5830621/2eff8cad-bd00-442b-96c1-37df4d21b45f)

**Comment by sbussinger** [comment]
I'm having this issue as well. I have a lot of Task categories and several calendars shared on the Outlook.com side, so there are about 11 entries in the scroll box that I can't reach.

**Comment by jobisoft** [comment]
Can you try this beta?
https://github.com/jobisoft/EAS-4-TbSync/files/12468302/TbSync_beta_4_7.zip

**Comment by jobisoft** [comment]
We need one where there are actually more items that fit into the available space, which adds a scrollbar :-)

**Comment by kelvinchin12070811** [comment]
Sorry for the misleading. Yes, it did add the scroll bar.

![image](https://github.com/jobisoft/TbSync/assets/31331535/facf56c5-6544-4133-9d9a-5e4a4b8381a2)

**Comment by MarcMichalsky** [comment]
> Can you try this beta? https://github.com/jobisoft/EAS-4-TbSync/files/12468302/TbSync_beta_4_7.zip

This also works for me.

Ubuntu 23.04
Thunderbird 115.2.0 (64-Bit)
Mozilla Thunderbird Snap for Ubuntuubuntu-snap-build - 1.0

**Comment by jobisoft** [comment]
Great.

I will not fix the UI hiccup (extra spaces, scrollbar in header area), because that is XUL, which is dead. After I finished the UI conversion of Quicktext, I will fix the issues related to the deprecated richlistbox for good (in HTML).

**Comment by jobisoft** [comment]
Released.
