### ISSUE TITLE
synch Javascript error

### ISSUE THREAD

**Issue by gcat60** [jobisoft/TbSync#685]
## Your environment
windows 11

TbSync version:
Thunderbird version: 102.14.0 (64-bit)

## Expected behavior
...synchronization with Outlook calendars account (EAS account)

## Actual behavior
OS is not defined

setDeviceInformation@chrome://eas4tbsync/content/includes/network.js:700:21
folderList@chrome://eas4tbsync/content/includes/sync.js:114:27
syncFolderList@chrome://eas4tbsync/content/provider.js:398:28
syncAccount@chrome://tbsync/content/modules/core.js:109:109
notify@chrome://tbsync/content/tbsync.jsm:156:29

Also a bunch of errors about timezones cannot be mapped to any exchange timezone
## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by gcat60** [comment]
made a mistake--this computer is windows 10 Pro 22H2 19045.3324.  Last update was from 8/9/23 so not likely a Windows update issue?  Have another computer with the same issue also Windows 10.  Several Windows 11 computers are all still working fine.

**Comment by gcat60** [comment]
noticed an update was made today for 115 compat--I downgraded my version to 4.3 and it is working again...

**Comment by jobisoft** [comment]
I raised the min version of v4.6 to TB115. Thanks for the report.
