### ISSUE TITLE
Add compatibility to TB 116

### ISSUE THREAD

**Issue by user858753257** [jobisoft/TbSync#687]
I know that you are working hard for supporting 115 . 

But today I have seen on my Linux desktop (arch distro) where I have installed "thunderbird-beta-bin" that I can't even use the add on when manual installed . 

Installation works fine . When I click on the "screwer" symbol and try to open the settings the window will close immediately

**Comment by panther7** [comment]
#669

**Comment by jobisoft** [comment]
I only support ESR.
