### ISSUE TITLE
New event to added to an EAS calendar does not show up on outlook.com

### ISSUE THREAD

**Issue by geckonapper** [jobisoft/TbSync#690]
When I add an event to an EAS calendar in Thunderbird, the event does not appear on outlook.com unless I click "Synchronize now".  Please make it so that when I add an event to an EAS calendar in Thunderbird, the event appears on outlook.com without having to click "Synchronize now".  I looked for a setting that would enable this but did not see one.

## Your environment

TbSync version: 4.7
Thunderbird version: 102.15.0 (64-bit)

## Expected behavior
Adding event to EAS calendar in Thunderbird causes the event to show up on outlook.com.

## Actual behavior
It does not unless I click "Synchronize now".

## Steps to reproduce
Add event to Thunderbird EAS calendar.  Log in to outlook.com and see that the event does not appear.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
You have to click sync now or setup an auto sync intervall.
