### ISSUE TITLE
Javascript error since latest version

### ISSUE THREAD

**Issue by DerXteMensch** [jobisoft/TbSync#691]
## Your environment

TbSync version: 4.7
Thunderbird version: 115.2.0

## Expected behavior
No error during sync

## Actual behavior
Error while syncing:

Javascript-Fehler! Bitte überprüfen Sie das Ereignisprotokoll für weitere Details!
addAlarm@resource:///components/calItemBase.js:1103:26
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/includes/calendarsync.js:88:18
setItemRecurrence@chrome://eas4tbsync/content/includes/sync.js:1332:49
setThunderbirdItemFromWbxml@chrome://eas4tbsync/content/includes/calendarsync.js:175:18
processCommands@chrome://eas4tbsync/content/includes/sync.js:915:49

This error doesn't happen for all synced calendars. It happens for two calendars from 12 synced calendars. All calendars are synced from the same account via Provider für Exchange ActiveSync (version 4.7).

The error didn't occur before. I used the beta version for TB 115 before and in this version the error didn't occur either.

## Steps to reproduce
Sync (manually or automatically)

I sent the debug.log via e-mail

**Comment by eddiermar** [comment]
I am experiencing the same problem...

TbSync version: 4.7
Thunderbird version: 102.6.1

Sent debug file by email too...

**Comment by jobisoft** [comment]
You are on an unexpected old version of Thunderbird (Why?). I updated the version limits, and you no longer get 4.7, but you have to manually downgrade to 4.3.

**Comment by DerXteMensch** [comment]
For my case, do you already have a clue? I'm on TB 115

**Comment by eddiermar** [comment]
> You are on an unexpected old version of Thunderbird (Why?). I updated the version limits, and you no longer get 4.7, but you have to manually downgrade to 4.3.

Thanks. It worked for me.

I had to downgrade to this version since TB started asking enhanced security and the organization I work for didn't take action on it. I think this was a year ago, so I kept this old but functional version so I can still using my favorite email software!
