### ISSUE TITLE
availibilities of invited persons when creating meeting are unseen

### ISSUE THREAD

**Issue by etremond** [jobisoft/TbSync#694]
## Your environment

TbSync version:
Thunderbird version:

## Expected behavior
...

## Actual behavior
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by Lev-Shereshevsky** [comment]
Duplicate of #696
