### ISSUE TITLE
No scheduling assistant available

### ISSUE THREAD

**Issue by af00b22f-4fd1-42c0-ba3f-a74ec02e08d0** [jobisoft/TbSync#696]
## Your environment

TbSync version: 4.7
Thunderbird version: 102.13.0
Server: MS-Exchange, version unknown

## Expected behavior

When I schedule a meeting, I see other peoples free and busy times, if they are on the same server.

## Actual behavior

I do not see other peoples busy times, it looks like nobody had any appointments.

## Steps to reproduce

Schedule a meeting with people on the same server, who already have some busy time slots.

## Note

I believe, that this feature used to work with calendar-exchange-provider back than, but I'm not sure.

**Comment by Lev-Shereshevsky** [comment]
The same behavior at Thunderbird 115.6.0 (32-bit), TbSync 4.8, Provider for Exchange ActiveSync 4.8, Exchange Server 2013.
It's a frustrating lack of functionality for teamwork.

**Comment by jobisoft** [comment]
That is not supported and I do not have the resources to implement that feature.
