### ISSUE TITLE
Nextcloud calendars not appearing as option to import event into

### ISSUE THREAD

**Issue by hockeymikey** [jobisoft/TbSync#699]
## Your environment

TbSync version: 4.7
Thunderbird version: 115.5.1

## Expected behavior
I have a number of calendars setup from Nextcloud. When I click accept on an event that someone emails me to choose which to import in to, it shows me all the calendars .

## Actual behavior
The calendars it shows for me to import in to are the external ones subscribed to in Nextcloud (such as a calendar for a sports team). These calendars are setup as webcals in Thunderbird it looks like, while the other ones are not. 
## Steps to reproduce
Setup TBSync using a nextcloud account and sync all your calendars. Try accepting an event in an email and see which ones it shows you. I have no issue creating new events or syncing otherwise. These calendars work otherwise if setup manually on their own.

**Comment by jobisoft** [comment]
Please note that CalDAV/CardDAV support will be sunset in TbSync. Thunderbird now has native support for CalDAV/CardDAV, and if it is not able to find your resources, you need to file a bug with Thunderbird.
