### ISSUE TITLE
Problem with recurrent events

### ISSUE THREAD

**Issue by hjmitsd** [jobisoft/TbSync#7]
Hi
first of all I am really glad about your project and impressed about the status, it already reached.
Congratutalions!

I discovered an issue with recurring events
I am using an  kopano/zarafa email server and
- my recurrent events already created  in zarafa are not shown in thunderbird tbsync calendar
- recurrent events created in thunderbird tbsync calendar show in zarafa a wrong period
If you want me to debug/test something, just let me know

Regards

Hansjörg

**Comment by jobisoft** [comment]
Hi,

recurring events are not yet implemented, it is scheduled for v.0.7.0

https://github.com/jobisoft/TbSync/issues/5

John

**Comment by Explorare** [comment]
Got the same issue with repeat event on Outlook.com calendar. Any work around? Thanks.

**Comment by jobisoft** [comment]
I think we will get there in 2018.
