### ISSUE TITLE
sync with CalDav not working

### ISSUE THREAD

**Issue by DoctorSubtilis** [jobisoft/TbSync#704]
## Your environment

TbSync version: 4.8
Thunderbird version: 115.7

## Expected behavior

a correct syncro between remote (murena) CAlDAv and TB tasks

## Actual behavior

while **contacts** are correctly synced (between remote CalDAv and TB), **tasks** are not synced (I still see old tasks).

## Steps to reproduce

Using tasks in ThunderBird

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please note that CalDAV support for TbSync will be sunset. Thunderbird supports CalDAV natively now, and if it is not able to find your resources, you need to file a bug with Thunderbird.
