### ISSUE TITLE
TbSync with EAS fails recently

### ISSUE THREAD

**Issue by ToBo69** [jobisoft/TbSync#705]
Linux Mint 21.2 Cinnamon

TbSync version: 4.8 (latest download)
Thunderbird version: 115.7.0 (64 bit)

## Expected behavior
Microsoft Outlook account should be synced in Thunderbird so that address and calendar items stay up to date

## Actual behavior
since several days, TbSync stopped synchronizing my Microsoft account (using the second required add-on Exchange ActiveSync) TbSync Event Log says:
`The server does not provide information about the supported ActiveSync versions. Is EAS blocked for this user or this client (TbSync)? You could try to set the ActiveSync version manually.`

## Steps to reproduce
Try to sync the account

So far I tried without avail:

    - Removing and adding the account information in TbSync (server address: outlook.office365.com)

    - Uninstalling both TbSync and Exchange ActiveSync add-on and installing them again

    - Turning on MFA for my Microsoft account and turning it off again

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

TbSync debug log says:
```
** Thu Jan 25 2024 11:24:40 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [setSyncState] : State: prepare.request.options, Account: ...@gmx.de

    ** Thu Jan 25 2024 11:24:40 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [Sending] : OPTIONS https://account.live.com/Microsoft-Server-ActiveSync

    ** Thu Jan 25 2024 11:24:40 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [setSyncState] : State: send.request.options, Account: ...@gmx.de

    ** Thu Jan 25 2024 11:24:41 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [setSyncState] : State: eval.request.options, Account: ...@gmx.de

    ** Thu Jan 25 2024 11:24:41 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [EventLog] : InvalidServerOptions


    ** Thu Jan 25 2024 11:24:41 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [EventLog] : InvalidServerOptions


    ** Thu Jan 25 2024 11:24:41 GMT+0100 (Mitteleurop�ische Normalzeit) **
    [setSyncState] : State: accountdone, Account: ...@gmx.de
```

When trying to open the link from the debug log,
https://account.live.com/Microsoft-Server-ActiveSync
the website opens with the following message:
```
    This website is temporarily not available.
    This website is temporarily unavailable because of maintenance. Please try again later.
```

**Comment by RRNYC** [comment]
Having the same problem for a month now.  Is there anything that can fix this?  Oauth for Outlook.com accounts is not an option for TBsync 4.3 on TB 102.  Throws errors whenever attempting to use it.

**Comment by RRNYC** [comment]
Thanks for the quick reply, John!  

I'm using the MS Active Sync add on (see image) from the TB add-ons site.

![image](https://github.com/jobisoft/TbSync/assets/160291927/14a78904-623a-451d-833a-57959545fb56)

I've tried a variety of attempted fixes, including changing the server (m.hotmail.com; eas.outlook.com;  m.outlook,com).  Some work for a brief time but eventually start throwing password prompts every few minutes.  

I also tried removing and reinstalling both add-ons to no effect. Also, the latest version of TBSync compatible with TB 102 throws a java script error and won't allow for the connection of any accounts.  

I have two accounts successfully connected via the Oauth MS Office option, and one legacy Hotmail account that used to connect via the Exchange option.  Whenever I attempt to use the Oauth MS Office option, I get error messages such as:

* Could not authenticate, check username and password (HTTP error 401)
* User not found (HTTP error 404)
* Could not connect to server (NS_ERROR_UNKNOWN_HOSTS)
* status.451

Thanks in advance for any help you can offer.  I don't want to upgrade to TB 115 just yet. The UX is terrible.
