### ISSUE TITLE
Apple reminders not showing up after sync

### ISSUE THREAD

**Issue by stephanieraymos** [jobisoft/TbSync#707]
## Your environment

TbSync version: 4.8
Thunderbird version: 115.7.0 (64-bit)

## Expected behavior
Reminders show up in calendar and in tasks sections of thunderbird

## Actual behavior
After setting up icloud connection, my calendars sync and show up as expected, but my reminders has a yellow triangle next to it with an exclamation, but it's not clickable so i dont know what the issue is.
I can see my reminders account in the left panel in both tasks and calendar sections but the reminders themselves do now showl up. The yellow warning flag is also visible in these tabs next to the account name 'reminders': iCloud (Reminders ⚠️)

## Steps to reproduce
Install tbsync add on to thunderbird on mac, add caldev extension, create app specific password on icloud, sign in, synchronize. Then your accounts will show. Mine all were good except for icloud which had the yellow flag next to it. Nothing in error logs. 

I enabled debug and toggled offf the enable sync account option, then reenabled it and started over. The same thing happened. The yellow flag is there even before selecting it as a resource and syncing it. When syncing it says it was successful. 
Nothing in debug or event logs.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Apple reminders are not CalDAV, Apple decided to move them to a proprietary system. There is a stale reminder entry on the CalDAV server, but it is not connected to the iOS Reminders App.
