### ISSUE TITLE
tbSync/CalDAV&CardDAV Provider cannot find any resources on Zimbra anymore or cannot identify Zimbra as a CalDAV/CardDAC server

### ISSUE THREAD

**Issue by cluster15** [jobisoft/TbSync#709]
## Your environment

TbSync version: 4.8 
Thunderbird version: 115.7.0 (64-bit)

I synchronize calendars (yes several!)  and two address books flawlessly with a zimbra server for years now. Yesterday I noticed that the two address books were marked as being deleted on the server. The calendars  were seemingly still present and working. Since there was an update on the zimbra server last december I disabled and re-enabled the synchronization so that if the address books had "moved" or were being renamed,  tbSync would be informed the new location. However, after that tbSync claimed it could not find any resources. Trying to set up the account as a new account fails equally with either the message that the server is not a CalDAV/CardDAV server or if I specify the URL for the DAV interface it cannot find any resources. 

The built-in capability of TB to synchronize a calendar with a CalDAV-server as well as DAVx5 on my mobile work as expected. DAVx5 can also synchronize the address books. 

I suspect that really the resource discovery does not work anymore, while found resources might synchronize well. 

Will send a debug.log via mail.
## Expected behavior
Connecting to zimbra (Version 10.0.6_GA_4585 (build 20231201121250)) it should find the resources and synchronize calendars and address books 
## Actual behavior
No resources are found. 

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please note that CalDAV/CardDAV support in TbSync is going to be sunset. Thunderbird has native CalDAV/CardDAV support now. If Thunderbird is not able to find your resources (without TbSync), you need to file a bug with Thunderbird.
