### ISSUE TITLE
Received appoinments are sometimes showed as personal appoinments

### ISSUE THREAD

**Issue by mccaan** [jobisoft/TbSync#71]
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.7.0 under Mac OS 10.12.6

[X] Yes, I have installed the latest available version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Detect correctly that an appointment is not organized by me and show the right organizer.

## Actual behavior
When I open a appointment sent to me where I'm not the organizer, sometimes appear that I'm the organizer instead the real organizer.

## Steps to reproduce
Open couple of appointments received and confirm that you appear as organizer even if you aren't.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Could you restart Thunderbird, disable and re-enable your account, sync fresh and send me the debug.log? There is dedicated button inside the Help tab of the TbSync account manager.

What server are you using? 
If this bug "promoted" you from attendee to organizer, what happend to the original organizer?

Organizers and attendees usually have two identifiers, a name and an id/email. Is your id/email matching your EAS username?

Thanks!

**Comment by jobisoft** [comment]
I have not forgotten, but it will take a while...

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#9
