### ISSUE TITLE
Allow more than one OAUTH2 account

### ISSUE THREAD

**Issue by vanillbaum** [jobisoft/TbSync#713]
## Your environment
Win 11

TbSync version:  4.8
Thunderbird version: 115.8.0 

## Expected behavior
set up the account... or at least let me enter the password
...

## Actual behavior
I can not enter the password. i have 2 hotmail accounts. with account A mail is working and Kalender Sync with tb sync aswell. with account B mail is working, but not tb sync. I can not put in my password when i add the account to tb sync. It sets the account up, and when i check the safed passwords from Thunderbird, i see that it is the tb sync password from account A that tb sync somehow connects to account b. i deleted all the passwords for account b, so that i would be able to reenter de correct password. if i try to set up account b then - with active exchange sync and then Microsoft account  - i'll either get en Error 404 directly and i cant do anything else or i see that a window pops up, but closes again imidiatly without asking me anything, and then i will see in the password section, that it took the tb sync password from account A.

so my question is: how do i get thunderbird or tb sync to let me enter the password again?

## Debug Log (i just activated it now for one set up trial)
** Tue Mar 05 2024 17:00:40 GMT+0100 (Mitteleuropäische Normalzeit) **
[Querry EAS autodiscover V2 URL] : https://autodiscover-s.outlook.com/autodiscover/autodiscover.json?Email=piepsundpieks%40hotmail.com&Protocol=ActiveSync

** Tue Mar 05 2024 17:00:42 GMT+0100 (Mitteleuropäische Normalzeit) **
[Received non-standard EAS url via autodiscover:] : https://eas.outlook.com

** Tue Mar 05 2024 17:00:44 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: prepare.request.options, Account: pp

** Tue Mar 05 2024 17:00:44 GMT+0100 (Mitteleuropäische Normalzeit) **
[Sending] : OPTIONS https://eas.outlook.com/Microsoft-Server-ActiveSync

** Tue Mar 05 2024 17:00:44 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: send.request.options, Account: pp

** Tue Mar 05 2024 17:00:57 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: eval.request.options, Account: pp

** Tue Mar 05 2024 17:00:57 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : InvalidServerOptions

** Tue Mar 05 2024 17:00:57 GMT+0100 (Mitteleuropäische Normalzeit) **
[EventLog] : InvalidServerOptions

** Tue Mar 05 2024 17:00:57 GMT+0100 (Mitteleuropäische Normalzeit) **
[setSyncState] : State: accountdone, Account: pp

**Comment by jobisoft** [comment]
Currently not supported to have more than one OAUTH account, due to cookie clashes.

**Comment by jobisoft** [comment]
Can you check the beta for TB128?
https://github.com/jobisoft/EAS-4-TbSync/issues/267#issuecomment-2297181031

**Comment by Dave-Lowndes** [comment]
Tried it now John, it's synced OK for me with 2 outlook accounts 👍

**Comment by acseven** [comment]
I'm not able to use the beta, as it throws an error installing in Betterbird 115.14.0-bb31 (64 bits) - but version 4.8 is working though. 

> 1724269013039	addons.xpi-utils	WARN	Add-on eas4tbsync@jobisoft.de is not compatible with application version.
