### ISSUE TITLE
caldav.calendar.yahoo.com authentication error

### ISSUE THREAD

**Issue by PaulBliz** [jobisoft/TbSync#715]
## Your environment W10

TbSync version: 4.8
Thunderbird version: 115.9.0

## Expected behavior
Normally would sync my calendars with Yahoo

## Actual behavior
As of 3/18/24, I can no longer synch my AT&T (hosted by yahoo) calendars in TBSync.  I tried deactivating and now I can't reactive or add my account.  Keep receiving a "cannot authenticate USER ID or Password" error.  I have reset my secure key to no avail.  Still works on other devices (non-Thunderbird/TBSync). 

## Steps to reproduce
Adding new account, CalDAV & CardDav, then enter my credentials like normal.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Please note that CalDAV/CardDAV support will be sunset in TbSync. Thunderbird now has native support for CalDAV/CardDAV, and if it is not able to find your resources, you need to file a bug with Thunderbird.

**Comment by PaulBliz** [comment]
Thank you.  I was now able to get it set up directly in TB.  I appreciate the help and quick response.
