### ISSUE TITLE
Random error with outlook.com calendar: Invalid synchronization key (status 9)

### ISSUE THREAD

**Issue by misar1** [jobisoft/TbSync#716]
Windows 10 and 11 (two separate systems running TB)
TbSync version: 4.8
Provider for EAS: 4.8
Thunderbird version: 115.8.0 (64 bit)

Much of the time TbSync works correctly but there is an apparently random error as stated. This is annoying because instead of just reporting a non-fatal error TbSync deselects the outlook calendar and deletes all entries in the local TB calendar. If the calendar is immediately reselected and synchronized TbSync works correctly and restores all entries.

Invalid synchronization key (status 9) 
Account Outlook (EAS)

Request:
?xml version="1.0"?
FolderSync xmlns='FolderHierarchy'
SyncKey2/SyncKey
/FolderSync

Response:
?xml version="1.0"?
FolderSync xmlns='FolderHierarchy'
Status9/Status
/FolderSync

**Comment by jobisoft** [comment]
Did you clone the Thunderbord profile from one machine to the other, so both are using the same DeviceID? EAS is a state-based sync and if two systems use the same DeviceID, it will cause sync errors.

**Comment by misar1** [comment]
Yes, with two different profiles (work and personal) on each PC. I checked the ID for each profile and as you say in each case it is the same on both PCs. Is it possible to change the ID of one installation, e.g. by reinstalling Provider for EAS?
Thanks.
