### ISSUE TITLE
Cannot connect to Exchanage Account

### ISSUE THREAD

**Issue by MKostura** [jobisoft/TbSync#717]
Windows 10

TbSync version: Last Updated Dec 3 2023
Thunderbird version: 115.9.0

## Expected behavior  TBSync  reliably connected to my personal MS Outlook account
...

## Actual behavior  TBSync has stopped connecting to my personal Outlook account.  There is a permission failure (will not recognize the password).  
...

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
OAUTH2
