### ISSUE TITLE
Sync shared calendar and address book

### ISSUE THREAD

**Issue by croulibri** [jobisoft/TbSync#72]
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.7.0
Windows 7 and Debian 8

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When I discover calendar and address book of my Zimbra activesync account, I expect to see all calendar and address book available on that account.

## Actual behavior
I only see address book and one calendar and task _that I own_, and not the ones shared with me

## Steps to reproduce
Just set up an account on Zimbra server with Active Sync (may be same issue on other Email providers) and you can see only address book and calendar that you own, not the shared ones

I have several address book and several calendar shared by co-workers and so I would be happy to be able to select them for sync on Thunderbird.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F

Best regards
John

**Comment by croulibri** [comment]
Sorry for not being able to find this information in the wiki!

Thanks for your great add-on that works very well, except this issue that is out of your range.
