### ISSUE TITLE
support Thunderbird 125

### ISSUE THREAD

**Issue by mael2** [jobisoft/TbSync#722]
## Your environment
TbSync version: 4.8
Thunderbird version: 125.0

## Expected behavior
TbSync works

## Actual behavior
TbSync cannot be used

## Steps to reproduce
Update to TB 125

Thank you very much!

**Comment by JJHF7** [comment]
> ## Your environment
> TbSync version: 4.8 Thunderbird version: 125.0
> 
> ## Expected behavior
> TbSync works
> 
> ## Actual behavior
> TbSync cannot be used
> 
> ## Steps to reproduce
> Update to TB 125
> 
> Thank you very much!

Hi, everyone

Same issue here; same versions, and after upgrading Thunderbird, TbSync goes disabled (with no option to re-enable it).

Kind regards!

**Comment by jobisoft** [comment]
Thunderbird 125 is not an official ESR release. The next update of TbSync will be for Thunderbird ESR 128.

**Comment by gyozo-gidofalvi** [comment]
I have Thunderbird 128.0esr (64-bit) but TbSync is not found / available and an add-on.

**Comment by gyozo-gidofalvi** [comment]
@jobisoft I have Thunderbird 128.0esr (64-bit) but TbSync is not found / available in the add-on page. How can I use TbSync?
