### ISSUE TITLE
no sync of contacts with Synology NAs in home net

### ISSUE THREAD

**Issue by GoeWink** [jobisoft/TbSync#723]
## Your environment:
OS Windows10, using 

TbSync version: TBSync version 4.8, Provider für CardDav + Categoryy Manager integrated
Thunderbird version: Betterbird V115.11.0-bb28 (64-Bit)

## Expected behavior
Sync for contacts with Synology NAS DS 416
...

## Actual behavior
no sync of contacts but shown as "OK" as status
...

## Steps to reproduce
To ensure to be connected to the right addressbook I moved all contacts from the connected addressbook in Betterbird All contacts but one was deleted on server. In TBSync Manager the addressbook was deleted and enterd again. Then the newly shown Addressbook in Bettterbird was refille by moving into this addressbook there. On server 38/54 contacts were imported finally on server.
It seems that the not imported contacts are newr contacts. Maybe added after the new structure o f addressbooks in Thunderbird/ Betterbird?
I tested to add this addressbook in Betterbird directly and copied contacts there in Betterbird. No contacts reached the server. So there seem to be a knd of incompatibility  - maybe different fields?
...

I do non send a log file because there are shown no errors...

**Comment by jobisoft** [comment]
Support for CalDAV/CardDAV has been removed.
