### ISSUE TITLE
TbSync is not symcing Posteo contacts (Shaun Gage)

### ISSUE THREAD

**Issue by ShaunGage** [jobisoft/TbSync#724]
## Your environment

TbSync version: 4.8
Thunderbird version: 115.11.1

## Expected behavior
...Sync contacts from Posteo account

## Actual behavior
...Posteo contacts are not syncing with TbSync into Thunderbird contacts
<img width="572" alt="ShaunGageScreenshot 2024-06-17 110258" src="https://github.com/jobisoft/TbSync/assets/165221655/c186e013-9137-4c9f-9962-09c5c2470034">
<img width="434" alt="ShaunGageScreenshot 2024-06-17 110358" src="https://github.com/jobisoft/TbSync/assets/165221655/41126f20-7fdc-4090-bac9-41835227d516">
<img width="574" alt="ShaunGageScreenshot 2024-06-17 110430" src="https://github.com/jobisoft/TbSync/assets/165221655/98f395b7-97f1-489a-9f20-f6c8de753316">

## Steps to reproduce
...Deleted Posteo address from Thunderbird and synced Posteo address book within TbSync

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Support for CardDAV has been removed.
