### ISSUE TITLE
Supports TB 128

### ISSUE THREAD

**Issue by panther7** [jobisoft/TbSync#726]
Add compatibility forThunderbird 128.

Release date: 11 July 2024

**Comment by bjo81** [comment]
Is this still needed due to TB128's experimental EWS support?

**Comment by jobisoft** [comment]
I think next year MZLA will add calendar and address book support, but for now it is only email. But yes  as soon as they have added support for these, TbSync is no longer needed.

**Comment by jim-davenport** [comment]
For planning purposes, approximately when do you think TBSync will be updated to support 128?

**Comment by jim-davenport** [comment]
Thank you.

**Comment by john-g-davies** [comment]
AFIK Thunderbird Exchange support uses the Exchange Web Services protocol.
If your server uses Exchange ActiveSync then the native support will not work and you will still need TBSync.

**Comment by peci1** [comment]
It seems the version on master branch has problems with registration of providers on TB 128.

I see this exception when I try to load Google-4-TbSync with https://github.com/zanonmark/Google-4-TbSync/pull/54:

```
[Exception... "AddonManager is not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource:///modules/AddonManager.sys.mjs :: getAddonByID :: line 2850"  data: no] AddonManager.sys.mjs:2850:24
    getAddonByID resource:///modules/AddonManager.sys.mjs:2850
    getAddonByID resource:///modules/AddonManager.sys.mjs:4265
    loadProvider chrome://tbsync/content/modules/providers.js:51
    observe chrome://google-4-tbsync/content/bootstrap.js:30
    startup chrome://google-4-tbsync/content/bootstrap.js:44
    registerBootstrapScript file:///D:/programovani/TB addons/Google-4-TbSync/content/api/BootstrapLoader/implementation.js:783
    AsyncFunctionNext self-hosted:807
```

Just trying to debug this, I see `AddonManager.isReady` always returns false. Calling `AddonManager.init()` ends up with an error.

**Comment by jobisoft** [comment]
It is: https://addons.thunderbird.net/addon/quicktext/versions/

**Comment by gcat60** [comment]
I thought this was for TbSync but the link is for quicktext? Is there a download for TbSync that works with 128?

**Comment by ThatWasLeftHanded** [comment]
> I thought this was for TbSync but the link is for quicktext? Is there a download for TbSync that works with 128?

I agree, the add-on isn't listed as compatible yet...

**Comment by jobisoft** [comment]
Oh, sorry, got mixed up in the projects. You are correct, TbSync is not done yet.

**Comment by A-Tarraf** [comment]
By the way, it also seems that the new beta version of Thunderbird only supports [email ](https://wiki.mozilla.org/Thunderbird:Exchange?_gl=1*tz6lt9*_ga*MTg2NzU1MjUzMy4xNzIxODk1NTUy*_ga_X4N05QV93S*MTcyMjkyNzQ3Mi4zLjEuMTcyMjkyNzQ4Ny4wLjAuMA..). Honestly, I don't mind as  I have been using TBsync for years now without any complains. Many thanks for the continuous development!

**Comment by john-g-davies** [comment]
Hello jobisoft, is there anything we can do to help you get this working with TB 128?

**Comment by ravensorrow** [comment]
Dropping in so I can catch an update on this when it's released for 128.x. Kinda lost w/o it right now. I rely heavily on my calendars and with them not syncing is harming my ability to stay focused and organized.

**Comment by ThatWasLeftHanded** [comment]
... I seriously don't want to subscribe to Owl for Exchange, so just tell is when you'll never release the update...

**Comment by spiregarden** [comment]
For the time being, I decided to downgrade and migrate from v128(snap version) to v115(APT version). Please note that this procedure is NOT OFFICIAL NOR SAFE. In fact this is hacky and may lead to loss of your mail and calendar events. If you decide to apply any part of my memo, please be sure to take backups! My OS is Ubuntu, but parts of this can be applicable in other environments. I hope this saves time from someone else.

My migration progressed like this:
- I took backups:
  rsync -avh ~/snap/thunderbird/ ~/backup/2024-08-08_backup_thunderbird/
- I deleted the Snap version (at the same time, Snap took a gzipped snapshot, but I don't know where it put it, if anywhere)
- I pinned Thunderbird to major version 115:
  sudo nano /etc/apt/preferences.d/thunderbird-115
  Package: Thunderbird
  Pin: version 1:115.*
  Pin Priority: 1001
- I added the Mozilla ppa
		sudo add-apt-repository ppa:mozillateam/ppa
- I double-checked that apt won't push newer major version than the pinned one:
		apt-cache madison Thunderbird
- I installed Thunderbird
		sudo apt install Thunderbird
- I had to edit the profiles.ini file
- I deleted the ~/.thunderbird/8sfj38s9.default/compatibility.ini file to bypass version check
- I deleted the local IMAP mails
  /2024-08-08_thunderbird_pre_rollback_2/common/.thunderbird/8sfj38s9.default/ImapMail/outlook.office365.com/*
- I started Thunderbird first as a test with the PC NETWORK CONNECTION DETACHED (this was to test Thunderbird first without fetching mail from POP3 accounts into a potentially broken Thunderbird) and finally with a network connection. 
- It would seem that the rollback was successful -accounts, settings and everything was there. Nothing needed to be reconfigured in thunderbird itself.
- now I just need to remember to update the apt preferences.d/thunderbird-115 restriction file to allow major update when the plugins start supporting the newer thunderbird

**Comment by achmafooma** [comment]
I'm also anxiously awaiting the update. I rely on tbsync! I am a web developer, and while I've never worked on a Thunderbird plugin before I'm happy to help write some JS if it'll be helpful...or just help with testing if you want to have some extra validation before you go live with an update. @jobisoft, Please reach out if there's anything I can do.

I also just sent you a PayPal donation. It's not a bribe for tbird128 support ;-) just a small 'thank you' for your hard, thankless work on this plugin and the EAS connector. Living without it this last week or two has reminded me how important it is for my day-to-day work. I was taking it for granted :-)

**Comment by ThatWasLeftHanded** [comment]
Okay, so Thunderbird on the Microsoft Store is still on version 115, which can use TbSync.

I recommend going there for now - https://apps.microsoft.com/detail/9pm5vm1s3vmq?lc=1049&hl=en-us&gl=us

**Comment by ravensorrow** [comment]
> For the time being, I decided to downgrade and migrate from v128(snap version) to v115(APT version). Please note that this procedure is NOT OFFICIAL, NOR SAFE. In fact, it is hacky and may lead to the loss of your mail and calendar events. If you decide to apply any part of my memo, please be sure to take backups! My OS is Ubuntu, but parts of this can be applicable in other environments. I hope this saves someone else's time.
> 
> My migration progressed like this:
> 
>     * I took backups:
>       rsync -avh ~/snap/thunderbird/ ~/backup/2024-08-08_backup_thunderbird/
> 
>     * I deleted the Snap version (at the same time, Snap took a gzipped snapshot, but I don't know where it put it, if anywhere)
> 
>     * I pinned Thunderbird to major version 115:
>       sudo nano /etc/apt/preferences.d/thunderbird-115
>       Package: Thunderbird
>       Pin: version 1:115.*
>       Pin-Priority: 1001
> 
>     * I added the Mozilla ppa
>       sudo add-apt-repository ppa:mozillateam/ppa
> 
>     * I double-checked that apt won't push a newer major version than the pinned one:
>       apt-cache madison Thunderbird
> 
>     * I installed Thunderbird
>       sudo apt install Thunderbird
> 
>     * I had to edit the profiles.ini file
> 
>     * I deleted the ~/.thunderbird/8sfj38s9.default/compatibility.ini file to bypass version check
> 
>     * I deleted the local IMAP mails
>       /2024-08-08_thunderbird_pre_rollback_2/common/.thunderbird/8sfj38s9.default/ImapMail/outlook.office365.com/*
> 
>     * I started Thunderbird first as a test with the PC NETWORK CONNECTION DETACHED (this was to test Thunderbird first without fetching mail from POP3 accounts into a potentially broken Thunderbird) and finally with a network connection.
> 
>     * It would seem that the rollback was successful—accounts, settings, and everything else were there. Nothing needed to be reconfigured in Thunderbird itself.
> 
>     * now I just need to remember to update the apt preferences.d/thunderbird-115 restriction file to allow major updates when the plugins start supporting the newer Thunderbird

While useful for someone with a specific use case for Ubuntu or someone running a Debian SNAP system, it is definitely not recommended for the faint of heart.

**Comment by jobisoft** [comment]
I would like to reaffirm you that I am working on the updates, but I am stuck at a network connection error: All connections come back as 401 currently. I keep you posted.

I am sorry for the delay.

**Comment by dabockster** [comment]
Hey @jobisoft take your time! Thunderbird just changed their whole update model, so it's only natural to see a 3rd party aftermarket addon break. The message regarding the CalDav addon was a bit jarring at first when displayed next to every TbSync related addon being disabled, but this isn't your day job so I really have no right to be upset.

For everyone who's mad at a developer basically donating their time ✨for free✨, they can go buy Owl or just migrate completely back to Microsoft Outlook. Or y'all should probably migrate to the new ESR Thunderbird branch ASAP if you're _that_ worried about a Thunderbird update ruining your business workflow. Do some actual risk analysis before trusting your mission critical business IT infrastructure to a bunch of random unpaid open source volunteers online.

(And John should charge actual money for an ESR edition of TbSync. Just my two cents considering the absolute drama going on here.)

**Comment by theofficialgman** [comment]
> For everyone who's mad at a developer basically donating their time ✨for free✨, they can go buy Owl or just migrate completely back to Microsoft Outlook. Or y'all should probably migrate to the new ESR Thunderbird branch ASAP if you're _that_ worried about a Thunderbird update ruining your business workflow. Do some actual risk analysis before trusting your mission critical business IT infrastructure to a bunch of random unpaid open source volunteers online.

Yes. A quick reminder that FOSS software and the "Software Supply Chain" are incompatible
https://www.softwaremaxims.com/blog/not-a-supplier
https://www.softwaremaxims.com/blog/open-source-hobbyists-turf

If your business relies open source software reach out to those software maintainers and reach a mutually beneficial agreement (eg: exchange of money, developers, and/or time for your support)

**Comment by dabockster** [comment]
@theofficialgman Or just buy closed source in the first place. Open source is basically the multiverse in supply chain form.

![Doctor Strange falling through the multiverse - I mean the Software Supply Chain](https://tenor.com/view/doctor-strange-doctor-strange-in-the-multiverse-of-madness-multiverse-sam-raimi-benedict-cumberbatch-gif-24893998)

**Comment by jobisoft** [comment]
The bug regarding all network connections coming back as 401 has been fixed. I have the combo TbSync+EAS running again for an 3rd party EAS Server (Kopano). Now looking into OAUTH issues.

**Comment by jobisoft** [comment]
See https://github.com/jobisoft/EAS-4-TbSync/issues/267#issuecomment-2295470811

**Comment by gcat60** [comment]
Beta working with no issues 128.1.0esr (64-bit) on Windows 11 Pro. Thanks! I'll throw some bones your way for the work :)

**Comment by jobisoft** [comment]
TbSync 4.11 for TB128 itself is now listed on ATN:
https://addons.thunderbird.net/addon/tbsync/versions/

The google provider as well:
https://addons.thunderbird.net/addon/google-4-tbsync/versions/

My EAS provider still needs a bit and its progress is tracked in the issue linked in https://github.com/jobisoft/TbSync/issues/726#issuecomment-2295471419
