### ISSUE TITLE
Is the provider für CalDAV & CardDAV needed or not?

### ISSUE THREAD

**Issue by mbiebl** [jobisoft/TbSync#729]
Hi,

this might be more of a question rather than a bug report:
With TB 128, the "Provider für CalDAV & CardDAV" addon prompted me to uninstall it, as TB apparently now supports this natively.

That said, if I open TbSync, I see the following (mynebula is a Nextcloud server, providing both calendar and contacts data via caldav/carddav)

![grafik](https://github.com/user-attachments/assets/3f7df08c-505c-4707-be48-5bd77dd3ee8c)

I'm using TbSync, as I have several calendards and addressbooks and don't want to set them up individually.

Is this only  temporary issue due to the TB 128 port or is the CardDAV/CalDAV support in TbSync gone for good?

**Comment by jobisoft** [comment]
For good. The UI of Thunderbird is not perfect, but good enough that my own work is no longer worth the effort. When I initially created my DAV provider, there was no CardDAV support in Thunderbird at all, so the main objective was to add CardDAV, which is no longer needed.

**Comment by mbiebl** [comment]
Say I add a new addressbook or calendar, how is this handled in TB now?
So far I only needed to click refresh in TbSync and click a checkbox.

**Comment by mbiebl** [comment]
Related to that, does that mean I can shut down the NC test instance at https://nextcloud.michael....de or do you still have use for i?

**Comment by jobisoft** [comment]
It might be useful if you run into issues related to Thunderbird's own CalDAV/CardDAV implementation and need a reproducer example. But for TbSync itself, it will not be needed any more. Thanks for your support!

**Comment by Ferdi265** [comment]
@jobisoft: your selection window for setting up CalDAV/CardDAV links was really nice, and allowed easy adding and removing of multiple calendars from the same NextCloud instance. The new Thunderbird UI only allows linking individual calendars and requires entering credentials for all of them.

**Comment by hockeymikey** [comment]
@jobisoft Last I checked Thunderbird is still garbage with adding calendars. Still doesn't covered read only calendars, I have to add those individuals. Your addon was solid, it's a disappointment with the abandonment of it.
