### ISSUE TITLE
TbSync keeps asking for the password

### ISSUE THREAD

**Issue by vlcekvv** [jobisoft/TbSync#730]
## Your environment

TbSync version: 4.11 | Released August 23, 2024

Thunderbird version: 128.1.1esr | Released August 21, 2024

## Expected behavior
TbSync should remember my credentials once I am authenticated with my Office365 credentials.

## Actual behavior
I am asked for the credentials of the Office365 approximately every 30 minutes.

<img width="821" alt="TbSync" src="https://github.com/user-attachments/assets/95dcbddf-6e0f-455f-ac52-9a48686fb98e">

I am using OAuth 2.0

Thank you,
Vaclav

**Comment by Betterbird** [comment]
I can confirm the issue, in fact, I came here to file a ticket and found it had already been filed. May I suggest to change the title to:
"TbSybc/EAS requests re-authentication frequently for O365 calendars".

I have my synchronisation set to 120 minutes, and it appears to request authentication each time. This wasn't the case in TB 115.

**Comment by vlcekvv** [comment]
A small update. When I keep Thunderbird opened and do not close it, I do not get these prompts. When I close Thunderbird, I would need to put credentials again; I am not sure if this is an intended behaviour.

**Comment by jobisoft** [comment]
I am looking into this.

**Comment by vlcekvv** [comment]
> > When I keep Thunderbird opened and do not close it, I do not get these prompts.
> 
> I cannot confirm. I get the authentication prompts periodically even when i Thunderbird running.

Yes, you are right @sni; now I was asked again to insert the password even when the Thunderbird was opened all the time.

**Comment by jobisoft** [comment]
Closing in favour of https://github.com/jobisoft/EAS-4-TbSync/issues/271#issuecomment-2313044455
