### ISSUE TITLE
Synchronizing to Outlook365 calendar does not show previously existing calendar events

### ISSUE THREAD

**Issue by seyfeb** [jobisoft/TbSync#733]
## Your environment

TbSync version: 4.11
Thunderbird version: 128.2.0esr (64-bit)

## Expected behavior

Using Exchange ActiveSync, I add an account and synchronize it. All existing calendar events should be synchronized (at least for the past sync period as defined in the settings).

## Actual behavior
No existing events are synced. Newly created and deleted events are synced as expected.

## Steps to reproduce
1. Add Exchange ActiveSync account.
2. Select calendar to sync.
3. Click Synchronize now.
4. See Status "Ok" but no synced event show up in the calendar.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/274
