### ISSUE TITLE
EAS and MSOffice365 calendars no longer syncing

### ISSUE THREAD

**Issue by RRNYC** [jobisoft/TbSync#734]
## Your environment

TbSync version: both tbsync-4.3-tb and 4.11
Thunderbird version:  both 102 and 128.2.0esr

## Expected behavior:  synced calendars
...

## Actual behavior:  no data at all, despite displaying as connected in the Available Resources section of the Synchronization Status tab
...

## Steps to reproduce:  tried removing and reconnecting on all versions. nothing restores the data 
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/274
