### ISSUE TITLE
Sync failed. Server responsed with status <4>

### ISSUE THREAD

**Issue by MrcLpz** [jobisoft/TbSync#75]
## Your environment

TbSync version:
Thunderbird version:

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I want to sync many changes after debugging my book address with "Duplicate Contact Manager".

## Actual behavior
Sync failed and the Sync status says "Sync failed. Server responsed with status <4>". I red the log and found something like this:

** Fri May 11 2018 13:06:26 GMT+0200 **
[JavaScript Error: "TypeError: aDocumentNode is undefined" {file: "chrome://messenger/content/msgHdrViewOverlay.js" line: 1391}]
UpdateExtraAddressProcessing@chrome://messenger/content/msgHdrViewOverlay.js:1391:1
updateExtraAddressProcessing@chrome://messenger/content/mailWidgets.xml:907:17
OnAddressBookDataChanged/<@chrome://messenger/content/msgHdrViewOverlay.js:395:9
OnAddressBookDataChanged@chrome://messenger/content/msgHdrViewOverlay.js:389:3
AddressBookListener.onItemPropertyChanged@chrome://messenger/content/msgHdrViewOverlay.js:384:7
eas.tzpush.tozpush<@chrome://tbsync/content/provider/eas/tzpush.js:630:29
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
TaskImpl@resource://gre/modules/Task.jsm:277:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14
eas.tzpush.start<@chrome://tbsync/content/provider/eas/tzpush.js:134:19
TaskImpl_run@resource://gre/modules/Task.jsm:319:42
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:932:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11

## Steps to reproduce

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I am sorry, but I cannot fix that error right now. It is inside the old "TzPush" contact sync code, which I am not able to maintain. 

TbSync started as a fork of TzPush and I added all the other stuff (manager UI, calendar & task sync, autodiscover) but created my own method to communicate with the server. The contact sync is still using the original method also used by TzPush, which I cannot fix.

The next step is a total rewrite of the contact sync using my method. But I cannot give you any due date.

**Comment by jobisoft** [comment]
A detailed roadmap can be found here:
https://github.com/jobisoft/TbSync/wiki/Roadmap

**Comment by MrcLpz** [comment]
Thank you very much for your answer!
I could workaround the problem because I always try to maintain all the important information in outlook.com and I unsubscribe and subscribe again the contact folder. Now I´m working fine and data is syncing in both ways.

**Comment by MrcLpz** [comment]
And thank you for your add-on. I have been looking for something like this for years.
I will make a donation soon.

**Comment by jobisoft** [comment]
Are you willing to spend time on beta testing? You can activate the current state of the new sync code and test it:

https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#extensionstbsynceasuse_tzpush_contactsync_code

If something is unclear, just ask. You must install the latest beta to use this.

**Comment by jobisoft** [comment]
I am closing this issue, because it is very similar to issue https://github.com/jobisoft/TbSync/issues/76

If you post something there, you will be notified about updates as well.

**Comment by jobisoft** [comment]
I just released a final beta, containing the new sync method. Its stable now. Also I created a dedicated wiki page for this:

https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code

I consider this done. The new sync method will be promoted to default with the release of v0.8. Until than, it needs to be activated manually.
