### ISSUE TITLE
Contacts not syncing

### ISSUE THREAD

**Issue by PotatoCarl** [jobisoft/TbSync#76]
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.7

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
Syncing Contacts

## Actual behavior
Hi,
I have the same issue here. I am using Z-Push for syncing with my Groupware (Group-E) on the server side. Calendar and Tasks sync fine, but not Contacts.
In the "Sync Status" the following message is displayed: "Sync failed. Server responded with status <Xj>"
(X = scrambled characeter).
I have >4000 contacts, this works on my mobile fine.
I tried to get the beta from the link above, but the link is a 404 dead end.
Thank you.

## Steps to reproduce
Sync contacts

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by PotatoCarl** [comment]
Thank you for your quick response. I rather wait a bit, it is not a urgent matter for me at this time.

**Comment by jobisoft** [comment]
Are you willing to spend time on beta testing? You can activate the current state of the new sync code and test it:

https://github.com/jobisoft/TbSync/wiki/Advanced-configurations#extensionstbsynceasuse_tzpush_contactsync_code

If something is unclear, just ask.

**Comment by BillBrowne** [comment]
Hi,
I have set this to false, the contacts sync OK but I cannot see where I can use the address book.  It does not show up as a Thunderbird address book and contacts which are in it are not searchable.

**Comment by jobisoft** [comment]
Also: You must install the latest beta

https://github.com/jobisoft/TbSync/releases

**Comment by jobisoft** [comment]
Let me also point this out one more time: 
**DO NOT USE THIS FEATURE ON PRODUCTION DATA!**

If you activate this method, you are using very new code, it has pre beta status. 
**YOU WILL PROBABLY LOOSE CONTACT INFORMATION.**

That being said, feedback on this is very appreciated.

**Comment by PotatoCarl** [comment]
Okay, okay, I see.

Being fearful, I turned it off again, however, with the latest Beta is
synced the infos into Thunderbird fine...



-------- Original Message  --------
Subject: Re: [jobisoft/TbSync] Contacts not syncing (#76)

**Comment by jobisoft** [comment]
In the latest beta, I changed how **extensions.tbsync.eas.use_tzpush_contactsync_code** works. It does not directly activate/deactivate the new sync code, but sets the default value for newly enabled accounts.

So if you want to activate/deactivate the new sync code, you have to change the value AND also have to disable and re-enable your account. This is to prevent users from switching the sync method while syncing.

**Comment by jobisoft** [comment]
Also, the status of the new sync code in the latest beta is no longer pre beta. But still, do not use it without having a backup of your data!

**Comment by jobisoft** [comment]
I just released a final beta, containing the new sync method. Its stable now. Also I created a dedicated wiki page for this:

https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code

I consider this done. The new sync method will be promoted to default with the release of v0.8. Until than, it needs to be activated manually.

**Comment by ChameleonScales** [comment]
sorry I'm not so clear about this. Do we need to install z-push or not?

**Comment by jobisoft** [comment]
z-push is an open source ActiveSync (EAS) server. You need a server to be able to sync with Thunderbird of course, either something from microsoft or something else with an EAS interface. Maybe create a new issue with a specific question.

**Comment by ChameleonScales** [comment]
ok [here it is](https://github.com/jobisoft/TbSync/issues/353)
