### ISSUE TITLE
Outlook Categories into Thunderbird Tags.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [jobisoft/TbSync#77]
Is there a way Outlook Categories could be translated into Thunderbird Tags by tbSync?

**Comment by jobisoft** [comment]
What are thunderbird tags? Do you mean a list? Maybe this helps:

First update to the latest beta:
https://github.com/jobisoft/TbSync/issues/77

Than activate the new sync code:
https://github.com/jobisoft/TbSync/wiki/Rewrite-of-tzpush-contact-sync-code

Than install my CategoryManager:
https://addons.mozilla.org/de/thunderbird/addon/categorymanager/

That should make the categories usable in Thunderbird...

**Comment by jobisoft** [comment]
Wrong link for beta:
https://github.com/jobisoft/TbSync/releases/download/v0.7.7/TbSync-beta.xpi

**Comment by Zombie-Ryushu** [comment]
No, what I mean is, my work place uses Color coded Tags to assign E-mails from a Group shared Inbox on Office 365, we are supposed to respond to each E-mail that matches our Color by tag. aI can access the group inbox, but not see the tags in Thunderbird.

**Comment by jobisoft** [comment]
I think not. TbSync does not access your emails at all. Only contacts, events and tasks. I do not think I will ever implement email access:
https://github.com/jobisoft/TbSync/wiki/What-about-email-support-via-EAS%3F

TbSync (and Exchange ActiveSync) has the home user as target. Group shared stuff is mostly not supported by the protocol. You need to go for Exchange WebServices (EWS):
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F
