### ISSUE TITLE
TbSync configured, but nothing show up in the new lighning calendars.

### ISSUE THREAD

**Issue by Lurch440** [jobisoft/TbSync#78]
## Your environment

TbSync version: 0.7.7.17
Thunderbird version: 52.7

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I configure the client and my calendar is visbible in Lightning

## Actual behavior
Calendars are created but are empty

## Steps to reproduce
Followed the instructions several times.  Repeats everytime.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Your server indeed tells TbSync, that the calendars are empty. (estimate = 0). What type of server are you using?

**Comment by jobisoft** [comment]
User reported: After adding a test event, it synced properly and pulled down calendar, tasks, and contacts.
