### ISSUE TITLE
Beta 0.7.7.17 not syncing to server after enablig new sync method

### ISSUE THREAD

**Issue by MrcLpz** [jobisoft/TbSync#80]
## Your environment

TbSync version:
Thunderbird version:
52.8.0 (32 bits)
[ x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Actual behavior
In Beta 0.7.7.17, after activation of new sync metod enabling to false the value of the advanced setting and disbling and enabling muy account, I obtain an error "Sync status: Not yet supported, skiped."
I send you a capture of the window and the log file after rebooting Thunderbird.
The changes made in local now are not syncing to the server
![errortbsync_beta0 0 0 17](https://user-images.githubusercontent.com/39190139/40585259-d3728a8e-61af-11e8-82ed-1be5e6346918.JPG)
.

## Steps to reproduce
...

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
I have an idea, where this is coming from. Could you test something, to verify?

- Disable and Delete(!) your Account in TbSync Account Manager.
- Recreate your account from scratch in TbSync Account Manager.
- It should work.
- Disable your account.
- Re-Enable your account.
- It should no longer work.

Thanks!

**Comment by MrcLpz** [comment]
Sure, but now I´m at office. I'll tell you the results of this test later.

**Comment by jobisoft** [comment]
Can I close this? Is it solved?

**Comment by MrcLpz** [comment]
I'm sorry, but the Internet access of my house is down since 29/05/2018 and I can't test this installation.
I hope I can test it this afternoon.


En 31 de mayo de 2018 13:36:20 John Bieling <notifications@github.com> escribió:

Can I close this? Is it solved?

**Comment by MrcLpz** [comment]
I could´t do the test. I will try to do this afternoon.

**Comment by MrcLpz** [comment]
Finally I can say that the problem is solved. I tested it again at home.
Although I have to say that I had to delete my account and create it again. The standard method consisting of disabling and enabling account didn´t work. So, in some cases, I think you must suggest to do that, delete and re-create account.
Thank you very much for your patient, definitely I'm not a good beta tester.

**Comment by jobisoft** [comment]
Thanks, that was the last step before I can release 0.7.8!
