### ISSUE TITLE
TbSync not working on Mac OS X

### ISSUE THREAD

**Issue by digodigo** [jobisoft/TbSync#82]
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.8.0

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
After installing TbSync choosing "Synchronization Settings (TbSync)" from the Tools menu should start the preferences dialog as it does on Windows installations of Thunderbird with TbSync.

## Actual behavior
On two different OS X-based setups of Thunderbird, there is just nothing happening when trying to open the TbSync settings.

## Steps to reproduce
Choosing "Synchronization Settings (TbSync)" from the Tools menu doesn't give any reaction whatsoever.

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

TbSync settings won't open, so activating the debug.log can't be chosen.

**Comment by jobisoft** [comment]
Can you retry with the latest beta?
https://github.com/jobisoft/TbSync/releases/download/v0.7.7/TbSync-beta.xpi

**Comment by digodigo** [comment]
Hi, thanks for the beta. Unfortunately, the behaviour stays the same. The options dialog just doesn't open. Do you have any further ideas?

**Comment by jobisoft** [comment]
What is shown in the status panel in lower right corner of Thunderbird?

![-](https://github.com/jobisoft/TbSync/raw/master/screenshots/TbSync_000.png)

What happens if you left-click on that status panel?
What happens if your right-click on that status panel?

**Comment by Letterus** [comment]
I can approve this issue. Using a Mac the settings window of TbSync does not open when you use the "Extras" menu. But it works when you left click the status panel you marked, @jobisoft.

**Comment by digodigo** [comment]
Thank you very much for the hint, @jobisoft. As well as @Letterus I can confirm that the options dialogue opens when accessing via the status panel. The plugin works fine now. Thanks a lot!

**Comment by jobisoft** [comment]
Can you retry with the latest beta (.20)?
https://github.com/jobisoft/TbSync/releases/download/v0.7.7/TbSync-beta.xpi

Unrelated but maybe interesting: That beta is also able to search the global contacts directory, also called global address list (GAL), if the user searches an address inside an EAS address book. Does that work for you?

**Comment by Letterus** [comment]
Yep, that version works for me. I can open the settings using the "Extras" menu.

The second feature works as well: It's very impressing and very useful!

**Comment by jobisoft** [comment]
Thanks!

**Comment by digodigo** [comment]
Hej,
please excuse my delayed response - been on vacation. Thanks a bunch! The beta works flawlessly.
Kind regards.
