### ISSUE TITLE
lightning is not detected

### ISSUE THREAD

**Issue by Ri0n** [jobisoft/TbSync#86]
## Your environment

TbSync version: 0.7.7
Thunderbird version: 52.8.0
Lightning: 5.4

I didn't try to reproduce it. If it's just for me, then just close this bug.

## Expected behavior
lightning is detected

## Actual behavior
TbSync can't see working Lightning

## Steps to reproduce
Installed thunderbird, Lightning, TbSync (exactly in this order on a new profile). After restart TbSync reports it can't find Lightning even so it definitely works.

If I uninstall Lightning and install it again then it's detected.

**Comment by jobisoft** [comment]
Any feedback?

**Comment by Ri0n** [comment]
sorry. was to busy with other stuff. if you said it's fixed then let's just close the bug.

**Comment by jobisoft** [comment]
ok, if you ever encounter this problem again (with beta) and it indeed skips calendars during sync even lightning is installed, just reopen.

**Comment by samenkov** [comment]
I'm having that issue right now. Just wanted to save my calendar from my previous college before they close my account and installed TbSync, Provider for Exchange ActiveSync, as well as Lightning Calendar Tabs and when I try to sync all my resources (Contacts, Calendar, ..) it says "Lightning add-on not installed, calendars are not supported". I tried removing it and installing it again, even restart the computer (in case restarting Thunderbird wasn't enough) but nothing helped. I'm on Ubuntu  18.04.5 LTS.
Thanks for any advice!
