### ISSUE TITLE
TBSync autodiscover does not support SRV method?

### ISSUE THREAD

**Issue by webtrader** [jobisoft/TbSync#88]
## Your environment

OS X High Sierra 10.13.3
TbSync version: v0.7.7/TbSync-beta.xpi
Thunderbird version:

[X ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

Using beta (.20)

## Expected behavior
Autodiscover would complete successfully.

## Actual behavior
Error popup "Autodiscover for user <user@redacted.com> failed. Either the provided credentials were wrong or your ActiveSync provider has a temporary issue, or does not support Autodiscover"

## Steps to reproduce
Add a new calendar account. Enter user name in email address form and password, choosing the "automatic configuration via activesync autodiscover". Sorry I prefer to not provide the actual email address here, but can email or message privately if it matters.

Our exchange setup uses the SRV record method for autodiscover. However from the debug log, TBSync appears to only do a lookup for autodiscover.DOMAIN.COM and does not do a SRV lookup if that method is unsuccessful.

From the autodiscover process guide at https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/autodiscover-for-exchange (phase 3):

"If the unauthenticated GET request doesn't work out, the last thing to try is a DNS query for SRV records for the Autodiscover service. The record will take the form "_autodiscover._tcp." + domain. This query might return multiple records, but you should only use records that point to an SSL endpoint and that have the highest priority and weight."

It seems that TBSync does not do this DNS query.

**Comment by jobisoft** [comment]
I have not implemented that yet, because I never had a server to test against. Are you or your company able to implement that and send me a PR?

**Comment by webtrader** [comment]
Unfortunately I am not a coder, so I am unable to implement it myself. However anyone who can code should be able to do it easily. 

Pseudocode:
If lookup of autodiscover.DOMAIN.COM fails, then 
do DNS lookup for SRV record  _autodiscover._tcp.DOMAIN.COM
If a value is found, then the returned value should be used for the exchange server.

**Comment by jobisoft** [comment]
This is the function which needs to be extended:
https://github.com/jobisoft/TbSync/blob/master/content/provider/eas/eas.js#L1687-L1760

From what you are writing, it looks like you can code :-) Why not give it a try? I simply do not have the time right now.

**Comment by webtrader** [comment]
@jobisoft , I can follow basic code and logic, but I never written in javascript before. If you are willing to guide, I am willing to give it a shot. I will need to first figure out how to be able to edit the add-on code that Thunderbird is using.

**Comment by jobisoft** [comment]
First you need to fork this repository:
https://github.com/jobisoft/TbSync/fork

Than you need github desktop (or any other git software)
https://desktop.github.com

Start github desktop and sign in with your github account and clone your own copy (fork) of tbsync. Now all files are on your disk.

The repository contains a file pack.bat, which creates the xpi file, which you than can install in Thunderbird. Xpi is a renamed zip file. Pack.bat uses 7zip. You can use any other zip tool, you just need to adapt pack.bat (this is obviously for a windows system, if you use linux or mac, you need to write a script of your own to get all the needed files into the xpi file)

Everytime you change something in the sources (on your computer) you need to run pack.bat, to create a new xpi file, which you then need to install in thunderbird to get the changes into thunderbird.

An easy test ist to change the version number in install.rdf and see your change in thunderbird.

The next step is than to understand that the git in github is a version control system, where you can commit you changes in smaller chuncks (commit and push).

After you have fixed a bug or added a new feature and pushed them to github, you need to create a pull request (PR) to get your changes back into my version of TbSync. Github Desktop will guide you.

Feel free to ask for more help.

**Comment by jobisoft** [comment]
This issue was moved to jobisoft/EAS-4-TbSync#17
