### ISSUE TITLE
Error status 6 when sync calendar to server

### ISSUE THREAD

**Issue by joda01** [jobisoft/TbSync#9]
If I create a new calendar event and try to sync to the server I get Status 6 as return code.
Sync from server to local calender is working

`
** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[Sending data sendingchanges (XML)] : 
<?xml version="1.0"?>
<Sync xmlns='AirSync'>
<Collections>
<Collection>
<SyncKey>********</SyncKey>
<CollectionId>********</CollectionId>
<Commands>
<Delete>
<ServerId>********</ServerId>
</Delete>
<Add>
<ClientId>********</ClientId>
<ApplicationData>
<TimeZone xmlns='Calendar'>iP///ygARwBNAFQAKwAwADIAOgAwADAAKQAgAEUAdQByAG8AcABlAC8AVgBpAGUAbgBuAGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgARwBNAFQAKwAwADIAOgAwADAAKQAgAEUAdQByAG8AcABlAC8AVgBpAGUAbgBuAGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==</TimeZone>
<StartTime xmlns='Calendar'>20170824T160000Z</StartTime>
<EndTime xmlns='Calendar'>20170824T170000Z</EndTime>
<DtStamp xmlns='Calendar'>20170715T192249Z</DtStamp>
<BusyStatus xmlns='Calendar'>2</BusyStatus>
<Sensitivity xmlns='Calendar'>1</Sensitivity>
<AllDayEvent xmlns='Calendar'>0</AllDayEvent>
<Subject xmlns='Calendar'>ToServer</Subject>
<Location xmlns='Calendar'/>
<Categories xmlns='Calendar'/>
<Reminder xmlns='Calendar'>15</Reminder>
<Body xmlns='AirSyncBase'>
<Data xmlns='AirSyncBase'/>
<EstimatedDataSize xmlns='AirSyncBase'>0</EstimatedDataSize>
<Type xmlns='AirSyncBase'>1</Type>
</Body>
<NativeBodyType xmlns='AirSyncBase'>1</NativeBodyType>
</ApplicationData>
</Add>
</Commands>
</Collection>
</Collections>
</Sync>

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[sending] : POST https://m.one.com/Microsoft-Server-ActiveSync?Cmd=Sync&User=********&DeviceType=Thunderbird&DeviceId=mztb********

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[PolicyKey used] : ********

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[Receiving Data (WBXML)] : 
3 1 6a 0 45 5c 4f 4b 3 31 35 30 30 31 34 36 35 37 34 35 33 37 0 1 52 3 33 39 38 34 31 38 37 0 1 4e 3 31 0 1 46 47 4c 3 32 63 62 64 30 63 34 65 2d 38 39 63 62 2d 34 66 62 34 2d 61 37 66 34 2d 31 33 34 32 39 34 39 35 31 61 39 63 0 1 4d 3 0 1 4e 3 36 0 1 1 1 1 1 1

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[Receiving Data (XML)] : 
<?xml version="1.0"?>
<Sync xmlns='AirSync'>
<Collections>
<Collection>
<SyncKey>********</SyncKey>
<CollectionId>********</CollectionId>
<Status>1</Status>
<Responses>
<Add>
<ClientId>********</ClientId>
<ServerId>
</ServerId>
<Status>6</Status>
</Add>
</Responses>
</Collection>
</Collections>
</Sync>

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[setSyncState] : State: serverid, Account: ********, Folder: calendar

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[Extracted XML data] : 
Sync => 
 Collections => 
  Collection => 
   SyncKey = [********]
   CollectionId = [********]
   Status = [1]
   Responses => 
    Add => 
     ClientId = [********]
     ServerId => 
     ServerId <= 
     Status = [6]
    Add <= 
   Responses <= 
  Collection <= 
 Collections <= 
Sync <= 

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[wbxml status] : Server reports status <6>. Error? Aborting Sync.

** Sat Jul 15 2017 21:22:54 GMT+0200 (CEST) **
[finishSync(): Error @ ********] : ActiveSync error (Status 6).
`

**Comment by hmaegaard** [comment]
Had the same error with the standard 0.6.8 from the Mozilla repository and  m.one.com
Seems the issue is resolved by installing TbSync-0.6.8.1.xpi

**Comment by joda01** [comment]
Tank you! Fixed in TbSync-0.6.8.1.xpi
