### ISSUE TITLE
Shared Calendar not visible/synced?

### ISSUE THREAD

**Issue by kmindi** [jobisoft/TbSync#90]
## Your environment

TbSync version: 0.7.9
Thunderbird version: 52.8.0

[x] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I expected to see also shared calendars with this extension?

## Actual behavior
Only my own calendar is visble, but not the calendard made availble to me in exchange.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F
