### ISSUE TITLE
Automatica Sync not Working

### ISSUE THREAD

**Issue by thwyster** [jobisoft/TbSync#92]
## Your environment

TbSync version: 0.7.9
Thunderbird version: 52.8.0 (32-bit)

[ ] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
I was hoping that the application automatically updates calendar events, but for it to update, I have to get into the TbSync menu and give Sync.

## Actual behavior
Currently, tbsync only updates calendar events if I click to sync

## Steps to reproduce
Not applicable.

**Comment by jobisoft** [comment]
Can I close this?

**Comment by thwyster** [comment]
Yeap, of course, tks for aswer!

Sent from my iPhone

On 27 Jun 2018, at 15:34, John Bieling <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I close this?
