### ISSUE TITLE
Support for group calendars

### ISSUE THREAD

**Issue by t-animal** [jobisoft/TbSync#95]
This is a feature request, not a bug. It would be nice if TbSync supported Group calendars.

**Comment by jobisoft** [comment]
https://github.com/jobisoft/TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F

**Comment by t-animal** [comment]
Oh. Sorry for creating extra work.

**Comment by aluaces** [comment]
The link was broken on the rename.  I am posting it here for future reference:

https://github.com/jobisoft/EAS-4-TbSync/wiki/What-about-access-to-shared-calendars-via-EAS%3F
