### ISSUE TITLE
Reminders Disappearing

### ISSUE THREAD

**Issue by BillBrowne** [jobisoft/TbSync#97]
## Your environment

TbSync version: 0.7.9
Thunderbird version: 52.8.0

[X] Yes, I have installed the latest available (beta) version from 
https://github.com/jobisoft/TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
When setting a reminder on a meeting which has been accepted, the alarm should stay

## Actual behavior
Alarms get reset on accepted alarms to "No Reminder".  This may be more prevalent on repeated reminders but it's hard to say - they just may be in my calendar for a longer time.

## Steps to reproduce
Accept an appointment
Change the reminder
Wait (takes some time but, I think, < 1 day) - Reminder changes to "No Reminder"

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by jobisoft** [comment]
Could you verify, if this is fixed in [0.7.10.2](https://github.com/jobisoft/TbSync/releases/download/v0.7.10/TbSync-0.7.10.2.xpi) ?

**Comment by BillBrowne** [comment]
Hi, thanks I can confirm that after a few days of monitoring, reminders no longer seem to be disappearing.

**Comment by alistairlow** [comment]
I see this issue on Thunderbird 60.3.0 with TbSync 0.7.16.9. Is this a known problem?
I have turned on debug logging now, so I will follow up with the log if necessary.

**Comment by jobisoft** [comment]
Can you specify what kind of reminders get lost? What do you need to do, to make them disappear?

**Comment by alistairlow** [comment]
We are using Office 365 and I have a lot of recurring meetings set up, all of which have a reminder set for some duration between 0 minutes and 1 day. I noticed when looking at my Thunderbird calendar that the alarm bell icon on some events had disappeared, and opening them shows "No reminder".

After manually setting the reminders again in Thunderbird, at some point later they disappeared again (not necessarily the same events, though I am not sure).

Some investigation reveals that changing the duration of a reminder in the Office 365 web application (not removing the reminder) seems to trigger this behaviour, though it doesn't seem to be the only cause.

I have a log file now, so will send that through.

**Comment by jobisoft** [comment]
You are now using the latest version. Did you SEE that behavior with the latest version? Or did you update just now?

Until a couple of weeks ago I did remove reminders of old events, because they all turned up on initial sync, which staled TB. However with the release of TB60, that bug was fixed and i removed that code.

Commit of removing that code:
https://github.com/jobisoft/TbSync/commit/fedeb13239b08e01daf01545290b0a60e1e8e47f#diff-ec744025b3cdee30df0740489714f212

Loosing reminders of recurring events looks like an unwanted side effect of that old code. Can you observe, if it happens with the latest version?

**Comment by alistairlow** [comment]
I saw this behaviour when using the latest version from Thunderbird Addons last week, then manually installed the 0.7.16.9 beta to see if that would fix it, but the issue persists.

I've sent you a log file by email.

**Comment by jobisoft** [comment]
This issue is tricky and the logfile does not help in this case. Can you do the following for me:
- disable your account in the TbSync account manager
- use the O365 webinterface to set/fix reminders of your events
- re-enable your Account in the TbSync Account Manager
- observe what happens to your reminders.

Thanks.

**Comment by alistairlow** [comment]
Ok here's what I tried:

* Disabled my account in the TbSync account manager
* Checked an event for tomorrow ("Ops Meeting") in the O365 web application - it has a reminder set for 12 hours before (so I didn't change it). However: the event is part of a weekly recurring series - the series has the same 12-hour reminder, but the first two events in the series have a slightly different title
* Restarted Thunderbird
* The TbSync calendar isn't present in the Calendar view
* Re-enabled my account in the TbSync account manager
* The calendar appears and is populated with the events
* Several reminders appear for events in the past (not "Ops Meeting")
* I dismiss them all
* The "Ops Meeting" event has an alarm set for all recurrences except the next two (tomorrow and next week)

Is it possible that there is an issue that's only exposed by meetings that are part of a series but are changed in some way? I can see that all of my meetings in January - March 2019 have reminders set, but November and December 2018 have a lot of meetings that are missing the reminders, so it seems likely that those have had something edited e.g. moved to another room, another time etc.

**Comment by alistairlow** [comment]
Should I open a new ticket for this issue? It now seems that it's different from the original issue.

**Comment by jobisoft** [comment]
Sorry for not responding, I was working on other parts and forgot about this one. Yes, please open a new issue specific to your findings.
